### ISSUE TITLE
how to change font size?

### ISSUE THREAD

**Issue by livrth** [getcursor/cursor#100]
When I use `command` + `+` on macOS, cursor only globally scales the UI size
I want to know how to customize the font size only?

Thanks.

**Comment by AUENDXYZ** [comment]
me too .

**Comment by imingsmings** [comment]
me too.

**Comment by changshengmin** [comment]
me too

**Comment by Fire-** [comment]
consolidate into #103

**Comment by truell20** [comment]
Should be able to customize all you want in the newest version 🙂
