### ISSUE TITLE
Cannot sign in to Github Copilot

### ISSUE THREAD

**Issue by edmondnow** [getcursor/cursor#1006]
Cannot sign-in to Github copilot on latest version of cursor, after update. Works well on VSCode. could you advise?

Steps:
1. Update CoPilot
2. Try to login

OS: MacOs:

Output:

INFO] [auth] [2023-10-22T11:35:11.140Z] GitHub login failed
[ERROR] [default] [2023-10-22T11:35:11.140Z] Extension activation failed: "GitHub login failed"

**Comment by jakobFNF** [comment]
You could try using the 'Sign Out of GitHub' command from the command palette and then log in again.

**Comment by edmondnow** [comment]
That worked! Thank you.
