### ISSUE TITLE
OpenSSH stop working with new update 0.13.1

### ISSUE THREAD

**Issue by trungklam** [getcursor/cursor#1008]
I got the below error when using the SSH extension for remoting to my server.

I tried to delete the `.cursor-server/bin` on the server but It didnt help.

Client OS: Windows 10 with Cursor 0.13.1
Server OS: Centos 7

> [Trace  - 10:34:00.509] Server install command stderr:
2023-10-23 17:33:56 URL:https://cursor.blob.core.windows.net/remote-releases/0.13.1-6a9b9ee2426e8c76377b9695e69edb2ae325d4a0/vscode-reh-linux-x64.tar.gz [56472321/56472321] -> "vscode-server-982697c1-07b5-4785-8fd5-7b29b90fd1f3.tar.gz" [1]
[Trace  - 10:34:00.509] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.13.1-6a9b9ee2426e8c76377b9695e69edb2ae325d4a0/vscode-reh-linux-x64.tar.gz'
Server PID: 12217
Server script: /root/.cursor-server/bin/0.13.1-6a9b9ee2426e8c76377b9695e69edb2ae325d4a0/bin/cursor-server
Server running process: 
Error server did not start sucessfully
Failed once false
Exiting without
8000ac6edce0b405d84112e1: start
exitCode==1==
listeningOn====
connectionToken==26e7b4b2-ce05-4fea-b988-45d1bedb5a8e==
logFile==/root/.cursor-server/.6a9b9ee2426e8c76377b9695e69edb2ae325d4a0.log==
osReleaseId==centos==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/0==
8000ac6edce0b405d84112e1: end
[Error  - 10:34:00.510] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\happiness\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:821412)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\happiness\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:438341

**Comment by truell20** [comment]
There's an active problem with our 0.13.1 SSH on CentOS 7 and Ubuntu 18.04. Comes from official builds of Node 18 not being supported on those platforms. We will have a patch out soon! In the meantime, you can use this build: 

https://download.cursor.sh/builds/231008c5ursm0oj/mac/zip/arm64
https://download.cursor.sh/builds/231008c5ursm0oj/mac/zip/x64
https://download.cursor.sh/builds/231008c5ursm0oj/windows/nsis/x64
https://download.cursor.sh/builds/231008c5ursm0oj/linux/appImage/x64

**Comment by trungklam** [comment]
Thank you @truell20 , so I will stick with the old version in the mean time.

**Comment by truell20** [comment]
Fix should be live for this with the newest versino

**Comment by trungklam** [comment]
Hi @truell20, I tested 0.13.2 and can confirm it fixed the issue. Thank you
