### ISSUE TITLE
⌘+k does not work

### ISSUE THREAD

**Issue by loranger** [getcursor/cursor#1012]
Hi,

I can't figure out why my ⌘+k shortcut does not trigger anything whereas the shortcut seems good

<img width="678" alt="SCR-20231024-lutj" src="https://github.com/getcursor/cursor/assets/6014/4f92e43b-1d6f-4c86-8fab-c367044fe0fc">

![SCR-20231024-luwy](https://github.com/getcursor/cursor/assets/6014/cd843726-ae9d-4756-8aa5-67f638a32556)

![SCR-20231024-lvew](https://github.com/getcursor/cursor/assets/6014/d7810683-d87d-4757-abd6-81dbdd55f099)

Pressing the shortcut does not do anything.

What did I miss?

**Comment by jakobFNF** [comment]
Continued in our forum. https://forum.cursor.sh/t/k-shortcut-does-not-trigger/1267/2
