### ISSUE TITLE
unable to attach to a running container 

### ISSUE THREAD

**Issue by SweeToxin** [getcursor/cursor#1013]
1) If you can, please include a screenshot of your problem

![image](https://github.com/getcursor/cursor/assets/66974163/41694567-c453-4a2c-a49a-25634cda2a6f)

2) Please include the name of your operating system
Windows 10

3) If you can, steps to reproduce are super helpful
Open cursor => try to connect through dev containers extension to a running container 

( able to attach to the same container using the basic VScode )

**Comment by jakobFNF** [comment]
Dev Containers don't work with Cursor yet. Will close this issue because we already have another issue opened for this: https://github.com/getcursor/cursor/issues/718
