### ISSUE TITLE
History version download for windows 7.

### ISSUE THREAD

**Issue by d-wang03** [getcursor/cursor#1016]
I'm using cursor on windows 7. however, after auto upgrading to 0.13.3, it can not be opened, saying "DiscardVirtualMemory on KERNEL32.dll". 

Then I tried to download a previous version, but can not find any link to it. Is there any way to get an older version?

**Comment by jakobFNF** [comment]
Sounds like a compatibility issue.

https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-older-windows-versions says: "VS Code desktop versions starting with 1.71 (August 2022) no longer run on Windows 7 and starting with 1.80 (June 2023) will no longer run on Windows 8 and 8.1. You will need to upgrade to a newer Windows version to use later versions of VS Code."

Here's the download URL for Cursor 0.12.3: https://download.cursor.sh/builds/231008c5ursm0oj/windows/nsis/x64

**Comment by 787070135** [comment]
how can i close auto update,because when i close client ,it will be auto update immediately

**Comment by d-wang03** [comment]
Thanks! 0.12.3 works.

**Comment by DacianFD84** [comment]
Hello, Can anyone help me with the installer ? https://download.cursor.sh/builds/231008c5ursm0oj/windows/nsis/x64

**Comment by SeriousBuggie** [comment]
Worked link as for now: https://downloader.cursor.sh/builds/231008c5ursm0oj/windows/nsis/x64

**Comment by cdhigh** [comment]
You can run the latest version of cursor in Windows 7 if you install the [VxKex](https://github.com/i486/VxKex)

It works with me:
![Snipaste](https://github.com/user-attachments/assets/14434e74-974f-412b-a077-a494224b7161)
