### ISSUE TITLE
Github copilot cannot sign in

### ISSUE THREAD

**Issue by tonydavis629** [getcursor/cursor#1018]
After the most recent update, my github copilot is stuck spinning. I check the output, which is empty, but the github copilot chat says that Github is not signed in. I don't see how to sign into github for copilot? It was set up normally before using VSCode import, but that did not solve the problem again.

Version: 0.13.3
VSCode Version: 1.83.1
Commit: d8a013a98c7499058631e60a9e147fccb1f45e00
Date: 2023-10-25T07:39:14.791Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by jakobFNF** [comment]
You could try using the 'Sign Out of GitHub' command from the command palette (Ctrl + Shift + P), restart Cursor, and then log in again.

**Comment by tonydavis629** [comment]
Solved in 2 minutes, a new record. Thanks.
