### ISSUE TITLE
How to copy text from the terminal on Windows

### ISSUE THREAD

**Issue by mrticker** [getcursor/cursor#102]
I open the terminal at the bottom, run some code, get some errors, want to copy these errors. I can select text but it doesn't get copied with Ctrl-C or right click.

**Comment by tw-luo** [comment]
> I open the terminal at the bottom, run some code, get some errors, want to copy these errors. I can select text but it doesn't get copied with Ctrl-C or right click.

Select what you want to copy, press `Ctrl` + `INS`  to copy, and press `SHIFT` + `INS` to paste

**Comment by tw-luo** [comment]
@mrticker

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
