### ISSUE TITLE
Add azure open ai API deployment support

### ISSUE THREAD

**Issue by umar052001** [getcursor/cursor#1021]
**Is your feature request related to a problem? Please describe.**
There is an option for putting in API key but when I put in the azure deployment API key for usage of gpt-3.5 turbo it through error.

**Describe the solution you'd like**
A clear cut solution to this is to give an option of putting in azure endpoint along with API.

**Additional context**
![image](https://github.com/getcursor/cursor/assets/79453927/191ac612-e0d6-49f2-8ec8-739e91ee529f)

**Comment by jakobFNF** [comment]
There is an Azure API section in the "Advanced" collapsible further down.

![image](https://github.com/getcursor/cursor/assets/74077124/93f2fae3-ab87-4ae9-9e40-8673e75fcebe)

**Comment by umar052001** [comment]
> There is an Azure API section in the "Advanced" collapsible further down.
> 
> ![image](https://github.com/getcursor/cursor/assets/74077124/93f2fae3-ab87-4ae9-9e40-8673e75fcebe)
> 

Found it. Thanks.
