### ISSUE TITLE
based on gpt-3 ? 

### ISSUE THREAD

**Issue by Itsdarkhere** [getcursor/cursor#1030]
![Screenshot 2023-10-31 at 9 23 00](https://github.com/getcursor/cursor/assets/57869878/7e5b5c9f-be41-4298-bc12-995b4610bf07)

Im paying for gpt-4, cursor feels a whole lot like gpt-3.5, when asked, it also tells me its 3 ?
Are you fucking me ?

**Comment by AirOne01** [comment]
lmao
