### ISSUE TITLE
Can't connect to GitHub Codespaces

### ISSUE THREAD

**Issue by ricklamers** [getcursor/cursor#1031]
It's stuck loading and ends with an error (no indication of what the error is, just "fails to connect").

1) If you can, please include a screenshot of your problem

![Screenshot 2023-10-31 at 10 17 17 AM](https://github.com/getcursor/cursor/assets/1309307/15dc4786-7a0b-4036-8986-13291e5d1fab)

![Screenshot 2023-10-31 at 10 19 08 AM](https://github.com/getcursor/cursor/assets/1309307/a628779b-7eab-405c-934a-1551b22fcb55)

2) Please include the name of your operating system
macOS

3) If you can, steps to reproduce are super helpful
Try to connect to a GitHub Codespace (it has already started as per GitHub UI).

Also tried stopping the Codespace and booting it through the Connect to Codespace flow from Cursor, no dice.

Same Codespace works fine from VS Code.

**Comment by jakobFNF** [comment]
[Forum our forum:](https://forum.cursor.sh/t/im-getting-this-failed-to-start-vs-code-remote-server-error/1114)

![image](https://github.com/getcursor/cursor/assets/74077124/853a0fa7-c832-4502-94dd-3be27dac4d92)

**Comment by ricklamers** [comment]
Msft e^3 I guess
