### ISSUE TITLE
Fails at the most basic task

### ISSUE THREAD

**Issue by alessandro-newzoo** [getcursor/cursor#1035]
Hello!
I was just testing Cursor for the first time, and after adding my GPT-4 key and indexing my local repo successfully, it seems to fail at the most basic tasks.

In this example I've asked it to tell me in which files a certain variable is defined, and it cannot find it:

<img width="1571" alt="image" src="https://github.com/getcursor/cursor/assets/47320294/cb4eae26-8b93-4444-a974-7caf0fd4a81c">

I have no extensions installed FYI.
Am I doing something wrong?

**Comment by truell20** [comment]
Oh hmm, how big is our codebase in source lines of code? Did your codebase finish indexing? Does the codebase context look relevant at all?

**Comment by jakobFNF** [comment]
Try putting `@Codebase` in your message and play around with the advanced codebase context settings. For example, you could increase the number of results per search or enable the "Reasoning step".

![image](https://github.com/getcursor/cursor/assets/74077124/d28be4d7-9ac0-46bd-9975-17c942407cb3)

**Comment by alessandro-newzoo** [comment]
Thank you @jakobFNF, after re-indexing (for some reason the first run didn't index everything) and trying your suggestion, I was finally able to make it work.
Thank you both for your replies and your help, wish you a great weekend ahead!
