### ISSUE TITLE
Automatic code execution is bad

### ISSUE THREAD

**Issue by tonydavis629** [getcursor/cursor#1037]
I have noticed when the chat window produces code in the latest update, it tends to attempt to execute it. This is almost always a bad idea because the code being requested is usually meant to be used in a specific environment, so the execution always fails. Then it fails and GPT is stuck trying to fix it and offer suggestions why it doesn't run, preventing the rest of the message from being completed and offering nonrelevant suggestions about fixing code that isn't broken. Please, please, remove this. 

Version: 0.13.4
VSCode Version: 1.83.1
Commit: fe924b35718993dc0821b4583f718e4cbe79b330
Date: 2023-10-29T00:38:06.904Z (3 days ago)
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by truell20** [comment]
Hey! Did you turn on Bash Mode in Advanced Settings (reachable by the gear in the top right)? That will give the AI the ability to execute bash commands.

**Comment by tonydavis629** [comment]
As usual, my issues are user error. Thanks. I didn't know this would run ALL bash scripts in the chat window. It's a kind of wonky feature, but I get what you're going for. Something like Open Interpreter.

**Comment by tonydavis629** [comment]
As usual, my issues are user error. Thanks. I didn't know this would run ALL bash scripts in the chat window. It's a kind of wonky feature, but I get what you're going for. Something like Open Interpreter.
