### ISSUE TITLE
Codespaces and Dev Container Integration

### ISSUE THREAD

**Issue by sbarman-mi9** [getcursor/cursor#1040]
Hi Cursor Team,

Currently I'm unable to use neither github codespaces nor dev containers from within cursor. I tried installing cursor script in a docker image to see if it would download the server and connect to cursor but it didn't work.  It has become a show-stopper for my team irrespective of the IDE's AI features. 

I hope this feature will be available soon.

Thanks.

**Comment by jakobFNF** [comment]
Cursor doesn't support GitHub Codespaces or Dev Containers right now.

**Comment by jjfantini** [comment]
Is it on the roadmap to support them?

**Comment by sbarman-mi9** [comment]
Thanks for adding dev containers. I will close this issue.
