### ISSUE TITLE
vscode-neovim: can not repeat the movement keys, hjkl

### ISSUE THREAD

**Issue by 2nthony** [getcursor/cursor#1041]
https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#vscode-configuration

when i held `k`, it shows:

<img width="156" alt="image" src="https://github.com/getcursor/cursor/assets/19513289/a2675dd5-0ae2-4ff8-9ecc-6aa0b65737cc">

### os

macOS

### issue

the document said run this command:
```sh
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
```

but it is not working on cursor, can you provider the correct identifier(`com.microsoft.VSCode`) or something useful.

**Comment by 2nthony** [comment]
just resolved, I found the app id

**Comment by engageintellect** [comment]
> just resolved, I found the app id

what was the app id?

The vs code command (defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false) isn't working for me.

**Comment by shoebham** [comment]
https://github.com/getcursor/cursor/issues/777

> > just resolved, I found the app id
> 
> what was the app id?
> 
> The vs code command (defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false) isn't working for me.

https://github.com/getcursor/cursor/issues/777

**Comment by engageintellect** [comment]
I was able to get it working on Mac OS using this:

```
com.todesktop.230313mzl4w4u92
```

This is found by right-click "Cursor" in your Applications folder, -> Show Package Contents, then opening info.plist.

Hopefully this helps someone else.
