### ISSUE TITLE
Pro users can't use chat-gpt3.5 with inplace generation (diff generation)

### ISSUE THREAD

**Issue by hynky1999** [getcursor/cursor#1044]
1. User have pro subscription
2. Trigger inplace generation (diff), choose gpt-3.5

![image](https://github.com/getcursor/cursor/assets/39408646/510ace9c-0c3a-46ec-8751-a717f9cda5ec)

**Comment by jakobFNF** [comment]
There's something wrong on Cursor's side. Sorry for the inconvenience!

**Comment by drpedapati** [comment]
same here
"The model gpt-3.5-turbo does not work with your current plan
or api key"

**Comment by jakobFNF** [comment]
It's fixed now. Thank you for your report!
