### ISSUE TITLE
Error message when trying to use Chat GPT-3.5 query after upgrading to Cursor 0.14.0

### ISSUE THREAD

**Issue by carlca** [getcursor/cursor#1046]
* macOS 13.6 
* Cursor 0.14.0

Steps...
1. Press ⌘K
2. Type "look at last digit of i-str-full and if it is >= 5 then increment the previous digit of i_str_full" and Enter
3. Error message appears

![SCR-20231106-nfzb](https://github.com/getcursor/cursor/assets/260612/38940a2f-56cd-4344-9181-bd53ecc4a394)

I am on the Cursor Pro subscription, and usually use the "unlimited" Chat 3.5 option on a regular basis...

![SCR-20231106-nhwl](https://github.com/getcursor/cursor/assets/260612/65e338ca-5faf-42fe-94b6-e18cf881f1f2)

**Comment by jakobFNF** [comment]
There's something wrong on Cursor's side. Sorry for the inconvenience! An issue was already opened for that => https://github.com/getcursor/cursor/issues/1044
