### ISSUE TITLE
Unable to paste inside a chat window.

### ISSUE THREAD

**Issue by hynky1999** [getcursor/cursor#1057]
I am unable to paste into a chat prompt. Neither right-click -> paste nor Command+v works.
Anywhere else in editor I can paste

![image](https://github.com/getcursor/cursor/assets/39408646/093cce48-9369-4acc-a387-f1c3efc68835)

## System info
Version: 0.14.0
VSCode Version: 1.83.1
Commit: edbb49b5481d7fddb9a1115a33617591f39a6d00
Date: 2023-11-02T20:00:53.580Z (5 days ago)
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

**Comment by codebycarlos** [comment]
Seems ok on my end

**Comment by truell20** [comment]
Do you have any reproduction steps? Does this reproduce if you open a new chat?

**Comment by hynky1999** [comment]
@truell20. It works again now, after I reloaded cursor.
This strange bug happened during the time OpenAI had a major outage, so I assume that it's connected to it. I reloaded the cursor 3 times without luck :(

Well glad it works now :)
