### ISSUE TITLE
/edit issues

### ISSUE THREAD

**Issue by spskelly** [getcursor/cursor#1068]
0.15.1, asked for code review with ctrl+enter for full codebase context using gpt-4-1106-preview. Gave good info but at the end of the response had a series of EDIT windows and API key not supported errors. 
![image](https://github.com/getcursor/cursor/assets/103201627/1a99bb21-cc99-4751-8c3e-0c31289d488e)

**Comment by sualehasif** [comment]
/edit is not supported with api keys. it uses non-public features and we really can not support that.

**Comment by jaymuk** [comment]
@sualehasif  @jakobFNF can you explain a bit more? What is one actually supposed to do if they'd like to edit their code - what is a path forward?

**Comment by jakobFNF** [comment]
@jaymuk You can use the /edit slash command in Chat: https://anysphere.mintlify.app/features/slash-commands#edit
Or the Inline Code Edit feature: https://anysphere.mintlify.app/features/inline-code-edit-and-generation#inline-edit
