### ISSUE TITLE
m1 mac can't install

### ISSUE THREAD

**Issue by JS-mark** [getcursor/cursor#108]
m1 mac can't install

**Comment by truell20** [comment]
Thanks for reporting! What happens? Can you send a screenshot?

**Comment by JS-mark** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/31335385/226239140-41a9eddf-8c1f-4128-90c6-0c008f6ec9c0.png">
When the progress is over, there is no hint of a successful installation!

**Comment by JS-mark** [comment]
Can you give me a way to install offline?

**Comment by kibuniverse** [comment]
I am also m1 chip but I can install successfully, I guess it is the network problem.

**Comment by JS-mark** [comment]
> I am also m1 chip but I can install successfully, I guess it is the network problem.

What kind of network environment do you need? I'm in China.

**Comment by JS-mark** [comment]
But I'm not reporting an error on the Internet, but I'm retreating.

**Comment by Sdot-Python** [comment]
> But I'm not reporting an error on the Internet, but I'm retreating.

我刚开始下载也是卡在那里，开全局代理以后就可以了

**Comment by sigmaError** [comment]
I'm in m1 chip too, installation works all good.

**Comment by DanteLuo** [comment]
> > But I'm not reporting an error on the Internet, but I'm retreating.
> 
> 我刚开始下载也是卡在那里，开全局代理以后就可以了

但是我开了代理也还是不行，主要是 也没有报错信息

**Comment by Sdot-Python** [comment]
> > > But I'm not reporting an error on the Internet, but I'm retreating.
> > 
> > 
> > 我刚开始下载也是卡在那里，开全局代理以后就可以了
> 
> 但是我开了代理也还是不行，主要是 也没有报错信息

你是先开的全局代理，然后再打开这个软件？

**Comment by JS-mark** [comment]
Found the cause of the problem, is the network problem, resulting in the failure of the network download！
download url: https://download.todesktop.com/230313mzl4w4u92/Cursor%200.1.3%20-%20Build%202303188rs3re2n9-x64-mac.zip

**Comment by truell20** [comment]
is this still true for anyone in the newest versions?

**Comment by danperks** [comment]
Will close as v0.2.0 has some significant changes which means this may not be a bug anymore. If anyone is still suffering from this on the latest version, feel free to comment here or open a new bug!

**Comment by lilian-han** [comment]
I made that mistake again today
