### ISSUE TITLE
Truncated Information 'More' Tab when 'Rules for AI' is large.

### ISSUE THREAD

**Issue by voytas75** [getcursor/cursor#1081]
Entering a large amount of text into the "rules for AI" truncates the bottom part of the information in the "More" tab. The slider doesn't work (screen). it can't be moved more down (my screen resolution is fullHD).

My rule has:

```
WordCount CharacterCount
--------- --------------
      372           2767
```

screenshot of the problem: 
![image](https://github.com/getcursor/cursor/assets/13856061/6c4cba5a-6051-4850-b09e-7733f446ef9d)
OS: Windows 10 Enterprise (22621.1.amd64fre.ni_release.220506-1250)

**Comment by jakobFNF** [comment]
Oh, okay. Thank you for the report.
