### ISSUE TITLE
Support set activityBar to `side`

### ISSUE THREAD

**Issue by gglin001** [getcursor/cursor#1086]
**Is your feature request related to a problem? Please describe.**

it seems that the activityBar is fixed

this config not works
```
"workbench.activityBar.location": "side",
```

**Describe the solution you'd like**

not found

**Additional context**

null

**Comment by jakobFNF** [comment]
You need to set `workbench.activityBar.orientation` to the default `vertical`. Otherwise it uses Cursor's own horizontal layout.

![image](https://github.com/getcursor/cursor/assets/74077124/e6717637-3407-4a45-9c18-9248cee9f485)
