### ISSUE TITLE
Typescript and Javascript language features keeps crashing

### ISSUE THREAD

**Issue by baileyg2016** [getcursor/cursor#1099]
Type: <b>Bug</b>

I have noticed this a lot, but TS/JS languages features always crash every so often. This happens multiple times a day.

VS Code version: Cursor 0.16.0 (62c4c972aa5e76a3f5b465c2e07bce967ffb2e80, 2023-11-16T22:43:05.957Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 8, 7|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|--ms-enable-electron-run-as-node ../../2-respell|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.6
vscode-markdownlint|Dav|0.52.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
copilot|Git|1.138.0
copilot-chat|Git|0.10.2
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.76.1
latex-workshop|Jam|9.15.0
vscode-latex|mat|1.3.0
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.228.0
azure-dev|ms-|0.8.0
vscode-azureappservice|ms-|0.25.1
vscode-azurecontainerapps|ms-|0.6.1
vscode-azurefunctions|ms-|1.13.1
vscode-azureresourcegroups|ms-|0.8.0
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.23.1
vscode-cosmosdb|ms-|0.20.0
vscode-docker|ms-|1.28.0
csharp|ms-|2.10.28
vscode-dotnet-runtime|ms-|2.0.0
vscode-kubernetes-tools|ms-|1.3.15
autopep8|ms-|2023.8.0
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.6.40
azure-account|ms-|0.11.6
azurecli|ms-|0.5.0
powershell|ms-|2023.8.0
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.11
debugger-for-chrome|msj|4.13.0
color-highlight|nau|2.5.0
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
volar|Vue|1.8.22
vscode-import-cost|wix|3.3.0
vscode-bond|yiw|0.0.10
markdown-all-in-one|yzh|3.5.1

</details>

**Comment by blokku-chan** [comment]
I noticed this happens when the AI returns a code example after a prompt. So I have to restart Cursor to get it working again.

**Comment by danperks** [comment]
Hey, to keep things clean, I'm moving all JS/TS issues into #1888, so please post your issues there, thanks!
