### ISSUE TITLE
@folder not working on windows

### ISSUE THREAD

**Issue by bweinlich-wps** [getcursor/cursor#1101]
1) If you can, please include a screenshot of your problem
![folder](https://github.com/getcursor/cursor/assets/115983817/aeb7c20c-b075-45ec-8b93-9f16a1a68b9a)

2) Please include the name of your operating system
Windows 11

3) If you can, steps to reproduce are super helpful
When I reference a folder using @folder, ask a question about it, and then press Enter, the text "Searching Folder..." initially appears. However, it seems that Cursor does not actually transfer any context / content of the folder, because in the response in the chat window, I only get the information that there is no content here (see screenshot).

**Comment by jakobFNF** [comment]
We'll have a look.

**Comment by bweinlich-wps** [comment]
It works now (v. 0.18.4) - thanks!
