### ISSUE TITLE
Figma extension always get back to VSCode

### ISSUE THREAD

**Issue by thinoo-thepsyentist** [getcursor/cursor#1108]
1.If you can, please include a screenshot of your problem

I'm using an extension called Figma.

<img width="1300" alt="image" src="https://github.com/getcursor/cursor/assets/63044927/6c5394b3-08b5-439a-bb2c-4fbb794b1e97">

After logging in figma, I can't return to Cursor.
Any work around?

<img width="1762" alt="image" src="https://github.com/getcursor/cursor/assets/63044927/5c54c000-35b5-4b13-a6e4-b746913f594f">

2. Platform

<img width="186" alt="image" src="https://github.com/getcursor/cursor/assets/63044927/2b56d97c-4cb6-4fde-8a1d-ce24623a04ea">

**Comment by jakobFNF** [comment]
Yeah, that is annoying. Here's a workaround:

1. Open the Figma login URL.
2. Open Chrome DevTools (Ctrl + Shift + I).
3. Go to the "Network" tab.
4. Click on the "Open Figma for VS Code" button on the website.
5. A "app_auth_redeem..." request in the network tab will show up.
6. Click on that request.
7. Copy the request URL. The request URL will look like this: "vscode://figma.figma-vscode.....".
8. Replace "vscode" at the beginning with "cursor". Now it looks like this: "cursor://figma.figma-vscode-ex....".
9. Open that URL in your browser. It should now redirect to Cursor.

**Comment by jaosn60810** [comment]
![image](https://github.com/getcursor/cursor/assets/26405746/be66ea72-ff74-4d7a-a558-979962f306e2)

**Comment by truell20** [comment]
Figma's extension now natively supports Cursor (as of v0.3.4)! Let us know if you run into any issues.

**Comment by mtin79** [comment]
> Figma's extension now natively supports Cursor (as of v0.3.4)! Let us know if you run into any issues.

How do i need to configure this in figma and cursor so there's an option to open in cursor?
Thank you!
