### ISSUE TITLE
Asking unlimited control to private repos should be removed from application

### ISSUE THREAD

**Issue by samayo** [getcursor/cursor#1115]
I mean I have never seen anything like this before.
![image](https://github.com/getcursor/cursor/assets/5304093/0778380f-0ca6-4769-9f11-8c0e744a55bc)

For now the only solution is to create another github account and possibly get another copilot subscription. 
This is not going to work for any sensible person. There should be more options

**Comment by jakobFNF** [comment]
This is "GitHub for VS Code" requesting access to your GitHub account, not Cursor. It's the same in normal VSCode.
