### ISSUE TITLE
could not connect the github copilot

### ISSUE THREAD

**Issue by Ringzer369** [getcursor/cursor#112]
When I followed the operation, whenever the github prompt was successful, I returned to click done and nothing happened, I tried N times and still didn't work

**Comment by Ringzer369** [comment]
Now there's a more serious problem, I can't install any services, including C Language Server

**Comment by digger-yu** [comment]
I also have the same problem phenomenon

**Comment by TRICO5756** [comment]
me too

**Comment by mirrorHe** [comment]
me too

**Comment by wmlcry** [comment]
me too

**Comment by jonah-chen** [comment]
me too

**Comment by glon** [comment]
> When I followed the operation, whenever the github prompt was successful, I returned to click done and nothing happened, I tried N times and still didn't work

Same!

**Comment by glon** [comment]
> Now there's a more serious problem, I can't install any services, including C Language Server

For me, some can be installed, such as Python, but, after Cursor restart, it need to reinstall.

My Cursor version is v0.1.6

**Comment by OnePieceJoker** [comment]
#7

**Comment by XiaoDong678** [comment]
My Cursor version is v0.1.12, But the problem still remains

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂

**Comment by truell20** [comment]
If you'd like to install copilot, you can download it from [here](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) at "Download extension"

You can then drag the vsix file into cursor
