### ISSUE TITLE
`cursor .` not working with `git-bash`

### ISSUE THREAD

**Issue by k1lgor** [getcursor/cursor#1121]
When using `cursor .` thru Powershell there is no problem with the command. When I run it thru git-bash shows an error:
```
/c/Users/<username>/AppData/Local/Programs/cursor/resources/app/bin/cursor: line 62: /c/Users/<username>/AppData/Local/Programs/cursor/resources/app/bin/../cursor: No such file or directory
```

Using Windows 10

**Comment by seaneez** [comment]
I am facing the same issue. It appears that the files in the bin directory need to be moved to a higher directory.

We can now modify the 'cursor' script as follows:

```
...
if [ ! -L "$0" ]; then
	# if path is not a symlink, find relatively
	VSCODE_PATH="$(dirname "$0")/../../.."
else
     ...

```

**Comment by k1lgor** [comment]
Yeah, nice. This works, but after every update needs to be modified.

**Comment by seaneez** [comment]
Yeah, just a quick fix😂

**Comment by itsbapic** [comment]
Still getting this issue! Is there a planned fix for this?

**Comment by fubostudy** [comment]
Still getting this issue! Is there a planned fix for this?

**Comment by Haskely** [comment]
Still getting this issue! Is there a planned fix for this?

**Comment by letoast** [comment]
> I am facing the same issue. It appears that the files in the bin directory need to be moved to a higher directory.
> 
> (quick fix) We can modify the 'cursor' script as follows:
> 
> ```
> // /c/Users/<username>/AppData/Local/Programs/cursor/resources/app/bin/cursor
> 
> ...
> if [ ! -L "$0" ]; then
> 	# if path is not a symlink, find relatively
> 	VSCODE_PATH="$(dirname "$0")/../../.."
> else
>      ...
> ```

you need to end the if statement with `fi`
``` bash
...
if [ ! -L "$0" ]; then
	# if path is not a symlink, find relatively
	VSCODE_PATH="$(dirname "$0")/../../.."
fi <------ THIS
else
...
```

@itsbapic @fubostudy @Haskely
