### ISSUE TITLE
Requirement to login 

### ISSUE THREAD

**Issue by NabilHunt** [getcursor/cursor#1130]
![image](https://github.com/getcursor/cursor/assets/36118786/a4ddf356-c949-47e1-92ae-6cb964bec168)

Although I have my OAI key configured in, and it is activated, I'm being asked to login "to prevent abuse of the backend", this wasn't the case last time I used it.

Is it no longer possible to use personal keys?

**Comment by truell20** [comment]
You can use an OAI key but you'll still need to login

**Comment by NabilHunt** [comment]
@truell20 Thanks for your response.

Does that means I'd be limited to 50 gpt4 calls/month? and my requests and responses are being stored?

**Comment by truell20** [comment]
> Does that means I'd be limited to 50 gpt4 calls/month?

Nope, you can use unlimited!

>  and my requests and responses are being stored?

Nope, if you turn on privacy mode none of your code will ever be stored. That said, you should know that we do  our final prompt building on our server -- your data will pass through there but cease to exist after the life of the request.
