### ISSUE TITLE
Recurring Code Duplication Bug in AI Feature on Latest Software Build

### ISSUE THREAD

**Issue by JeremiLorenti** [getcursor/cursor#1131]
The AI feature in the software is causing an unexpected duplication glitch. When trying to modify or generate new code segments within a project environment, the existing code starts duplicating erratically, resulting in a messy and unusable state. Unfortunately, this issue hasn't been resolved in the latest software build and is negatively affecting code generation and editing functionality.

![Cursor_0tOzcKcFVD](https://github.com/getcursor/cursor/assets/120612878/0bb76bc5-4594-4bdb-9929-15077043b6f4)

**Comment by arvid220u** [comment]
Hi! Is this only happening if you do edits from the interpreter mode (the `ide.edit`) or also if you do `/edit` or ctrl+k?

**Comment by arvid220u** [comment]
Think I've located the bug! Building 0.19.1 and will release it by tomorrow end-of-day

**Comment by JeremiLorenti** [comment]
Hello,

Just when using interpreter mode or /edit from the chat. Ctrl+K in actual
code seems to work as intended.

Thanks for your quick response!

Best Regards,

Jeremi Lorenti

**Comment by arvid220u** [comment]
Hi! This should be fixed now in 0.19.1 which is now out for everyone. Please let me know if it works for you or not!

**Comment by gsusI** [comment]
Amazing!

**Comment by gsusI** [comment]
I can confirm that 0.19.1 resolves the issue for me
