### ISSUE TITLE
CMD+Shift+O stops working after using CMD+K

### ISSUE THREAD

**Issue by crimson-knight** [getcursor/cursor#1159]
1) If you can, please include a screenshot of your problem
Sorry I cannot produce an image because nothing appears.

2) Please include the name of your operating system
Mac OS 14.2.1 - M1 Max & M1 Pro

Version: 0.21.1
VSCode Version: 1.84.2
Commit: 1a7903c409e3e915db28f4c124497660066e85a0
Date: 2023-12-30T03:05:39.344Z
Electron: 25.9.2
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

3) If you can, steps to reproduce are super helpful

Reproduction Steps:
1. Open Cursor, to an existing project.
2. Use CMD+Shift+O (the letter) and a menu will open, backspace to remove the `@` and type a file name in the project to open, press `ENTER` and the file will open.
3. use CMD+K and ask the AI to generate a code example, accept or decline the code snippet.
4. Now try and use CMD+Shift+O and the menu to choose a file does not appear.

**Comment by truell20** [comment]
Thank you for the report 🙂 I've located the bug and there should be a fix out in the next major update.

**Comment by crimson-knight** [comment]
This is working as expected in the latest release
