### ISSUE TITLE
How to close the previous chat context

### ISSUE THREAD

**Issue by Jussick** [getcursor/cursor#116]
there is no method to close the previous chat context, as soon as I start a chat, a new one created, but how close the previous?

**Comment by truell20** [comment]
hey! could you give some more details on this problem? not sure I understand

**Comment by danperks** [comment]
If I understand correctly, you are referring to starting a new query, with no previous conversation log, for when you want to discuss something totally new? 
The latest version of Cursor has significant changes, including the ability to have multiple chats, similar to ChatGPT. 
Give that a try, and see if it does want you were looking for :smile:

**Comment by danperks** [comment]
Following from my comment, as I believe this is a bug for the older versions of Cursor, I will close this.

Feel free to comment or create a new Issue if you still have issues!
