### ISSUE TITLE
Unable to connect to ssh directory

### ISSUE THREAD

**Issue by LucaRao** [getcursor/cursor#117]
Environment:windows 10
Problem:Unable to connect to ssh directory
There is no response when you click on submit

**Comment by raymondchu-z** [comment]
Environment macOS12.4 meets same problem.

**Comment by guoweiyu** [comment]
Environment macOS13.2 meets same problem.

**Comment by danperks** [comment]
The new version of Cursor should support SSH via an extension, but it may currently not be working. Discussion is ongoing at #489 so I'll close this issue in favor of that one.
