### ISSUE TITLE
Read Changelog Button Just Updates Instead!

### ISSUE THREAD

**Issue by emilrueh** [getcursor/cursor#1184]
For the past two update notifications in the bottom left corner of cursor I clicked the 'read changelog' button which immediately closed the editor and started the installer wizard which went through with the update instead of linking to your changelogs.

I am on Windows 10.

**Comment by gsusI** [comment]
It is the same on Win 11; it's been happening for 3 versions now (that is, 3 times I pressed the "Read changelog" button, and it updated the Cursor instead of showing me the Changelog).

**Comment by AncalagonX** [comment]
I think they fixed it today. Did it work for anyone else? It opened up in a browser window (but the browser didn't take focus, I would have preferred it taking focus). Thanks for the devs being receptive to user issues!

**Comment by emilrueh** [comment]
@AncalagonX I dunno, now clicking the 'Read the changelog.' button doesn't do anything at all, it didn't even open a non-focused browser window.

**Comment by emilrueh** [comment]
With the most recent update request clicking the read changelog button did show me the changelog again before updating so will mark this issue as resolved.
