### ISSUE TITLE
无法中文回答问题

### ISSUE THREAD

**Issue by seamusopen** [getcursor/cursor#119]
0.1.0 版本可以中文回答
0.1.3 版本拒绝中文回答问题 
请问是否有添加"限制英文回答的"系统提示词？
----------------------------------------------
"0.1.0 version can answer in Chinese
0.1.3 version refuses to answer questions in Chinese
May I know if there is a system prompt word to restrict answering in English?"

0.1.0版本图：
![image](https://user-images.githubusercontent.com/30491113/226281435-808015d0-8d72-4be5-8061-83b2a5ef5089.png)
0.1.3版本图：
![image](https://user-images.githubusercontent.com/30491113/226280363-bf96bca4-0363-4787-bee8-a7e772310a32.png)

**Comment by jay1ong** [comment]
可以在问题之后加一句，请将结果翻译为中文。

有时候gpt用起来会有这样的问题，不管是gpt还是newbing，使用中文提问，它使用的语言环境是英文。

会话另开的话，语言环境又监测是中文了，而且也会从中文的网页里面检索信息（源网页，非翻译）。

**Comment by zuohx** [comment]
![image](https://user-images.githubusercontent.com/13301391/226526901-42e0594b-fa6d-4fbb-bdb8-deeb82ea57c9.png)

**Comment by truell20** [comment]
Hey! By default, Cursor will output english because it is prompted in english. To get it to output chinese, please see this tutorial video

https://user-images.githubusercontent.com/4297743/230709872-e277687b-2b81-421d-aae1-96521a9d40bc.mov
