### ISSUE TITLE
CMD+C (and CMD+X) & then highlighting text to paste over will override the clipboard with the highlighted text

### ISSUE THREAD

**Issue by crimson-knight** [getcursor/cursor#1194]
System details:

2021 Macbook Pro Max
OS 14.2.1
Cursor version details:

Version: 0.23.8
VSCode Version: 1.85.1
Commit: 8cbd0bf24e5c279cdece285075618a5b4fc752c0
Date: 2024-01-23T20:50:25.002Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

Steps to reproduce
1. Open Cursor to any text file
2. Highlight some text and then press CMD+X or CMD+C to copy the text to the clipboard
3. Paste this text on another line to ensure it's on your clipboard
4. Highlight a different piece of text to paste over and press CMD+V, you will not see your previously copied text
5. For more testing, move to a new line and try pasting again. You will see the last text highlighted gets pasted.

This works the same for any text you highlight: it gets copied to the clipboard.

The same behavior happens when using the mouse instead of the keyboard shortcuts.

**Comment by truell20** [comment]
I'm unable to reproduce. Does this still happen to you if you disable your extensions?

**Comment by crimson-knight** [comment]
@truell20 you are correct, it appears that after I published this I updated to a new update and the issue is now resolved.

Thank you!
