### ISSUE TITLE
windows  v0.1.3  回答经常到一半后就被cancel调

### ISSUE THREAD

**Issue by qiangyongyang** [getcursor/cursor#120]
当回答内容过长时，回答到一半就被cancel掉了
![Uploading img_v2_07bba5b6-39fb-4151-9e95-1c73d6447fag.jpg…]()

**Comment by wangdabin2333** [comment]
是的，确实有这个问题，正在代码生成中突然就停住了

**Comment by ly7638714** [comment]
确实，我今天就遇到这种情况

**Comment by WLiangJun** [comment]
我也是遇到这种情况

**Comment by truell20** [comment]
Should give much longer outputs in the newest version! 🙂 Lmk if this is still a problem

**Comment by WLiangJun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
