### ISSUE TITLE
Newly released "gpt-4-0125-preview" model does not work in Cursor.sh

### ISSUE THREAD

**Issue by AncalagonX** [getcursor/cursor#1201]
When attempting to use the new `gpt-4-0125-preview` model with reduced "laziness" and more complete code responses, Cursor.sh throws the following error:

![image](https://github.com/getcursor/cursor/assets/37827291/32be388d-1e82-42be-86f6-3df0c96e9dad)

This error occurs regardless of whether using own API Key or Cursor.sh account.

**Comment by AncalagonX** [comment]
To be clear, I have confirmed that this model *does* work with my API key. I even generated a new all-access API key and it still doesn't work in Cursor.sh.

**Comment by InsightfulFuture** [comment]
#1203 Same thing

**Comment by truell20** [comment]
You can now try out gpt-4-0125-preview as a pro or API key user if you configure the model in settings. Let me know if you run into any issues.

<img width="397" alt="Screenshot 2024-01-27 at 1 30 08 AM" src="https://github.com/getcursor/cursor/assets/4297743/81655511-c817-4a76-bd5b-53876e76f57e">
