### ISSUE TITLE
gpt-4-0125-preview does not work

### ISSUE THREAD

**Issue by InsightfulFuture** [getcursor/cursor#1203]
We should be able to use gpt-4-0125-preview with our own api key.
![image](https://github.com/getcursor/cursor/assets/109481728/b198b7a2-e162-4ddd-b5e8-ee8bf01a1fff)

Got this message while using my own api key

**Comment by gebeer** [comment]
Same for me here on 0.24.1 Linux AppImage. I tried both model names, gpt-4-0125-preview and the alias gpt-4-turbo-preview.
Also see this [forum topic](https://forum.cursor.sh/t/the-model-gpt-4-turbo-preview-does-not-work-with-your-current-plan-or-api-key/2582)

**Comment by truell20** [comment]
You can now use gpt-4-0125-preview as an API key or pro user if you configure the model in settings:

<img width="397" alt="Screenshot 2024-01-27 at 1 30 08 AM" src="https://github.com/getcursor/cursor/assets/4297743/81655511-c817-4a76-bd5b-53876e76f57e">

**Comment by gebeer** [comment]
> You can now try out gpt-4-0125-preview as a pro or API key user if you configure the model in settings. Let me know if you run into any issues.
> 
> <img alt="Screenshot 2024-01-27 at 1 30 08 AM" width="397" src="https://private-user-images.githubusercontent.com/4297743/300169221-81655511-c817-4a76-bd5b-53876e76f57e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDkxMzQsIm5iZiI6MTcwNjM0ODgzNCwicGF0aCI6Ii80Mjk3NzQzLzMwMDE2OTIyMS04MTY1NTUxMS1jODE3LTRhNzYtYmQ1Yi01Mzg3NmU3NmY1N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMDk0NzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODljYzllNTAxNTZhMTViY2ZkZjZhNWZmZGQ4ODgwMDQ4YWM3MDgxYTAzNWZhZjBhZjVlNjlmNjc1ZTdjYWE0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4GzenmS4cBl2mBV0tZZwdcSDmyX2x_5q4BninMwzbOI">

Great, thank you! I can confirm it is working.

**Comment by InsightfulFuture** [comment]
Thanks!
