### ISSUE TITLE
[Bug] @web doesn't work, because of web connection, and seems not.

### ISSUE THREAD

**Issue by TJtangjun** [getcursor/cursor#1204]
![image](https://github.com/getcursor/cursor/assets/23148245/97901435-6723-4977-8312-c9ae48b23cb5)

![image](https://github.com/getcursor/cursor/assets/23148245/17470ae3-ff79-4f09-861a-a265dc341f13)

If I use @web, it shows the error above.

if I remove @web, everything is ok, so I don't think it is a web connection problem. But it shows that this is a web connection problem.

I don't know what web site it is visiting, so I don't confirm the real reason.

**Comment by TJtangjun** [comment]
Version: 0.24.1
VSCode Version: 1.85.1
Commit: 2b43a99503060cf7809cf79540dbc9119c225aa0
Date: 2024-01-27T03:14:19.834Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by TJtangjun** [comment]
this is the one of Request Id: 85174af2-96b0-497e-badc-96822ed221af

**Comment by truell20** [comment]
Could you try again? Made a change on our end.

**Comment by TJtangjun** [comment]
![image](https://github.com/getcursor/cursor/assets/23148245/b3d87d99-b1e7-49be-831f-737418e0d193)

it works successfully, thank you. Your production is so good, I like it.

**Comment by truell20** [comment]
Amazing! Please let me know if you run into any more issues or if you have any feedback on the feature :) closing for now
