### ISSUE TITLE
Can't install any extension on fresh install

### ISSUE THREAD

**Issue by Cafezinho** [getcursor/cursor#1210]
1) Can't install any extension on fresh install

![error 2](https://github.com/getcursor/cursor/assets/16946896/f1c18d7a-4fca-49f6-b358-1d155efd4a7c)
![error 1](https://github.com/getcursor/cursor/assets/16946896/8efb71ae-2c9e-43b6-a473-c1c724968e71)

2) Please include the name of your operating system

Windows

3) If you can, steps to reproduce are super helpful

Fresh install cursor 0.24.4, tries to install any extension

**Comment by arvid220u** [comment]
Thanks for reporting. Looking into this.

**Comment by Cafezinho** [comment]
It looks like it is only black extension.

**Comment by arvid220u** [comment]
Does it work now? We think we fixed the problem.

**Comment by Cafezinho** [comment]
Let me check

**Comment by Cafezinho** [comment]
It did work, Thanks!
