### ISSUE TITLE
Allow drag to open in finder toolbar

### ISSUE THREAD

**Issue by danejordan** [getcursor/cursor#1220]
**Is your feature request related to a problem? Please describe.**
Allow drag and drop cursor opening in finder toolbar

**Describe the solution you'd like**
Drag a file / folder from finder onto the cursor icon in the toolbar to open repo / file with cursor

https://github.com/getcursor/cursor/assets/10985108/89813a88-e0e0-4ff7-8668-7eefba608498

**Comment by danperks** [comment]
Duplicate of #586

**Comment by stevensiweix** [comment]
我也很需要這個功能，再請開發團隊加油了～
