### ISSUE TITLE
"What" when using inline code generation.

### ISSUE THREAD

**Issue by jamesneal** [getcursor/cursor#1226]
When using inline code generation with cursor 0.25.1, the text "What" is left on the screen after clicking "Accept."

<img width="400" alt="image" src="https://github.com/getcursor/cursor/assets/1154457/a5e6fbd7-3058-4eef-90bd-3f3beff29acd">

To reproduce:

- Cmd+K
- "Write a function that counts to 10"
- Accept the code.

(This is a visual bug only.  If you save the code, the text goes away.)

**Comment by sualehasif** [comment]
oh lord. this is a famous bug that just started happening. we happen to be in a bit of a bind in figuring out why this is happening but believe me this is a high priority. (we also arent sure how to reproduce so if you can that you would help a lot.)

in the meantime, just doing cmd+shift+p > reload window should help.

**Comment by arvid220u** [comment]
We have located the bug, and are releasing a hotfix! Stay tuned. Will be out within the next two hours.

**Comment by arvid220u** [comment]
released in 0.25.3! https://changelog.cursor.sh/?
