### ISSUE TITLE
Unable to SSH Connect to EC2 Instance

### ISSUE THREAD

**Issue by YoshihideMaruyama** [getcursor/cursor#1240]
While I can SSH connect from my Mac's terminal, attempting to use Cursor's RemoteSSH results in the following error, preventing the connection:

[Info  - 09:33:52.971] Resolving ssh remote authority 'ssh-remote+target_management_app' (attemp #1)
[Trace  - 09:33:52.984] Identity keys:
/Users/y_maruyama/Documents/target_management_app/target_management_app.pem ssh-rsa SHA256:ILJMNxuynBVFozPo4gt0z+9kH7i6B8Z5mGKM4VecB20=
[Info  - 09:33:54.585] Trying no-auth authentication
[Info  - 09:33:54.871] Trying publickey authentication: /Users/y_maruyama/Documents/target_management_app/target_management_app.pem ssh-rsa SHA256:ILJMNxuynBVFozPo4gt0z+9kH7i6B8Z5mGKM4VecB20=
[Error  - 09:33:55.440] Error resolving authority
Error: All configured authentication methods failed

Please advise on how to resolve this issue.

**Comment by Sanger2000** [comment]
Could you share what the ssh config entry for this host looks like?

I assume it has sensitive data. If so, please send over email to aman@anysphere.co.

**Comment by YoshihideMaruyama** [comment]
Dear Sanger2000,

Thank you for your reply. I am sharing the SSH connection logs from the server side.
If you have any advice, it would be greatly appreciated.


Feb 19 02:34:12 ip-172-31-32-76.eu-west-2.compute.internal sshd[122904]: Connection from 125.103.126.210 port 54140 on 172.31.32.76 port 22 rdomain ""
Feb 19 02:34:14 ip-172-31-32-76.eu-west-2.compute.internal sshd[122904]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Feb 19 02:34:14 ip-172-31-32-76.eu-west-2.compute.internal sshd[122904]: Received disconnect from 125.103.126.210 port 54140:11:  [preauth]
Feb 19 02:34:14 ip-172-31-32-76.eu-west-2.compute.internal sshd[122904]: Disconnected from authenticating user ec2-user 125.103.126.210 port 54140 [preauth]

**Comment by YoshihideMaruyama** [comment]
@Sanger2000 

Afterwards, upon further investigation, it appeared that Amazon Linux 2023 on EC2 has deprecated RSA keys. 
Therefore, I recreated the keys with the ed25519 type and attempted the connection again, which succeeded. 

Thank you for the advice.

**Comment by endymion** [comment]
@Sanger2000, thank you so much!  I had the same problem and that was the solution.  I was using an RSA key that always worked before but suddenly did not.  It worked with VS Code but it did not work with Cursor.  I created a new key with the `ed25519` type and added that to my existing EC2 instance (with some help from ChatGPT) and added it to my local identities -- AND NOW IT WORKS!!  Thanks!
