### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by elnexreal** [getcursor/cursor#1251]
* Typo on text "Toggle AI Panel"

![image](https://github.com/getcursor/cursor/assets/40328573/2f5a2eea-313b-4f32-a4bf-7360416b25fc)

**Comment by truell20** [comment]
I think pane was intentional, but agree that panel is more consistent with the naming of the other UI components. Will be fixed in the next major update.

**Comment by truell20** [comment]
Nevermind! We're probably going to keep Pane. [Panel](https://code.visualstudio.com/api/ux-guidelines/panel) has an existing meaning.
