### ISSUE TITLE
Opening current directory in cursor like you can do with "code ." in VSCode

### ISSUE THREAD

**Issue by avocardio** [getcursor/cursor#1255]
**Is your feature request related to a problem? Please describe.**
The problem is I would like to quickly open the current directory in cursor the way I used to open them in VSCode, typing "code /dir". 

**Describe the solution you'd like**
I want to type "cursor /dir" or "cursor ." to open the current folder in the workspace of Cursor.

**Comment by yeyaowei** [comment]
I think it's already implemented, you can open the command palette and type `install cursor` to find the command.

**Comment by avocardio** [comment]
Wow nice! Thanks!

**Comment by SpBills** [comment]
Is `install cursor` still a command? I don't see it anymore.

**Comment by ishwarthecodddr** [comment]
same here

**Comment by JoeDareZone** [comment]
Weird...I installed 'code' first and then 'cursor' appeared. Maybe it works for someone else!
