### ISSUE TITLE
C Language Server can't install

### ISSUE THREAD

**Issue by yuptse** [getcursor/cursor#126]
Hello, I have run into a problem that prevents me from starting the C language service. I am using Windows 11 and have installed the latest version of VSCode. I have also installed clang, clangd, gcc, llvm and other tools through Msys2 and added their paths to the system variables. What else should I do to get the C language service working? Thank you.

**Comment by Climber2** [comment]
me too

**Comment by hjliu-cool** [comment]
same

**Comment by Fire-** [comment]
duplicate of #20

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
