### ISSUE TITLE
[Bug] UI: Custom Title Bar Style Not Fully Applied on Linux

### ISSUE THREAD

**Issue by JumpLink** [getcursor/cursor#1262]
![Bildschirmfoto vom 2024-02-26 09-37-13](https://github.com/getcursor/cursor/assets/1073989/27c6cea1-678f-4d50-b17a-a14d3dea1358)

**Cursor Information**
Version: 0.28.0
VSCode Version: 1.86.2
Commit: 5719f9d13ceeb311b54ffe441ad66bbcff5297a0
Date: 2024-02-24T08:59:00.820Z
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.7.5-200.fc39.x86_64

**Compared VSCode Information**
Version: 0.28.0
VSCode Version: 1.86.2
Commit: 5719f9d13ceeb311b54ffe441ad66bbcff5297a0
Date: 2024-02-24T08:59:00.820Z
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.7.5-200.fc39.x86_64

**OS**
Fedora Linux 39 (Workstation Edition)

**Description**
In the provided screenshot, the left side demonstrates VSCode with the desired custom title bar style, as expected with the applied settings. However, on the right side, while the title bar itself reflects the intended appearance, the native title bar remains visible, which is inconsistent with the expected behavior.

**Comment by JumpLink** [comment]
Seemed to be due to a broken config that may have been caused by the import of the VSCode settings

**Comment by tiagorangel2011** [comment]
Also happened to me. very annoying

**Comment by JumpLink** [comment]
In my case, the problem actually occurred again when I reinstalled and then disappeared again at some point. This has happened to me several times.

**Comment by a9udn9u** [comment]
This happened to me today (it used to work), I compared the `~/.config/Cursor/User/settings.json` with the VSCode `settings.json`, somehow the Cursor version doesn't have the custom title bar setting even though I'm 100% sure I've toggled between native and custom several times. Adding `"window.titleBarStyle": "custom"` to the Cursor `settings.json` fixed it for me.
