### ISSUE TITLE
Copilot ++ suggestion for sh scripts inside markdown often remove the closing quotes

### ISSUE THREAD

**Issue by MarArMar** [getcursor/cursor#1268]
Resembles https://github.com/getcursor/cursor/issues/1236

Inside markdown files, I have regularly copy/paste commands in Readme.md like this

    ```sh
    cd /home/dev/
    ```

If I complete the script and Copilot ++ makes a suggestion and I apply it, it regularly remove the next quotes
    
    ```sh
    cd /home/dev/folder
    
    
On latest cursor version to date (updated this moring).

**Comment by truell20** [comment]
Could you try again and let me know if you still see this? Made a change on our end

**Comment by truell20** [comment]
Do you still see these? Just made a change on our end.

**Comment by truell20** [comment]
Closing this for now, let us know if you're still seeing problems
