### ISSUE TITLE
Request for Refund

### ISSUE THREAD

**Issue by kwngmin** [getcursor/cursor#1272]
Dear Customer Service Team,

I paid $193.82 USD for a one-year plan of CURSOR PRO on Monday, Jan 8 at 16:52 KST. Then a few days passed and I requested refund. But now I have not received a refund yet and my account is not on the PRO plan.

I'd like to revert my account back to the pro plan and cancel the refund, but if that's not possible, I'd like to get my money back quickly. My account is registered under [kwngmink@gmail.com (signed in with Google)].

**Comment by truell20** [comment]
Refund sent! Should show up in the next few days.
