### ISSUE TITLE
Editor Froze after trying to Cmd + K (+ devs whispered to me)

### ISSUE THREAD

**Issue by ufkhan97** [getcursor/cursor#1275]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

<img width="896" alt="Screen Shot 2024-02-28 at 12 14 45 PM" src="https://github.com/getcursor/cursor/assets/43886242/54ef3770-a492-4076-a8e3-e65788fd4e33">

2) macOS Monterery V 12.6

3) I pressed Cmd +K three times, then went to close out the chat box because it opened in the wrong spot in the file. Then the editor froze and this cute message popped up :)

**Comment by truell20** [comment]
Hello! Thanks for reporting. What version of Cursor are you on?

**Comment by ufkhan97** [comment]
Version: 0.27.4
VSCode Version: 1.85.1
Commit: 590c39f7a32f1f9458a65a5f9624f1f854c80ca0
Date: 2024-02-19T20:29:05.551Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.6.0

**Comment by arvid220u** [comment]
Could you try upgrading to the newest version of Cursor (0.28.1)? We think we fixed this bug. Let us know if you still see it after upgrading.

**Comment by truell20** [comment]
Closing this for now, let us know if you run into any trouble
