### ISSUE TITLE
any plan to support a proxy setting?

### ISSUE THREAD

**Issue by butterl** [getcursor/cursor#128]
some times the user may behind a proxy but now it seem do not have a proxy setting in config

**Comment by godpowerscn** [comment]
Strongly agree

**Comment by farss** [comment]
Strongly agree

**Comment by haicc-wang** [comment]
'A server error has occurred'....
If  cannot configure the network, you will receive a similar error.

**Comment by clipsheep6** [comment]
Strongly agree

**Comment by q920447939** [comment]
Strongly agree

**Comment by novNorthSea** [comment]
Strongly agree

**Comment by truell20** [comment]
What would a good feature look like here? Could you say more? What options would you need? What are examples of software with good proxy settings

**Comment by danperks** [comment]
Cursor should (to some extent) support VSCodium's proxy settings, give my suggestion a try from https://github.com/getcursor/cursor/issues/381#issuecomment-1502170243 and report back if it works for you!

**Comment by butterl** [comment]
proxy config could be set in 0.2.2 , but not sure if it works.
0.2.2 need login account，but after the webpage login success，the ide still kept un-login，showing fetch failed all time

**Comment by danperks** [comment]
@butterl Sounds like the bug mentioned in #409, so keep an eye there for now
