### ISSUE TITLE
typescript server is crashing a lot.

### ISSUE THREAD

**Issue by OdapX** [getcursor/cursor#1281]
Type: <b>Bug</b>

Sorry, dont have any steps to reproduce, but I just noticed (and my colleagues) a huge problem with typescript server, as it keeps crashing all the time.

VS Code version: Cursor 0.27.4 (590c39f7a32f1f9458a65a5f9624f1f854c80ca0, 2024-02-19T20:29:05.551Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
codespaces|Git|1.16.11
vscode-typescript-next|ms-|5.5.20240302
color-highlight|nau|2.5.0
vim|vsc|1.27.2
pretty-ts-errors|Yoa|0.5.3

(2 theme extensions excluded)

</details>

**Comment by kacperpaczos** [comment]
I also think that the cursor is unstable, I don't know why. I use it to create React/Vue applications, I don't turn off either the computer or the cursor for several days, and from time to time the cursor stops working.
![paste (2)](https://github.com/getcursor/cursor/assets/23406555/3138d332-94ea-4567-b321-55cf8ab36188)
![paste (3)](https://github.com/getcursor/cursor/assets/23406555/b707b148-f33e-406a-9c2a-373e20e4b663)

**Comment by OdapX** [comment]
bumping JavaScript and TypeScript Nightly tov5.5.20240304 fixed it for me

**Comment by parsatajik** [comment]
@OdapX's comment worked for me as well!
