### ISSUE TITLE
OpenAI API return error

### ISSUE THREAD

**Issue by ricoxor** [getcursor/cursor#1293]
When I add my own OpenAI API key the system return an error : Invalid API Key.

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
 (status code 429)

 My quota is not exceeded at all and the key is correct, I just created it.

![Usage_-_OpenAI_API_–_Brave_7PmL4r1Vyd](https://github.com/getcursor/cursor/assets/3131462/4bdee5a5-0e9d-4721-b4c5-344b7bf7c540)
 
 Thank you in advance

**Comment by hemangjoshi37a** [comment]
how to add openai key in this? if you know please help me .

**Comment by ykosan1** [comment]
I experienced same error. I have just created a API key then I have put in the cursor. the error has been shown.

`(status code 429)
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}`

**Comment by martinhelfert** [comment]
Same. Any solution to this?
