### ISSUE TITLE
Copilot++ doesn't make many suggestions

### ISSUE THREAD

**Issue by tonydavis629** [getcursor/cursor#1300]
In general use of cursor with Copilot++ enabled and github Copilot disabled, I don't really notice Copilot++ making suggestions. Every once in a while, I will get the blue Copilot++ squiggles, but I don't see any shortcuts to actually accept the suggestion. Additionally, it's usually some kind of extremely minor single character suggestion that is sometimes even incorrect syntax. I'm finding zero use out of it. 

Version: 0.29.1
VSCode Version: 1.86.2
Commit: a962ca5721e80876320cb6a3a500cbc1cf679150
Date: 2024-03-02T20:35:34.996Z (4 days ago)
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

**Comment by truell20** [comment]
Apologies about this. Could you say a bit more about what you mean by\ blue squiggles or provide a screenshot? The Copilot++ UI is expected to look like [this](https://cursor.sh/cpp) (a mix of grey text or the diff box depending on the suggestion).

**Comment by tonydavis629** [comment]
Sorry it is highly possible I mistook blue squiggles from my linter as a copilot++ suggestion. I do very occasionally see copilot++ suggestions, but it is quite rare. It is nowhere as responsive as the demo at that link. They are generally helpful suggestions, but they are just so rare.

**Comment by tonydavis629** [comment]
Just wanna say the latest update totally fixed my problems. Copilot++ is awesome, way more effective now than copilot. You guys are killing it.

**Comment by AllyourBaseBelongToUs** [comment]
is that feature still available? 

Cant find it in the settings
