### ISSUE TITLE
Bug: The cursor doesn't suggest CSS

### ISSUE THREAD

**Issue by kacperpaczos** [getcursor/cursor#1315]
![image](https://github.com/getcursor/cursor/assets/23406555/77adda6f-b096-4ff3-89de-cb50130da50a)

**Comment by truell20** [comment]
Are you talking about intellisense? Or Copilot++? Do you have the same set of extensions installed in both?

**Comment by kacperpaczos** [comment]
`intellisense`

I reinstalled the cursor, it works now. Maybe I did something wrong with my extensions.
