### ISSUE TITLE
Issue!! convert "\n's to new lines unintentionally.

### ISSUE THREAD

**Issue by fightingnoble** [getcursor/cursor#132]
Bug!! When I save my code, which contains "\n" in some strings, Cursor will transform the "\n" into "true returns," i.e., a new line. This behavior leads to disaster errors. 
The client of Cursor runs on Win11, and the Python code is placed on Remote Ubuntu18.04, which is connected by SSH.
![image](https://user-images.githubusercontent.com/29675145/226542678-280b8323-57ce-488f-8ea9-cf43b79fb081.png)
![image](https://user-images.githubusercontent.com/29675145/226542663-6f147df2-2fc5-4936-8e60-4433c3afffe4.png)

**Comment by lichengzhe** [comment]
same~~~

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
