### ISSUE TITLE
Incorrect Caret Position

### ISSUE THREAD

**Issue by lightify97** [getcursor/cursor#1324]
![Animation](https://github.com/getcursor/cursor/assets/16276964/35c47231-922a-48d4-8699-439643f78b08)

Windows 11 with WSL

The problem is with the caret or any mouse action that is associated with the caret. As can be seen in the recording above it's always off by 2 characters. I've tried changing fonts, letter spacing and everything but to no avail. I love using cursor but this is a very annoying situation. Looking forward to a solution.

**Comment by OscarBarrett** [comment]
This seems to be caused by some of the default appearance or font settings. I exported/imported my profile from VSCode and it resolved this for me.
