### ISSUE TITLE
Copilot++ not auto suggesting anything

### ISSUE THREAD

**Issue by ErlanBazarov** [getcursor/cursor#1330]
Copilot++ stopped suggesting. There is no autocompletion anymore. Yesterday it was working fine. I tried restarting the cursor, log out & log in. Nothing is working
Example:
<img width="1496" alt="image" src="https://github.com/getcursor/cursor/assets/56782170/a82ff824-bdfd-4a3a-bccf-ef6324635d2f">

OS: MacOS 14.0

Cursor:
Version: 0.29.1
VSCode Version: 1.86.2
Commit: a962ca5721e80876320cb6a3a500cbc1cf679150
Date: 2024-03-02T20:35:34.996Z
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.0.0

**Comment by meerbex** [comment]
I am having the same problem

**Comment by ErlanBazarov** [comment]
Now, it is working fine again
