### ISSUE TITLE
Can we expect the next release to update the Chinese language pack?

### ISSUE THREAD

**Issue by isreturn-ture** [getcursor/cursor#134]
It would be really nice for developers in China if Cursor could update the Chinese language pack

**Comment by truell20** [comment]
Yes! Would love to add chinese support. Here's a video of how you can get the AI to speak chinese

https://user-images.githubusercontent.com/4297743/230710114-88bd6000-3b9e-48d9-9d8b-f80d8b44f323.mov


I do not speak chinese so don't have a lot of context here. Could you say a bit more about what you'd like from chinese language support in Cursor? Is the problem that you can't input chinese characters easily right now?

**Comment by isreturn-ture** [comment]
I'm sorry, what I mean is that the Chinese language package is similar to VScode, which can convert the whole IDE into Chinese. In this way, it will prompt high development efficiency, and also enable Cursor to get a larger market, right
