### ISSUE TITLE
stop charging.

### ISSUE THREAD

**Issue by ItsFaizan** [getcursor/cursor#1343]
I purchased cursor pro last month for $20 but now I want to remove my card info as I no longer need the cursor pro. My manager said he will provide me with the api key but the I am getting transaction failed transaction error due to insufficient funds in my card as cursor is trying to charge me ultimately I have gotten 326rs fine from my bank for failed international transactions stop charging. @arvid220u @abbychau @webpro @fangxiao @truell20 
Contact me at faizanjavid71@gmail.com

please remove my card as my I am getting fined again and again for failed transactions

**Comment by truell20** [comment]
Canceled your subscription and sent you a refund. Let me know if it doesn't show up in a few days.

**Comment by ItsFaizan** [comment]
ok
