### ISSUE TITLE
Shell not supported. command detection must be available, for now

### ISSUE THREAD

**Issue by grass29** [getcursor/cursor#1368]
OS: Ubuntu 22.04

How to reproduce: Start the interpreter mode chat, ask the AI to run a test shell command for Ubuntu. The above message is printed: "Shell not supported. command detection must be available, for now".

Python execution works, only shell commands aren't working currently

**Comment by grass29** [comment]
It seems this has resolved it:
https://code.visualstudio.com/docs/terminal/shell-integration

**Comment by mikepsinn** [comment]
Hi!  I'm using Windows, and I still get this error.  Does anyone know a workaround?  If so, should we add more instructions or a link to the "Shell not supported. Command detection must be available, for now."  error message?  Thank you so much! :D

**Comment by Aubermean** [comment]
I have this issue. On MacOS.

**Comment by ryanmio** [comment]
also having this issue on MacOS

**Comment by jjblancob** [comment]
Hi.

Me too.
I have the same error using zsh:
"Failed.
Shell not supported. Command detection must be available, for now."

Any idea?
