### ISSUE TITLE
Please allow us to specify token limits when using our own API key

### ISSUE THREAD

**Issue by grass29** [getcursor/cursor#1370]
**Is your feature request related to a problem? Please describe.**
Currently the token limit is set globally, which severely limits the potential when using our own API key.

**Describe the solution you'd like**
Allow us to specify custom limits, ideally per model and output/input tokens (so Claude would be 200k, Gpt-4-turbo would be 128k).

**Additional context**
The user should have more control when using their own API key, this would significantly help users who need to tackle a difficult code problem where huge context is important, and don't mind spending extra doing that.

**Comment by Dreamzlol** [comment]
As I mentioned a couple of weeks ago in this thread: https://forum.cursor.sh/t/capped-at-10k-context-no-matter-api-key-or-cursor-pro/3442

Please let us choose how much we limit the context. Sometimes, I have more than 3-4 files that I need to add for context. And i am not the only one it seems. Would be great, Cursor Team!

**Comment by Pwuts** [comment]
This seems to only be fixed for chat. Code gen is still capped.
