### ISSUE TITLE
Request for Refund

### ISSUE THREAD

**Issue by dmcgill50** [getcursor/cursor#1378]
I had several problems with Cursor and I cancelled my subscription. I was charged again today. I went and canceled my subscription again. I would like to have a refund for today's charge.

**Comment by HiepPP** [comment]
Hi @dmcgill50 , did you get the refund? I am considering subscribing to Cursor, but I read your request. This project seems like a dead project; there are tons of GitHub issues, but no one in charge is replying...

**Comment by dmcgill50** [comment]
Generated email from the owner. Crickets after I emailed him. I'd hold off.

**Comment by truell20** [comment]
Refunded the entire subscription! Apologies about the delay.

**Comment by dmcgill50** [comment]
Thank you Michael!

**Comment by Kento-Sec** [comment]
> Refunded the entire subscription! Apologies about the delay.

Dear Cursor Support Team,
I hope this message finds you well. I'm writing to request assistance with adjusting my subscription plan.
On February 12, 2025, I accidentally subscribed to the annual Cursor Pro plan .while intending to select the monthly option. Could you kindly help me:

Cancel the current annual subscription
Process the remaining app balance refund
I've emailed about it to [hi@cursor.com](mailto:hi@cursor.com), but got no response after several days. I can provide information about the order number.

I genuinely appreciate your flexibility in resolving this oversight. Please let me know if you require additional details from my end.
Thank you for your prompt attention to this matter.
