### ISSUE TITLE
5th April: Cursor.sh is down which breaks everything

### ISSUE THREAD

**Issue by OllyMcBrideOB** [getcursor/cursor#1381]
Cursor was working perfectly fine up until around 10am GMT on Friday 5th April 2024 but it suddenly stopped making suggestions. After trying to manually refresh the index (usually fixes the issue when it has occurred before), I get the new error about `Handshake failed`.

![image](https://github.com/getcursor/cursor/assets/15731383/73f50885-e0a9-40f4-b9d5-c51c8ff94d44)

![image](https://github.com/getcursor/cursor/assets/15731383/4e8c4a60-c1ce-4aaf-9256-f554eb0680dd)

The [cursor.so](https://www.cursor.so/) website is still up.

**Comment by Soleil-Digital** [comment]
Yep, look like an ssl issue on cursor.sh as all subdomains are down too.

**Comment by OllyMcBrideOB** [comment]
Update: 10:44 GMT

Email from Cursor:

```
Hey Olly,

Thanks for the report. We are having a DNS issue. We are working very hard to fix it. We will be back up soon.
```

It appears that everything is back up and working now. Thanks for the prompt response Cursor 🙂
