### ISSUE TITLE
Add new gpt-4-turbo model support

### ISSUE THREAD

**Issue by riley-wood** [getcursor/cursor#1391]
I attempted to add `gpt-4-turbo` as a custom model and it says this model is not supported. The new model is supposedly much improved on coding benchmarks and would likely be a strong model in Cursor as it should work with the existing internal prompts (unlike Claude Opus which has not been performing well for me despite overall being a better model).

Please add support for the new `gpt-4-turbo` model. :)

**Comment by InsightfulFuture** [comment]
+1. Based on the benchmarks, it now beats Claude 3 Opus

**Comment by riley-wood** [comment]
> +1. Based on the benchmarks, it now beats Claude 3 Opus
> 
> EDIT: @riley-wood It is available via the `gpt-4-turbo-2024-04-09` model name

Thanks for the info!
