### ISSUE TITLE
Typescript server craching constantly

### ISSUE THREAD

**Issue by carl-eriksen** [getcursor/cursor#1394]
Type: <b>Bug</b>

In my project the typescript server crashes constantly. 

VS Code version: Cursor 0.31.3 (fcd6e551d6f014d13071eac9bd4904e7e0346720, 2024-04-02T20:20:11.019Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.10.4
gitlens|eam|14.9.0
prettier-vscode|esb|10.4.0
copilot|Git|1.180.0
copilot-chat|Git|0.12.2
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.80.1

</details>

**Comment by danperks** [comment]
Hey, can you repost this as a comment in #1888? Hopefully by moving all the discussion into one issue, it'll help push things along :)
