### ISSUE TITLE
Need to send back refund to cursor

### ISSUE THREAD

**Issue by ItsFaizan** [getcursor/cursor#1408]
Hi Cursor Team,

I hope this message finds you well. I am writing to address an issue regarding my recent subscription payment and subsequent refund.

Last month, I subscribed to Cursor for a month and paid $20 for the service.
However, when the automatic renewal was attempted this month, I realized that I no longer require the subscription. Unfortunately, due to insufficient funds in my account, the renewal transaction failed, resulting in a fine for a failed international transaction (1-2$).

In an attempt to resolve this issue, I raised a concern on GitHub regarding my inability to cancel the subscription and the cursor team replied and cancelled the subscription but However, it seems there was a misunderstanding, 
as they refunded $20 
to my account as well while I was fined only 1-2$.

While I appreciate the prompt action taken by your team, I would like to clarify that I only intended to request a refund for the fine amount, which was approximately $1-2 and wanted my subscription cancelled. I believe there might have been an oversight, resulting in the refund of the entire subscription fee.

To rectify this situation, I am reaching out to arrange the return of the excess funds. Please advise on the best way to proceed with this refund process, and I will ensure the extra amount is returned promptly.

Thank you for your attention to this matter. I appreciate your assistance in resolving it swiftly.

@truell20 
Kindly reach out to my email at faizanjavid71@gmail.com

**Comment by truell20** [comment]
We're happy to refund the full amount! It's no problem. All the best.
