### ISSUE TITLE
Can't edit when using "Go to References"

### ISSUE THREAD

**Issue by joelbqz** [getcursor/cursor#1409]
1) <img width="575" alt="image" src="https://github.com/getcursor/cursor/assets/19965325/9ae86060-8d28-46a0-95f8-e72c35b033ec">

2) MacOS Sonoma 14.1

3) Click + Cmd to see references → Can't edit

**Comment by iam153** [comment]
same problem, it has last for about half year.
especially when I wanna go to certain line from reference window

**Comment by iam153** [comment]
honestly it's the only reason why I sometimes still use vscode

**Comment by xxchan** [comment]
Same problem. Come from the forum https://forum.cursor.com/t/cannot-jump-edit-in-reference-window/5463/8

Cursor:

https://github.com/getcursor/cursor/assets/37948597/4caca936-bcd6-41b2-be22-c8cec50817f9



VS Code:

https://github.com/getcursor/cursor/assets/37948597/7d323d0a-b0e6-40ef-9d7e-9ba770c80d6e
