### ISSUE TITLE
Download installer for Linux gives dmg file

### ISSUE THREAD

**Issue by grassick** [getcursor/cursor#1426]
1) If you can, please include a screenshot of your problem
![image](https://github.com/getcursor/cursor/assets/1238335/90204e07-79b6-4f34-b07f-f99336eb7521)

2) Please include the name of your operating system

Pop_OS

3) If you can, steps to reproduce are super helpful

Go to https://cursor.sh/ and try to download the version for Linux

**Comment by truell20** [comment]
Closing this as fixed, let me know if you run into anything similar again
