### ISSUE TITLE
Hit your OpenAI key rate limit

### ISSUE THREAD

**Issue by cryptoboogie** [getcursor/cursor#1430]
1) If you can, please include a screenshot of your problem
<img width="382" alt="Screenshot 2024-05-03 at 12 47 46 PM" src="https://github.com/getcursor/cursor/assets/83265270/1ea8c6fd-2eed-4753-92c1-6b1eec9c0b3d">

2) Please include the name of your operating system

```
Version: 0.32.8
VSCode Version: 1.86.2
Commit: 798a1e81a56b0d19565b818839aa2c00fb6ea030
Date: 2024-04-28T22:47:57.969Z
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

3) If you can, steps to reproduce are super helpful
Input an OpenAI API key, use Cursor as you normally would, get rate limit warning.
---

I've been getting this error for about 2 weeks now. I'm not sure what the issue is as I'm nowhere near the OpenAI API rate limit. I tried a new key just in case, and that didn't work either. Love this product and rely on it both for work and side-projects. Please lmk if there's anything I can do to try to fix this. Thanks!

**Comment by mohamm-ad** [comment]
hey! running into the same problem. checked limits, refreshed api keys, etc, but not resolving. did you figure anything out?

**Comment by jdamon96** [comment]
running into this same problem - anyone figured it out?

**Comment by KernAlan** [comment]
Just ran into this problem. No solution yet. Using Claude 3.5 Sonnet with an API key.

**Comment by RockyBRB** [comment]
Anthropic does put a rate limit per minute, 40K tokens per minut, if you exceed this rate limit it cuts you off, if you wait a minute you can restart processing, unless you exceed it again, looking into my logs with Anthropic I can see that there was times when cursor would make 90K token calls and that is why I was getting the cut off. I am looking for a solution to see if I can somehow throttle cursor to stay within the 40K token limit. My luck, it does not exist.

**Comment by DanielGillett** [comment]
Looks like Cursor doesn't handle the rate limiting to correspond with, for example, openai's 

gpt-4o | 10,000 TPM | 3 RPM200 RPD | 90,000 TPD
gpt-4o-mini | 60,000 TPM | 3 RPM200 RPD | 200,000 TPD
gpt-3.5-turbo | 40,000 TPM | 3 RPM200 RPD | 200,000 TPD

I also don't see where I'm supposd to exclude the node_modules (extra files I don't want to embed)

Hope this issues gets solved.  I have the credits but it keeps cutting me off.

**Comment by codingayam** [comment]
Same problem.. Does anyone have a fix?
