### ISSUE TITLE
Unable to log in to the latest version

### ISSUE THREAD

**Issue by lqun** [getcursor/cursor#1446]
1.After clicking on login, the tool will redirect to the browser. After successfully logging in, the tool will not display as logged in
2.get https://api2.cursor.sh/auth/poll  ERR_CONNECTION_RESET
![image](https://github.com/getcursor/cursor/assets/15151958/23065882-2cab-487c-8361-048779ffad40)

**Comment by truell20** [comment]
Are you able to visit api2.cursor.sh in your browser?

**Comment by lqun** [comment]
1.Welcome to Cursor. From server s5xop8z1d2dn35or1t1w with time 0.1398049984127283. Pod name: local-machine. Pod IP: 127.0.0.1

**Comment by lqun** [comment]
> Are you able to visit api2.cursor.sh in your browser?

Welcome to Cursor. From server s5xop8z1d2dn35or1t1w with time 0.1398049984127283. Pod name: local-machine. Pod IP: 127.0.0.1

**Comment by lqun** [comment]
> Are you able to visit api2.cursor.sh in your browser?

Thank you. I found the reason. China needs a VPN for normal use.
