### ISSUE TITLE
make Appimage download URL publicly available

### ISSUE THREAD

**Issue by gebeer** [getcursor/cursor#1447]
**Is your feature request related to a problem? Please describe.**
The Appimage for Linux currently is only available through the Download button on cursor.sh website. There is no obvious Download URL for the Appimage. 
**Describe the solution you'd like**
make the latest Appimage available through a generic URL that does not contain the version number. Something like @latest  
**Additional context**
System integration of Appimages is often limited.
We could use the generic URL for automated installations, for instance on NixOS with https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-appimageTools

**Comment by truell20** [comment]
It should always be available through https://downloader.cursor.sh/linux/appImage/x64

**Comment by JayDoubleu** [comment]
@truell20 FYI, if you are on Chrome OS, the cursor download site takes you to the Mac download instead of Linux. I had to go on a journey through Google to eventually end up here just so that I could download the cursor for Linux. Sometimes having a "downloads" page with all supported OSs is better than trying to do some magic by detecting the OS and only providing a download for that OS.

**Comment by mratanusarkar** [comment]
> It should always be available through https://downloader.cursor.sh/linux/appImage/x64

As of today, I see:
- https://downloader.cursor.sh/linux/appImage/x64 downloads: `cursor-0.45.14x86_64.AppImage`
- where as, https://www.cursor.com/downloads downloads: `Cursor-0.48.8-x86_64.AppImage`

**Comment by mobiusjwodwo** [comment]
https://downloader.cursor.sh/linux/appImage/x64 ... "server not found"

**Comment by csaladenes** [comment]
OK doing some housekeeping: https://github.com/getcursor/cursor/issues/3002 and https://github.com/getcursor/cursor/issues/3012

**Comment by csaladenes** [comment]
I've created an update script now:

```
#!/bin/bash

APPDIR=~/Cursor
API_URL="https://www.cursor.com/api/download?platform=linux-x64&releaseTrack=stable"

# Install jq if not present
if ! command -v jq &> /dev/null; then
    echo "Installing jq for JSON parsing..."
    sudo apt-get update && sudo apt-get install -y jq
fi

# Fetch the download URL from the API
echo "Fetching latest Cursor download URL..."
DOWNLOAD_URL=$(curl -s "$API_URL" | jq -r '.downloadUrl')

if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" = "null" ]; then
    echo "Error: Failed to get download URL from API"
    exit 1
fi

echo "Downloading Cursor AppImage..."
wget -O "$APPDIR/cursor.AppImage" "$DOWNLOAD_URL"
chmod +x "$APPDIR/cursor.AppImage"

echo "Update complete!"

```

**Comment by LionelL83** [comment]
Hey,

Any plan to have something easy like some other solutions:
- Add the repository to sources.list.d
- Update
- Install?

**Comment by damon314159** [comment]
> Why did this one get the `closed` tag? Using the `.sh` mirror throws a `Server not found` now.. What is the alternative -> just changing `.sh` to `.com` does not seem to do the job.

It was closed months before the `.sh` mirror stopped working to be fair. But yes it would be good if they reopened it

**Comment by mratanusarkar** [comment]
@csaladenes, thanks for mentioning #3002 
Hope cursor team solves this soon!
