### ISSUE TITLE
Fix the badges in the README - PRs welcome (to what?), Discord vs. Discourse

### ISSUE THREAD

**Issue by dandv** [getcursor/cursor#1451]
The "PRs welcome" badge in the README should be removed, since Cursor is not open source.

The link to Discord should probably be replaced with a link to the Forum, which [says](https://forum.cursor.sh/t/welcome-to-the-cursor-forum/5),

> Hello there! We’re moved over to a forum format instead of Discord to increase the speed at which we can get answers to folks.

**Comment by truell20** [comment]
Good point! Done!

**Comment by dandv** [comment]
No link to the forum?
