### ISSUE TITLE
support for gpto

### ISSUE THREAD

**Issue by Am0stafa** [getcursor/cursor#1456]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by truell20** [comment]
Support is added! You should just need to reload your editor. Otherwise, you can plug it in in Settings > Models.

<img width="154" alt="Screenshot 2024-05-16 at 3 02 21 PM" src="https://github.com/getcursor/cursor/assets/4297743/0186853a-2ace-4c1e-a2fa-069518e3b480">
