### ISSUE TITLE
Let me cancel my trial - without billing me pls

### ISSUE THREAD

**Issue by Teamsuccess2024** [getcursor/cursor#1469]
1) If you can, please include a screenshot of your problem - yes
2) Please include the name of your operating system - on cursor ai, there is no cancel trial button. On settings, there is no manage
![2024-05-27_210603](https://github.com/getcursor/cursor/assets/156045035/b3d52105-1678-49e2-859a-4e2bcad131c0)

3) If you can, steps to reproduce are super helpful
manage plan - is missing from Settings page. Please cancel my trial.
my email is: teamsuccessnetwork5@gmail.com

Your help is appreciated.

**Comment by truell20** [comment]
Hey! You don't need to put in a card for the trial? So no cancellation is necessary and you won't be billed? Let me know if I'm missing something
