### ISSUE TITLE
@linter dosent not work anymore

### ISSUE THREAD

**Issue by Dreamzlol** [getcursor/cursor#1470]
Seems like "@linter" does not work anymore, is this a bug? It was very useful.

**Comment by andrew-healey** [comment]
This is a bug - we're working on a fix. Glad to hear you like the feature.

**Comment by joeBlockchain** [comment]
any updates?

**Comment by kinopeee** [comment]
still working on this?

**Comment by joeBlockchain** [comment]
any feedback on this?

**Comment by andrew-healey** [comment]
Should be fixed in the next release!

**Comment by Dreamzlol** [comment]
Awesome! I close this issue then :)
