### ISSUE TITLE
Set model to `GPT-4o` but `GPT-4` is used instead

### ISSUE THREAD

**Issue by qu8n** [getcursor/cursor#1482]
# Screenshots
I'm using Cursor free plan with my OpenAI API key. I opted to send all of my prompts to GPT-4o, but the OpenAI responses are coming from GPT-4.

### My Cursor settings:
![Cursor settings](https://github.com/getcursor/cursor/assets/86090707/0d72190e-102f-488d-8929-159823057471)

### My OpenAI usage history:
![OpenAI usage](https://github.com/getcursor/cursor/assets/86090707/7131e0d9-18df-4414-98d3-d3ebb15ee2bd)
Looks like *a few* requests were sent to GPT-4o initially but then all got sent to GPT-4 afterwards.

# Operating system
MacOS Sonoma 14.4.1 on an M1 Pro Max

# Steps to reproduce
The usual workflow:
- Cursor settings > Models > Add `gpt-4o` under Model Names and enable it
- Cursor settings > Enter the API key under OpenAI API Key and click Verify
- In the Cursor sidebar chat, toggle to use `gpt-4o` before sending a prompt

# What I've tried
- Quitting and reopening the Cursor app
- Removing and adding back the `gpt-4o` model in settings
- Restarting my computer

**Comment by c4mz** [comment]
I've also had this which has costed me close to $50. This needs to be critical. Obviously won't use Cursor till it's fixed.

**Comment by bjornsyse** [comment]
I have the same issue, but I'm on Windows.

**Comment by Am0stafa** [comment]
Same issue here

**Comment by c4mz** [comment]
@truell20 Updates mate? Seems to have gone quiet here. Someone should at least be watching the issues for critical bugs and responding.

**Comment by qu8n** [comment]
@c4mz @bjornsyse @Am0stafa Were you all able to figure out a fix or an alternative? Not sure if we'll hear from Cursor's team on this.

**Comment by c4mz** [comment]
> @c4mz @bjornsyse @Am0stafa Were you all able to figure out a fix or an alternative? Not sure if we'll hear from Cursor's team on this.

Hi mate, they have a post on their forum about it also: https://forum.cursor.com/t/gpt-4-0613-is-being-used-instead-of-gpt-4o/5734/10

But I completely reinstalled mine and made sure to delete all folders and settings. I believe this has worked. Been using it for days now and only 4o is showing up on usage.

**Comment by wfischer42** [comment]
Same issue.

**Comment by quasimik** [comment]
By the way, asking LLMs about themselves (e.g. its model name GPT-4o) will not give the correct answer, as its training parameters are not part of its training data. Your usage seems to be good evidence, though.

**Comment by qu8n** [comment]
FYI looks like Cursor's [recent update](https://changelog.cursor.sh/) (0.35.1) fixed this issue for me.
