### ISSUE TITLE
Long filenames / directory structures obscure filename visibility

### ISSUE THREAD

**Issue by Fire-** [getcursor/cursor#149]
Directory structures expand the tree view to the right indefinitely, causing filenames to be impossible to read
<table><tr><td><img src="https://user-images.githubusercontent.com/1456217/226789686-2c1ad9ba-4494-450f-b874-5a3dc49b5dd3.png"></td><td><img src="https://user-images.githubusercontent.com/1456217/226789595-f70833ad-90fc-4569-9fbc-2274d8c2d505.png" height="696"></td><td>
<img src="https://user-images.githubusercontent.com/1456217/226808481-a4c8ebaa-7605-4f5f-9351-57ff8c13915f.png" height="696">
</td></tr></table>

For reference, this is how vscode handles it, collapsing empty folder and otherwise making sure things are stacked so filenames are visible :
![image](https://user-images.githubusercontent.com/1456217/226789723-2e442b6b-37b3-4ef4-9bc3-a9f9b46fe88e.png)

**Comment by truell20** [comment]
Thanks for reporting -- Fixed in 0.1.5 :) try restarting the app to get the update
