### ISSUE TITLE
[Feature Request]: Opening up Cursor.Sh from the Terminal

### ISSUE THREAD

**Issue by gssakash-SxT** [getcursor/cursor#1504]
Not sure if this exists already and I couldn't find it but my request is very simple.
It would be great to add a capability to ``cursor.sh's`` IDE to be able to open it up directly from the command line similar to how vscode / sublime text allow you to do it with the ``code .`` or ``subl .`` commands respectively.

This would be an extremely good UX addition helping out a lot of developers as I have to drag and drop my desired directory into cursor right now  manually which is an hassle to find a lot of times especially when my root directory has over a 100 directories.

**Comment by Am0stafa** [comment]
Yeah please do that!

**Comment by Flux159** [comment]
This should already exist at least on Mac - Cmd+Shift+P to open the command box, search for `Shell command: Install 'cursor' command`, then restart your terminal to be able to `cursor .` in any directory.

**Comment by gssakash-SxT** [comment]
Never found out about this, would be good to have it documented if not already, it works like a charm now. Thanks
This issue can now be closed
