### ISSUE TITLE
Add DeepSeek Model

### ISSUE THREAD

**Issue by lutfi-haslab** [getcursor/cursor#1509]
**Is your feature request related to a problem? Please describe.**
DeepSeek Coder offers seamless integration with OpenAI API Compatible, but I cannot use the DeepSeek-Coder-V2 model in AI Chat when I add the Deepseek API key to the OpenAI API Key field in settings.

**Describe the solution you'd like**
It would be nice to add compatibility for the DeepSeek API key in the OpenAI API Key field in settings.

**Additional context**

**Comment by YuniorGlez** [comment]
Is there any way to use it? the new version deepseek v2 coder looks so good and the cheapest one actually, cheaper than gpt-4o-mini

**Comment by cougarten** [comment]
bonus for a diff-mode use with less token use

**Comment by SeKi81** [comment]
Deepseek is working fine with Cursor. Just follow these steps:

- in Cursor Settings disable all models
- add deepseek-coder as new model
- in Open AI API Key add https://api.deepseek.com/beta as URL - add your API key. 

thats it.

![image](https://github.com/user-attachments/assets/e8fb9211-f72c-444f-a950-967d2096905f)

**Comment by 18175613591** [comment]
Deepseek models can already be added
Several points to note
The request address is:https://api.deepseek.com
Do not fill in "DeepSeek-Coder-V2-0724" as the name of the model. Just fill in "DeepSeek-Coder".
Good luck

**Comment by didnhdj** [comment]
除了直接注册deepseek，也推荐通过[siliconFlow](https://cloud.siliconflow.cn?referrer=clwvzjh6j0016stbv39dnw4dy)
平台来使用deepseek-coder，因为这个平台注册可以获得大约2000w不限时的token额度，还提供了Qwen系列模型可以选择。并且设置方法和使用方法都是相同的。

Besides directly registering for Deepseek, it is also recommended to use Deepseek-Coder through the
[siliconFlow](https://cloud.siliconflow.cn?referrer=clwvzjh6j0016stbv39dnw4dy) platform. This is because registration on this platform can provide about 20 million tokens without a time limit, and it also offers a selection of Qwen series models. Moreover, the setup and usage methods are the same

**Comment by lutfi-haslab** [comment]
Thank you @SeKi81 it is work, i am using https://api.deepseek.com/beta, and i am tested with expert question:

<img width="1440" alt="Screenshot 2024-08-13 at 08 39 30" src="https://github.com/user-attachments/assets/595f9bbe-7506-4e70-aeff-6dbafefe53c9">
<img width="1440" alt="Screenshot 2024-08-13 at 08 39 41" src="https://github.com/user-attachments/assets/55e1dab9-4dc4-4054-8f41-57af43794c29">

**Comment by GroundbreakerLhy** [comment]
I followed the steps to add Deepseek model, but I know little about api. I wander why I cannot add successfully.
![QQ截图20240814190125](https://github.com/user-attachments/assets/86f8f457-9f6f-43f2-b0d1-dca887cf7a64)
![image](https://github.com/user-attachments/assets/e2e49e53-f08b-4f8b-98eb-69e0a9588001)

**Comment by GroundbreakerLhy** [comment]
I followed these steps to add model, but I failed and I know little about api. I wonder why I cannot add model successfully.
![image](https://github.com/user-attachments/assets/1926645a-0f6c-4060-9944-29cb1dedaae1)
![image](https://github.com/user-attachments/assets/ad202d5b-d904-40c1-8e6d-fc4728ec1db7)

**Comment by cougarten** [comment]
> I followed these steps to add model, but I failed 

spelling: coder, not corder

**Comment by GroundbreakerLhy** [comment]
> > I followed these steps to add model, but I failed
> 
> you got at least 2 spelling errors in there. One in model name, one in the url

Sorry, my mistake. I was too careless

**Comment by mrmign** [comment]
> Deepseek models can already be added Several points to note The request address is:https://api.deepseek.com Do not fill in "DeepSeek-Coder-V2-0724" as the name of the model. Just fill in "DeepSeek-Coder". Good luck

the model name need to be `deepseek-coder`

**Comment by lgh06** [comment]
try [oneapi](https://github.com/songquanpeng/one-api) ,then you can use one-api as a proxy for many other model providers

**Comment by razhangwei** [comment]
The following config works for me today: 
- base url: `https://api.deepseek.com/v1`
- model name: `deepseek-coder`
- openai key ai: put in Deepseek key api
- other models don't have to be toggled off. 

<img width="888" alt="image" src="https://github.com/user-attachments/assets/0101b52a-86f5-4e59-90e1-101b90b03082">

**Comment by eliseumds** [comment]
@razhangwei did you actually get `https://api.deepseek.com/v1` to work? I was getting error messages and had to change it to `https://api.deepseek.com/beta`.

**Comment by leotpp** [comment]
why am I getting 400 error ?! 
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/52a00ab4-05a7-4bd2-a468-94a2fa3e13fe">

**Comment by leotpp** [comment]
I tried https://api.deepseek.com/beta, https://api.deepseek.com/v1 https://api.deepseek.com, also create new key for curosr. But still get 400 error

**Comment by bshawk** [comment]
![image](https://github.com/user-attachments/assets/c9395d17-54ab-4187-bae9-2e70aef4acd8)

**Comment by williamyorkl** [comment]
> I tried https://api.deepseek.com/beta, https://api.deepseek.com/v1 https://api.deepseek.com, also create new key for curosr. But still get 400 error

same here, got 400, not model found
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/97fcd8af-df25-4b02-976e-7cda1ac635ae">

**Comment by SeKi81** [comment]
so i have tested all three deepseek urls:

https://api.deepseek.com/beta
https://api.deepseek.com/v1
https://api.deepseek.com/

all of them working fine here.

**Comment by rishabkapadia** [comment]
@tianyw0 It works for free account. Just tried it.
**under OpenAI model section:** 
base URL: https://api.deepseek.com
Add API key
Click verify. (No ui feedback expected. Means auth worked.)

**Comment by tianyw0** [comment]
> @tianyw0 It works for free account. Just tried it. **under OpenAI model section:** base URL: https://api.deepseek.com Add API key Click verify. (No ui feedback expected. Means auth worked.)

tried, not works.

**Comment by rishabkapadia** [comment]
if it doesn't work then you must be getting a pop with the error details
upon clickijg 'verify'.
--
Rishab Kapadia.
Website: https://rishabkapadia.com
Twitter: https://twitter.com/rishabkapadia
Linktree: https://linktr.ee/rishab

**Comment by tianyw0** [comment]
steps:
1. config deepseek(model name 'deepseek-chat') api(done and success)
2. cmd+L chat with deepseek-chat
3. click the 'apply' and 'continue'
4. then show this pic 

<img width="409" alt="image" src="https://github.com/user-attachments/assets/39ebb808-9e1c-444b-8a22-f0d13d4f1d4d">

<img width="641" alt="image" src="https://github.com/user-attachments/assets/fb1a1835-9d87-4edb-9b5e-c3f461f39dbe">

**Comment by domdefault** [comment]
For anyone who still getting this error, eventhough steps above are completed
![image](https://github.com/user-attachments/assets/b7f2f460-ac2e-49c2-b4e8-867aa37f1f89)

make sure to remove "@web" in your prompts. I saw a post above that had the same error while using @web but once I removed it, it works. shame it doesn't work with it as that's why I like cursor.

**Comment by KeWangKW** [comment]
![WeChatb22728e5b48248dc7adb739589e6b22a](https://github.com/user-attachments/assets/d27db690-a20f-4fd4-aaaf-15b1136177a8)

Excuse me:
What is the reason that chat cannot apply deepseek after I have configured it

**Comment by luispl77** [comment]
It does not work because you need click "Verify", and that sends a request with gpt-4 model, which is not available on deepseek for obvious reasons, and so we can't verify the added deepseek API key.

Cursor needs to let us add a key without verifying somehow

**Comment by armanddp** [comment]
@luispl77 if you untick all the openai models, only leave the deepseek-coder one you configured verification will work. 

You also need to ensure that your Deepseek account has funds available. Otherwise it will fail as well. 

My settings:

OpenAI Base URL: 
https://api.deepseek.com/v1 (The v1 is irrelevant in terms of deekseek model number)

Uncheck all other models. Verify. ✅

(I guess after verification you can enable the other models again, I'm just using Sonnet3.5 and Deepseek though. )

**Comment by luispl77** [comment]
> @luispl77 if you untick all the openai models, only leave the deepseek-coder one you configured verification will work. 
> 
> You also need to ensure that your Deepseek account has funds available. Otherwise it will fail as well. 
> 
> My settings:
> 
> OpenAI Base URL: 
> https://api.deepseek.com/v1 (The v1 is irrelevant in terms of deekseek model number)
> 
> Uncheck all other models. Verify. ✅
> 
> (I guess after verification you can enable the other models again, I'm just using Sonnet3.5 and Deepseek though. )

Yes I later realised that, it works. The new V3 model is so good and cheap!

**Comment by RainerWaldmann** [comment]
I am using https://api.deepseek.com/ and deepseek-coder as model.
Works but https://platform.deepseek.com/usage shows usage for deepseek-chat and no usage for deepseek-coder.
Looks like the requests are going to deepseek-chat.

**Comment by GaryCooper23** [comment]
Worked for me:
https://api.deepseek.com/
Custom Model: deepseek-coder
Turning off all other models, then verify the deepseek api key

**Comment by 1000v** [comment]
![изображение](https://github.com/user-attachments/assets/338de43f-d39b-4625-8887-7f44865dc9ba)
(status code 402)
{"error":{"message":"Insufficient Balance","type":"unknown_error","param":null,"code":"invalid_request_error"}}

curl https://api.deepseek.com//chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer ************************" -d "{ \"messages\": [ { \"role\": \"system\", \"content\": \"You are a test assistant.\" }, { \"role\": \"user\", \"content\": \"Testing. Just say hi and nothing else.\" } ], \"model\": \"deepseek-chat\" }"


Не работает (ключ взял из https://platform.deepseek.com/api_keys) пытался с 
https://api.deepseek.com/v1
https://api.deepseek.com
https://api.deepseek.com/beta

It doesn't work (I took the key from https://platform.deepseek.com/api_keys). I tried with  
https://api.deepseek.com/v1  
https://api.deepseek.com  
https://api.deepseek.com/beta

**Comment by GaryCooper23** [comment]
You Need to Fund the Balance on deepseek.

**Comment by ZerkerEOD** [comment]
If I'm correct, deepseek 3 still isn't supported for use in composer right? With their pricing I would love to be able to have deepseek API used in composer.

**Comment by luispl77** [comment]
> If I'm correct, deepseek 3 still isn't supported for use in composer right? With their pricing I would love to be able to have deepseek API used in composer. 

No it's not sadly, this is because the composer uses LLM tools

**Comment by djbob2000** [comment]
> Мне помогло: https://api.deepseek.com/ Пользовательская модель: deepseek-coder Отключите все остальные модели, затем проверьте ключ API deepseek

deepseek-coder != deepseek-chat (v3)

**Comment by alexeyda** [comment]
Do you mean you can use deepseek 3 in composer?
Your configuration works for "chat", not for "composer"


> > Мне помогло: https://api.deepseek.com/ Пользовательская модель: deepseek-coder Отключите все остальные модели, затем проверьте ключ API deepseek
> 
> deepseek-coder != deepseek-chat (v3)

**Comment by mihailmariusiondev** [comment]
Okay after messing around for a while:

### Tutorial: Using DeepSeek v3 as a Chat Model (Alternative to Sonnet 3.5)

#### Step 1: Obtain an API Key
1. Visit [DeepSeek API Keys](https://platform.deepseek.com/api_keys).
2. Create an account if you don’t already have one.
3. Generate an API key for DeepSeek.

#### Step 2: Add Funds
1. Add a minimum of $5 to your DeepSeek account to activate your API key.

#### Step 3: Configure DeepSeek in Cursor (Experimental)
DeepSeek is not yet officially integrated with Cursor, but you can manually set it up:

1. **Add the model:**
   - Go to the chat settings in Cursor.
   - Add the model `deepseek-chat`.
   - Disable other models (e.g., OpenAI, Claude).

2. **Override OpenAI Base URL:**
   - Set the base URL to: `https://api.deepseek.com`.

#### Step 4: Performance and Cost Insights
- **Performance:** Achieves 90-95% of Claude 3.5 Sonnet's performance.
- **Cost:** Operates at approximately 7% of Sonnet’s cost, making it a highly economical alternative.

Enjoy leveraging DeepSeek for efficient and cost-effective AI interactions!

![image](https://github.com/user-attachments/assets/48d5f576-d640-459d-b6b0-ece56b4b8eb3)

**Comment by ZerkerEOD** [comment]
> > If I'm correct, deepseek 3 still isn't supported for use in composer right? With their pricing I would love to be able to have deepseek API used in composer.
> 
> No it's not sadly, this is because the composer uses LLM tools

I've seen references to LLM tools in the composer, mainly when I hit 25 interactions. But I'm not sure what they do that makes it so that composer can't use them with our API key. I know that it all has to route from their servers to the LLM, but I think they could still have our key forwarded to their server for use (securely). I think that requiring a pro subscription for this would be great and reduce their cost so they don't need to limit context to reduce costs as the individual is paying for their usage.

**Comment by luispl77** [comment]
> > > If I'm correct, deepseek 3 still isn't supported for use in composer right? With their pricing I would love to be able to have deepseek API used in composer.
> > 
> > 
> > No it's not sadly, this is because the composer uses LLM tools
> 
> I've seen references to LLM tools in the composer, mainly when I hit 25 interactions. But I'm not sure what they do that makes it so that composer can't use them with our API key. I know that it all has to route from their servers to the LLM, but I think they could still have our key forwarded to their server for use (securely). I think that requiring a pro subscription for this would be great and reduce their cost so they don't need to limit context to reduce costs as the individual is paying for their usage.

Tools means that the LLM API needs to be capable of more than just chat completions. Concretely, it needs to be able to await submission of tool results from the host, after the LLM chooses to call a function (such as Edit tool in composer), to then continue generation smoothly.
DeepSeek API does seem to have function calling (which is another name for tools), but doesnt seem to have streamed tool calls. 
Either way, the point is that tools/function calling in LLMs needs a custom integration to fit the API provider, which Cursor has done for Anthropic (Sonnet 3.5), but not for DeepSeek

**Comment by ZerkerEOD** [comment]
> > > > If I'm correct, deepseek 3 still isn't supported for use in composer right? With their pricing I would love to be able to have deepseek API used in composer.
> > > 
> > > 
> > > No it's not sadly, this is because the composer uses LLM tools
> > 
> > 
> > I've seen references to LLM tools in the composer, mainly when I hit 25 interactions. But I'm not sure what they do that makes it so that composer can't use them with our API key. I know that it all has to route from their servers to the LLM, but I think they could still have our key forwarded to their server for use (securely). I think that requiring a pro subscription for this would be great and reduce their cost so they don't need to limit context to reduce costs as the individual is paying for their usage.
> 
> Tools means that the LLM API needs to be capable of more than just chat completions. Concretely, it needs to be able to await submission of tool results from the host, after the LLM chooses to call a function (such as Edit tool in composer), to then continue generation smoothly. DeepSeek API does seem to have function calling (which is another name for tools), but doesnt seem to have streamed tool calls. Either way, the point is that tools/function calling in LLMs needs a custom integration to fit the API provider, which Cursor has done for Anthropic (Sonnet 3.5), but not for DeepSeek

Thanks for this, that is great information.

**Comment by malingxin** [comment]
This my settings, I hope it helps!
![image](https://github.com/user-attachments/assets/609d535f-aa7e-435b-9bc8-a5dbb45fe488)

**Comment by cloverasx** [comment]
> > > > If I'm correct, deepseek 3 still isn't supported for use in composer right? With their pricing I would love to be able to have deepseek API used in composer.
> > > 
> > > 
> > > No it's not sadly, this is because the composer uses LLM tools
> > 
> > 
> > I've seen references to LLM tools in the composer, mainly when I hit 25 interactions. But I'm not sure what they do that makes it so that composer can't use them with our API key. I know that it all has to route from their servers to the LLM, but I think they could still have our key forwarded to their server for use (securely). I think that requiring a pro subscription for this would be great and reduce their cost so they don't need to limit context to reduce costs as the individual is paying for their usage.
> 
> Tools means that the LLM API needs to be capable of more than just chat completions. Concretely, it needs to be able to await submission of tool results from the host, after the LLM chooses to call a function (such as Edit tool in composer), to then continue generation smoothly. DeepSeek API does seem to have function calling (which is another name for tools), but doesnt seem to have streamed tool calls. Either way, the point is that tools/function calling in LLMs needs a custom integration to fit the API provider, which Cursor has done for Anthropic (Sonnet 3.5), but not for DeepSeek

https://api-docs.deepseek.com/guides/function_calling

I'm not sure when this was added as I haven't really messed with deepseek until today. According to their docs, they have function calling.

**Comment by Lyzin** [comment]
Deepseek cannot use the composer feature, hoping to get support for it

**Comment by ivancucer** [comment]
It'd be just great to add the DeepSeek model to use it in the composer!
I found that DeepSeek provides better code results than 3.5 Sonnet...

**Comment by LeOndaz** [comment]
I came here to say that

Besides, deepseek can help cursor make their product cheaper because the API is 90% cheaper in this case

I tested Anthropic API and it's super expensive to the point that $20 for cursor is definitely accounted for, but not all devs are ready to pay $20 for a product that's only used 3 days on the bigger models then continue on a stupid 4o-mini

My idea is that deepseek will help increase the request limit by at least 10x, while maintaining the same price, or even less

**Comment by alehano** [comment]
Why don't you just allow us to use our own API keys in Composer?

**Comment by ivancucer** [comment]
> Why don't you just allow us to use our own API keys in Composer?

because obviously they wanna lock you into their ecosystem...
running a business means making as much profit as possible without hitting a plateau

**Comment by ZerkerEOD** [comment]
> > Why don't you just allow us to use our own API keys in Composer?
> 
> because obviously they wanna lock you into their ecosystem... running a business means making as much profit as possible without hitting a plateau

There is a lot more to it than that. If they required the pro plan to use private API keys then it would be beneficial to their business as it would cut down on calls they are making. This would be a subscription for them but offload additional costs to users that wish to use their own keys. They also make all the calls from their server which means everything needs to funnel through them and the composer handles requests at a varying degrees.

**Comment by ivancucer** [comment]
> > > Why don't you just allow us to use our own API keys in Composer?
> > 
> > 
> > because obviously they wanna lock you into their ecosystem... running a business means making as much profit as possible without hitting a plateau
> 
> There is a lot more to it than that. If they required the pro plan to use private API keys then it would be beneficial to their business as it would cut down on calls they are making. This would be a subscription for them but offload additional costs to users that wish to use their own keys. They also make all the calls from their server which means everything needs to funnel through them and the composer handles requests at a varying degrees.

yeah that'd be a good option... but you know:
I'm pretty sure their main source of revenue is not the subscription but the "enable usage-based pricing" feature
that's where the main revenue comes from
the subscription is just the entry point

just charging for the app is not a profitable model considering that there are other good alternatives
not to mention that these alternatives are free

VC Code + https://github.com/RooVetGit/Roo-Code + DeepSeek combo does a good job at the moment
not perfect but it does a good job

**Comment by alehano** [comment]
> > > Why don't you just allow us to use our own API keys in Composer?
> > 
> > 
> > because obviously they wanna lock you into their ecosystem... running a business means making as much profit as possible without hitting a plateau
> 
> There is a lot more to it than that. If they required the pro plan to use private API keys then it would be beneficial to their business as it would cut down on calls they are making. This would be a subscription for them but offload additional costs to users that wish to use their own keys. They also make all the calls from their server which means everything needs to funnel through them and the composer handles requests at a varying degrees.

It's exactly what I'm talking about

**Comment by diadras** [comment]
Alright boys, listen up. I have your solution.

Cursor does some behavior it doesn’t explicitly tell you but after some digging I found out what the issue was.

Make sure you have your Deepseek API key and then do the following;

    Go to cursor settings → Models
    Enable the OpenAI API Key setting ← If you do this step later, your models will change. So do it before making any custom API changes.
    DISABLE ALL YOUR MODELS ← This is one of the critical steps
    Add the deepseek-chat, deepseek-reasoner and deepseek-coder models.
    Paste your API key into the API key box (This will not actually update your API key yet), you need to verify it first.
    Toggle open the custom API URL and enter https://api.deepseek.com. NO /v1 appended to it. Simply the URL https://api.deepseek.com.
    Click the verify button. If you followed the above instructions and you have a valid API key, this will succeed.
    Start using Deepseek in Cursor natively.

Now why does this work? And how did I figure it out?
At first I simply pasted in the key and found someone saying I had to use the https://api.deepseek.com/v1. This is what usually is the case when an API supports the “default” LLM API structure but Deepseek does not use /v1. We read [the docs](https://api-docs.deepseek.com/) and use the URL detailed in there.

If you still get an error, copy the curl request you see in the error window and thoroughly read through the curl request and double check if the request is correct. If it is not, you probably have something you need to fix. For some reason I pasted my API key wrong and I figured that out by copying the error curl request into my terminal and comparing it to the one in de [Deepseek docs](https://api-docs.deepseek.com/). I was able to re-paste it and verify it was correct after that.

Now. We have the correct URL, I am succesfully authenticating because I dont get the “User not found” error in my verify request.
This is where the DELETE ALL MODELS EXCEPT DEEPSEEK step comes in. If you have any model above the deepseek ones, it will use that model to verify your custom OpenAI API key and URL. Removing all other models allowes the verify button to use one of the deepseek models to verify the request and save your custom API key and API URL.

There. This is it. Nobody has explained it this well so far but I figured it out and thought I would share my experience. Let me know if this fixed it for you so I can feel like my effort wasn’t in vein :v:

Happy Coding :sparkles:

**Comment by danilofalcao** [comment]
Hey guys, I wrote this proxy that makes it possible for Cursor to use deepseek-chat in the Composer area disguised as gpt-4o: https://github.com/danilofalcao/cursor-deepseek

Feedbacks are most welcome!

**Comment by guilhermeguirro** [comment]
> Hey guys, I wrote this proxy that makes it possible for Cursor to use deepseek-chat in the Composer area disguised as gpt-4o: https://github.com/danilofalcao/cursor-deepseek
> 
> Feedbacks are most welcome!

Wow.

I'll give it a try. Thanks!

**Comment by alehano** [comment]
> Hey guys, I wrote this proxy that makes it possible for Cursor to use deepseek-chat in the Composer area disguised as gpt-4o: https://github.com/danilofalcao/cursor-deepseek
> 
> Feedbacks are most welcome!

This is awesome. 
Also DeppSeek recently released r1 reasoning model. But it's not working even in the chat. Seems because it requires latest OpenAI SDK. Did you try to add r1 as a alias to o1?

**Comment by danilofalcao** [comment]
> > Hey guys, I wrote this proxy that makes it possible for Cursor to use deepseek-chat in the Composer area disguised as gpt-4o: https://github.com/danilofalcao/cursor-deepseek
> > Feedbacks are most welcome!
> 
> This is awesome. Also DeepSeek recently released r1 reasoning model. But it's not working even in the chat. Seems because it requires latest OpenAI SDK. Did you try to add r1 as a alias to o1?

Hey Alex, so, deepseek-reasoner wouldn't work with Composer because it doesn't support function calling. If you're planning to use in the Chat area like o1 would, you could use DeepSeek API directly and add deepseek-reasoner as the model of choice. Hope that helps.

**Comment by danilofalcao** [comment]
Yep, it doesn’t work because o1 and reasoner do not support function calling

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
