### ISSUE TITLE
Linux texts look less sharp than vscode

### ISSUE THREAD

**Issue by abaudhuin** [getcursor/cursor#1510]
I'm on manjaro linux with a DPI scaling of 1,60. 

All the texts look noticeably more blurry compared to VSCode on the same machine.

Any way to fix it?

**Comment by abaudhuin** [comment]
I'm using wayland if that helps.

**Comment by tmlye** [comment]
try export ELECTRON_OZONE_PLATFORM_HINT=auto, that worked for me

also see https://github.com/getcursor/cursor/issues/1789
