### ISSUE TITLE
Can't use claude 3.5 sonnet with openrouter, seems like a cursor issue

### ISSUE THREAD

**Issue by Patryz** [getcursor/cursor#1511]
Using cursor on windows 11. Was working till very recently, at leas until last friday.

If I use anthropic/claude-3.5-sonnet i get error Invalid API key.

On verify API key in the model preferences, I pass the tests. I can leave only anthropic/claude-3.5-sonnet, and it works, but if I add an error like anthropic/claude-3.5-sonnetasdadd, verify will fail.

I'm using the same setup in other custom clients and it's working.

**Comment by Am0stafa** [comment]
same here

**Comment by viavirus** [comment]
does not work for me at all anymore, can get it to work now and then when i try to use it with pro - i just get an error that it can't reach openai. Its a bit sad because gpt 4 is extremely stupid and useless compared to 3.5.

**Comment by viavirus** [comment]
hey so if anyone else has issues and has to keep reopening for it to work, i took a bit of an investigation into why my claude wasnt working, i paid $5 to try and use the api key instead, and i noticed that it had the same issue of it saying it had issues reaching open ai servers. so it didnt matter whether i used my cursor pro or the api key for my claude. I went and reset my cursor and noticed it worked and then stopped working again. So I thought about what the new tabs were doing and when it failed (it seemed to fail when it was trying to look into the files and index them), I also noticed it failed when i would try send my codebase, with ctrl enter. So i went into my settings and decided to clear out my codebase indexing and resynced the index again. it seems that if you do this you can continue a convo with claude longer without it having errors. it seems after a period of time that the requests break due to some kind of code indexing issue. so if you wipe it every like 10 requests you should be able to keep using the same tab and have it have the context window that claude is known for. i also cleared out my files in my appdata because my issue even before clearing my files is that it didn't ever work. just know doing that will make you lose any settings you did locally do your vscode, shortcuts, themes, etc, but not extensions.

**Comment by viavirus** [comment]
@truell20 i dont really know who else to tag about this but hopefully it helps. I saw a few days ago you guys were investigating it and its still not fixed so maybe that makes it a bit easier to find out what it is

**Comment by Patryz** [comment]
For me, it doesn't work in any way: ALT+Enter, Enter, CTRL+Enter.
Resetting the indexing didn't work either.

**Comment by Patryz** [comment]
Still have the issue on latest patch. Different error, it seems to be trying to reach anthropic, even though anthropic is disabled and only openai with custom api for openrouter is enabled. Will not update further as I was forced to switch product.

**Comment by kfwebdev** [comment]
Same error, using OpenRouter api key used to work but is broken now.
Cursor v0.37.1 Vscode 1.89.1. Windows 10.

![Cursor_kDp80mpEEY](https://github.com/user-attachments/assets/54525fc9-d270-42f2-8361-fde38f6134ef)
![Cursor_mqQpWwpAoR](https://github.com/user-attachments/assets/d79346ae-1523-4a00-9e3e-794b5ce38ca7)

**Comment by generalsvr** [comment]
Same here, any solutions or hot fixes for now?

**Comment by psinger** [comment]
unfortunately same issue

**Comment by byrondelgado** [comment]
Same here, @psinger is right there is some sort of hard coded routing.

**Comment by puterhimself** [comment]
You're using your own API key, and we got the following error from Anthropic:
{"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}

I dont even have anthropic turned on and yet 
<img width="810" alt="Screenshot 2024-08-23 at 06 09 19" src="https://github.com/user-attachments/assets/24fec537-8bee-4446-aebf-4a9cabab6eee">

**Comment by alexanderatallah** [comment]
Cursor team, how can we help get this fixed? (OpenRouter dev here)

**Comment by deadblue22** [comment]
> Cursor team, how can we help get this fixed? (OpenRouter dev here)

I used a proxy（one-api） to change claude model to another name and it works. Maybe OpenRouter could support model name alias.

**Comment by sFritsch09** [comment]
It works for models which cursor don't provide like: deepseek/deepseek-coder

**Comment by iudicium** [comment]
Still getting this issue, are there any hot fixes?

**Comment by ardhi-de** [comment]
> > Cursor team, how can we help get this fixed? (OpenRouter dev here)
> 
> I used a proxy(one-api) to change claude model to another name and it works. Maybe OpenRouter could support model name alias.

hi @deadblue22 any guide for doin that?

**Comment by PierrunoYT** [comment]
> Cursor team, how can we help get this fixed? (OpenRouter dev here)

I really need it

**Comment by sunlanchang** [comment]
> Cursor team, how can we help get this fixed? (OpenRouter dev here)

please Cursor, please take this user need to higher priority, we really need this feature.

**Comment by da-moon** [comment]
I have a quick fix. Disable all models but one from Openrouter and then validate the API key. You can toggle them on afterwards.

> It seems like this trick does not work with Anthropic models as I was getting an error regarding wrong API key in `x-api-key` header

![image](https://github.com/user-attachments/assets/5f30805d-551c-4dd3-a351-9d68a9f75bf2)

## additional context

```console
❯ cursor --version
0.40.4
63dae81aea2c3fc079420fe72578a8eef26ba870
x64
```

**Comment by kfwebdev** [comment]
> I have a quick fix. Disable all models but one from Openrouter and then validate the API key. You can toggle them on afterwards.
I'm able to validate the Openrouter API key and use other models like deepseek-coder. Anthropic still fails to connect apparently due to [reasons above](https://github.com/getcursor/cursor/issues/1511#issuecomment-2258410882).

**Comment by da-moon** [comment]
@kfwebdev You are absolutely correct. I forgot to update my original thread. 
I ended up using https://crosshatch.app mixture of experts models instead

**Comment by paradiselabs-ai** [comment]
imo the people behind cursor are being extremely lazy to implement this simple little openrouter glitch. when it sends calls to openrouter it doesnt put the model names correctly i noticed ("gpt-4" instead of "openai/gpt-4") and so idk if thats it or what but it is SOOOOO frustrating

**Comment by bonk** [comment]
I also feel inconvenienced and don't understand the details, but the situation is that they are not accepting feedback for development, so I think it's pointless to write about this. The recent commits also seem to be adjusting the wording of the README, so maybe it's more like an archive?

**Comment by sunlanchang** [comment]
maybe it's time to switch to open-source Cursor alternative, Void https://voideditor.com

**Comment by psinger** [comment]
Continue.dev also works fine with OpenRouter and Claude

I am also a bit puzzled that this heavily requested feature is not fixed, although it is trivial to fix.

**Comment by tmm1** [comment]
openrouter + anthropic/claude-3.5-sonnet works again. sorry it was broken!

**Comment by psmyrdek** [comment]
I'm on the following version of Cursor and getting 401, invalid x-api-key:

```
Version: 0.41.2
VSCode Version: 1.91.1
Commit: 297991d169fa3a11975c5aa95adc69be73250c70
```

**Comment by kevin-kidd** [comment]
> openrouter + anthropic/claude-3.5-sonnet works again. sorry it was broken!

When using the "anthropic/claude-3.5-sonnet" model via OpenRouter, it seems to work fine until I add the @Web tag. I get an error message: Problem reaching Anthropic - "Invalid x-api-key". I have Anthropic disabled in the Cursor settings.

**Comment by kfwebdev** [comment]
openrouter + anthropic/claude-3.5-sonnet works again! thank you @tmm1 !!

**Comment by ducmbui** [comment]
It still does not work for me today with the same error.  Can anyone confirm?

**Comment by leoatchina** [comment]
can work with  openai/gpt-4o-2024-08-06  ?

**Comment by ans-4175** [comment]
> It still does not work for me today with the same error. Can anyone confirm?

It worked for me on
![image](https://github.com/user-attachments/assets/3a68af33-0d9f-4554-8866-423f40acbea8)
using `anthropic/claude-3.5-sonnet` as model
![image](https://github.com/user-attachments/assets/7092663d-70de-4601-bfd6-bae4bca7acff)

**Comment by Shakahs** [comment]
![image](https://github.com/user-attachments/assets/e852139d-8c92-4ae4-8178-ec269d30a96a)
![image](https://github.com/user-attachments/assets/e819ae7a-4b9b-48dc-a69b-13f1df0d25a3)

![image](https://github.com/user-attachments/assets/0cd703db-7ef2-41ce-b584-ceb50eea934a)


It works, I'm using it daily, but it's buggy:

- Cursor will randomly disable the `OpenAI API Key` option, so I have to re-enable it
-  Cursor will randomly lose the ability to query a certain model (I'm using Sonnet 3.5), so I will have to temporarily switch to another model.

**Comment by chrisptang** [comment]
It didn’t work for me. The cursor just gets stuck when I try to verify the Openrouter API key
![image](https://github.com/user-attachments/assets/ba738a88-72b8-478e-81c9-e96ac475b84a)

**Comment by BedroomDev** [comment]
**Hey everyone! I found out how to trick cursor and solve it.** 

I think cursor filters by the word "anthropic" and doesnt use the "anthropic/claude..." models when activating the OpenAI Key slot. 

**### You have to disable all the models and only use "openai/gpt-4.1" to test the connection. This will force cursor to use this model in the test request with openrouter. Which will then activate the openai Slot.** 

You can then add the other models with the "anthropic/..." prefix freely and choose them in the chat! 

<img width="689" alt="Image" src="https://github.com/user-attachments/assets/eaabb9f5-7dc6-40d4-935b-ab157f516e6a" />

**Comment by BedroomDev** [comment]
> Cursor team, how can we help get this fixed? (OpenRouter dev here)

@alexanderatallah create an api route for cursor users like /api/cursor/v1 and let the users use the Models without the vendor prefix "anthropic/" "deepseek/" "openai/" simply the model name. 

Then it will work.

**Comment by chrisptang** [comment]
It’s pretty clear that the cursor team intends to NOT allow us to use custom key freely, they want us to subscribe plans sold by cursor so that they can make money.
