### ISSUE TITLE
No connection while behind corporate proxy

### ISSUE THREAD

**Issue by tonydavis629** [getcursor/cursor#1534]
The side panel, inline editing, and copilot++ are recently experiencing either no connection (inline editting, copilot++) or spotty connection (in the side panel) while used behind an SSL proxy. I currently cannot use any features of cursor. This is a recent change, previously inline editting and the side panel were working fine. I have tested with several cursor models, and using an openai key, to the same effect.

failed request IDs:
inline edits:
21a17ae0-6a0b-49dc-b747-eca733e31f77
side panel:
981b8c18-b7ae-4c3c-931e-9dd8a4176c37
copilot++:
2024-07-08 09:47:07.990 [info] CURSOR LOG: Error in streaming cpp [internal] Protocol error
2024-07-08 09:47:07.990 [info] CURSOR LOG: restFunc done 693d9e49-65fc-4ab0-8d6e-748ebce98df4

Version: 0.36.2
VSCode Version: 1.89.1
Commit: 9a6d781540ba2732cf26551c07629e68121c6580
Date: 2024-07-07T21:57:45.723Z (15 hrs ago)
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0

**Comment by Am0stafa** [comment]
+1

**Comment by laciferin2024** [comment]
I wonder if a relay server can solve this issue

**Comment by vmasrani** [comment]
+1

**Comment by Ching0509** [comment]
Having the same issue currently after having the latest update. This is very frustrating.

**Comment by harukary** [comment]
+1

**Comment by hitajitech** [comment]
+1

**Comment by Belleye** [comment]
+1

**Comment by harukary** [comment]
After today's update, the side panel is working. However, Ctrl+K editing mode still doesn't work.

**Comment by anth-dinosaur** [comment]
+1

**Comment by Ching0509** [comment]
Are they giving up on responding any potential solution? (I know they're slow on response)
I should also mention in the corporation environment, indexing, copilot++, and ctrl+k are all malfunctioned. 
This is unacceptable unstable for cursor running on certain environment.

**Comment by brad-luo** [comment]
Same to me. 

2024-08-19 15:57:26.490 [info] CURSOR LOG: restFunc done 6ef268b0-e9eb-4860-8df0-819cfe148265
2024-08-19 15:57:26.770 [info] CURSOR LOG: restFunc initiated 615ef513-85cc-4787-9f1c-49fb72d2f730
2024-08-19 15:57:27.015 [info] CURSOR LOG: Error in streaming cpp [canceled] This operation was aborted

Also using Zscaler for proxy http://127.0.0.1/9000

**Comment by thefazzer** [comment]
Might be due to corp security deploying SSL clients prevented from requesting insecure connections and gateways that reject self signing in the certificate chain.  Big companies desperate to both leverage the benefits of the tech and prevent access to it.

**Comment by Phoenixmatrix** [comment]
Hitting the same issue (also ZScaler). We have the cert setup so that pretty much everything else, including Github Copilot, Nodejs, WSL, etc all work through ZScaler. The chat in cursor also works, but indexing and code edits don't.

It doesn't seem like Cursor's extension is quite standard under the hood so I'm not sure where I'd poke to debug this. We have access to the ZScaler log, and see the failed SSL Handshake coming from Cursor's requests there, but don't know what to do about it.

**Comment by anmorgunov** [comment]
Have you tried disabling http/2?

[Here is how to do that](https://docs.cursor.com/miscellaneous/common-issues#cursor-tab-and-cmd-k-do-not-work-behind-my-corporate-proxy), and I found that link on the [forum](https://forum.cursor.com/t/solved-connection-failed-on-ctrl-k-for-latest-version/6305/30). It helped in my case.

**Comment by tonydavis629** [comment]
Wow yeah that helped! Still doesn't fix the tab autocomplete, but fixes the side panel and cmd K. It seems like they've abandoned the github issues and just use their own forum. Thanks for the info @anmorgunov.

**Comment by anmorgunov** [comment]
The tab actually works for me as well, but glad it helps at least partially

**Comment by tonydavis629** [comment]
Yeah, seems to be an unrelated issue. It works for me now on simple files. Thanks so much dude.

**Comment by brad-luo** [comment]
> Have you tried disabling http/2?
> 
> [Here is how to do that](https://docs.cursor.com/miscellaneous/common-issues#cursor-tab-and-cmd-k-do-not-work-behind-my-corporate-proxy), and I found that link on the [forum](https://forum.cursor.com/t/solved-connection-failed-on-ctrl-k-for-latest-version/6305/30). It helped in my case.

Oh yeah, It does work!!!!

Appreciate it mate.

**Comment by anth-dinosaur** [comment]
> Have you tried disabling http/2?
> 
> [Here is how to do that](https://docs.cursor.com/miscellaneous/common-issues#cursor-tab-and-cmd-k-do-not-work-behind-my-corporate-proxy), and I found that link on the [forum](https://forum.cursor.com/t/solved-connection-failed-on-ctrl-k-for-latest-version/6305/30). It helped in my case.

This fixed both cmd k and tab. Thank you!!!

**Comment by tonydavis629** [comment]
Closing this, solution here

> Have you tried disabling http/2?
> 
> [Here is how to do that](https://docs.cursor.com/miscellaneous/common-issues#cursor-tab-and-cmd-k-do-not-work-behind-my-corporate-proxy), and I found that link on the [forum](https://forum.cursor.com/t/solved-connection-failed-on-ctrl-k-for-latest-version/6305/30). It helped in my case.

**Comment by vmasrani** [comment]
For anyone still stuck, the solution by @anmorgunov worked, just add `"cursor.general.disableHttp2": true` to your settings

**Comment by zhaoxin111** [comment]
> For anyone still stuck, the solution by @anmorgunov worked, just add `"cursor.general.disableHttp2": true` to your settings对于仍然卡住的人，解决方案有效，只需添加 `"cursor.general.disableHttp2": true` 到您的设置

Can you describe in detail where to add this instruction? I don't know which file to modify.

**Comment by zhaoxin111** [comment]
> For anyone still stuck, the solution by @anmorgunov worked, just add `"cursor.general.disableHttp2": true` to your settings

Can you describe in detail where to add this instruction? I don't know which file to modify.

**Comment by Azreal42** [comment]
@zhaoxin111 : `Cmd/Ctrl + ,` then search for `http2`
But, it didn't help much for me. Cusor still don't see I''ve "business" plan. Tab don't work.
I guess I'm stuck with alternatives of cursor for now.

**Comment by anmorgunov** [comment]
Depending on how your corp proxy works, you may need to launch cursor from the terminal chaining it with whatever script enables proxy in your case. At least in my case it won't work otherwise.

**Comment by eugenet8k** [comment]
@anmorgunov could you post your terminal command example? My corp is using Lookout SASE Tunnel and replacing CA root certs, disabling http2 does not help my case...

**Comment by anmorgunov** [comment]
Try talking with sonnet about your specific case

**Comment by vmasrani** [comment]
> > For anyone still stuck, the solution by @anmorgunov worked, just add `"cursor.general.disableHttp2": true` to your settings
> 
> Can you describe in detail where to add this instruction? I don't know which file to modify.

I just put it into my user settings, available via 'Open User Settings (JSON)' from the command palette and it worked

**Comment by Azreal42** [comment]
> Depending on how your corp proxy works, you may need to launch cursor from the terminal chaining it with whatever script enables proxy in your case. At least in my case it won't work otherwise.

Wdym ? We don't know how the requests are made, and why it doesn't work (logs are unclear). 
I suppose this is because my proxy (ZScaler) need the use of some custom signing certificates. 
But the certificates are registered in the windows store, i've added them in the node.js store (the tricks for copilot). 
But for cursor, if you know where/if they use a specific store, please enlight us. 
(btw sonnet won't be of any help here :) )

**Comment by anmorgunov** [comment]
> if you know where/if they use a specific store, please enlight us

mate, I'm not a sysadmin, I probably know less about proxies than you do. 

I just said that in my particular case launching cursor as an app led to tab\cmd k not working, so I went, talked to sonnet for half an hour, and had a solution for my particular case in which everything works. I'll just say that I have zscaler as well and I didn't have to mess with it.

**Comment by eugenet8k** [comment]
> @anmorgunov mate, I'm not a sysadmin, ... 

definitely a teaser. Please post your solution for your particular case here or get out.

**Comment by anmorgunov** [comment]
lmao

**Comment by christopherstaub** [comment]
> For anyone still stuck, the solution by @anmorgunov worked, just add `"cursor.general.disableHttp2": true` to your settings

BINGO!  That did it

**Comment by TrueBurn** [comment]
Works to allow indexing, pity that it disabled agentic mode
