### ISSUE TITLE
Opening second window freezes typing

### ISSUE THREAD

**Issue by klar-C** [getcursor/cursor#1535]
Hi,

Using cursor.sh for some Python coding.

The following steps disable being able to type anything in opened files.

1) Drag a file into a second window.
2) Open Extensions through the triangle.
3) Click on the last extension (or anything that's not part of the pinned ones).

![image](https://github.com/getcursor/cursor/assets/51972811/9c65c842-d25d-4957-ba2f-524de6aea160)

Seems to be across a few versions. Tried 0.36.2 and a few older ones.

![image](https://github.com/getcursor/cursor/assets/51972811/2cfb9071-5748-41ad-b750-722d25a66865)

**Comment by arvid220u** [comment]
Thank you for the detailed reproduction! I can reproduce and will investigate.

**Comment by arvid220u** [comment]
Resolved! A fix will be out in the next release. (See https://github.com/microsoft/vscode/pull/221296 for the upstream fix.)
