### ISSUE TITLE
输出代码超过45行不显示

### ISSUE THREAD

**Issue by simplesmall** [getcursor/cursor#154]

**Comment by Ares413** [comment]
我也有这个问题，不知道是不是我网络不好的原因，有时候能完整的输出代码

**Comment by greenlgy** [comment]
同样的问题，求解

**Comment by greenlgy** [comment]
代码行数多了，这家伙就罢工了O(∩_∩)O

**Comment by jiayisheji** [comment]
再次输入`继续`

**Comment by Ares413** [comment]
我试过输入继续，也是有时候能接上，有时候接不上

**Comment by xiang3** [comment]
got same issue

**Comment by FINALxxx** [comment]
确实，而且代码切片之后，markdown就接不上了，后面的格式全是乱的，还得让他用markdown把后面的一段给重新打一遍。。

**Comment by truell20** [comment]
Should be fixed in newest version 🙂 We changed Cursor to output more code, let me know if this is ever still an issue

**Comment by kedoupi** [comment]
> Should be fixed in newest version 🙂 We changed Cursor to output more code, let me know if this is ever still an issue

I still encounter this problem in the latest version. As long as the code is added in the markdown format, I will encounter it.
