### ISSUE TITLE
JS/TS crash

### ISSUE THREAD

**Issue by jonasms** [getcursor/cursor#1546]
Type: <b>Bug</b>

¯\_(ツ)_/¯ 

I just got a pop-up in the lower-right corner flagging that some JS/TS service crashed 5 times in the past 5 minutes.

VS Code version: Cursor 0.36.2 (9a6d781540ba2732cf26551c07629e68121c6580, 2024-07-07T21:57:45.723Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|36.00GB (2.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.8
gitlens|eam|15.2.0
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
playwright|ms-|1.1.7
debugpy|ms-|2024.8.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.10.40
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vs-code-prettier-eslint|rve|6.0.0
sort-lines|Tyr|1.11.0
gitblame|wad|11.0.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by moritzlaube** [comment]
Since maybe a week, I am experiencing the same thing with Cursor version 0.39.4
VSCode Version: 1.91.1
Commit: 0c8eb0f46a532a73f16f4427fcdaf7cd9070e140

**Comment by danperks** [comment]
Hi, if you're still having this issue, please post a comment in #1888, as all JS/TS issues are being collated there. Thanks!
