### ISSUE TITLE
Searching files on Windows does not work properly

### ISSUE THREAD

**Issue by LioTree** [getcursor/cursor#155]
I found that I could not get any result when searching files, sometimes cursor couldn't even pop up the search box.

And I found something like this in log.log:

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/12847578/226799914-793bb05a-7f6b-49f0-a4ff-97bb2907b40d.png">

It seems that there was an error when searching files because there are no `grep` and `head` commands in Windows.

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
