### ISSUE TITLE
Cant upload images to claude 3.5!!

### ISSUE THREAD

**Issue by Am0stafa** [getcursor/cursor#1554]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

**Comment by truell20** [comment]
Thanks for flagging! Image support for claude 3.5 will be available in the next update.

**Comment by Am0stafa** [comment]
> Thanks for flagging! Image support for claude 3.5 will be available in the next update.

Still doesn't work! you can uplo
![Screenshot 2024-07-30 at 3 37 33 PM](https://github.com/user-attachments/assets/7c3906e2-9e77-4fe7-b97e-b5f9b0b714b8)
ad image but claude cannot see it
