### ISSUE TITLE
[Docs] Improper redirect within the check your usage docs page 

### ISSUE THREAD

**Issue by adiadd** [getcursor/cursor#1556]
Within this paragraph in the cursor docs: https://docs.cursor.com/get-started/usage#check-your-usage, clicking on the "Cursor Settings" page redirects to https://cursor.sh/dashboard versus the correct redirect to https://www.cursor.com/settings

2) Please include the name of your operating system
MacOS

3) If you can, steps to reproduce are super helpful
1. Navigate to https://docs.cursor.com/get-started/usage#check-your-usage
2. Click on "Cursor Settings"

**Comment by truell20** [comment]
Thank you for flagging this! Fix pushed
