### ISSUE TITLE
cursor 0.13 windows x64 can not go back to initial status by reinstallation

### ISSUE THREAD

**Issue by scShan** [getcursor/cursor#156]
cursor 0.13 windows x64 can not go back to initial status by reinstallation

**Comment by danperks** [comment]
What do you mean by "inital status"? If you mean the inital test files that open the first time you try the app, I don't believe there is an obvious way to get back to those if you close them, but any simple project file is enough to test out the application. The icons at the top right of the editor are shortcuts to the current functions of Cursor.

**Comment by truell20** [comment]
Thanks for trying to dig into this @danperks 

@scShan could you send a screen recording of your problem? Does it still occur with the newest version? What operating system are you on?

**Comment by danperks** [comment]
Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!
