### ISSUE TITLE
"The JS/TS language service crashed 5 times in the last 5 Minutes."

### ISSUE THREAD

**Issue by charlesdwesley** [getcursor/cursor#1573]
Type: <b>Bug</b>

Just open up my repo and after a little while of waiting through the status message "Initializing JS/TS language features" I get this error message:

> The JS/TS language service crashed 5 times in the last 5 Minutes.

It seems to be stuck in an infinite initialization loop, starting up and crashing over and over.

VS Code version: Cursor 0.38.1 (39ded7305e8d625076ebbbf98510c53152232660, 2024-07-25T20:18:41.490Z)
OS version: Darwin arm64 23.5.0
Modes:
Remote OS version: Linux x64 5.15.0-1061-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|36.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bento|
|OS|Linux x64 5.15.0-1061-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 0)|
|Memory (System)|62.01GB (55.62GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-graphql-syntax|Gra|1.3.6
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
scala|sca|0.5.7

</details>

**Comment by danperks** [comment]
Hi, if you're still having this issue, please post a comment in #1888, as all JS/TS issues are being collated there. Thanks!
