### ISSUE TITLE
Coding based on cursor position to write continuelly

### ISSUE THREAD

**Issue by xiang3** [getcursor/cursor#158]
Cursor help me write a python script, I move my cursor to another place. then I describe my new requirement. The coding start from my cursor. I think it can start from based on the current code logic.

**Comment by truell20** [comment]
Hey! this is a cool idea. could you send me some example prompts where you'd want cursor to infer the position of the insertion.

**Comment by dddraxxx** [comment]
Want this too. maybe sth like `@current` to tell model to focus on the before and after 10 lines of cursor position

**Comment by danperks** [comment]
This functionality is now included, either by selecting code to provide as context to the AI, or just from where you start your CTRL+K edits.
