### ISSUE TITLE
server error has occured frequently

### ISSUE THREAD

**Issue by cocoroise** [getcursor/cursor#159]
platform: MAC
version: v0.1.3

Q: it happen today and yesterday use very smooth
<img width="496" alt="image" src="https://user-images.githubusercontent.com/30644193/226837143-d2385efd-613e-4cf0-a7ca-e7f94d8349ea.png">

**Comment by pengyouak** [comment]
me to.
platform: windows 11

**Comment by iamlaom** [comment]
Yes I have this problem today as well. MacOS

**Comment by danperks** [comment]
As stated in the Discord, due to the amount of users, the servers used by Cursor are being rate limited and they are working on scaling up the system to fit the increased demands. For now, if an error occurs, just cancel the incomplete changes, wait a few seconds, and try again.

**Comment by cocoroise** [comment]
> it happen today and yesterday use very smooth

thanks 👍 Please sync with us after the system is fixed. We really like this software and appreciate your work. 😊
