### ISSUE TITLE
Configure a BaseURL option for anthropic

### ISSUE THREAD

**Issue by seefs001** [getcursor/cursor#1604]
**Is your feature request related to a problem? Please describe.**
Accessing anthropic's API directly in China is not feasible and requires a proxy to forward requests.

**Describe the solution you'd like**
Configure a BaseURL option for anthropic

**Additional context**
None

**Comment by cuizheng0520** [comment]
same problem

**Comment by jhs1873** [comment]
![image](https://github.com/user-attachments/assets/c32e9c8f-d4cf-4e9b-86be-820413c35a57)
使用newapi来做中转,使用模型重定向到claude-3.5, 实测可行

**Comment by seefs001** [comment]
> ![image](https://github.com/user-attachments/assets/c32e9c8f-d4cf-4e9b-86be-820413c35a57)
> 
> 使用newapi来做中转,使用模型重定向到claude-3.5, 实测可行

Currently, it is being used temporarily in this way, but through observation, there is suspicion that the software backend might have optimizations for specific model names. The redirected model seems unable to achieve the same effects as the official one.

**Comment by jhs1873** [comment]
> > ![image](https://private-user-images.githubusercontent.com/11732611/356453859-c32e9c8f-d4cf-4e9b-86be-820413c35a57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzU3MTEsIm5iZiI6MTcyMzE3NTQxMSwicGF0aCI6Ii8xMTczMjYxMS8zNTY0NTM4NTktYzMyZTljOGYtZDRjZi00ZTliLTg2YmUtODIwNDEzYzM1YTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAzNTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYmI2OTgxZWVkMmY1YjUzMGY0NjI5YTNiZmRkOGE1YmNjZDc2ZjhjZDJkNDZkYjk1Y2EzZGY4Y2JlMzg0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ufzN-k07zW2ClENRjNKDDvrVzUXPxGCp_Y7DFH-NINo)
> > 使用newapi来做中转,使用模型重定向到claude-3.5, 实测可行
> 
> Currently, it is being used temporarily in this way, but through observation, there is suspicion that the software backend might have optimizations for specific model names. The redirected model seems unable to achieve the same effects as the official one.

[requests always routed through the Cursor backend](https://docs.cursor.com/miscellaneous/privacy#are-requests-always-routed-through-the-cursor-backend)

**Comment by cuizheng0520** [comment]
> ![image](https://private-user-images.githubusercontent.com/11732611/356453859-c32e9c8f-d4cf-4e9b-86be-820413c35a57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzg5NDgsIm5iZiI6MTcyMzE3ODY0OCwicGF0aCI6Ii8xMTczMjYxMS8zNTY0NTM4NTktYzMyZTljOGYtZDRjZi00ZTliLTg2YmUtODIwNDEzYzM1YTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA0NDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwODkxY2E3ZTMzNzY3M2EwNGYwOTRlNjQwZTI3ODU2MTAyZThhYjFkMWFhZjllMWExZTAxMjAyNTFkYjQxNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMA0ZoLp7stcDaRHvMUqTrdXAZdpyqra3SMAwUdk7PQ) 使用newapi来做中转,使用模型重定向到claude-3.5, 实测可行

thanks，smart way

**Comment by edisonzf2020** [comment]
+1

**Comment by labolado** [comment]
#647

**Comment by labolado** [comment]
Use Cloudflare Workers to proxy your API and alias the model name.
```

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

const BASE_URL = 'https://my_api_url'
const MODEL_ALIASES = {
  'mymodel': 'claude-3-5-sonnet-20240620'
}

async function handleRequest(request) {
  const url = new URL(request.url)
  const path = url.pathname
  const queryParams = url.search

  console.log(`Received request: ${request.method} ${path}`)

  if (request.method === 'GET' && path === '/') {
    return new Response("Claude API Proxy is running!", { status: 200 })
  }

  if ((request.method === 'POST' && path === '/v1/chat/completions') ||
      (request.method === 'GET' && path === '/v1/models')) {
    return await proxyRequest(request, path, queryParams)
  }

  console.log(`Unhandled route: ${path}`)
  return new Response(JSON.stringify({ error: 'Not Found', path: path }), { 
    status: 404,
    headers: { 'Content-Type': 'application/json' }
  })
}

async function proxyRequest(request, path, queryParams) {
  const authHeader = request.headers.get('Authorization')
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    console.log('Missing or invalid Authorization header')
    return new Response(JSON.stringify({ error: 'Valid Authorization header is required' }), { 
      status: 401,
      headers: { 'Content-Type': 'application/json' }
    })
  }

  const apiKey = authHeader.split(' ')[1]

  const url = BASE_URL + path + queryParams
  const headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json'
  }

  let body = request.body
  if (path === '/v1/chat/completions' && request.method === 'POST') {
    const requestData = await request.json()
    console.log(`Request data: ${JSON.stringify(requestData)}`)
    if (requestData.model && MODEL_ALIASES[requestData.model]) {
      requestData.model = MODEL_ALIASES[requestData.model]
    }
    body = JSON.stringify(requestData)
  }

  try {
    console.log(`Sending request to: ${url}`)
    const response = await fetch(url, {
      method: request.method,
      headers: headers,
      body: body
    })

    const responseData = await response.text()
    console.log(`Received response: ${responseData}`)
    return new Response(responseData, {
      status: response.status,
      headers: {
        'Content-Type': 'application/json'
      }
    })
  } catch (error) {
    console.error(`Error: ${error.message}`)
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: {
        'Content-Type': 'application/json'
      }
    })
  }
}
```

**Comment by Hambaobao** [comment]
> > ![image](https://github.com/user-attachments/assets/c32e9c8f-d4cf-4e9b-86be-820413c35a57)
> > 
> > 使用newapi来做中转,使用模型重定向到claude-3.5, 实测可行
> 
> Currently, it is being used temporarily in this way, but through observation, there is suspicion that the software backend might have optimizations for specific model names. The redirected model seems unable to achieve the same effects as the official one.

You are absolutely right. I have the same observation.
