### ISSUE TITLE
it seem not process by ChatGPT4

### ISSUE THREAD

**Issue by killianMei** [getcursor/cursor#161]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/41984397/226854926-cc5a8769-d24a-40a0-8a5b-5f55fb8c396f.png">

**Comment by danperks** [comment]
While the GPT-3 was trained to know itself, it appears that GPT-4, for the moment, is not aware of it's own existance, so it's answers to these types of questions are likely untrustworthy. As Cursor are working directly with OpenAI on the development of this app, it's unlikely (but not impossible) for the app to be using a Microsoft model.

**Comment by SailFlorve** [comment]
Take a closer look, if you were a developer, you would definitely use GPT-3.5-Turbo. Its token cost is the cheapest, only one-tenth of Davinci003, and GPT4 limits 25 messages every three hours, which cannot support so many people using it at the same time. Moreover, the GPT4 cost is very expensive.

**Comment by killianMei** [comment]
> Take a closer look, if you were a developer, you would definitely use GPT-3.5-Turbo. Its token cost is the cheapest, only one-tenth of Davinci003, and GPT4 limits 25 messages every three hours, which cannot support so many people using it at the same time. Moreover, the GPT4 cost is very expensive.

Indeed, you can determine whether it is GPT4 by the number of supported Tokens, but I haven't tried it yet.

**Comment by truell20** [comment]
Cursor is currently based on GPT3.5, you can use GPT4 if you put in an API that has access, you'll be able to pay to use GPT4 if you'd like soon.
