### ISSUE TITLE
How to change the language of the editor back to english?

### ISSUE THREAD

**Issue by BingeCode** [getcursor/cursor#1610]
I just installed Cursor on macOS and was trying to correctly set up my themes when I was prompted with the installation of the german language pack. 
I accidentally clicked yes and now the whole editor is in German. I looked everywhere for the setting to change the language of the editor but to no success. I've looked in the user and workspace settings (CMD + ,) under "language" and "sprache" (german for language) as well as in the Cursor settings (Shift + CMD + J). 
Language setting nowhere to be found - am I blind?

**Comment by RickyWooo** [comment]
![截圖 2024-08-12 上午10 58 57](https://github.com/user-attachments/assets/44728be0-bb95-4ea0-9a98-ed00ea179bf3)

On macOS, Shift+Cmd+P to open the Command Palette, then type display...to modify the default display langauge.

**Comment by BingeCode** [comment]
Thank you so much!

**Comment by thehien93** [comment]
I has been trying setting like above. But can not change language to English. Cursor editor language is English but when using prompt by English but default response Japanese I don't know reason

**Comment by mrluisfer** [comment]
> I has been trying setting like above. But can not change language to English. Cursor editor language is English but when using prompt by English but default response Japanese I don't know reason

I think what you are looking for is a Cursor rule, you can edit it directly in the editor

<img width="624" alt="Image" src="https://github.com/user-attachments/assets/3c5ab8d9-f2c2-4f01-8926-9aa007b0adcc" />

 Or create the MDC file to create specific rules for each workspace in `.cursor/rules`

```mdc
---
description: AI Response
globs: 
alwaysApply: true
---

- Always responds in English
```

**Comment by Moulirichards** [comment]
thanks . was struggling a lot for a while .
