### ISSUE TITLE
Win7 环境启动后白屏

### ISSUE THREAD

**Issue by dboyct** [getcursor/cursor#163]
Win7操作系统，启动后白屏，无法显示任何内容

**Comment by mengzhongshuike** [comment]
If you don't know how to describe a problem in English, you can first describe it in Chinese and then use cursor to translate it into English.

**Comment by sfc9982** [comment]
Maybe related to the Electron and Chromium core the Cursor using.

**Comment by truell20** [comment]
Is this still a problem with the newest version? Could you send a screen recording? What operating system are you on?

**Comment by danperks** [comment]
This seemed to be a bug in the older version of Cursor when a users anti-virus got in the way. As the thread has gone somewhat stale, and with the reply for @dboyct, I'll consider this resolved.

Feel free to comment and we can reopen this if needed.
