### ISSUE TITLE
Extensions defined in devcontainer.json are not installing in Dev Container

### ISSUE THREAD

**Issue by tonsh** [getcursor/cursor#1634]
- Cursor Version: 0.39.5
- VSCode Version: 1.91.1
- Local OS Version: macOS 14.5
```
Version: 0.39.5
VSCode Version: 1.91.1
Commit: 274e2e5d572bd0b99449183635a0f94c7b9f54d0
Date: 2024-08-14T15:49:16.270Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

Some extensions that are defined in devcontainer.json are not installed when rebuild the container. 

devcontainer.json:
<img width="848" alt="Screenshot 2024-08-15 at 2 35 36 PM" src="https://github.com/user-attachments/assets/87063ee6-3e68-456a-9407-77fc83ad448f">

The installation failed for the extensions with the following error:
```This extension is disabled in this workspace because it is defined to run in the Remote Extension Host.```
<img width="1008" alt="Screenshot 2024-08-15 at 2 31 24 PM" src="https://github.com/user-attachments/assets/a46d90f9-7c6a-438c-a1ee-50ce4cc2a7b8">

Some similar issues existed in older version of VSCode，but it has already been fixed.
[Extensions defined in devcontainer.json are not installing](https://github.com/microsoft/vscode-remote-release/issues/8097)

**Comment by kyleboddy** [comment]
Does the `makefile` extension work while none of the Microsoft Python extensions work? It is possibly related to Pylance licensing issues.

https://forum.cursor.com/t/pylance-breaks-on-cursor-0-38-1/6920

**Comment by tonsh** [comment]
> Does the `makefile` extension work while none of the Microsoft Python extensions work? It is possibly related to Pylance licensing issues.
> 
> https://forum.cursor.com/t/pylance-breaks-on-cursor-0-38-1/6920

The `makefile` extension is work well.

I’m not sure if these two issues are related. The `pylance` extension can be  installed when I install it manually. (Press "Install in Dev Container: xxx@desktop-linux" button can be successfully installed)

**Comment by kyleboddy** [comment]
Got it, yeah. I ended up deleting the remote-ssh `.cursor-server` metadata directory which fixed the Git extension problem but that's obviously not the same workflow a container would use.

**Comment by tsdaemon** [comment]
I have the same issue. It was reported before, and there seems to be a workaround https://github.com/getcursor/cursor/issues/1382#issuecomment-2282219196. Although, I didn't try it myself.

**Comment by tonsh** [comment]
> I have the same issue. It was reported before, and there seems to be a workaround [#1382 (comment)](https://github.com/getcursor/cursor/issues/1382#issuecomment-2282219196). Although, I didn't try it myself.

I don’t think this is the same issue. The problem is that the Python extensions fail to install automatically in the devcontainer, even though it can be manually installed after the container rebuild. 
The extensions.json config file doesn’t seem to be very relevant for the devcontainer environment.

**Comment by tsdaemon** [comment]
> > I have the same issue. It was reported before, and there seems to be a workaround [#1382 (comment)](https://github.com/getcursor/cursor/issues/1382#issuecomment-2282219196). Although, I didn't try it myself.
> 
> I don’t think this is a good solution. The problem is that the Python extensions fail to install automatically in the devcontainer, even though it can be manually installed after the container rebuild. The extensions.json custom config file doesn’t seem to be very relevant for the devcontainer environment.

Not sure why is it not the same issue, descriptions are the same to me. `extensions.json` has to do with a workaround for this issue.

**Comment by matssk** [comment]
Some extensions install, some do not. For example ms-python.vscode-pylance does not install.

**Comment by AlejandroCN7** [comment]
I have the same problem.
