### ISSUE TITLE
代码无法完整显示

### ISSUE THREAD

**Issue by chenchuren** [getcursor/cursor#164]
代码无法完整显示

**Comment by bisslot** [comment]
> If you don't know how to describe a problem in English, you can first describe it in Chinese and then use cursor to translate it into English.

The issue he described is that the code generated in the cursor editor cannot be fully displayed.

**Comment by code2077** [comment]
ctrl + k     continue

**Comment by littlecay** [comment]
> 

but the successive code is likely to be wrong

**Comment by truell20** [comment]
Should be fixed in newest version 🙂 we changed cursor to output more code, let me know if this is still a problem
