### ISSUE TITLE
Interface issue: When opening the terminal, the Chat interface cannot be used properly.

### ISSUE THREAD

**Issue by dishuizhu** [getcursor/cursor#165]
Steps to reproduce the bug:
1. Open the editor.
2. Open the terminal within the editor.
3. Open Chat and start chatting.
4. When the Chat window overlaps with the terminal interface, clicking on Chat does not respond, but the terminal does.

System version: Windows 11: 22000.1455
Software version: Cursor: v0.1.3

**Comment by truell20** [comment]
Thanks for reporting -- Fixed in 0.1.5 :) try restarting the app to get the update
