### ISSUE TITLE
Changing `cmd+k` `cmd+shift+k` keyboard shortcut issue

### ISSUE THREAD

**Issue by 2nthony** [getcursor/cursor#1659]
recently switch back to cursor. This issue has actually been bothering me for a long time since I started to use Cursor.

---

**Is your feature request related to a problem? Please describe.**

Since `cmd+k` is a lot of things from VS Code, so I changed the shortcut to `cmd+i` and `cmd+shift+i`, and I'm facing some unexpected behaviour.

Get used to the new shortcut is a little painful :(
because I use `delete line(cmd+shift+k)` often, and I have a combo shortcut `cmd+k {anykey}` as my own "key" shortcuts.

**Describe the solution you'd like**

there are two solutions I hope (personally prefer the first one):

- revert all `cmd+k` `cmd+shift+k` to VS Code default, and the Cursor open edit shortcut change to `cmd i` by default, just like Copilot inline chat did. Means totally replace the Copilot extension.
- **fix the shortcuts in open edit popup and terminal.**

**Additional context**

this video shows, I changed to shortcut to `cmd+i` and `cmd+shift+i`, I can do `open edit` with these shortcuts. But when focusing on the edit popup, I only can do toggle via old shortcut `cmd+k` or `cmd+shift+k`.

https://github.com/user-attachments/assets/ed839ff7-c75f-459e-b2e3-4080b45c192a

this video basically the same issue as above but for terminal

https://github.com/user-attachments/assets/57504de0-0ad8-4da9-9525-45c2738af58c

---

an old issue: #672

**Comment by 2nthony** [comment]
NVM, I found the solution

**Comment by tjx666** [comment]
or you can try:

https://marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience

**Comment by 2nthony** [comment]
> or you can try:
> 
> [marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience](https://marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience)

that is great, I'll try

**Comment by kannwism** [comment]
> or you can try:
> 
> https://marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience

The link doesn't seem to work for me :(

**Comment by tjx666** [comment]
@kannwism https://marketplace.visualstudio.com/items?itemName=YuTengjing.vscode-classic-experience

**Comment by maximedupre** [comment]
What's the difference between "cmd+k" and "cmd+shift+k" anyway? Both seem to open up the edit panel.

So I simply removed the "cmd+shift+k" to retain the old VSC "delete line" behaviour.

**Comment by vkboo** [comment]
> @kannwism https://marketplace.visualstudio.com/items?itemName=YuTengjing.vscode-classic-experience

Perfectly solved my problem, thank you very much. ❤️

**Comment by markjfisher** [comment]
> or you can try:
> 
> https://marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience

I've raised an issue in your repo as this isn't working on Windows (and I assume Linux, but I don't have one handy to test on).

**Comment by mundane799699** [comment]
> What's the difference between the "cmd+k" and "cmd+shift+k" shortcuts anyway? Both seem to open up the edit panel.
> 
> So I simply removed the "cmd+shift+k" shortcut to retain the old VSC "delete line" behaviour.

me too

**Comment by sapter** [comment]
> What's the difference between the "cmd+k" and "cmd+shift+k" shortcuts anyway? Both seem to open up the edit panel.
> 
> So I simply removed the "cmd+shift+k" shortcut to retain the old VSC "delete line" behaviour.

Yes, but even after I've removed it, the behavior still opens the popup window instead of deleting the line...
Can you explain what else you did to make it work?
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/766f8e49-576b-4f79-a70a-bfe63bab4aa5" />

**Comment by neil-peirce** [comment]
Setting `Cursor: Open Edit (Command K)` and also `Open Composer as Bar` to be `Command+K` resolved this for me.

**Comment by palcisto** [comment]
> > or you can try:
> > https://marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience
> 
> The link doesn't seem to work for me :(

Thank you for sharing, this has definitely resolved all the keybinding issues I have had with Cursor. I was getting ready to "throw away" Cursor into the MacOS Trash can...

**Comment by arigon** [comment]
> [@kannwism](https://github.com/kannwism) https://marketplace.visualstudio.com/items?itemName=YuTengjing.vscode-classic-experience

How can I install this extension? The marketplace doesn't show the "Download Extension" link for the extension anymore as it should according to [the how to](https://www.cursor.com/how-to-install-extension)..

**Comment by damafeez** [comment]
This solution worked for me https://forum.cursor.com/t/shift-cmd-k-not-working-and-undefined-showing-in-terminal-hint/6393/2.

**Comment by fordooo** [comment]
> What's the difference between the "cmd+k" and "cmd+shift+k" shortcuts anyway? Both seem to open up the edit panel.
> 
> So I simply removed the "cmd+shift+k" shortcut to retain the old VSC "delete line" behaviour.

This is what worked for me

I wanted `cmd+shift+k` to delete line and `cmd+k` to still open the Cursor edit panel

1) `cmd+r` then `cmd+s` to open Keyboard Shortcuts
2) Search for "command shift k" in the search bar
3) Right click on the Cursor keybinding and click "Remove Keybinding"
