### ISSUE TITLE
The file tree isn't sync with file system.

### ISSUE THREAD

**Issue by Zhwt** [getcursor/cursor#166]
The IDE can't sense file / file system change.

When I modified a file outside of the IDE, it won't be able to tell that the file is being modified. If I choose to save at this time, all changes made externally will be lost.
Inside the file tree, there shoule be a "Refresh" or "Sync with disk" to reload file changes outside of the IDE. Now, if I added one or more files to the project using Windows Explorer, the IDE won't be able to detect them. The only way to make them "discovered" is to restart the IDE.

~~Also there could be a "Open in Explorer" option which can open the selected folder using system's default file manager.~~
Added in b14e01296e0bfbea026d0e3be20e29bbca964bdc

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
