### ISSUE TITLE
How to remove "code ." on Windows

### ISSUE THREAD

**Issue by ismailhozza** [getcursor/cursor#1676]
I am using Windows and command "code ." is associated with Cursor. I want remove it and revert to back to Visual Studio Code, so that "code ." launches VS Code. 

I have tried 

![image](https://github.com/user-attachments/assets/d796869c-8541-425f-92e5-9b56c1e5c938)

Uninstall 'cursor' command from PATH, but it does not help.

I want to associate 'cursor .' with Cursor and 'code .' with Visual Studio Code.

Thanks

**Comment by ismailhozza** [comment]
I have found solution for this...

Remove 'code' and 'code.cmd' from %userprofile%\AppData\Local\Programs\cursor\resources\app\bin

**Comment by rimoza** [comment]
Thank you for sharing the solution! I followed your steps by removing code and code.cmd from %userprofile%\AppData\Local\Programs\cursor\resources\app\bin, and it worked perfectly for me. Now, cursor . opens Cursor, and code . opens Visual Studio Code just as expected.

Thanks again for your help!

**Comment by DannJohnrem** [comment]
> I have found solution for this...
> 
> Remove 'code' and 'code.cmd' from %userprofile%\AppData\Local\Programs\cursor\resources\app\bin

this works for me. Thank you
