### ISSUE TITLE
Can the code generator in the editor access code from other files when generating code?

### ISSUE THREAD

**Issue by Hao1Zhang** [getcursor/cursor#168]
Hello, I am wondering if the code generator in the editor has the capability to access code from other files when generating code. Specifically, if there is a main.py file that has a main() function which calls another function located in a separate file, can the editor generate code for main.py based on that called function?

I have noticed that the code generator prompts and generates code based on the previous code in the current file, but I am curious if it has the ability to access code from other files as well.

Additionally, I would like to know how many tokens the code generator will read from one request. Is there a limit to the amount of code it can access at one time?

Thank you for your help.

**Comment by truell20** [comment]
Just hte current file for now, multi-file coming soon!

**Comment by danperks** [comment]
At the moment, Cursor's AI can use code from other files, but only when you tell it to, and only in the chat window. 
To keep discussion in one place, #460 is about the AI reading multiple files when generating code, and #369 is regarding the AI editing more than one file when it wants to make changes.
I'll close this issue to avoid duplication.
