### ISSUE TITLE
The JS/TS language service crashed 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by kr3t3n** [getcursor/cursor#1680]
Type: <b>Bug</b>

I am using the Composer and working via SSH on my replit project

VS Code version: Cursor 0.39.6 (a4f99b7dfb14460cb0bcebd9f6ac7ca158217920, 2024-08-19T00:03:08.275Z)
OS version: Darwin arm64 23.6.0
Modes:
Remote OS version: Linux x64 6.5.0-1025-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|18.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: b72472e4-e722-40e9-a26a-79d0eb9794cd-00-1x63bl89nhgy2.janeway.replit.dev|
|OS|Linux x64 6.5.0-1025-gcp|
|CPUs|AMD EPYC 7B13 (16 x 0)|
|Memory (System)|62.78GB (10.88GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.17.2
remotehub|Git|0.62.0
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
python|ms-|2023.22.1
vscode-pylance|ms-|2023.10.40

</details>

**Comment by danperks** [comment]
Hi, if you're still having this issue, please can you post a comment in #1888 to help keep the discussion in one thread for all JS/TS issues. Thanks!
