### ISSUE TITLE
Unable to input a second question in the chat function.

### ISSUE THREAD

**Issue by BeMax92** [getcursor/cursor#170]
When using the cursor's chat function, after the first answer is outputted, if you try to input another question, the page will freeze and you won't be able to input another question.
System: Windows 10
![image](https://user-images.githubusercontent.com/110655716/227080940-a80a8664-8b30-423d-a127-546085de7e5a.png)

**Comment by rahul3236** [comment]
@truell20 @raymond-ley can I assign this issue to myself

**Comment by truell20** [comment]
This should be fixed in 0.1.5 lmk if this is still a problem! @BeMax92 thanks for reporting
