### ISSUE TITLE
无法移除导入的项目

### ISSUE THREAD

**Issue by ZedCoding** [getcursor/cursor#171]
导入一个项目后想移除它 发现没有地方可以操作？！

**Comment by sfc9982** [comment]
> 导入一个项目后想移除它 发现没有地方可以操作？！

Translation: He has imported a workspace/project but cannot remove it, he want a way to remove it.

**Comment by terminalqo** [comment]
You are already proficient in using GPT-4, is it difficult for you to express yourself in English?

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
