### ISSUE TITLE
Indexing: Handshake Failed

### ISSUE THREAD

**Issue by thelazydogsback** [getcursor/cursor#1728]
Indexing my (Python) code shows "Handshake Failed"

![image](https://github.com/user-attachments/assets/8b6c4ea6-e4cf-4dc8-9799-7f6357f149c9)

Windows 11 Business
Version: 0.40.1
VSCode Version: 1.91.1
Commit: 58b91712431381a1b75817cd3437cee35dddcb30
Date: 2024-08-24T02:52:24.035Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by solbolt2** [comment]
Mine just started doing this too.
I see old posts of this happening. Figured I''d try to find a more recent one to see if I'm the only one.
<img width="825" alt="Screenshot 2024-08-28 at 3 36 23 AM" src="https://github.com/user-attachments/assets/6ffab568-2b41-409f-893d-eedfe358d60a">

I was in the middle of something too.
Guess no cursor tonight.

**Comment by VinayChaudhari1996** [comment]
Hi,

It worked perfectly fine till yesterday. (30-08-2024)

Today (31-08-2024) I updated the cursor version to the latest and got following issue,

> How to rollback Cursor to previous version or what are the other ways ? 

![image](https://github.com/user-attachments/assets/a67be792-0a48-4e06-9209-b3067653fe17)

Thanks,

**Comment by VinayChaudhari1996** [comment]
> Mine just started doing this too.
> 
> I see old posts of this happening. Figured I'd try to find a more recent post to see if I'm the only one. <img alt="Screenshot 2024-08-28 at 3 36 23 AM" width="825" src="https://private-user-images.githubusercontent.com/174697017/362205548-6ffab568-2b41-409f-893d-eedfe358d60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjA1NTQ4LTZmZmFiNTY4LTJiNDEtNDA5Zi04OTNkLWVlZGZlMzU4ZDYwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzhhMDkxYWVjYTIwNDVkYWMxMGViM2EyMzJlNGQwMTdiNDUzZjY4ZWY2NTVmZWVjZjZlNjZmMjgxNWM4OTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8HOES8EIFBjDLbCZYfRb_LDoPo6xu3MMj7WwjTYz0rI">
> 
> I'm on a Mac accessing an Ubuntu server on my network via SSH. I tried Deleting my index to see if maybe it got too full from a previous project. Just basic stuff to double check. Haven't had any problems up until now. Restarted my server. Restarted Cursor. Same message.
> 
> Check back here later.
> 
> I was in the middle of something too. Guess no cursor tonight.
> 
> Also what happened to the blue progress bar? The little " ... " is too ambiguous. I like being able too see the progress personally. Unless it's just not loading for me.
> 
> Seems to be working on my other server. I did change some network settings DNS stuff on the problem rig. But it was working fine even after changing those settings. Not sure if that may have done something though. Gonna try reverting that and check back. <img alt="Screenshot 2024-08-28 at 3 58 34 AM" width="832" src="https://private-user-images.githubusercontent.com/174697017/362213457-cb5d9b97-fdbf-4399-979b-bdb92154685b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjEzNDU3LWNiNWQ5Yjk3LWZkYmYtNDM5OS05NzliLWJkYjkyMTU0Njg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDdjMGYzNjFiYTFhN2NkOTA5MGFhOTQ0MzY1OTY4MmVmMDYwNzU4NGMyMmYyMmI3MjNiMjA1M2QxMTk0YTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fcSUc-dKnfwsfLCSqLkISDKQfUpsZsX53dLucEvKUrU">
> 
> While messing with Pi-hole I guess I disabled this. <img alt="Screenshot 2024-08-28 at 4 30 02 AM" width="508" src="https://private-user-images.githubusercontent.com/174697017/362224733-6bfd4a38-1e65-47d2-abd6-1314a2f8d78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjI0NzMzLTZiZmQ0YTM4LTFlNjUtNDdkMi1hYmQ2LTEzMTRhMmY4ZDc4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGQxOGJhZTQxZjdlNjllODIyOTZmNTQ2NDVmOGU0ODE0ZTMyOGM0YTFmMjQzMTVhZWYwZjUyODlmN2MxMTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5p26GRpJ0fOun8-kLNuLRfOXUwwEp0LN603T7LwlVw">
> 
> Seems to be working now. <img alt="Screenshot 2024-08-28 at 4 31 41 AM" width="820" src="https://private-user-images.githubusercontent.com/174697017/362225270-13be636b-2c23-47eb-8ced-8e33b543152a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjI1MjcwLTEzYmU2MzZiLTJjMjMtNDdlYi04Y2VkLThlMzNiNTQzMTUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTNmMTg5YmZjNDBlMmZlYzI4Y2Q0MjQzMDM2MWIwM2JmZDRmNzBlMjAxYTI1NTdmYWE4MjI0MThiOGRmOWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DqxHNxrVLMMLNUnUYTAEo7RqqbyaqB0dRbSpXkOl2XA">
> 
> I'll leave this here just in case it helps someone. Goodluck
> 
> -Sol

It works fine for me with a smartphone 5g network hotspot. but when I switch it to WIFI network nothing is working. Do you know how you fixed the DNS issue ?

**Comment by solbolt2** [comment]
> > Mine just started doing this too.
> > I see old posts of this happening. Figured I'd try to find a more recent post to see if I'm the only one. <img alt="Screenshot 2024-08-28 at 3 36 23 AM" width="825" src="https://private-user-images.githubusercontent.com/174697017/362205548-6ffab568-2b41-409f-893d-eedfe358d60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjA1NTQ4LTZmZmFiNTY4LTJiNDEtNDA5Zi04OTNkLWVlZGZlMzU4ZDYwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzhhMDkxYWVjYTIwNDVkYWMxMGViM2EyMzJlNGQwMTdiNDUzZjY4ZWY2NTVmZWVjZjZlNjZmMjgxNWM4OTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8HOES8EIFBjDLbCZYfRb_LDoPo6xu3MMj7WwjTYz0rI">
> > I'm on a Mac accessing an Ubuntu server on my network via SSH. I tried Deleting my index to see if maybe it got too full from a previous project. Just basic stuff to double check. Haven't had any problems up until now. Restarted my server. Restarted Cursor. Same message.
> > Check back here later.
> > I was in the middle of something too. Guess no cursor tonight.
> > Also what happened to the blue progress bar? The little " ... " is too ambiguous. I like being able too see the progress personally. Unless it's just not loading for me.
> > Seems to be working on my other server. I did change some network settings DNS stuff on the problem rig. But it was working fine even after changing those settings. Not sure if that may have done something though. Gonna try reverting that and check back. <img alt="Screenshot 2024-08-28 at 3 58 34 AM" width="832" src="https://private-user-images.githubusercontent.com/174697017/362213457-cb5d9b97-fdbf-4399-979b-bdb92154685b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjEzNDU3LWNiNWQ5Yjk3LWZkYmYtNDM5OS05NzliLWJkYjkyMTU0Njg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDdjMGYzNjFiYTFhN2NkOTA5MGFhOTQ0MzY1OTY4MmVmMDYwNzU4NGMyMmYyMmI3MjNiMjA1M2QxMTk0YTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fcSUc-dKnfwsfLCSqLkISDKQfUpsZsX53dLucEvKUrU">
> > While messing with Pi-hole I guess I disabled this. <img alt="Screenshot 2024-08-28 at 4 30 02 AM" width="508" src="https://private-user-images.githubusercontent.com/174697017/362224733-6bfd4a38-1e65-47d2-abd6-1314a2f8d78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjI0NzMzLTZiZmQ0YTM4LTFlNjUtNDdkMi1hYmQ2LTEzMTRhMmY4ZDc4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGQxOGJhZTQxZjdlNjllODIyOTZmNTQ2NDVmOGU0ODE0ZTMyOGM0YTFmMjQzMTVhZWYwZjUyODlmN2MxMTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5p26GRpJ0fOun8-kLNuLRfOXUwwEp0LN603T7LwlVw">
> > Seems to be working now. <img alt="Screenshot 2024-08-28 at 4 31 41 AM" width="820" src="https://private-user-images.githubusercontent.com/174697017/362225270-13be636b-2c23-47eb-8ced-8e33b543152a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjI1MjcwLTEzYmU2MzZiLTJjMjMtNDdlYi04Y2VkLThlMzNiNTQzMTUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTNmMTg5YmZjNDBlMmZlYzI4Y2Q0MjQzMDM2MWIwM2JmZDRmNzBlMjAxYTI1NTdmYWE4MjI0MThiOGRmOWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DqxHNxrVLMMLNUnUYTAEo7RqqbyaqB0dRbSpXkOl2XA">
> > I'll leave this here just in case it helps someone. Goodluck
> > -Sol
> 
> It works fine for me with a smartphone 5g network hotspot. but when I switch it to WIFI network nothing is working. Do you know how you fixed the DNS issue ?




My issue was happening because I switched the DNS on my Ubuntu server. I was trying to have PIhole Resolve addresses on my network.
I was trying to setup name spaces for PI-hole. Which I need to switch/redirect in my router but didn't do it.
Not sure if you changed any thing with the resolve.conf.
Not even sure which OS you're running. Linux? Windows? Mac?

I still had internet connection. But I guess Cursor has to be able to resolve to be able to create the index? Thus the handshake? Atleast that was what my issue was.

I'm just guessing. I mean it makes sense since they have to be able to reach their API. But it probably requires the proper DNS resolve as well.

It could be something in the router? Did you change any settings with it?
I'm just not sure what your setup is or what you were doing before it started giving you problems. Was it just the update?

It's possible that the update may have changed how it interacts with the DNS. If you had any pre-existing network configurations it's possible that something with your network setup may have became an issue after the update. This is assuming your using Linux though. Maybe something else you have setup got in the way because of the update. Where as it might not have been a problem before but the update possibly changed the protocol.

I'm just guessing as I don't have a lot of information to go off.
If it doesn't work on the wifi then it may be something along those lines.


Here are some suggestions to troubleshoot:

1: DNS Configuration:

Check your DNS settings on the device you're using Cursor on.
If you're using a custom DNS (like Pi-hole), ensure it's configured correctly.
Try temporarily setting your DNS to a public DNS server (e.g., 8.8.8.8 for Google) to see if it resolves the issue.


2:Network Settings:

Compare the settings between your 5G hotspot (which works) and your WiFi network.
Check if your router has any firewall or content filtering settings that might be blocking Cursor's connections.


3:Cursor-specific checks:

Ensure Cursor has the necessary network permissions on your device.
Try clearing Cursor's cache or reinstalling the application.


4:General troubleshooting:

Restart your router and the device you're using Cursor on.
Check if other applications that require internet access are working correctly on the WiFi network.



If you've made any recent changes to your network setup or if this started after a Cursor update, consider reverting those changes to see if it resolves the issue.
Can you provide more information about your operating system and any recent changes you've made to your network or device settings? This would help in providing more specific advice.

-Sol

**Comment by VinayChaudhari1996** [comment]
> > > Mine just started doing this too.
> > > I see old posts of this happening. Figured I'd try to find a more recent post to see if I'm the only one. <img alt="Screenshot 2024-08-28 at 3 36 23 AM" width="825" src="https://private-user-images.githubusercontent.com/174697017/362205548-6ffab568-2b41-409f-893d-eedfe358d60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjA1NTQ4LTZmZmFiNTY4LTJiNDEtNDA5Zi04OTNkLWVlZGZlMzU4ZDYwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzhhMDkxYWVjYTIwNDVkYWMxMGViM2EyMzJlNGQwMTdiNDUzZjY4ZWY2NTVmZWVjZjZlNjZmMjgxNWM4OTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8HOES8EIFBjDLbCZYfRb_LDoPo6xu3MMj7WwjTYz0rI">
> > > I'm on a Mac accessing an Ubuntu server on my network via SSH. I tried Deleting my index to see if maybe it got too full from a previous project. Just basic stuff to double check. Haven't had any problems up until now. Restarted my server. Restarted Cursor. Same message.
> > > Check back here later.
> > > I was in the middle of something too. Guess no cursor tonight.
> > > Also what happened to the blue progress bar? The little " ... " is too ambiguous. I like being able too see the progress personally. Unless it's just not loading for me.
> > > Seems to be working on my other server. I did change some network settings DNS stuff on the problem rig. But it was working fine even after changing those settings. Not sure if that may have done something though. Gonna try reverting that and check back. <img alt="Screenshot 2024-08-28 at 3 58 34 AM" width="832" src="https://private-user-images.githubusercontent.com/174697017/362213457-cb5d9b97-fdbf-4399-979b-bdb92154685b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjEzNDU3LWNiNWQ5Yjk3LWZkYmYtNDM5OS05NzliLWJkYjkyMTU0Njg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDdjMGYzNjFiYTFhN2NkOTA5MGFhOTQ0MzY1OTY4MmVmMDYwNzU4NGMyMmYyMmI3MjNiMjA1M2QxMTk0YTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fcSUc-dKnfwsfLCSqLkISDKQfUpsZsX53dLucEvKUrU">
> > > While messing with Pi-hole I guess I disabled this. <img alt="Screenshot 2024-08-28 at 4 30 02 AM" width="508" src="https://private-user-images.githubusercontent.com/174697017/362224733-6bfd4a38-1e65-47d2-abd6-1314a2f8d78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjI0NzMzLTZiZmQ0YTM4LTFlNjUtNDdkMi1hYmQ2LTEzMTRhMmY4ZDc4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGQxOGJhZTQxZjdlNjllODIyOTZmNTQ2NDVmOGU0ODE0ZTMyOGM0YTFmMjQzMTVhZWYwZjUyODlmN2MxMTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5p26GRpJ0fOun8-kLNuLRfOXUwwEp0LN603T7LwlVw">
> > > Seems to be working now. <img alt="Screenshot 2024-08-28 at 4 31 41 AM" width="820" src="https://private-user-images.githubusercontent.com/174697017/362225270-13be636b-2c23-47eb-8ced-8e33b543152a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMyNjksIm5iZiI6MTcyNTE3Mjk2OSwicGF0aCI6Ii8xNzQ2OTcwMTcvMzYyMjI1MjcwLTEzYmU2MzZiLTJjMjMtNDdlYi04Y2VkLThlMzNiNTQzMTUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTNmMTg5YmZjNDBlMmZlYzI4Y2Q0MjQzMDM2MWIwM2JmZDRmNzBlMjAxYTI1NTdmYWE4MjI0MThiOGRmOWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DqxHNxrVLMMLNUnUYTAEo7RqqbyaqB0dRbSpXkOl2XA">
> > > I'll leave this here just in case it helps someone. Goodluck
> > > -Sol
> > 
> > 
> > It works fine for me with a smartphone 5g network hotspot. but when I switch it to WIFI network nothing is working. Do you know how you fixed the DNS issue ?
> 
> My issue was happening because I switched the DNS on my Ubuntu server. I was trying to have PIhole Resolve addresses on my network. I was trying to setup name spaces for PI-hole. Which I need to switch/redirect in my router but didn't do it. Not sure if you changed any thing with the resolve.conf. Not even sure which OS you're running. Linux? Windows? Mac?
> 
> I still had internet connection. But I guess Cursor has to be able to resolve to be able to create the index? Thus the handshake? Atleast that was what my issue was.
> 
> I'm just guessing. I mean it makes sense since they have to be able to reach their API. But it probably requires the proper DNS resolve as well.
> 
> It could be something in the router? Did you change any settings with it? I'm just not sure what your setup is or what you were doing before it started giving you problems. Was it just the update?
> 
> It's possible that the update may have changed how it interacts with the DNS. If you had any pre-existing network configurations it's possible that something with your network setup may have became an issue after the update. This is assuming your using Linux though. Maybe something else you have setup got in the way because of the update. Where as it might not have been a problem before but the update possibly changed the protocol.
> 
> I'm just guessing as I don't have a lot of information to go off. If it doesn't work on the wifi then it may be something along those lines.
> 
> Here are some suggestions to troubleshoot:
> 
> 1: DNS Configuration:
> 
> Check your DNS settings on the device you're using Cursor on. If you're using a custom DNS (like Pi-hole), ensure it's configured correctly. Try temporarily setting your DNS to a public DNS server (e.g., 8.8.8.8 for Google) to see if it resolves the issue.
> 
> 2:Network Settings:
> 
> Compare the settings between your 5G hotspot (which works) and your WiFi network. Check if your router has any firewall or content filtering settings that might be blocking Cursor's connections.
> 
> 3:Cursor-specific checks:
> 
> Ensure Cursor has the necessary network permissions on your device. Try clearing Cursor's cache or reinstalling the application.
> 
> 4:General troubleshooting:
> 
> Restart your router and the device you're using Cursor on. Check if other applications that require internet access are working correctly on the WiFi network.
> 
> If you've made any recent changes to your network setup or if this started after a Cursor update, consider reverting those changes to see if it resolves the issue. Can you provide more information about your operating system and any recent changes you've made to your network or device settings? This would help in providing more specific advice.
> 
> -Sol

Thank you for your valuable insights and observation. I will look into it for my windows 11 machine :)

**Comment by thelazydogsback** [comment]
Same behavior with 0.40.3.
The only difference is that rather than failing immediately, now it seems to chug along for a minute or two with
**Setting up indexing...**  (ostensibly showing progress)
before I get the handshake error.

**Comment by VinayChaudhari1996** [comment]
Hello Everyone, 

### Here is a working solution , please try it and let me know. it is working for me :) 


https://www.linkedin.com/posts/vinay-chaudhari-ai_cursor-prototyping-productdevelopment-activity-7236388125227290624-8jSm?utm_source=share&utm_medium=member_android

**Comment by danperks** [comment]
Hey, anyone still facing this, please can you comment your OS and Cursor info in #2035, thanks!

**Comment by Ma-1003** [comment]
I'm a Chinese student. When I connect to my school's server via SSH to run programs, it prompts "handshake failed". However, when I open the local project with cursor, indexing works normally. I think it's a server issue, but I don't have the permission to modify the server's DNS. Do you have any suggestions or ideas to solve this problem? Thank you! :)
