### ISSUE TITLE
TS services crashing

### ISSUE THREAD

**Issue by jonasms** [getcursor/cursor#1730]
Type: <b>Bug</b>

"JS/TS language features" are constantly "Initializing"

VS Code version: Cursor 0.40.0 (0f6d62072f1bd060caf2876ac639b7d9541add00, 2024-08-22T04:12:20.364Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|36.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gitlens|eam|15.3.1
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
playwright|ms-|1.1.7
debugpy|ms-|2024.6.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vs-code-prettier-eslint|rve|6.0.0
sort-lines|Tyr|1.11.0
gitblame|wad|11.0.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by danperks** [comment]
Hi, please can you repost this in #1888 as a comment, as I am collating all JS/TS issues there for now, thanks!
