### ISSUE TITLE
Azure API Key not working

### ISSUE THREAD

**Issue by kemeny** [getcursor/cursor#1732]
With latest update azure openAI key not working. no changes on my configuration. API key works. 
macOS 15 
Version: 0.40.1
VSCode Version: 1.91.1
Commit: 58b91712431381a1b75817cd3437cee35dddcb30
Date: 2024-08-24T02:52:24.035Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 24.0.0

**Comment by guocity** [comment]
same here, can't get azure api working
![image](https://github.com/user-attachments/assets/4b708374-6ed5-43e3-9772-3237ae60cdac)

**Comment by gcdsss** [comment]
remember using correct deploy name, it is works on me

**Comment by guocity** [comment]
I can't find deployment name, what is the deployment name for this?

curl -X POST "https://models.inference.ai.azure.com/chat/completions" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -d '{
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "What is the capital of France?"
            }
        ],
        "model": "gpt-4o"
    }'

**Comment by kemeny** [comment]
I got it to work, but still cant run vision using GPT4

**Comment by danperks** [comment]
Looks like this is resolved, by ensuring the deploy name is correct.
#1922 is being used to track further Azure support.
