### ISSUE TITLE
Cursor had been the go to tool for software engineers but what about research engineer?

### ISSUE THREAD

**Issue by Am0stafa** [getcursor/cursor#1745]
The most helpful feature would be the ability to chat with PDFs so please support sending PDFs in chat
<img width="515" alt="Screenshot 2024-08-28 at 2 44 10 AM" src="https://github.com/user-attachments/assets/0759e2f0-e583-48cb-a2e8-03eab323c140">

**Comment by danperks** [comment]
Duplicate of #1894
