### ISSUE TITLE
Can't sign in by Google Oauth and composer is Cancelled

### ISSUE THREAD

**Issue by Tzyito** [getcursor/cursor#1765]
First problem: 
1. When I log in through Google, cursor cannot recognize my login status. I had to log in via email and password

Second problem: 
![image](https://github.com/user-attachments/assets/922018d1-9185-471c-baa1-7deb96ee9f71)
1. I can't use composer and chat. it was sudden

System Version：OS: mac 14.5
Cursor Version：the latest version in website

**Comment by MakeFunG** [comment]
Is the second question solved?

**Comment by Tzyito** [comment]
> Is the second question solved?

i guess it's probably the VPN node. just change the ip and work it

**Comment by MakeFunG** [comment]
> > Is the second question solved?
> 
> i guess it's probably the VPN node. just change the ip and work it

Yes, because some of the models in the free version are limited in the number of times, and after they run out, they will come back with "cancelled" and no longer work
