### ISSUE TITLE
Stucking with Connection Failed Error

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [getcursor/cursor#1768]
1) Screenshot of the problem
<img width="500" alt="image" src="https://github.com/user-attachments/assets/8082caac-ebcb-4dea-896c-026151c7c962">

2) Operating system
MacOS Sonoma 14.2.1
3) The error pops out after using a few days when clicking "cmd + K". When I switch to models with unlimited times, e.g., `gpt-3.5`, the error still exists. I have checked my internet and VPN, they are all fine.

 Please help me with this issue. Thanks in advance!

**Comment by z333d** [comment]
This seems to be due to the lack of. NET, and the automatic installation fails due to network reasons. You need to install it manually, and then change the configuration. You can refer to this article to deal with it:
https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net
![image](https://github.com/user-attachments/assets/20cefef8-ccea-4f20-9165-a3cc00707dc6)

**Comment by AlonzoLeeeooo** [comment]
> This seems to be due to the lack of. NET, and the automatic installation fails due to network reasons. You need to install it manually, and then change the configuration. You can refer to this article to deal with it: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net ![image](https://private-user-images.githubusercontent.com/11628392/363083081-20cefef8-ccea-4f20-9165-a3cc00707dc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDQwMTIsIm5iZiI6MTcyNTAwMzcxMiwicGF0aCI6Ii8xMTYyODM5Mi8zNjMwODMwODEtMjBjZWZlZjgtY2NlYS00ZjIwLTkxNjUtYTNjYzAwNzA3ZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA3NDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDkxNzVlN2ZiNjY5YjJhODQ3YzM2Nzk5NzJjNzFjMjI2ZDI5ZWY1Yjc2ODNjMTYzMzhkNDZiMjgzZjU1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P1qUNYbOefDZoc2GbGpSZCyD1YcWEbOhMIpzNqG6Ls8)

Thanks for responding! I'll check and reply you.

**Comment by AlonzoLeeeooo** [comment]
This works! Thanks!
