### ISSUE TITLE
The file content cannot be displayed after SSH connection

### ISSUE THREAD

**Issue by yeloveyou** [getcursor/cursor#177]
Thank you very much. I encountered a problem while using Cursor to connect to remote Ubuntu 20.04 via SSH on Windows. When I open a code file, the code cannot be displayed in the Cursor interface. Is it because the code is too long? As shown in the pictures, one is my original code file and the other is the Cursor code file.
![image](https://user-images.githubusercontent.com/51388802/227135425-474b45fa-c650-434d-ac06-f3fde8c9576f.png)
![image](https://user-images.githubusercontent.com/51388802/227135455-b12fe021-a834-41cd-bd10-76ace6594584.png)

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
