### ISSUE TITLE
deepseek-coder does not support custom base URL configuration.

### ISSUE THREAD

**Issue by Mgrsc** [getcursor/cursor#1774]
I am using cursor version 0.40.3 on win11. When I use a custom openai base url, deepseek-chat follows the base url, but deepseek-coder does not follow it and defaults to requesting api.deepseek.com.
![image](https://github.com/user-attachments/assets/494dc43d-bc11-4dad-85c0-00915b9b1596)
![image](https://github.com/user-attachments/assets/dbc2d02f-a46e-43c1-89b5-f232521a0db4)

**Comment by lonrencn** [comment]
I have a same issue.
