### ISSUE TITLE
Can we use Cursor in cmd or linux command

### ISSUE THREAD

**Issue by cdzm** [getcursor/cursor#178]
Sometimes, we use other IDE, for example. Can we use it directly in terminal?

**Comment by truell20** [comment]
Yep! Try pulling up the command palette and searching for "install cursor..."

**Comment by pathikg** [comment]
hey @truell20 
there's no option to install the same in the command pallete
![image](https://github.com/getcursor/cursor/assets/55437218/30fbb2ea-5931-4733-8789-15efe3062ecc)

![image](https://github.com/getcursor/cursor/assets/55437218/c150a9b6-0106-4526-a1cc-7752f909c8c1)
