### ISSUE TITLE
Auto-complete git commit messages

### ISSUE THREAD

**Issue by SteveYuOWO** [getcursor/cursor#1787]
As a developer, I often find myself frustrated when trying to craft meaningful and concise Git commit messages.
I would like to see an auto-complete feature for Git commit messages integrated into the existing commit workflow.

Add a button to the red box for generating concise git commit messages automatically

<img width="406" alt="image" src="https://github.com/user-attachments/assets/f9011188-f7bb-425e-83f3-101e762734a1">

**Comment by Am0stafa** [comment]
Amazing

**Comment by danielmahon** [comment]
Duplicate of https://github.com/getcursor/cursor/issues/1298? Which is implemented as of `0.43.4`
