### ISSUE TITLE
Cursor blurry on Wayland

### ISSUE THREAD

**Issue by rober-m** [getcursor/cursor#1789]
Everything in Cursor is blurry, which makes it impossible to use.

This is a common issue when running X11 apps on Wayland. Interestingly enough, this was solved on VSCode (and Electron and Chromium apps) a long time ago. So, I'm a bit puzzled as to why Cursor didn't inherit that capability from the start.

Please enable Ozone-Wayland on Cursor so I can use it! :pray:

**Comment by tmlye** [comment]
try `export ELECTRON_OZONE_PLATFORM_HINT=auto`, that worked for me

**Comment by rober-m** [comment]
That solved it, thank you @tmlye!
