### ISSUE TITLE
VSCode extension for Cursor

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [getcursor/cursor#18]
I'm not sure about the long term plan for Cursor as an IDE, but currently it lacks a lot of functionality that I use in VSCode. It might make sense for it to be an extension for VSCode rather than a whole new IDE.

**Comment by truell20** [comment]
what features do you miss the most from vscode?

**Comment by dhruv-anand-aintech** [comment]
Some extensions and features of VSCode I use:
- Jupyter
- Python env manager
- Black Formatter for Python
- Github (pull requests and issues)
- AWS
- Google Cloud Code
- SSH
- Project Manager
- Themes Library

I'm sure each person has their list of pet features that they'll not want to move to a different IDE without.

Integrating LLMs into coding workflows should not require a brand new IDE (as github copilot has demonstrated). Features like Chat with code, edit code should ideally just be additions to the right click context menu.

IMO It'll be better to build this on top of the VSCode project.

**Comment by truell20** [comment]
Appreciate the feedback here! We decided to switch to building off of a fork of VSCode instead of our own handrolled Codemirror editor. Think this will allow us to focus on building the AI features instead of reinventing the wheel.

Lmk if you love this or hate it or have any feedback 🙂

**Comment by truell20** [comment]
(gonna close this so I can organize bugs, but please keep the convo going!)

**Comment by dhruv-anand-aintech** [comment]
> Appreciate the feedback here! We decided to switch to building off of a fork of VSCode instead of our own handrolled Codemirror editor. Think this will allow us to focus on building the AI features instead of reinventing the wheel.
> 
> Lmk if you love this or hate it or have any feedback 🙂

Great decision! Looking forward to what you build!
