### ISSUE TITLE
Sign in/Sign up problem

### ISSUE THREAD

**Issue by headrickleonard** [getcursor/cursor#1804]
Dear Cursor Support Team,
I am writing to report an issue I'm encountering when attempting to log in or sign up for an account on your platform.

## Steps to Reproduce:

1) I navigate to the Cursor.ai login/signup page.
2) I enter my credentials (if logging in) or fill out the signup form with my information or choose any auth provider.
3) When I click the submit button, the browser stops responding.
4) After a short while, the browser displays an error message: "ERR_CONNECTION_RESET" 
5) If i select Auth providers after i have just granted access to them the app stops and cannot redirect.

 **NB: Am not having trouble with internet connection**

## Additional Information:

> I am located in Tanzania
> I am using a windows 10 machine, Google Chrome Version 128.0.6613.86 (Official Build) (64-bit)
##
<h3 style="text-align:center" > I don't really think if this needs a screenshot but in case it does ,here it is, </h3>

![curor error](https://github.com/user-attachments/assets/60edc259-9987-4604-b2a6-81cdab4c7af7)

I would appreciate it if you could investigate this issue and advise on how to resolve it. Please let me know if you require any further information from my end.

**Comment by Simlex** [comment]
Hello @headrickleonard Try to add www to the URL. I had this issue to, and got it resolved by doing that.
Screenshot below:

![image](https://github.com/user-attachments/assets/774eba56-7fca-413f-af00-ac60813edaf8)

**Comment by headrickleonard** [comment]
Thanks @Simlex ,I've tried and the issue is resolved

**Comment by prantomollick** [comment]
![image](https://github.com/user-attachments/assets/21fdcae0-da50-4eb7-a443-a31b2e376f40)
I am also not able login cursor into my windows machine?

**Comment by Solid-Victor** [comment]
this was really helpful

**Comment by nielslange** [comment]
> I am also not able login cursor into my windows machine?

@prantomollick I don't have access to Windows, but on Mac, the Cursor settings are located at `Cursor » Settings » Cursor Settings`:

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/20045a30-2140-4be7-b90b-5af0885e8a67" />

**Comment by ahmed-abdat** [comment]
![Image](https://github.com/user-attachments/assets/d481db3d-eedb-4bab-90ce-bbb389bcaa1e)

can any one help me i try to sign up and after clicking to sign up it show me this screen !

**Comment by olaoyeayomide** [comment]
Thank you this was helpful

**Comment by songcook-git** [comment]
sign up is restriced.

**Comment by siyfa** [comment]
adding www to the URL works

**Comment by Ishola20** [comment]
i cant login to cursor

**Comment by Vonresc-code111** [comment]
I can't log in to Cursor from installed application. When I click the "Yes, log in" button in browser nothing happens.

<img width="1028" height="659" alt="Image" src="https://github.com/user-attachments/assets/f3fd6a86-2e6f-427d-990f-1f263eeb9b35" />


<img width="788" height="175" alt="Image" src="https://github.com/user-attachments/assets/0b24cbda-4b12-4302-9caa-b9f54c2078d2" />

**Comment by hor1ss** [comment]
Тоже не могу войти
