### ISSUE TITLE
Codebase Indexing Handshake Failed

### ISSUE THREAD

**Issue by MikeTheBard** [getcursor/cursor#1809]
![y2rj1MQ](https://github.com/user-attachments/assets/80c9f2c8-c550-450b-945d-354729d672cb)

Windows 10

I had been working with Cursor Composer on a project. Today I noticed that it stopped being aware of the codebase. I checked and today it's "Setting up indexing" for a long time and then it says "Handshaking failed."

I cannot get it to re-index my project no matter what I've tried (deleting index, restarting, starting as admin, etc.).

Composer is now useless as it has no context.

**Comment by Boardtale** [comment]
Same, Working this morning, restarted computer before it finilized and it won't work now. And I just wanted to give it a go. This is not good start :P And a day of free pro wasted.

**Comment by Tobarrientos2** [comment]
I'm having problems too due to the new version updated yesterday. The index is not working, and this is causing it not to load any responses from any model. Literally, Cursor AI cannot be used.

**Comment by houzixiashanxiedaima** [comment]
Try to logout and re-login your account. I just solved this problem by this way.

**Comment by georgeliu1998** [comment]
Logging out and back in solved the issue for me.

**Comment by khan7sh** [comment]
Please if somebody has a solution to this issue please let me know, I have tried to logging out and back and still the same

**Comment by mrpastewart** [comment]
yeah same here

**Comment by katawasiya** [comment]
the same

**Comment by DirkCohereHealth** [comment]
Same issue here

**Comment by pinion** [comment]
Why is it taking so long to respond? This is a paid service that this bug is rendering useless.

**Comment by danperks** [comment]
Hey, sorry for everyone facing this, the devs have been notified! Please comment in #2035 with your OS and Cursor info.

**Comment by phcodesage** [comment]
Logout and login via browser fixes this issue

**Comment by matheusmpedrosa** [comment]
I'm still facing this issue. Logout and login via browser didn't solve.

**Comment by wishborn** [comment]
Just noticed I am getting this issue as well. I had noticed a huge degradation in response quality before I saw the notice the codebase wasn't indexed. I have tried everything mentioned in this thread and still getting this issue. This is a bit of a critical issue.

**Comment by Quentintin** [comment]
Same on my side. I guess something wrong on their side.

**Comment by guustgoossens** [comment]
Same here

**Comment by redpredator8** [comment]
Same here Handshake Failed, Cursor fix this shit we are paying customers...

**Comment by maktheus** [comment]
Any update

**Comment by NewtonCookie** [comment]
Same here

**Comment by cheremovsky** [comment]
+1

**Comment by amdjedbens** [comment]
still same issue

**Comment by anandpathak** [comment]
same here.

**Comment by samitooooo** [comment]
me too.  i guess a lot of us have the same problem today

**Comment by ianpogi5** [comment]
I just paid for pro account yesterday so I can try cursor. This is pushing me back to windsurf.

**Comment by levi-berkowitz** [comment]
Same here
```
Version: 0.48.6 (Universal)
VSCode Version: 1.96.2
Commit: 1649e229afdef8fd1d18ea173f063563f1e722e0
Date: 2025-03-31T05:01:56.506Z
Electron: 34.3.4
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.3.0
```

**Comment by amdjedbens** [comment]
> me too. i guess a lot of us have the same problem today

on the Cursor status page, it doesn't indicate anything: https://status.cursor.com/

**Comment by samitooooo** [comment]
did anyone also update before starting? (and has early access turned on)

Version: 0.48.6
VSCode Version: 1.96.2
Commit: 1649e229afdef8fd1d18ea173f063563f1e722e0
Date: 2025-03-31T04:59:09.581Z
Electron: 34.3.4
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.0.0

**Comment by VaDominikKienzler** [comment]
Same here, stopped working after the update, Clicking on "See all included files" also just tells me to create a file

Version: 0.48.6 (user setup)
VSCode Version: 1.96.2
Commit: 1649e229afdef8fd1d18ea173f063563f1e722e0
Date: 2025-03-31T05:21:50.407Z
Electron: 34.3.4
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by NewtonCookie** [comment]
I found that disabling http2 in the settings worked.

**Comment by ibushong** [comment]
> I found that disabling http2 in the settings worked.

This worked for me too. How in the world did you figure that out?

**Comment by samitooooo** [comment]
> I found that disabling http2 in the settings worked.

you are a magician lol i am speechless

**Comment by NewtonCookie** [comment]
> I found that disabling http2 in the settings worked.

After disabling http2, just reload window and it works

**Comment by amdjedbens** [comment]
Cursor support should fix this, as it's not something efficient to work with when disabling HTTP2
![Image](https://github.com/user-attachments/assets/19221486-3636-4d50-b0c1-02baff013665)

**Comment by usorama** [comment]
How to disable http2 in cursor? Help please ?

**Comment by bheiddev** [comment]
Disabling http2 worked for me too. Its always the community lol

**Comment by fabiofranco85** [comment]
Logging out and in again solved the issue immediately for me

**Comment by divmgl** [comment]
> Logging out and in again solved the issue immediately for me

This was it for me as well. I opened up Cursor on a machine with a _very_ old session.

**Comment by heyabdulwahab** [comment]
> I found that disabling http2 in the settings worked.

Same for me, after trying logging out and signing again. I tried this disabling http2. It worked. Thanks
