### ISSUE TITLE
Need add all file's in folder to chat context

### ISSUE THREAD

**Issue by liaogang** [getcursor/cursor#1818]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when want to add few files to chat context, the Add file to context popup dialog is to small to add all files in a folder, some times the popup may overwrite files that have already been added, and the order of the file list in the pop-up window may change, causing me to get lost and be unable to tell which files have already been added.

**Describe the solution you'd like**
Add a shortcut in folder, popup "add all files to cursor chat"

**Comment by epinault** [comment]
@liaogang what was the solution?

**Comment by rashmibanthia** [comment]
> @liaogang what was the solution?

https://docs.cursor.com/context/@-symbols/@-folders

**Comment by liaogang** [comment]
no, I'm still have no idea

> @liaogang what was the solution?

**Comment by liaogang** [comment]
> > @liaogang what was the solution?
> 
> https://docs.cursor.com/context/@-symbols/@-folders

@folder ， It doesn't seem to work like that...
