### ISSUE TITLE
Easier way to open folders

### ISSUE THREAD

**Issue by Air1996** [getcursor/cursor#1823]
**Is your feature request related to a problem? Please describe.**
Support for dragging and dropping files and folders onto the dock icon to open them on macOS, like vscode does

**Comment by marcellocurto** [comment]
Yes, please add this! One of the first things I noticed when trying out Cursor.

**Comment by pasqualevitiello** [comment]
yeah, add this feature please!

**Comment by danperks** [comment]
Duplicate of #586
