### ISSUE TITLE
TS Sever Keeps Crashing

### ISSUE THREAD

**Issue by bmierdel** [getcursor/cursor#1836]
Type: <b>Bug</b>

Load TypeScript project

VS Code version: Cursor 0.40.4 (63dae81aea2c3fc079420fe72578a8eef26ba870, 2024-09-05T02:52:05.660Z)
OS version: Darwin arm64 23.3.0
Modes:
Remote OS version: Linux x64 5.15.0-1048-aws
Remote OS version: Linux x64 5.15.0-1048-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bento|
|OS|Linux x64 5.15.0-1048-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 0)|
|Memory (System)|62.01GB (31.02GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bento|
|OS|Linux x64 5.15.0-1048-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 0)|
|Memory (System)|62.01GB (31.02GB free)|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|34.5.2
vsc-material-theme-icons|equ|3.8.8
vscode-graphql-syntax|Gra|1.3.6
dotenv|mik|1.0.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2024081309
proto|pet|0.0.4
material-icon-theme|PKi|5.10.0
svg-preview|Sim|2.8.3
gistfs|vsl|0.6.0
vscode-sql-formatter|adp|1.4.4
vscode-tailwindcss|bra|0.12.10
vscode-eslint|dba|3.0.10
gitlens|eam|15.4.0
prettier-vscode|esb|11.0.0
vscode-diff|fab|2.1.2
shell-format|fox|7.2.5
go|gol|0.42.0
vscode-graphql|Gra|0.12.0
vscode-graphql-execution|Gra|0.3.0
vscode-graphql-syntax|Gra|1.3.6
terraform|has|2.32.3
css-to-jss|inf|1.0.7
vscode-codeowners|jas|1.1.1
json2csv|kha|0.0.1
vscode-rdbg|Koi|0.2.2
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
ruby-rubocop|mis|0.8.6
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
color-highlight|nau|2.8.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
ruby-extensions-pack|Sho|0.1.11
ruby-lsp|Sho|0.7.19
vscode-fileutils|sle|3.10.3
sorbet-vscode-extension|sor|0.3.36
alphabetical-sorter|ue|2.0.1
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.6.2

</details>

**Comment by stichingsd-vitrion** [comment]
Same, more then on VSCode

**Comment by Nodonisko** [comment]
Same for me.

**Comment by danperks** [comment]
Hi, can you all comment in #1888, if you are still having this issue, as I'm moving all JS/TS issues into there! Thanks :)
