### ISSUE TITLE
Where can I see the update log?

### ISSUE THREAD

**Issue by Zeal-L** [getcursor/cursor#184]

**Comment by truell20** [comment]
we publish a changelog on our discord https://discord.gg/PJEgRywgRy

would you prefer an in app version?

**Comment by Zeal-L** [comment]
> we publish a changelog on our discord https://discord.gg/PJEgRywgRy
> 
> would you prefer an in app version?

Sure, if you can add it. User experience would be great. The program was updated twice in a row today so I'm curious what was updated.
