### ISSUE TITLE
Requesting a refund

### ISSUE THREAD

**Issue by sandeepbali** [getcursor/cursor#1847]
Hi,

I am a complete non-developer but with great interest in tech. Less than a week ago I downloaded Cursor, and yesterday I took the premium subscription with intention to see full power of Cursor. Although it is very impressive, a non-developer like me can't use it to its full potential, additionally, I would still require a lot of support to make use the code that it gives.

So, I am requesting a refund for the subscription I took yesterday, as I won't be using it anymore.

I hope to keep a close eye on Cursor in future incase it adds features that would help me, then I'd be happy to subscribe again. Thanks. 

My account is at connect@sandeepbali.com.

Thanks.

**Comment by jucor** [comment]
This is a public issue tracker for bugs and feature requests. You will have better chance of response and be in a better place by contacting Cursor team via their email address: hi@cursor.com
