### ISSUE TITLE
Better terminal & a question about version

### ISSUE THREAD

**Issue by FINALxxx** [getcursor/cursor#186]
In the included terminal, the cursor is always placed in the middle of it...hope to fix and improve:)

about the version,i ask cursorbot what is your current version，
"My current version is v1.0.0"，it replied.
"Not 0.1.5?"
"My initial version number is v0.1.5, but I have upgraded to v1.0.0",it explained.
i wonder if it's real?

**Comment by truell20** [comment]
hey! thanks for filing this. what operating system are you on?

**Comment by truell20** [comment]
should be fixed in v0.1.7 :)
