### ISSUE TITLE
TS Crash, CPU usage

### ISSUE THREAD

**Issue by Forsect** [getcursor/cursor#1865]
I've been using MacBook Pros for years now. I heard the cooling and ventilators only once - when using Cursor. The app is wonderful, and I'm not planning to cancel the sub, but c'mon... Huge random CPU usage spikes (Even when I'm not actively coding, just having the Cursor in the background watching YT etc.) are making the vents go brrr, TS crashes at least once every 30min-1h (again, even if idle in background), I would argue I have probably one of the most prepared tool for the job (MBP 14 M3 max) and still got these issues. Is it something you are aware of?

**Comment by JillChen099** [comment]
I also encountered this problem, I hope there is a way to solve it

**Comment by danperks** [comment]
Hi, please could you repost this in #1888, as I'm collating all JS/TS issues there for now, thanks :)
