### ISSUE TITLE
image and link missing

### ISSUE THREAD

**Issue by FINALxxx** [getcursor/cursor#188]
![Cursor 2023_3_23 23_45_04](https://user-images.githubusercontent.com/40317137/227265441-b7e2e91a-b855-48a8-a63e-3ad5b8604c34.png)

i asked cursorbot for information of ACAutomation,it offered me an image link,but it doesn't work...

and i was offered an unavalible link in a former test(seemed like a markdown reference):**${"./algorithms/ACAutomaton.py"}**,
it advised me to "contact your administrator for permissions of code base",so how can i view it?

i dont know if it results from the web connection in China or maybe these links just dont exist at all.

**Comment by danperks** [comment]
Cursor's AI currently has no access to the internet, so Website links will most likely not work, and when they do, only out of luck and good guessing. In terms of file paths, Cursor can't currently see the whole folder structure of the folder you are working in, but this is a possible nice feature to help Cursor know more about your project.

**Comment by danperks** [comment]
See my previous comment for an answer here. Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!
