### ISSUE TITLE
error while fetching extensions. server returned 500

### ISSUE THREAD

**Issue by maxhochlenertarnoldnextg** [getcursor/cursor#1880]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful
![image](https://github.com/user-attachments/assets/bdfe325d-4b81-4e54-ba08-d6f2089b493f)
cant install any extensions. fresh install macos

**Comment by kunshouout** [comment]
Same problem here.

My system:

Version: 0.40.4
VSCode Version: 1.91.1
Commit: 63dae81aea2c3fc079420fe72578a8eef26ba870
Date: 2024-09-05T02:52:05.660Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.15.0-113-generic

**Comment by danperks** [comment]
Can you confirm this is still an issue? Seems to have had 2 reports one after the other (see #1881), so it may have been a temporary issue.

**Comment by danperks** [comment]
#1881 suggests this was a temporary issue. I'll close this for now but let me know if anyone has any further issues!

**Comment by puang59** [comment]
I have a similar issue @danperks 

![Image](https://github.com/user-attachments/assets/33d6a56f-fe84-437d-bdc7-859682642117)
