### ISSUE TITLE
o1 integration

### ISSUE THREAD

**Issue by Cafezinho** [getcursor/cursor#1883]
Waiting for the new o1 model integration!!!!

**Comment by chgaowei** [comment]
Waiting for the new o1 model integration!!!!

**Comment by chatterzhao** [comment]
如果自己有 `OpenAI` 的API，注意model 是填：`o1-mini` or `o1-preview`

**Comment by shreyashguptas** [comment]
Seems like it is integrated into Cursor! Issue seems like it can be closed.

**Comment by Cafezinho** [comment]
Perfect!
