### ISSUE TITLE
Chocolatey install md5 hash broken

### ISSUE THREAD

**Issue by darshanmarathe** [getcursor/cursor#1887]
1) If you can, please include a screenshot of your problem
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was 'B10D33AF5374DDA36EB5CD83869AD34066EA9FF2394B1F0BC605ED70EC03E0C0'.
Downloading cursoride
  from 'https://downloader.cursor.sh/windows/nsis/x64'
Progress: 100% - Completed download of C:\Users\Darshan\AppData\Local\Temp\chocolatey\cursoride\0.39.0\Cursor Setup 0.40.4 - x64.exe (120 MB).
Download of Cursor Setup 0.40.4 - x64.exe (120 MB) completed.
Error - hashes do not match. Actual value was 'B10D33AF5374DDA36EB5CD83869AD34066EA9FF2394B1F0BC605ED70EC03E0C0'.
ERROR: Checksum for 'C:\Users\Darshan\AppData\Local\Temp\chocolatey\cursoride\0.39.0\Cursor Setup 0.40.4 - x64.exe' did not meet '40FEE0A2589BE9430C66F9558A3C8FF4A3F8ED3BFA7D961C20A8C80E4E78E280' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of cursoride was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\cursoride\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - cursoride (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\cursoride\tools\chocolateyinstall.ps1'.
 See log for details.
2) Please include the name of your operating system
windows
3) If you can, steps to reproduce are super helpful
choco install cursoride

**Comment by danperks** [comment]
I don't believe Chocolatey is an official install method. While convenient, Cursor can't support or guarantee the security or functionality of download Cursor via Chocolatey. I'd recommend downloading it from the Cursor website, as the tool auto-updates itself, so you only have to do it once.

Alternatively, I believe Chocolatey has the facility to report these issues to the package maintainer, so I'd recommend doing that.

**Comment by szebrowski** [comment]
winget
