### ISSUE TITLE
[Feature Request] Add support for `.code-workspace` file

### ISSUE THREAD

**Issue by Lakphy** [getcursor/cursor#1898]
I hope that cursor can support right-clicking and selecting cursor to open the `.code-workspace` file in MacOS, just like using `cursor xxxxx.code-workspace` in the command line, which will help me replace vscode with cursor.

In short, I hope to be able to select cursor at this location👇.

<img width="505" alt="截屏2024-09-14 15 29 34" src="https://github.com/user-attachments/assets/cc09189a-9552-44bf-8661-dd6dfaf92f40">

about `.code-workspaces` file: https://code.visualstudio.com/docs/editor/workspaces

**Comment by daveebbelaar** [comment]
Just solved this problem:

1. Find a `.code-workspace` file in Finder
2. Right-click on the file and select “Get Info” from the context menu.
3. In the “Get Info” window, look for the “Open with:” section
4. Click on the selection field and select "Other"
5. Now here's the trick to make it work: select "All Applications" instead of "Recommended Applications"
6. You can now select Cursor from the list

![CleanShot 2024-09-15 at 10 57 14@2x](https://github.com/user-attachments/assets/cb701a3a-598b-471b-8abb-7bf52d005a30)

**Comment by Lakphy** [comment]
> Just solved this problem:
> 
> 1. Find a `.code-workspace` file in Finder
> 2. Right-click on the file and select “Get Info” from the context menu.
> 3. In the “Get Info” window, look for the “Open with:” section
> 4. Click on the selection field and select "Other"
> 5. Now here's the trick to make it work: select "All Applications" instead of "Recommended Applications"
> 6. You can now select Cursor from the list
> 
> ![CleanShot 2024-09-15 at 10 57 14@2x](https://private-user-images.githubusercontent.com/34709402/367570339-cb701a3a-598b-471b-8abb-7bf52d005a30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTM0MjYsIm5iZiI6MTcyNjM5MzEyNiwicGF0aCI6Ii8zNDcwOTQwMi8zNjc1NzAzMzktY2I3MDFhM2EtNTk4Yi00NzFiLThhYmItN2JmNTJkMDA1YTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA5Mzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkN2VhODYzZGE2ZGI4ZGI1NDFjYmY4ZWU5ZmVmYTlmMGI1ZGNhZmJiODZjZjk0MDIyM2VjZTQyYjMzNGYxMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yUz8KpDdu6b6W1zoS7r5coGDcfW2Wh3QlSRDA3EH4wE)

Thank you for your answer. It turns out that this method can be used to force MacOS to open with cursor, which perfectly solves my problem. 👍

**Comment by aymather** [comment]
How is it that i have had a mac as long as I have, and never known that the "greyed out applications" were only because they were not "recommended".

*screams into void*

**Comment by Redmega** [comment]
For anyone searching for this on google, you can also just run `cursor my.code-workspace` in the terminal and it will open.
