### ISSUE TITLE
history for prompts

### ISSUE THREAD

**Issue by yanyuechuixue** [getcursor/cursor#19]
Thanks for the awesome IDE.

Could you please add a history for prompts to facilitate quick modification of previous prompts?

Thanks a lot!

**Comment by yanyuechuixue** [comment]
Get! Thank you very much.

**Comment by Wirless** [comment]
how to find older prompts than jus tthe las tone

**Comment by TheArrowsmith** [comment]
Same question as @Wirless

**Comment by kaiserabliz** [comment]
Same question, is there any way that I can find my entire prompt history?

**Comment by ionut85** [comment]
+1 on this one

**Comment by Wirless** [comment]
Not all prompts but it remembers few in your history

**Comment by bajalnyt** [comment]
Keep hitting the up arrow, It went back at least 12 prompts for me
