### ISSUE TITLE
The copy button of the code-block is not aligned inside the code-block

### ISSUE THREAD

**Issue by abbychau** [getcursor/cursor#190]
![image](https://user-images.githubusercontent.com/350283/227328920-1d1900df-a378-4bea-af14-2776e10f9c1d.png)

**Comment by truell20** [comment]
good catch, thanks for reporting

**Comment by abbychau** [comment]
still not sure the exact process to reproduce, seems some cm-scroller will take place occasionally.

opening the terminal and make the window small maybe relevant.

**Comment by zidano88** [comment]
I have same Issue

![Screenshot from 2023-03-24 00-25-34](https://user-images.githubusercontent.com/28100885/227378432-acf1ddc6-fe89-450d-ab5a-8948702ef911.png)

**Comment by alexwebdevs** [comment]
> ![image](https://user-images.githubusercontent.com/350283/227328920-1d1900df-a378-4bea-af14-2776e10f9c1d.png)

I fixed this issue @truell20 @abbychau

**Comment by truell20** [comment]
sweet thanks for fixing this
