### ISSUE TITLE
System prompt

### ISSUE THREAD

**Issue by iloveitaly** [getcursor/cursor#1900]
**Is your feature request related to a problem? Please describe.**
better codegen

**Describe the solution you'd like**
I'd like to system prompt cursor. For instance, I have various coding styles that I personally like and I have a custom GPT to implement them. I would like to have a version of this custom GPT prompt applied to all workspaces and chats so the code generated aligns with my personal style guide.

**Additional context**

**Comment by Am0stafa** [comment]
You can use AI rules for that in the settings

**Comment by danperks** [comment]
Hi @iloveitaly,

As @Am0stafa says, there is the ability to set both global (across every project) and project-specific rules that are sent as part of the prompt to the LLM.

You can find the tutorial on how to do that here:
https://docs.cursor.com/context/rules-for-ai
