### ISSUE TITLE
Unable to login on Cursor

### ISSUE THREAD

**Issue by Anajrim01** [getcursor/cursor#1902]
1) If you can, please include a screenshot of your problem

![image](https://github.com/user-attachments/assets/b75507b4-39da-4052-9637-2195f86de10e)
![image](https://github.com/user-attachments/assets/5625850b-a9a4-4ce6-a721-2e455eeab239)

2) Please include the name of your operating system
Windows 11
3) If you can, steps to reproduce are super helpful
Switching from Code, just installed, tried to login through the "Login Sign Up" menu but that wasn't working either (same thing). Decided to skip and try to sign in later, which still doesn't work.

Logging in through website works fine.

**Comment by Anajrim01** [comment]
I was using a proxy in Code which got imported in Cursor too.

**Comment by sggwebs** [comment]
![Image](https://github.com/user-attachments/assets/9478e04e-c320-41fa-832e-3af9afa350d1)

![Image](https://github.com/user-attachments/assets/8abd76eb-2fbc-4b16-8e94-fb10474aba10)

**Comment by sggwebs** [comment]
my operating system is 64-bit Windows 11 pro
