### ISSUE TITLE
Image uploads in the chat window

### ISSUE THREAD

**Issue by savnani5** [getcursor/cursor#1903]
**Is your feature request related to a problem? Please describe.**
It would be great if we can upload images to describe certain code edits or feature requests via the chat window. The interface rn is good, but it feels lacking without the multimodal capabilities. 

**Describe the solution you'd like**
Would love OCR capabilities + ability to understand and create UI components is useful. Also general image understand would be handy.

**Comment by viko42** [comment]
Drag and drop an image to the chat and it will work

**Comment by savnani5** [comment]
Oh lol, I should have known this earlier. Thanks!
