### ISSUE TITLE
Hello cursor team

### ISSUE THREAD

**Issue by ricardogitalc** [getcursor/cursor#1906]
Hello cursor team

Recently, I signed the cursor to test what it was like, I sent an email beforehand to check if this period existed and they replied yes, however I am a beginner programmer, and in my case it did not meet the needs I was looking for, so I wanted this refund.

Thank you for your attention to this matter. I appreciate your help in resolving it quickly.

I have already tried to contact you using the same email address that you responded to, but so far I have not received a response.

Please contact me via email alcantara.ricardo00@gmail.com

**Comment by danperks** [comment]
Hi, billing issues can only be dealt with by emailing hi@cursor.com

While I appreciate you have already done that, it's unlikely you'll receive anything useful here.
All I can suggest is you try to email again, and ensure you have cancelled your subscription in the Cursor dashboard.
