### ISSUE TITLE
AppImage has messed up permissions that make it unusable on linux (workaround provided in description)

### ISSUE THREAD

**Issue by Livia-Zaharia** [getcursor/cursor#1907]
Your image is messed up and does not run by default in most of the Ubuntu-based linux distributions (tested on ubuntu studio and pop os, both based on 24.x LTS)

```
/home/liviazaharia/soft/cursor-0.40.4x86_64.AppImage

[5464:0916/160735.554601:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_cursoribOUcX/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```
Running with --no-sandbox does not work as well as it raises gpu-related issues.
The only way to solve it was to extract the image and change permissions manually:
```
./cursor-0.40.4x86_64.AppImage --appimage-extract
cd squashfs-root
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox
```
then I can use:
```
./AppRun
```
and thinks work. Obviously, it is a workaround to make things work, proper fix  must be implemented by the developers.

**Comment by danperks** [comment]
Hi, closing in favour of #1465 to keep discussions in one thread, feel free to post your workaround there for now. :)
