### ISSUE TITLE
[Feature Request] Export chat output to Markdown

### ISSUE THREAD

**Issue by RuDeeVelops** [getcursor/cursor#1913]
**Is your feature request related to a problem? Please describe.**
Exporting AI chats is paramount for various purposes: using chats as references, wikis, etc // self custody of crucial documentation in readable format // etc

**Describe the solution you'd like**
In the AI chat pane an option "export as markdown" is exposed. The whole chat session is parsed into an md format and exported into a local file.

**Additional context**
No additional context.

**Comment by danperks** [comment]
Duplicate of #29
