### ISSUE TITLE
Composer and Chat wont apply changes

### ISSUE THREAD

**Issue by nfteco** [getcursor/cursor#1915]
I am editing a Next.JS app and no matter what I prompt the composer or chat, it will return the result but wont apply it to the codebase no matter what. I tried upgrading my Cursor, still not applying

**Comment by MikeTheBard** [comment]
Also having this issue today. Was fine yesterday and before.

**Comment by gunjan5** [comment]
Same issue (apply doesn't work for chat or composer), worked fine last night. 
Here's the current version:
```Version: 0.40.4
VSCode Version: 1.91.1
Commit: 63dae81aea2c3fc079420fe72578a8eef26ba870
Date: 2024-09-05T02:52:05.660Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0```

**Comment by MikeTheBard** [comment]
It started working again after about 12 or so hours, randomly.

I tried multiple models.

**Comment by danperks** [comment]
Yeah, my guess is there may have been some changes or downtime while you were trying.
Will close this as resolved.

**Comment by yiyubruceliu** [comment]
Happening again now. Guess there is some updates happening? Or did I accidentally break something?
