### ISSUE TITLE
Request for new release / beta version

### ISSUE THREAD

**Issue by faheemstepsharp** [getcursor/cursor#1916]
Dear Team, Please update on latest

**Comment by gunjan5** [comment]
is there a way to downgrade it to Version: 0.40.3 (which was working)?

**Comment by danperks** [comment]
Hi @faheemstepsharp,

Can I ask, why do you want a newer version to be released?
Cursor prompts you when there is an update, and you can always run the `Cursor: Attempt Update` command if you think that is misbehaving. 

If there is an issue you are having, opening an issue for that specific problem is better than requesting an update without stating why you want one.

**Comment by danperks** [comment]
If you are requesting a new version due to extension compatibility, feel free to comment in #1896 and close the issue, to avoid duplication.

**Comment by faheemstepsharp** [comment]
Dear, I want a VISUAL option for checking for updates both for EXTENSIONS and THE EDITOR as well, it is not UX friendly to write this:Cursor: Attempt Updat also it dont seem to work for me at all, even the latest version from the wenbsite stil is .40

**Comment by danperks** [comment]
There is a visual update popup that shows when an update is available for you to accept.
If no popup is visible, you're likely on the latest version.
Also, if you run "Attempt Update" and it doesn't do anything, I think that means you are also on the latest version.

Extensions *should* auto-update but how quickly that happens isn't something I know.
To update them manually, you can do that in the extensions window.

While the UI you want already exists, note that the releases of Cursor and the extension library within it doesn't match with VSCode, so there may be new features or extensions in VSCode that aren't available in Cursor yet - this is already reported in other issues and will likely come soon enough.

**Comment by faheemstepsharp** [comment]
No I am not on the latest version, also the command wont do ANYTHING at all.
Also I have to check for updates manually to update ( for extensions)

PLEASE understand I am not lying

**Comment by danperks** [comment]
Can you send a screenshot of your About window, by going Help -> About in the top menu?
I don't think you are lying, not to worry!

**Comment by gunjan5** [comment]
That command doesn't do anything for me either. I am on the following version (which is not the latest per  https://changelog.cursor.sh

```
Version: 0.40.4
VSCode Version: 1.91.1
Commit: 63dae81aea2c3fc079420fe72578a8eef26ba870
Date: 2024-09-05T02:52:05.660Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

I have tried uninstalling and reinstalling multiple times but it keeps installing 0.40.0 version. I have also updated my mac. 

I still can not apply any changes through chat or composer. I've emailed the cursor team two days ago but no response and I haven't been able to get anything done with my pro subscription :/

**Comment by itzhoujun** [comment]
same issue.

**Comment by guruhao** [comment]
me too. stopped on 0.40.4

**Comment by lassestilvang** [comment]
Version 0.41 was rolling out gradually, but it should be available for everyone now. You should see the popup in the lower left corner of the window, or you can try using the 'Attempt Update' command.
