### ISSUE TITLE
should have a place to show ssh errors

### ISSUE THREAD

**Issue by abbychau** [getcursor/cursor#192]
so that one can track ssh errors while connect , cd, uploads, etc.
probably a panel besides terminal? (connection errors shows on connect modal)

https://github.com/getcursor/cursor/issues/117
https://github.com/getcursor/cursor/issues/179 
https://github.com/getcursor/cursor/issues/99

**Comment by truell20** [comment]
agree connection errors should show on connect modal. unsure of correct UI for showing any errors during the ssh session

**Comment by danperks** [comment]
With the move to Cursor v0.2.0, you can use the Remote-SSH plugin to connect to a system.

To install the plugin, head to https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh, then hit "Version History" and download the latest one. 
Drag the .vsix file into Cursor to install it, then use the command palette to connect to a target machine.

**Comment by momoitman** [comment]
I have dragged the .vsix file into the directory of Cursor, but the installation still fails leaving me with a notice that I should install the extension in vscode. Maybe the way I have tried is wrong. Could you give me more detailed hints to install the extension? My platform is Windows.
