### ISSUE TITLE
Apply All Unstable on Composer

### ISSUE THREAD

**Issue by Razikale365** [getcursor/cursor#1925]
1) If you can, please include a screenshot of your problem
Irrelevant
2) Please include the name of your operating system
Windows 11
3) If you can, steps to reproduce are super helpful
When i try to apply all changes using Composer whether or not i takes a long time it either applys the changes to one file only and not the other and none at all, when i open a large codebase folder and redirect the chat is even worse, most times i need to open a subfolder with no folders within it so it can try to apply i am using 0.40.1 i am hoping the next update fixes. I've tried disabling http2 but the results are a just as inconsistent.
Please test the composer apply on a large multi-folder code base because its not stable... Even with one folder open sometimes it just doesnt modify the code at all i have to manually click the suggestion, read and copy where it should be it is time consuming compared to just accepting or rejecting diffs...

**Comment by Razikale365** [comment]
I am a pro user now btw, it seems these last few days the feature got worse for some reason... Also since the beginning i had to open a single folder to be able to use it properly...

**Comment by SZim92** [comment]
It seems to be a bug with 0.41.1. Reverting to 0.40.4 got "Open in Composer" working for me again.

**Comment by Razikale365** [comment]
Weird i am using 0.40.4,  also like to add that today instead of claude 3.5 sonnet i used o1-mini the outputs are great, but the apply doesnt do anything i have to manually read and add i've added screenshots as proof as much as i can safely do
![{7B4FE2BB-B944-4108-AF2A-21F26E731FF4}](https://github.com/user-attachments/assets/ec5921c2-4199-4a7e-9690-99962ac33810)
![{8B2E76F9-3025-4ECB-8CAF-DBA165B39DDA}](https://github.com/user-attachments/assets/9397f861-b77f-4ddb-9908-73bc10e29eaf)

**Comment by SZim92** [comment]
Interesting. I'm finding 0.41.1 is having trouble moving codeblocks from Chat to composer:

![image](https://github.com/user-attachments/assets/11e168c4-2668-4980-b766-2ca1853e5fb8)

And I'm finding the option to swap to composer is not appearing if you're running a 200k context Claude chat.

**Comment by Razikale365** [comment]
Having updated to the latest version, it got better, too bad it cant apply code to large files... As a final note the instability is definitely model dependent... Cursor is amazing if this features get improved and more stable i think nothing can beat it :D.
