### ISSUE TITLE
visual studio dependency

### ISSUE THREAD

**Issue by shoaibmohommed** [getcursor/cursor#193]
You haven't mentioned in the docs about windows, that one would need `visual studio` installed on the machine, in order to install the `node_modules` 

In windows `npm i` results in error,  It Requires Visual Studio to be installed first

**Comment by truell20** [comment]
Is this for installing node-pty? https://github.com/microsoft/node-pty

**Comment by shoaibmohommed** [comment]
i am not sure, but when i tried to install `node_modules`  for this repo it gave me error (i think it was through node-gyp) about the VS then i have to install the VS and then it worked
