### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by remcohaszing** [getcursor/cursor#1931]
**Is your feature request related to a problem? Please describe.**
Is there an SVGO logo available of the Cursor logo? I could only find PNG versions and videos. There are SVG files available in https://github.com/getcursor/docs/tree/main/images/logo, but they contain an embedded PNG version of the Cursor icon.

**Describe the solution you'd like**
I would like a SVG icon of the Cursor logo.

**Additional context**
I intend to provide it to [`vscode-icons`](https://github.com/vscode-icons/vscode-icons) for use with the `.cursorrules` file.

**Comment by danperks** [comment]
You can find an SVG here:
[cursor.com/assets/images/logo.svg](https://www.cursor.com/assets/images/logo.svg)

**Comment by remcohaszing** [comment]
That’s also an SVG file containing an embedded PNG image. It’s not an actual SVG icon.

**Comment by remcohaszing** [comment]
For anyone interested: I emailed them, but they never responded. I ended up recreating the icon myself, which is available in https://github.com/vscode-icons/vscode-icons/pull/3686.
