### ISSUE TITLE
Unable to Start Chat

### ISSUE THREAD

**Issue by zidano88** [getcursor/cursor#194]
When I press CTRL+L to start chat and submit any question, it gives an error as following:
Error occurred in handler for 'setStore': No handler registered for 'setStore'
![Screenshot from 2023-03-24 00-03-42](https://user-images.githubusercontent.com/28100885/227374943-97dedf10-0de1-43b4-9d81-f4b094791be9.png)

**Comment by truell20** [comment]
You have some sort of error on the main thread. What's the output of the terminal?

**Comment by zidano88** [comment]
![Screenshot from 2023-03-24 00-14-33](https://user-images.githubusercontent.com/28100885/227376715-ed834b6d-e270-4030-8f70-03bd4b4cce48.png)

**Comment by truell20** [comment]
sorry about this! guessing its fixed by 88ac071fd5e43374f873e35ba9334c9bda52b42c
