### ISSUE TITLE
Request to Resolve Cursor 0.41.1 Version Update Issue

### ISSUE THREAD

**Issue by martxo** [getcursor/cursor#1945]
"I'm unable to get the latest version 0.41.1 of Cursor from the official website, and there's no update button within the software. It's surprising how someone in charge could be so negligent. I hope this issue will be resolved as soon as possible!"

**Comment by lassestilvang** [comment]
Version 0.41 was rolling out gradually, but it should be available for everyone now. You should see the popup in the lower left corner of the window, or you can try using the 'Attempt Update' command.
