### ISSUE TITLE
[feat] show word-level diff after editing

### ISSUE THREAD

**Issue by GrayXu** [getcursor/cursor#1955]
**Is your feature request related to a problem? Please describe.**
The current ctrl+k edit interface can only display line-level diffs, where deleted lines are marked in red and added lines in green. When most content is the same but only a small part has been modified, it's difficult for humans to track quickly.

**Describe the solution you'd like**
The existing git diff can actually display differences at the word level, where deleted words are highlighted in dark red within the red lines and newly added words are highlighted in dark green within the green lines. This greatly helps users to pinpoint specific diffs.

**Comment by GrayXu** [comment]
Already implemented!

**Comment by liaolunhui** [comment]
> Already implemented!
How to use it? I can't see the word level highlight
