### ISSUE TITLE
Unable to Open Folder

### ISSUE THREAD

**Issue by zidano88** [getcursor/cursor#196]
When I click on Open Folder button it gives me this error:

Error occurred in handler for 'get_folder': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)

![Screenshot from 2023-03-24 00-13-20](https://user-images.githubusercontent.com/28100885/227376534-e8a82c6e-8eb5-45f6-ba2b-160598b8a189.png)

**Comment by truell20** [comment]
Fixed
