### ISSUE TITLE
codebase indexing error with handshake failed

### ISSUE THREAD

**Issue by zhaoxin111** [getcursor/cursor#1963]
1) If you can, please include a screenshot of your problem
I usually connect to the server for development via remote-ssh. The server has limited network access, and I keep encountering a "handshake failed" error when Cursor is indexing the codebase. I suspect that Cursor needs to send code to a specific address for indexing. Could you please tell me which hostname should I open on the server to allow codebase indexing to work properly?
![image](https://github.com/user-attachments/assets/380a8b53-4913-40c5-b659-61c7eaa88869)

2) Please include the name of your operating system
  local is windows, remote is centos
  Version: 0.41.2
  VSCode Version: 1.91.1
  Commit: 297991d169fa3a11975c5aa95adc69be73250c70
  Date: 2024-09-21T04:18:39.370Z
  Electron: 29.4.0
  ElectronBuildId: undefined
  Chromium: 122.0.6261.156
  Node.js: 20.9.0
  V8: 12.2.281.27-electron.0
  OS: Windows_NT x64 10.0.22631

3) If you can, steps to reproduce are super helpful
step1: open the project with remote-ssh
step2: codebase indexing

**Comment by danperks** [comment]
Hey, please post this in #2035 please :)
