### ISSUE TITLE
Auto select conda environment editor terminal

### ISSUE THREAD

**Issue by zaeem4** [getcursor/cursor#1975]
**Is your feature request related to a problem? Please describe.**
Whenever I open a cursor I have to activate my conda environment every time I open terminal 

**Describe the solution you'd like**
But in vs code, you only define the environment for your project once. Whenever I open the terminal, it automatically activates that specific conda environment, even if I open multiple terminals.

**Comment by danperks** [comment]
If you run the "Python: Select Interpreter" command, does your conda environment show up there?

Note that neither Cursor or VSCode can setup a conda environment automatically if Powershell is set to your default terminal.

Check this link for more info:
https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters

**Comment by zaeem4** [comment]
yes, it got solved. thank you for the help.
