### ISSUE TITLE
Anthropic is experiencing a partial outage right now. To avoid downtime, we've temporarily fallen back to an OpenAI model.

### ISSUE THREAD

**Issue by sjuranek** [getcursor/cursor#1983]
Anthropic had an issue yesterday but appears to be up today. https://status.anthropic.com/
I shut off all other models but it still falls back to OpenAI. So the bug is that even with all models off it still falls back and also it is telling me Anthropic is down but it doesn't seem to me. Would be nice to have a status page for Cursor.

**Comment by ashenjy** [comment]
they are scammers, cursor team are scammers, still the issue exist, i have added a chargeback. cursor is completly unusable without anthropic

**Comment by sjuranek** [comment]
@ashenjy - I don't think they are scammers. This product has been very popular and I think they are going through some growing pains. It does point out how current Anthropic does have a great model for code assistance.

**Comment by danperks** [comment]
Looks like they were still having API issues around 3 hours ago, and the latest update still suggests things are working their way back to being normal. I have a feeling that, due to the amount of usage Cursor is accountable for on Anthropic servers, they may have an agreement to redirect to other LLM providers to help reduce the strain while they get things back up and running, but this is a guess.

https://status.anthropic.com/

There is no longer a redirect away from Anthropic, at least on my testing, so I'll close this for now unless some is still having the redirect message, in which case I'll leave this open until it's resolved.

**Comment by JonoGee** [comment]
Looks like this issue has re-emerged since I started getting this error again today! Anyone have a news on whats happening?

**Comment by LucaHermann** [comment]
@JonoGee what plan of cursor do you use ?
I'm using Pro plan and get this error since 20min, checked the status of Claude 3.5 everything seems fine tho, it's weird !

**Comment by paperplane123** [comment]
我今天也遇到了，请问该如何解决呀

**Comment by unsetlay** [comment]
I was facing the same situation, it happened in the middle of programming, it lasted for more than 10 minutes, and on the website it looked like Anthropic's service was running normally.

**Comment by JonoGee** [comment]
> @JonoGee what plan of cursor do you use ? I'm using Pro plan and get this error since 20min, checked the status of Claude 3.5 everything seems fine tho, it's weird ! Might be a security to not overload Anthropic when they have issues, they rather fallback to OpenAI.

Business

**Comment by LucaHermann** [comment]
> > @JonoGee what plan of cursor do you use ? I'm using Pro plan and get this error since 20min, checked the status of Claude 3.5 everything seems fine tho, it's weird ! Might be a security to not overload Anthropic when they have issues, they rather fallback to OpenAI.
> 
> Business

So it's not based on the plan used, they might have a problem on the Cursor side i think as you can use Anthropic model everywhere else.

**Comment by JonoGee** [comment]
Mine has been going on for about an hour now since it started.

https://status.anthropic.com/
This status reports zero downtime on this day, which is a mickey mouse metric, because I would hazard a guess that when the Anthropic error message states switching to openAI model to prevent downtime, this incorrectly prevents it recording downtime on Anthropic, because it pretends there is no issue. Just an con mans trick to avoid reporting reality I would imagine.

Makes the Anthropic health status reporting neither use nor ornament though!! I emailed cursor (for the first time may I add), so i have no idea what to expect about lead time on a response

**Comment by LucaHermann** [comment]
> Mine has been going on for about an hour now since it started.
> 
> https://status.anthropic.com/ This status reports zero downtime on this day, which is a mickey mouse metric, because I would hazard a guess that when the Anthropic error message states switching to openAI model to prevent downtime, this incorrectly prevents it recording downtime on Anthropic, because it pretends there is no issue. Just an con mans trick to avoid reporting reality I would imagine.
> 
> Makes the Anthropic health status reporting neither use nor ornament though!! I emailed cursor (for the first time may I add), so i have no idea what to expect about lead time on a response

Anthropics model's are back on my Cursor, anyway would be nice to have a Cursor status page too so we can see when they have a problem because apparently Anthropics can work just fine and Cursor won't.

**Comment by JonoGee** [comment]
Yup. It seems to be working now, fingers crossed, touch wood and all that!

Back in the game!

**Comment by JonoGee** [comment]
> > Mine has been going on for about an hour now since it started.
> > https://status.anthropic.com/ This status reports zero downtime on this day, which is a mickey mouse metric, because I would hazard a guess that when the Anthropic error message states switching to openAI model to prevent downtime, this incorrectly prevents it recording downtime on Anthropic, because it pretends there is no issue. Just an con mans trick to avoid reporting reality I would imagine.
> > Makes the Anthropic health status reporting neither use nor ornament though!! I emailed cursor (for the first time may I add), so i have no idea what to expect about lead time on a response
> 
> Anthropics model's are back on my Cursor, anyway would be nice to have a Cursor status page too so we can see when they have a problem because apparently Anthropics can work just fine and Cursor won't.

The error states Anthropics is experiencing a partial outage. Not Cursor . So one is wrong or misleading either way.

**Comment by danperks** [comment]
Hey all,

As you spotted, we did reroute from Anthropic to OpenAI temporarily! At least on our end, we were seeing a spike in errors with Anthropic, so made the decision to enable the rerouting to ensure queries weren't failing outright.

We do this based on our own metrics of how ours users are getting on, which may not coincide with when Anthropic say they are having issues, or whether or not every user would get the error. We believe that redirecting like this is best as it avoids breaking peoples flow's, even if the output of GPT may not be as good as Claude in some situations. 

The redirect is global and no plans or users are prioritised - even our own dev's get their queries redirected in this case!

All should be back to normal now, but we will do this whenever we spot issues with any of our LLM providers to ensure queries aren't failing and we don't break your flow!
