### ISSUE TITLE
Cursor consuming extreme CPU and causing battery draining

### ISSUE THREAD

**Issue by SurgeODDR** [getcursor/cursor#1986]
Since yesterday's update.

Apple M2 Pro
32 GB RAM
macOS Sonoma 14.5

Reaching 100% CPU frequently and triggering TG Pro fan control to use max fan speed; even then it still cooks the CPU to 100°C.

![image](https://github.com/user-attachments/assets/bf1b513d-eaad-4e10-83b3-054fe375b62c)
![image](https://github.com/user-attachments/assets/41255997-8e2e-4fff-a58f-b42ca90e4e6d)
![image](https://github.com/user-attachments/assets/e574383e-1c07-4845-aaec-69982ccf7a3d)

**Comment by lumix17** [comment]
How did you resolve the issue?

**Comment by mazenrashed** [comment]
this software should help you
https://github.com/mazenrashed/CursorPolice
