### ISSUE TITLE
[0.1.4]-hotkey failure

### ISSUE THREAD

**Issue by turanks** [getcursor/cursor#199]
As i update cursor from 0.1.3 to 0.1.4,the hotkey (Ctrl+K Ctrl+L) failed, no reaction.
winver: 22H2 22621.1413

**Comment by szdytom** [comment]
the same for Windows, looking for a solution

**Comment by truell20** [comment]
If you restart, it should upgrade you to 0.1.5? Does it work on that version?

**Comment by fcmfcm01** [comment]
it doesn't work on v0.1.5 either.

**Comment by MrLittleShark** [comment]
> it doesn't work on v0.1.5 either. it works only when you invoke "Ctrl+K" first time, and it would be failed when you invoke it again

I meet the same problem. Hotkeys don't work properly.

**Comment by huiminxu** [comment]
i meet the same  problem of hotkey , it doesn't work when i invoke it again. unless invoke the first time

**Comment by MrLittleShark** [comment]
> i meet the same problem of hotkey, it doesn't work when i invoke it again. unless invoke the first time
> 
> v0.1.5

Ctrl+Double L， It seems that the problem can be temporarily

**Comment by liuzhe1947** [comment]
After restarting, you can use ctrl+k for the first time, but you cannot use version v0.1.5 for the second time using shortcut keys

**Comment by turanks** [comment]
> If you restart, it should upgrade you to 0.1.5? Does it work on that version?

It works , I just restarted cursor, it is now 0.1.5, the problem seems to have been solved.
test steps:
1. chose and open a file from the file tree 
2. invoke the hotkey, it works
3. restart the software,and redo 1,2, it steel works

winver: 22H2 22621.1413

**Comment by turanks** [comment]
> After restarting, you can use ctrl+k for the first time, but you cannot use version v0.1.5 for the second time using shortcut keys

emm,just in case, did you forget to open a file? it seemes Ctrl+k is available just in a opened file （Ctrl+L  is always available )

**Comment by liuzhe1947** [comment]
> > After restarting, you can use ctrl+k for the first time, but you cannot use version v0.1.5 for the second time using shortcut keys
> 
> emm,just in case, did you forget to open a file? it seemes Ctrl+k is available just in a opened file （Ctrl+L is always available )

"I have entered a request while opening the file, and cannot use the shortcut key after adding the request. Use ctrl+LL and then press ctrl+K to complete the request."
