### ISSUE TITLE
Codebase indexing doesnt work

### ISSUE THREAD

**Issue by athmanar** [getcursor/cursor#1998]
New cursor install on windows 11. Codebase indexing always gives error "Handshake failed"

```
[error] Error: Command failed: git config --get remote.origin.url
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:514:28)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:337:12)
```
2024-09-25 15:12:11.785 [info] Doing the initial handshake with hash: 59493feeb029b25394e73eb3116b6be8a6b9d956d8b135a1f2f7ad8067b698ec
2024-09-25 15:12:11.785 [info] Handshake start
2024-09-25 15:12:15.642 [info] Handshake start
2024-09-25 15:12:23.658 [info] Handshake start
2024-09-25 15:12:39.670 [info] Handshake start
2024-09-25 15:13:11.677 [info] Handshake start
2024-09-25 15:14:05.271 [info] Handshake start
2024-09-25 15:15:30.841 [error] Handshake failed:
2024-09-25 15:15:30.842 [error] Error: timeout in handshake with retry

`2024-09-25 15:15:30.842 [error] Handshake failed.
`2024-09-25 15:15:30.843 [info] Indexing job successfully done or aborted.

**Comment by jamesryancooper** [comment]
Having the same issue.

**Comment by Maxime-Fleurant** [comment]
Same issue, many people have problem with this, i m using wsl2 right now with a fresh install of cursor and this is happening

**Comment by soumen02** [comment]
Facing the same issue and created an issue #2035 (didn't realize this was created)

**Comment by ascanio** [comment]
Same here!
<img width="505" alt="image" src="https://github.com/user-attachments/assets/39c3d920-2a04-42d2-9d14-31c14d591f73">

**Comment by georgeliu1998** [comment]
Just log out and log back in under "General - Account" and it should start working again!

**Comment by athmanar** [comment]
@georgeliu1998 Sorry tried that and it doesn't work. Still get a similar error:

> 
> 2024-10-02 10:06:07.652 [info] Setting indexing intent to should-index
> 2024-10-02 10:06:07.655 [info] Creating merkle client.
> 2024-10-02 10:06:07.655 [info] Done creating merkle client.
> 2024-10-02 10:06:07.656 [info] Doing a startup handshake.
> 2024-10-02 10:06:08.528 [info] Finished initializing merkle tree in 873.6273000240326 ms.
> 2024-10-02 10:06:08.530 [info] Doing the initial handshake with hash: ba088e651205d23a2561a2a127ba47f54bd00ba8382e36a8877b1168027f860d
> 2024-10-02 10:06:08.533 [info] Handshake start
> 2024-10-02 10:06:11.588 [info] Handshake start
> 2024-10-02 10:06:19.607 [info] Handshake start
> 2024-10-02 10:06:35.630 [info] Handshake start
> 2024-10-02 10:07:07.639 [info] Handshake start
> 2024-10-02 10:08:01.208 [info] Handshake start
> 2024-10-02 10:09:26.825 [error] Handshake failed:
> 2024-10-02 10:09:26.827 [error] Error: timeout in handshake with retry
> 	at t.RepoClientMultiplexer.handshakeWithRetry (c:\Users\USER\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:826553)
> 	at async w.getServerStatus (c:\Users\USER\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:841881)
> 	at async w.startIndexingRepository (c:\Users\USER\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:844181)
> 2024-10-02 10:09:26.829 [error] Handshake failed.
> 2024-10-02 10:09:26.829 [info] Indexing job successfully done or aborted.

**Comment by duzefu** [comment]
same problem

**Comment by LegalPrimes** [comment]
same issue

**Comment by samgabrail** [comment]
Same issue here, tried logging out and in and same problem

**Comment by athmanar** [comment]
@georgeliu1998 This is making cursor unusable

**Comment by danperks** [comment]
Closing for #2035

**Comment by duzefu** [comment]
> Same issue here, tried logging out and in and same problem. I'm also running Cursor installed on Windows 11 and have WSL2 running my repo

running below command in wls2
```
killall node
```
and reload windows , it works for me
