### ISSUE TITLE
Want to change my yearly subscription to monthly subscription

### ISSUE THREAD

**Issue by scatteringpollen** [getcursor/cursor#2000]
I am writing to request a change in my current subscription plan. I would like to switch from the annual subscription to a monthly subscription. Additionally, I kindly request a partial refund of the remaining amount after deducting $20 from the total payment.

Please let me know if there is any additional information or steps required from my side to process this request.

I am a student, so 192$ is a significant amount for me to pay all at once. And I would greatly appreciate it if you could accommodate my request.

Could you help me Cursor Team, please?

**Comment by danperks** [comment]
Hi, for billing issues, please email hi@cursor.com and they can help you out. I'll close this for now :)

**Comment by gimphammer** [comment]
The billing change is not friendly........it sucks.....

**Comment by morgler** [comment]
It is hilarious we cannot change plans. I have to cancel now to get a different plan. Just use Cursor to implement a plan change feature – takes 10min
