### ISSUE TITLE
Remote SSH not work in 0.41.2 version

### ISSUE THREAD

**Issue by 1Muggle** [getcursor/cursor#2001]
Remote ssh connection to Windows 10(and64) via Cursor version 0.41.2 still doesn't work on macOS (Apple Silicon / M1)

My cursor info
```
Version: 0.41.2
VSCode Version: 1.91.1
Commit: 297991d169fa3a11975c5aa95adc69be73250c70
Date: 2024-09-21T04:18:39.370Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 24.0.0
```

Remote - SSH output
It seems that the remote CLI address is incorrect or has not been uploaded
```
...
[10:20:24.473] Got request to download on client for {"artifact":"cli-win32-x64","destPath":"C:\\Users\\noah\\.cursor-server/vscode-cli-297991d169fa3a11975c5aa95adc69be73250c70.zip"}
[10:20:24.473] server download URL: https://cursor.blob.core.windows.net/remote-releases/297991d169fa3a11975c5aa95adc69be73250c70/cli-win32-x64.tar.gz
[10:20:24.473] Downloading VS Code server locally...
[10:20:25.462] Terminating local server
[10:20:25.468] Resolver error: Error: Failed to download VS Code Server (Server returned 404)
...
```

---

Related Issue:
* https://github.com/getcursor/cursor/issues/715
* https://github.com/getcursor/cursor/issues/1837

**Comment by adamkarvonen** [comment]
I have also never had any luck with Cursor and Remote SSH over the past year. I hope that this eventually works as right now it's completely worthless for me with out SSH support.

**Comment by faheemstepsharp** [comment]
What are they even doing??? with millions of dollars??

**Comment by patrontheo** [comment]
As suggested [here](https://github.com/getcursor/cursor/issues/489#issuecomment-2075734978), I uninstalled the remoteSSH extension and it started working. But I'm not on M1 mac but on an intel one, so not sure this will fix the issue for you

**Comment by marclundgren** [comment]
>  Failed to download VS Code Server (Server returned 404)

I don't know if this is helpful but I ran into this problem  and tried to uninstall `remoteSSH` extension per the comments in this thread. That didn't work, but I went ahead and re-enabled it and it was suddenly working once again. 

> Remote ssh connection to Windows 10(and64) via Cursor version 0.41.2 still doesn't work on macOS (Apple Silicon / M1)
> 
> My cursor info
> 
> ```
> Version: 0.41.2
> VSCode Version: 1.91.1
> Commit: 297991d169fa3a11975c5aa95adc69be73250c70
> Date: 2024-09-21T04:18:39.370Z
> Electron: 29.4.0
> ElectronBuildId: undefined
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Darwin arm64 24.0.0
> ```
> 
> Remote - SSH output It seems that the remote CLI address is incorrect or has not been uploaded
> 
> ```
> ...
> [10:20:24.473] Got request to download on client for {"artifact":"cli-win32-x64","destPath":"C:\\Users\\noah\\.cursor-server/vscode-cli-297991d169fa3a11975c5aa95adc69be73250c70.zip"}
> [10:20:24.473] server download URL: https://cursor.blob.core.windows.net/remote-releases/297991d169fa3a11975c5aa95adc69be73250c70/cli-win32-x64.tar.gz
> [10:20:24.473] Downloading VS Code server locally...
> [10:20:25.462] Terminating local server
> [10:20:25.468] Resolver error: Error: Failed to download VS Code Server (Server returned 404)
> ...
> ```
> 
> Related Issue:
> 
> * [Remote SSH with MacOS host not working. Release link broken. #715](https://github.com/getcursor/cursor/issues/715)
> * [Remote SSH not work in 0.40.4 version #1837](https://github.com/getcursor/cursor/issues/1837)

**Comment by Leymore** [comment]
I just find cursor using no folder as in `~/.cursor-server/bin/{hash}`.

I tried the following steps and everything magically works. 

1. delete the remote-ssh extension in vscode
2. restart both vscode and cursor
3. install and enable the remote-ssh extension in cursor
4. install and enable the remote-ssh extension in cursor

I am not sure which specific step makes thing work, but it is working after all.

**Comment by navels** [comment]
Per https://github.com/getcursor/cursor/issues/2251#issuecomment-2406409866:

> SSH to windows is not currently supported. You can try connecting to WSL instead.

**Comment by navels** [comment]
yessssss

**Comment by tmm1** [comment]
Does this work:

https://github.com/getcursor/cursor/issues/2440#issuecomment-2549310587

**Comment by navels** [comment]
> Does this work:
> 
> [#2440 (comment)](https://github.com/getcursor/cursor/issues/2440#issuecomment-2549310587)

Nope, target host is Windows and it errors installer the server:

```
Got request to download on client for {"artifact":"cli-win32-x64","destPath":"C:\\Users\\Administrator\\.cursor-server/vscode-cli-f3b5a63019e4e2283033b4db987a35f8413c7570.zip"}
[21:55:38.623] server download URL: https://cursor.blob.core.windows.net/remote-releases/f3b5a63019e4e2283033b4db987a35f8413c7570/cli-win32-x64.tar.gz
[21:55:38.623] Downloading VS Code server locally...
[21:55:38.746] Terminating local server
[21:55:38.750] Exec server for ssh-remote+dev.poker failed: Error: Failed to download VS Code Server (Server returned 404)
[21:55:38.750] Error opening exec server for ssh-remote+dev.poker: Error: Failed to download VS Code Server (Server returned 404)
```

and in fact that file doesn't exist:

```
> wget https://cursor.blob.core.windows.net/remote-releases/f3b5a63019e4e2283033b4db987a35f8413c7570/cli-win32-x64.tar.gz
--2024-12-22 21:57:06--  https://cursor.blob.core.windows.net/remote-releases/f3b5a63019e4e2283033b4db987a35f8413c7570/cli-win32-x64.tar.gz
Resolving cursor.blob.core.windows.net (cursor.blob.core.windows.net)... 20.209.35.129
Connecting to cursor.blob.core.windows.net (cursor.blob.core.windows.net)|20.209.35.129|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2024-12-22 21:57:06 ERROR 404: The specified blob does not exist..
```
