### ISSUE TITLE
iMPROVE THE CHAT AND ALSO UNDERSTAND THE QUERY BETTER

### ISSUE THREAD

**Issue by faheemstepsharp** [getcursor/cursor#2005]
IT FEELS CURSOR HAS BECEOME DUMBER

**Comment by danperks** [comment]
Hi, the Cursor team is constantly working to improve the Cursor app and the performance of the AIs. If you are finding one model to perform poorly, try others as well as changing your queries to see if you get better results.

As this isn't a specific bug or issue, I'll close this for now, but rest assured the team is working on making Cursor the best it can be!
