### ISSUE TITLE
Remote SSH Server download page unavailable

### ISSUE THREAD

**Issue by zelekharibo** [getcursor/cursor#2007]
[server] Error installing server: error requesting https://api2.cursor.sh/updates/download/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/vscode-reh-linux-x64.tar.gz: 504 <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

Can't connect to any server after latest cursor update.

**Comment by danperks** [comment]
Looks like that link is working now, could have just been some brief downtime when you were trying, can you try again and let me know if it's working?
