### ISSUE TITLE
Incorrect clang version api

### ISSUE THREAD

**Issue by andysun84** [getcursor/cursor#201]
I am trying to install c language server but failed to get the latest clang version from GitHub api.
I found a typo for clang version. This api should be "https://api.github.com/repos/clangd/clangd/releases/latest", but in the tool, seems we are missing a "repos" path.

**Comment by truell20** [comment]
sweet thanks @alexwebdevs, merged

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
