### ISSUE TITLE
It looks like there is a bug where a piece of code is split into three parts.

### ISSUE THREAD

**Issue by weiguanglai** [getcursor/cursor#202]
![微信截图_20230324102458](https://user-images.githubusercontent.com/15008221/227409340-646a7e5e-26c8-44c6-b140-44358b2e59c9.png)

**Comment by truell20** [comment]
huh thanks for filing this! what was your prompt? this will help me debug

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
