### ISSUE TITLE
模型根本不是gpt4,以下是我的测试结果。

### ISSUE THREAD

**Issue by woaidianqian** [getcursor/cursor#203]
克莱尔每天早饭都用3颗蛋做蛋卷，她4周会吃掉多少打鸡蛋？
To calculate the total number of eggs Claire will eat in 4 weeks, we need to first calculate the number of eggs she eats in a day and then multiply that by the number of days in 4 weeks.

Since Claire uses 3 eggs to make an egg roll every day, she eats 3 eggs per day.

To calculate the number of days in 4 weeks, we can multiply the number of days in a week (7) by the number of weeks (4).

Therefore, the total number of eggs Claire will eat in 4 weeks is:

3 eggs/day * 7 days/week * 4 weeks = 84 eggs

So Claire will eat 84 eggs in 4 weeks.
上面的答案是错误的。
真正的gpt4的答案如下：
克莱尔每天早饭都用3颗蛋做蛋卷，她4周会吃掉多少打鸡蛋？
克莱尔每天吃3颗蛋，一周有7天，所以一周吃掉3*7=21颗蛋。4周吃掉的鸡蛋数量为21*4=84颗。1打鸡蛋有12颗，所以克莱尔4周会吃掉84/12=7打鸡蛋。

**Comment by terminalqo** [comment]
你都会用gpt4了，用英语表达很难么
-------
You are already proficient in using GPT-4, is it difficult for you to express yourself in English?

**Comment by AeroXi** [comment]
Are you sure your prompt is the same as cursor?

**Comment by duguqqjian12** [comment]
现在市面上免费公开能用的基本都是3.5或者3的。最简单你直接问AI你是GPT3还是GPT2，都是回答的3，如果是4会否认你

**Comment by Sakura4036** [comment]
> 

I think so

**Comment by littlewwwhite** [comment]
I heard that the author changed it after the crash several days ago, it's GPT3.5 right now

**Comment by truell20** [comment]
closing this bc question is answered, but feel free to keep replying
