### ISSUE TITLE
Debug toolbar overlaps vscode window options on top left corner

### ISSUE THREAD

**Issue by sugaaloop** [getcursor/cursor#2032]
1) If you can, please include a screenshot of your problem
<img width="340" alt="image" src="https://github.com/user-attachments/assets/caa91a53-1d6e-47e6-a6cc-b5b280761070">

2) Please include the name of your operating system
MacOS Sonoma 14.6.1 (23G93)

3) If you can, steps to reproduce are super helpful
Not sure how I did it exactly, but dragging the debug toolbar around, possibly offscreen, it jumped to the upper left corner under the traffic light buttons. Seems to be [this exact issue](https://github.com/microsoft/vscode/issues/204265) from vs code.

You can't grab the toolbar handle under the buttons, so it seems stuck there. Toggling the toolbar location setting (`debug.toolBarLocation`) back and forth doesn't seem to fix it.

**Comment by danperks** [comment]
It appears that, from the bug you've sent, the fix has only been released to the "Insiders" (aka Beta) version of VSCode, as shown by the label on the right. Therefore, the latest real release of VSCode doesn't have the fix included yet. Therefore, I'll close this for now. If a version of VSCode is released with this fix in, feel free to open a new issue requesting the change to be merged into Cursor :)
