### ISSUE TITLE
Cannot paste any text in code window (can still paste in chat)

### ISSUE THREAD

**Issue by kirankunigiri** [getcursor/cursor#2040]
I cannot paste ANY text from ANY source inside any code window in Cursor. However, I am still able to paste inside the chat window, terminal, and composer. Only tabs for code files have broken CMD+V (paste). I have tried changing the keyboard shortcut to different keys, and that doesn't work either.

I have seen other issues posted, but they are the reverse of this issue (those users could paste in code windows, but not into the chat windows).

**Information**
Version: 0.41.3
VSCode Version: 1.91.1
Commit: 51c8aff7cb5a89f4a0e462fbacab938bdbfaf140
Date: 2024-09-25T17:13:50.377Z (5 days ago)
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0

**Comment by kirankunigiri** [comment]
UDPATE: This only happens on js/ts/jsx/tsx files. I have disabled all extensions and it still happens, so it is a Cursor issue.

**Comment by kirankunigiri** [comment]
I found out that the root cause of the issue was due to a profile setting.
`"typescript.experimental.updateImportsOnPaste": true,`

Removing this fixes the issue. However, note that this exact same setting does not cause any paste issues in VSCode. This is only a Cursor issue.

**Comment by danperks** [comment]
It does look like this is an issue that occurs in VSCode, potentially from an extension enabling the settings, so that even if you disable the extension, the experimental setting remains enabled. I'll close this now as an underlying issue with VSCode,:
https://stackoverflow.com/a/78993085/9178557
