### ISSUE TITLE
When talking to it, when there are too many English letters in the question, it will answer in English, and it needs to be re asked to answer in Chinese；在与它对话的时候，当问题中出现过多英文字母时，它便会用英文回答，还需要重新要求它用中文回答

### ISSUE THREAD

**Issue by WH1256** [getcursor/cursor#207]
**As the title shows**
**如标题所见**

![屏幕截图 2023-03-24 131442](https://user-images.githubusercontent.com/121672679/227431189-0cd9d36b-1e11-4d03-b190-4649d3dba704.png)

**Comment by kickTiger** [comment]
对话的时候，ChatGPT都这样。
是你自己使用的问题，加一句提示语就可以了。
```lua
用中文回复我
Reply in Chinese
```
