### ISSUE TITLE
Can i use my own Chatgpt Plus account?

### ISSUE THREAD

**Issue by DragonFSKY** [getcursor/cursor#208]

**Comment by truell20** [comment]
hey! are you proposing we let people use their own api keys? and then let them only use gpt-4?

**Comment by xxymag** [comment]
Yes, I want to use my own openapi key
Other wise if you can support the chatgpt access_token as a auth method ,we'll be appreciated
(for example ,the project "revchatgpt" in the github)

**Comment by 007lingqi** [comment]
> Yes, I want to use my own openapi key Other wise if you can support the chatgpt access_token as a auth method ,we'll be appreciated (for example ,the project "revchatgpt" in the github)

I also want to

**Comment by DragonFSKY** [comment]
> hey! are you proposing we let people use their own api keys? and then let them only use gpt-4?

Yes, I'd like to use Chatgpt-Proxy-v4 with chatgpt-4 to get an early experience of the capabilities of GitHub Copilot x.：:)

**Comment by 7flash** [comment]
If you already have monthly subscription you might want to avoid paying additional API usage. I can offer you a solution: run

**Comment by 7flash** [comment]
If you already have monthly subscription you might want to avoid paying additional API usage. I can offer you a possible solution: open chatgpt devtools and run a "bridge" script. It will listen for new requests in your cursor IDE, submit prompt in the input field, wait for response and give it back to cursor. If it makes sense, i can try to develop a demo.

**Comment by ShabbyWhineYear** [comment]
> If you already have monthly subscription you might want to avoid paying additional API usage. I can offer you a possible solution: open chatgpt devtools and run a "bridge" script. It will listen for new requests in your cursor IDE, submit prompt in the input field, wait for response and give it back to cursor. If it makes sense, i can try to develop a demo.

I did'n know it was an option. I'm looking forward to your demo.

**Comment by truell20** [comment]
Do you know if chatGPT plus has an API? either official or unofficial. would love to add support here

**Comment by truell20** [comment]
Also the latest versions have all included support for using your own OpenAI API key with GPT-4 if you'd like

**Comment by danperks** [comment]
As said in the last comment, you can use your own OpenAI key if you want to use GPT-4, and your own OpenAI account. Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!

**Comment by aishtiaq7** [comment]
Place to add your OpenAI api key for cursor: 
https://docs.cursor.com/advanced/api-keys

**Comment by timmbobb** [comment]
> If you already have monthly subscription you might want to avoid paying additional API usage. I can offer you a possible solution: open chatgpt devtools and run a "bridge" script. It will listen for new requests in your cursor IDE, submit prompt in the input field, wait for response and give it back to cursor. If it makes sense, i can try to develop a demo.

Were you able to get this to work?
