### ISSUE TITLE
Latest Version API or Latest Version Display on Website

### ISSUE THREAD

**Issue by dimitrirodis** [getcursor/cursor#2122]
Is there a way to determine the latest version of Cursor without downloading it? There does not seem to be a version number listing on the website, nor are there any listed releases in the Cursor github repo.

Is there an API that can be used to determine the latest available release version, or is there somewhere on the website that displays the latest version available for download that I have not found?

**Comment by danperks** [comment]
Hey, you can use this site to view the changelog:

https://changelog.cursor.sh

Not that on occasion, a release may have a gradual rollout, and therefore may show in the changelog before it's globally available.

**Comment by dimitrirodis** [comment]
I see the changelog, but that really doesn't lend itself to easily determining what the latest downloadable/installable version is, especially programmatically because the versions listed can't really deterministically be matched (using a regex for example).

The current September 17th heading shows a version of 0.41--but the latest version is actually 0.41.3. Sure, there's an update, but the "UPDATE" doesn't include a single version listing, it contains a range of versions, and a regex match on the page source itself matches a large number of irrelevant numbers.

Another thing I tried was just sending a HEAD request to https://downloader.cursor.sh/windows/nsis/x64  (because the headers you get from a GET contains the filename which contains the version), but that endpoint will not appropriately respond to HEAD for me to get that information (again, without having to download the entire package).

So is there a _better_ way to _programmatically_ determine the latest version of cursor?

**Comment by danperks** [comment]
Besides the changelog, I know of now way, especially programmatically, to get the latest version of Cursor available.

Can I ask what your use case is? I can put it to the team and see if it's something they'd be willing to support or assist with, but, to be clear, I'm not in that team so can't make any promises.

**Comment by dimitrirodis** [comment]
Found a way--putting this here in case it helps someone:
(Powershell)

`$Headers = (Invoke-WebRequest -Uri "https://downloader.cursor.sh/windows/nsis/x64" -Method Get -Headers  @{Range = "bytes=0-0"}).Headers`
`if([string]$Headers["Content-Disposition"] -match '\d+\.\d+(?:\.\d+(?:\.\d+)?)?') {`
`    $Matches[0]`
`}`

**Comment by danperks** [comment]
Nice find! Will close this to clean up the issues. :)

**Comment by bduffany** [comment]
The `downloader.cursor.sh` endpoint appears to have an outdated version (0.45) at least for the linux x64 appImage endpoint (https://downloader.cursor.sh/linux/appImage/x64)
