### ISSUE TITLE
400 Error Occurs When Using Gemini API

### ISSUE THREAD

**Issue by als141** [getcursor/cursor#2127]
**Issue Description:**
I am encountering a 400 error when attempting to use the Gemini API. The error occurs regardless of which models of Gemini I use and prompt. Below is the response I receive:

![スクリーンショット 2024-10-03 192232](https://github.com/user-attachments/assets/828ef111-e6d7-46eb-be12-17f424eb49a3)

```
{
  "error": {
    "code": 400,
    "message": "* GenerateContentRequest.safety_settings[4]: element predicate failed: $.category in (HarmCategory.HARM_CATEGORY_HATE_SPEECH, HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, HarmCategory.HARM_CATEGORY_HARASSMENT, HarmCategory.HARM_CATEGORY_CIVIC_INTEGRITY)\n",
    "status": "INVALID_ARGUMENT"
  }
}
```

**Environment:**
- Version: 0.41.3
- Commit: 1.91.1
- Date: 51c8aff7cb5a89f4a0e462fbacab938bdbfaf140
- Electron: 2024-09-25T17:13:50.377Z
- Electron Build ID: 29.4.0
- Chromium: Undefined
- Node.js: 122.0.6261.156
- V8: 20.9.0
- OS: 12.2.281.27-electron.0

Please let me know if any additional details are required.

**Comment by Ryukijano** [comment]
Ran into the same issue earlier, I think it has to do with how google has changed certain things for the request type for the api and cursor needs to be updated to send the request in the same way with an update.
![image](https://github.com/user-attachments/assets/73319c8f-4a7b-426b-a48e-dc16e8a5b2d3)

**Comment by danperks** [comment]
Thanks for the bug, it's likely already been noticed by the devs but I'll raise it regardless

**Comment by Zackh1998** [comment]
Hi! We've updated the backend to work with the latest Gemini API, and this error should be fixed now user specified Gemini keys now (it should always have been working with the Cursor key).

Closing the ticket for now, but please re-open or ping me if you see more issues with Gemini for custom keys.
