### ISSUE TITLE
Cannot download cursor

### ISSUE THREAD

**Issue by ZanyuanYang** [getcursor/cursor#2154]
1) If you can, please include a screenshot of your problem
![image](https://github.com/user-attachments/assets/fd5fadcb-3e52-4f49-b1d9-11c36c5b97be)

2) Please include the name of your operating system
mac
3) If you can, steps to reproduce are super helpful

**Comment by danperks** [comment]
Hey, is this still not working? I've checked that link and it appears to be working fine.

If you're still having issues, it may be a VPN or corporate firewall getting in the way and blocking the download.

As it's a direct download link, you could do "wget URL" in the terminal to download it that way, skipping the browser all together.

Let me know how you get on :)
