### ISSUE TITLE
Did cursor just wipe my windows 11 taskbar?

### ISSUE THREAD

**Issue by Web3NL** [getcursor/cursor#2191]
![image](https://github.com/user-attachments/assets/079f330d-d00c-4d82-92b4-6b8623c6dec5)

![image](https://github.com/user-attachments/assets/856e0291-4bdc-4c99-88e0-11e82558745e)

After restarting my system, the taskbar only contained cursor. 

I also noticed in the last weeks that the cursor taskbar icon stopped working saying that it cant find the binary. Taskbar funkyness

**Comment by danperks** [comment]
Seems like a Windows issue, as Cursor won't manipulate what is and isn't on the taskbar. 

I've known Windows 11 to have some funky issues like this, but if anyone else faces this issue I'll reopen the issue.
