### ISSUE TITLE
trying to enable o1-preview

### ISSUE THREAD

**Issue by unikzforce** [getcursor/cursor#2192]
1) If you can, please include a screenshot of your problem
![image](https://github.com/user-attachments/assets/9385e534-92d3-46fa-b7a3-0ac26c963f78)
2) Please include the name of your operating system
macos
3) If you can, steps to reproduce are super helpful

Hey cursor team, 
in the last couple of month i tried to use cursor ai only when i needed it, so there were a couple of month that i didn't need to use cursor and i set limit on the card that cursor is trying to charge me from and in those times that i didn't allow cursor to charge me  i didn't use cursor ai features. so i have two occasions that cursor tried to charge me but it was blocked.
now i want to use `o1-preview` and i need to enable `optional usage-based pricing` but it doesn't allow me to , and tells me that i had 2 unpaid invoices, the thing is that i didn't use cursor at those times, so i just simply blocked it from charging me, what should i do?
![image](https://github.com/user-attachments/assets/efd883d4-5f73-496d-8683-2d12d0aab952)

**Comment by danperks** [comment]
Hi, this looks to be the expected use case. When you sign up for Cursor, you agree to pay a monthly fee to get access to Cursor, regardless of whether you use it or not.

You could have avoided this by going onto your Cursor account via the button in the settings and cancelling your membership. As it's a 1 month reoccurring subscription, you could have done this whenever, cancelling for 1 month and restarting again.

To resolve this, please email hi@cursor.com for further help.
