### ISSUE TITLE
Set up project directory structure, automatically determine the context of code and files, and provide global suggestions for the project.

### ISSUE THREAD

**Issue by mengzhongshuike** [getcursor/cursor#220]

**Comment by truell20** [comment]
this is a cool idea! hopefully we'll have more updates in this direction soon 🙂

**Comment by danperks** [comment]
You've got a few suggestions here and each have been mentioned in other, individual bugs, so I'll close this in favour of those!

See #67 for the possibility of files and folders being created automatically and #158 for better context when writing code with the AI.
