### ISSUE TITLE
Cursor Tab is not functioning properly in Python files.

### ISSUE THREAD

**Issue by Lihaogx** [getcursor/cursor#2223]
I have enabled the Cursor Tab feature, but I find that it doesn't work in my Python files. It works well in tex files, json files, and yaml files. Meanwhile, I noticed that it works fine on my laptop. I wonder if I need to do some additional configuration.
My operating system is Windows 11 23H2, and my Cursor version is 0.41.3.
![image](https://github.com/user-attachments/assets/dc262d5a-f664-4091-acaf-e053dea0adde)

**Comment by danperks** [comment]
Can you try disable the Auto Import for Python feature, just on the off chance that is causing the whole thing to stop working on Python files? If that doesn't help, can you try change some of the settings you've screenshot and see if Cursor Tab starts working with certain features on or off?

**Comment by Lihaogx** [comment]
> Can you try disable the Auto Import for Python feature, just on the off chance that is causing the whole thing to stop working on Python files? If that doesn't help, can you try change some of the settings you've screenshot and see if Cursor Tab starts working with certain features on or off?

Thank you very much for your reply. I found that the issue was caused by the 'disable for python' option in the bottom right corner. The problem is now resolved.
