### ISSUE TITLE
Remote - SSH is only supported in Microsoft versions of VS Code

### ISSUE THREAD

**Issue by navels** [getcursor/cursor#2251]
On MacOS, Cursor 0.42.0, installed latest (0.116.2024100715) version of the Remote - SSH extension from here:

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

The extension installs but when I try to use it to connect to a remote host I get. this error in the output tab:

```
Resolver error: Error: Remote - SSH is only supported in Microsoft versions of VS Code
```

**Comment by Sanger2000** [comment]
Try uninstalling and re-installing from inside cursor?

**Comment by navels** [comment]
> Try uninstalling and re-installing the extension from inside cursor.

That extension (ms-vscode-remote.remote-ssh) doesn't come up in the extension marketplace search.

**Comment by tmm1** [comment]
Installing 0.113.1 should work.

**Comment by navels** [comment]
0.113.2024072315 gets further but then I run into ye old `BlobNotFound` trying to download the code server at https://cursor.blob.core.windows.net/remote-releases/9e8f0f993884031e2f08d75f7adab80d1732a980/cli-win32-x64.tar.gz

**Comment by tmm1** [comment]
SSH to windows is not currently supported. You can try connecting to WSL instead.

**Comment by navels** [comment]
> SSH to windows is not currently supported. You can try connecting to WSL instead.

Thanks for clarifying that, hope to see it fixed soon . . . WSL doesn't cut it for me.

**Comment by xiangmind** [comment]
Download the opensource version from https://open-vsx.org/extension/jeanp413/open-remote-ssh, and drag it into cursor's extensions tab. Enjoy!

**Comment by navels** [comment]
> Download the opensource version from https://open-vsx.org/extension/jeanp413/open-remote-ssh, and drag it into cursor's extensions tab. Enjoy!

Does this work for you?  Because it does not for me, it fails in the same way the MS extension does:
```
--2024-10-14 09:10:49--  https://cursor.blob.core.windows.net/remote-releases/c499aee5f16e67815c7dc795ff338dc8ab3e07f0/vscode-reh-win32-x64.tar.gz
Resolving cursor.blob.core.windows.net (cursor.blob.core.windows.net)... 20.209.35.129
Connecting to cursor.blob.core.windows.net (cursor.blob.core.windows.net)|20.209.35.129|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2024-10-14 09:10:53 ERROR 404: The specified blob does not exist..
```

**Comment by nickmealey** [comment]
This is a huge bummer because we need this

**Comment by ddolgov** [comment]
> SSH to windows is not currently supported. You can try connecting to WSL instead.

Why was this closed? This is a huge functionality piece missing

**Comment by drxmknight** [comment]
Got the same problem. I was trying to attach a python:3.12-alpine container. Switched to python:3.12-slim-bookworm and got fixed.

**Comment by tmontana** [comment]
> Download the opensource version from https://open-vsx.org/extension/jeanp413/open-remote-ssh, and drag it into cursor's extensions tab. Enjoy!

This does not work.  Cursor stuck trying to open the connection.

**Comment by cipri-tom** [comment]
> Try uninstalling and re-installing the extension from inside cursor.

I cannot uninstall it, as I get the same error when trying to uninstall 😁

**Comment by rpavlovicTT** [comment]
> > Try uninstalling and re-installing the extension from inside cursor.
> 
> I cannot uninstall it, as I get the same error when trying to uninstall 😁

Same here.

**Comment by navels** [comment]
FYI the nightly build has been working for me.

**Comment by 5shekel** [comment]
> FYI the nightly build has been working for me.

thanks  @navels for updating this issue, which extension(?) nightly build are you referring to?

**Comment by navels** [comment]
> > FYI the nightly build has been working for me.
> 
> thanks [@navels](https://github.com/navels) for updating this issue, which extension(?) nightly build are you referring to?

The nightly build of cursor, you have to register on the community forums: https://forum.cursor.com/t/windows-remote-ssh-support/37286/3

**Comment by LukeLIN-web** [comment]
Same in my mac cursor 0.45

**Comment by cherryWangqaz** [comment]
> Same problem in my mac cursor 0.45 `Try uninstalling and re-installing the extension from inside cursor.` it can work

i tried , but That extension (ms-vscode-remote.remote-ssh) doesn't come up in the extension marketplace search. then, i viewed the web of extensions for vscode , even can not find the download extension button!!!!

**Comment by bekriebel** [comment]
You can get it to work by installing a version from before when Microsoft began blocking its use on third party apps. `v0.113.1` is the latest version I was able to get working, which can be downloaded from here: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.113.1/vspackage

**Comment by liyichao** [comment]
Server returned 404

**Comment by bekriebel** [comment]
> using v0.113.1, when downloading vscode server, it returns `Server returned 404`

Perhaps try an older version first. I saw some odd behavior when downgrading, but was able to eventually upgrade to that version. It's also certainly possible that MS broke it further.

**Comment by mingfang** [comment]
Still a problem in the latest version.
```
Version: 0.45.15 (Universal)
VSCode Version: 1.96.2
Commit: 73dd83bb6f8e3a3704ad8078a8e455ac6d4260d0
Date: 2025-02-22T10:15:54.481Z
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0
```

**Comment by xiangyunkeji** [comment]
> You can get it to work by installing a version from before when Microsoft began blocking its use on third party apps. `v0.113.1` is the latest version I was able to get working, which can be downloaded from here: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.113.1/vspackage

thanks！it works，download this and drop it from finder to cursor。
