### ISSUE TITLE
Interpreter stays frozen in the screen

### ISSUE THREAD

**Issue by xoelop** [getcursor/cursor#2259]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

Using Cursor with these versions:
```
Version: 0.41.3
VSCode Version: 1.91.1
Commit: 51c8aff7cb5a89f4a0e462fbacab938bdbfaf140
Date: 2024-09-25T17:13:50.377Z (2 wks ago)
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0
```

When I try to use Interpreter, its panel 
1. Takes up more space than my screen, so the X button to close it disappears
2. I can't see any other way to remove it than force closing Cursor

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6edef4dd-2a85-4855-81de-e91e88bf7569">

Is this happening to someone else? How can I get it to work?

**Comment by shaoruu** [comment]
Hi, apologies for this. You can do "cmd-m" to minimize the top of composer and then drag it down for now. In v0.42+, this will be fixed so that composer will never exceed the top of the window.

**Comment by danperks** [comment]
As it's a known issue, with a fix coming in later versions, I'll close this for now :)
