### ISSUE TITLE
Application not openning

### ISSUE THREAD

**Issue by hayattgd** [getcursor/cursor#2266]
![image](https://github.com/user-attachments/assets/0c5b4f07-b931-41b2-93c0-f67aece223cf)

that error occur after starting from shortcut (only error, no window shown)

```bash
$ cursor .
node:internal/modules/cjs/loader:1155
  throw err;
  ^

Error: Cannot find module 'c:\Users\hayat\AppData\Local\Programs\cursor\resources\app\out\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at c._load (node:electron/js2c/node_init:2:13801)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:189:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.15.1
```

this is when i do `cursor .` in command line
it was all good yesterday and i didnt edited stuffs around node.js or cursor

**Comment by danperks** [comment]
Hey, can you try uninstall and reinstall Cursor? That should hopefully resolve it.

**Comment by hayattgd** [comment]
it solved issue, thanks. i still wonder why it happend though.
