### ISSUE TITLE
Cursor app freezes in Mac OS 

### ISSUE THREAD

**Issue by yubin-ai** [getcursor/cursor#2286]
Version: 0.42.2
VSCode Version: 1.93.1
Commit: c499aee5f16e67815c7dc795ff338dc8ab3e07f0
Date: 2024-10-12T05:39:54.471Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

Mac OS: 15.0.1 
during ssh, using jupyter notebooks (10MB size, with several plots in it).
It never happened before the Cursor update. Same usage as before. Sometimes it recovers itself, sometimes I have to restart it.

<img width="249" alt="image" src="https://github.com/user-attachments/assets/67789eb3-b354-4026-86f5-a297f5d5742c">

**Comment by verioussmith** [comment]
You should submit your request here:  https://forum.cursor.com/

They said they reply faster there.  I just submitted a request.

**Comment by danperks** [comment]
As the window is not responding, my first guess is that Cursor is waiting for SSH to finish passing through the output from your notebook.

To confirm, do you have a stable connection to the device you are SSH'd into?

If so, do you know if this behaviour occurs in VSCode, as the code that powers Notebooks and SSH are mostly shared between VSCode and Cursor?

**Comment by yubin-ai** [comment]
@danperks 
when it freezes it happens (4 times by now) when I copy the output from the Cursor notebook to my presentation. when I return to the Cursor, it freezes. there is no running code before it freezes. and the connection is very stable. 

I will try to use vs code for today and see if it happens.

**Comment by verioussmith** [comment]
I'm confused how you got a quicker answer here when as a paying customer I put in a report on the forums where they told me to put in a report and I have yet to get an answer.

**Comment by yubin-ai** [comment]
@danperks 
update: the freezing happens in the latest VS Code as well (never happened before). I will post it there too.

**Comment by danperks** [comment]
> I'm confused how you got a quicker answer here when as a paying customer I put in a report on the forums where they told me to put in a report and I have yet to get an answer.

Hi, can you link to your forum post, as I haven't come across it? Sorry we've not got to it yet!

**Comment by danperks** [comment]
@yubin-ai Ah, if VSCode has the issue, then it's likely in an underlying dependency and not fixable by the Cursor team.

If you raise an issue and it gets resolved, comment here again and we can prioritise the fix being including in Cursor releases.

**Comment by danperks** [comment]
@verioussmith It looks like your latest post on the forum had a response 1hr ago, asking for some logs. 

Response time is very dependant on platform, the contents of the issue and time zones, but you had a response in less than 12hrs, which for an app as large as Cursor seems like a decent response time.

**Comment by verioussmith** [comment]
The response came after me coming here and seeing a response here in this unpaid forum.  Anyway, my problem is solved.

https://forum.cursor.com/t/cursor-keeps-crashing-after-new-update/23287/3
