### ISSUE TITLE
How to hide this bar? 

### ISSUE THREAD

**Issue by MariuzM** [getcursor/cursor#2289]
In vscode i have this hidden and when i imported settings it shows in cursor, how can i hide it? 
<img width="368" alt="image" src="https://github.com/user-attachments/assets/64a7faee-aa18-4fb5-8b1f-3dbb21170080">

**Comment by danperks** [comment]
You may need to change the activity bar to be horizontal for this feature to work, but it should be the same as in VSCode!

Try setting it to horizontal and see if that resolves it :)

**Comment by MariuzM** [comment]
what is horizontal? 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/48df3b81-4ac1-4477-8097-979ae2258d8f">

**Comment by danperks** [comment]
Hey, I don't think it's an option in that menu.

If you open the Settings UI (CMD+P then search for it), the settings has the id:
`workbench.activityBar.orientation`

<img width="897" alt="image" src="https://github.com/user-attachments/assets/12b4684a-f46d-4e9b-9b0e-a5a5db3ba148">

**Comment by MariuzM** [comment]
It worked thank you :) but i have no idea what that option actually does

**Comment by tomgenoni** [comment]
Small correction: the `Workbench › Activity Bar: Orientation` setting needs to be set to `vertical`.

![Image](https://github.com/user-attachments/assets/d1926b5c-81b4-4774-8082-1a584d7486ce)

**Comment by Yaphet2015** [comment]
It looks like the `position: hidden` setting was removed in version 2.0.

**Comment by vaileamon** [comment]
Same here
