### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by PawKanarek** [getcursor/cursor#2291]
I'm getting the [internal] internal error error while i try to login on your site https://www.cursor.com/

![image](https://github.com/user-attachments/assets/353e716e-2c99-4312-8b82-79d01909f4b7)

**Comment by sonsoixam** [comment]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/20c1e395-8aae-4b3c-850b-2f341036a323">

same problem

**Comment by PawKanarek** [comment]
It is gone now
