### ISSUE TITLE
Unable to resize sidebar in cursor

### ISSUE THREAD

**Issue by ayush-vibrant** [getcursor/cursor#23]
## Description
I am facing an issue with the Cursor IDE where I am unable to resize the sidebar. This is causing problems when there is a lot of hierarchy in the project, as the file names are not clearly visible due to the narrow sidebar. This makes it difficult for me to navigate through the project and find the files I need to work on.

## Steps to reproduce
1. Open the Cursor IDE.
2. Open a project with a lot of hierarchy (e.g. a Java project).
3. Attempt to resize the sidebar by dragging the border between the sidebar and the main window.

### Expected result
The sidebar should resize to allow for better visibility of file names.

### Actual result
The sidebar does not resize, and the file names remain narrow and difficult to read.

## Environment
- Operating system: macOS Monterey v12.6.3
- Cursor IDE version: latest version, not sure about the version number.

Additional information: This issue occurs consistently on my machine, and I have not been able to find a workaround. I would greatly appreciate it if this issue could be addressed in a future update to the Cursor IDE.

**Comment by ruzhengzhao** [comment]
The same problem as I encountered. It affects normal use very much.

**Comment by Palai-s** [comment]
加1 ，项目结构侧面栏 无法调整 ，急需解决

**Comment by truell20** [comment]
Thanks for reporting :) should be fixed in the latest version (0.1.5). try restarting the app to get the update.
