### ISSUE TITLE
希望可以在右键单击文件夹后，可以选择在命令行终端打开文件夹位置

### ISSUE THREAD

**Issue by Seifon** [getcursor/cursor#232]

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂

**Comment by yuzhounh** [comment]
为Windows添加Cursor编辑器的右键菜单选项
https://blog.csdn.net/yuzhounh/article/details/142726171

**Comment by moxia** [comment]
The latest version still does not support this feature
