### ISSUE TITLE
Are there any shortkuts to open new folder in cursor along with other things ? 

### ISSUE THREAD

**Issue by Gitstar-OC** [getcursor/cursor#2327]
NOTE: We will try our best to check Github Issues, but [forum.cursor.com](https://forum.cursor.com/) is our main site for bug reports / user feedback. We'd recommend you post there for the fastest response.

There is no shortkut to open a new folder in cursor while in vs code `ctrl + o` opens a file and `ctrl + k + o` opens a folder in cursor both of this shortkuts are only opening the files, kindly fix this and add some more setting and shortkuts in it other than just AI api's and settings.

**Comment by JustTrott** [comment]
`Ctrl + M + O` works for me (Both in Windows and Linux versions). Moreover, there are all of the settings and shortcut settings that are present in VS Code.
