### ISSUE TITLE
I want Github to stop charging me immediately. I don't need & I don't use Github

### ISSUE THREAD

**Issue by H3ndrikus** [getcursor/cursor#2339]
NOTE: We will try our best to check Github Issues, but [forum.cursor.com](https://forum.cursor.com/) is our main site for bug reports / user feedback. We'd recommend you post there for the fastest response.

**Comment by danperks** [comment]
Hi @H3ndrikus,

This is the Github issues repository for Cursor, the AI coding app.
If you have issues with GitHub, you'll need to contact them directly!

**Comment by H3ndrikus** [comment]
Thank you for your action 🙏
