### ISSUE TITLE
Issue with APC Extension + Cursor (EROFS: read-only filesystem)

### ISSUE THREAD

**Issue by armenr** [getcursor/cursor#2347]
The APC Extension with Cursor appears problematic. 

I get the following error:

```
Apc Extension failed: Error: EROFS: read-only file system, copyfile '/home/<my_user>/.cursor/extensions/drcika.apc-extension-0.4.1/resources/bootstrap-amd.js' -> '/tmp/.mount_cursorqRw4LX/resources/app/out/bootstrap-amd.js'
```

This happens on Arch Linux (CachyOS). Any help or advice to get this working would be much appreciated! The same does not happen with VSCode (or other flavors of VSCode I've tried so far).

**Comment by danperks** [comment]
Unfortunately, a 3rd party extension like the APC Extension, which tries to modify Cursor's internal styling and code, is not something we recommend or can support.
