### ISSUE TITLE
A system error occurred (spawn EBADF)

### ISSUE THREAD

**Issue by Zih0** [getcursor/cursor#2348]
search input some words, then sometimes report error like screenshot.

<img width="433" alt="SCR-20241106-pkdm" src="https://github.com/user-attachments/assets/951491bd-54f7-4975-ba1b-fa89ce4063e2">

```
Version: 0.42.4
VSCode Version: 1.93.1
Commit: b1e87884330fc271d5eb589e368c35f14e76dec0
Date: 2024-10-29T17:17:29.347Z (1 wk ago)
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by danperks** [comment]
Hi, this may mean you have a corrupted Cursor installation.

Can you try to uninstall and reinstall Cursor with a fresh download from the website?

**Comment by Zih0** [comment]
@danperks Thank you for reply. I try to reinstall

**Comment by Zih0** [comment]
Thank you! it fixed. I close the issue
