### ISSUE TITLE
 Windows version  auto deleted

### ISSUE THREAD

**Issue by Siloen** [getcursor/cursor#241]
is this necessary for updates? or something went wrong on my pc

**Comment by Sanger2000** [comment]
Will look into this. We have some auto-update bugs that we're fixing now

**Comment by truell20** [comment]
Is this still happening with the newest version? If so, could you send a screen recording / could you say what operating system you're on?

**Comment by danperks** [comment]
Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!

**Comment by Dr34nn** [comment]
Repeated occurrences

**Comment by felvieira** [comment]
same here
