### ISSUE TITLE
The code in the chat box lost its highlight

### ISSUE THREAD

**Issue by boxizen** [getcursor/cursor#244]
## Description

After the response about generating a piece of code, and ask it to describe in another language, the code loses its highlighting

## Recurrence

Step 1. Type `command` + `L`.

Step 2. Enter `generate quicksort code` in the textinput.

Step 3.  Enter `use javascript` after the response code generation.

## Screenshot

<img width="428" alt="image" src="https://user-images.githubusercontent.com/6027456/227753600-26c1073c-3014-42f0-acf1-72b14059814a.png">

### Console

<img width="428" alt="image" src="https://user-images.githubusercontent.com/6027456/227753619-4143ef60-ae9b-4094-8ce2-1c7990cb542d.png">

### Analysis

When the second request is made, ` ``` ` token is returned at the beginning, 
as shown above, resulted in a markdown syntax error and loss of highlighting.

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂

Let me know if not!
