### ISSUE TITLE
Bug: Remote SSH connection issue after upgrading to version 0.43.5

### ISSUE THREAD

**Issue by WILLOSCAR** [getcursor/cursor#2440]
# Description: 
After upgrading to version 0.43.5, I am unable to establish a remote SSH connection using the Remote SSH plugin. However, version 0.42.3 works fine and I can connect to the server without issues.

# Steps to reproduce:
Upgrade to version 0.43.5.
Use the Remote SSH plugin to connect to a remote server.
Notice the connection failure.
Expected behavior: The Remote SSH plugin should connect to the remote server successfully, just like it does in version 0.42.3.

# Actual behavior: 
The connection fails after upgrading to version 0.43.5.
# Question about auto-updates: 
Can you provide instructions on how to disable automatic updates in Cursor?

# Environment:
Cursor version: 0.43.5
Remote SSH plugin version: [Add version if known]
OS: [Windows 11]
Remote server OS: [Ubuntu 20.04]
## server example：
Host server name
  HostName  xxxx
  Port xxxx
  User xxx
  ProxyJump xxx

**Comment by faulander** [comment]
i am using 0.43.5 and only working with the ssh plugin and got no problems.
So this is not a general problem.

**Comment by WILLOSCAR** [comment]
If possible, could you please specify the version of your remote SSH client? For reference, mine is version 0.113.1, which is the highest version I can install. Although my VSCode version is higher, I am unable to import plugins into Cursor.



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/03/2024 02:15 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [getcursor/cursor] Bug: Remote SSH connection issue after upgrading to version 0.43.5 (Issue #2440) |

i am using 0.43.5 and only working with the ssh plugin and got no problems.
So this is not a general problem.

**Comment by WILLOSCAR** [comment]
> i am using 0.43.5 and only working with the ssh plugin and got no problems. So this is not a general problem.

If possible, could you please specify the version of your remote SSH client? For reference, mine is version 0.113.1, which is the highest version I can install. Although my VSCode version is higher, I am unable to import plugins into Cursor.

**Comment by faulander** [comment]
I have v0.113.1 installed.
Sorry, that it's not different, but it just works.
At least it works on windows, i am currently on a mac and cannot test it.

Am Mo., 2. Dez. 2024 um 19:23 Uhr schrieb WILLOSCAR <
***@***.***>:

**Comment by dperique** [comment]
I'm on Mac (Sonoma 14.6.1) on this version of cursor:

```
Version: 0.43.6
VSCode Version: 1.93.1
Commit: a846435528b4b760494a836f96f0739889253530
Date: 2024-12-06T05:11:55.168Z (1 day ago)
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.6.0
```

and using `Remote - SSH v0.113.1` and just trying to get settings for `Remote-SSH`, I get a dialog message saying:

```
Command 'Remote-SSH: Settings' resulted in an error
command 'opensshremotes.settings' not found
```

So even just trying to configure settings doesn't work.

Also, I tried 'Connect to Host...' and nothing happens. Not sure how to get debugging info on that. But the remote ssh server is also mac.

What version of cursor did this work on? maybe I'll install that.

**Comment by pololi-stripe** [comment]
My colleague helped me.
Until Cursor bump its vscode version,
you can use this link to download the old version of "Remote - SSH" from MS https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.113.1/vspackage and then manually install in Cursor.

**Comment by bhuga** [comment]
To be clear, download the link at https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.113.1/vspackage, and then:

```shell
$ cursor --uninstall-extension ms-vscode-remote.remote-ssh
$ cursor --install-extensions <the downloaded vsix file>
```

There's nothing about this in the release notes, which is kind of a bummer from MSFT.

**Comment by tmm1** [comment]
If you uninstall and reinstall the SSH extension from inside Cursor, it should automatically pick the most compatible version. Let us know if that's not working for you.
