### ISSUE TITLE
Can not install c language server

### ISSUE THREAD

**Issue by hhuzzz** [getcursor/cursor#245]
When I click the install button, there is no response. Is there a solution?

**Comment by Desperado1001** [comment]
+1

**Comment by alexwebdevs** [comment]
@hhuzzz , @Desperado1001 please let me know if you got this error in the latest app version.

**Comment by hhuzzz** [comment]
> @hhuzzz , @Desperado1001 please let me know if you got this error in the latest app version.

I installed this app on the official website the day before yesterday. Currently, only the Python language server is valid. Although I installed Java, it still cannot prompt in the Java file.

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
