### ISSUE TITLE
After setting up deepseek, chat cannot be used

### ISSUE THREAD

**Issue by KeWangKW** [getcursor/cursor#2471]
![WeChatb22728e5b48248dc7adb739589e6b22a](https://github.com/user-attachments/assets/c8d78ec4-a7b8-4c61-af4d-fe5880aae20d)

** I tried using a different url**
 https://api.deepseek.com/v1
 https://api.deepseek.com/beta
 https://api.deepseek.com/
It had no effect

 **I sent the key to someone else, where it could be used** 
 
 Now what should I do to make it work

**Comment by yijiejiang** [comment]
try this.[https://github.com/deepseek-ai/awesome-deepseek-integration/tree/main/docs/cursor](url)
