### ISSUE TITLE
Updated composer frequently returns nothing

### ISSUE THREAD

**Issue by noahslens** [getcursor/cursor#2473]
# Expected Behavior

Enter a message in the composer, wait a few seconds, start seeing streaming output.

# Current Behavior

Wait for 60+ seconds with no response from Anthropic; "edit" the message, press return, and the expected behavior happens (sometimes you need to do this a couple times).

# Environment Details

Version: 0.43.6
VSCode Version: 1.93.1
Commit: a846435528b4b760494a836f96f0739889253530
Date: 2024-12-06T05:11:55.168Z
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

Operating System: MacOS 14.5 (23F79)
Model: claude-3-5-sonnet-20241022

**Comment by Loading-m** [comment]
+1

**Comment by noahslens** [comment]
Seems to be solved.

**Comment by VladSt90** [comment]
I encounter the same behavior
