### ISSUE TITLE
Feature Request: Keep input as comment in Edit Mode.

### ISSUE THREAD

**Issue by Jas-S** [getcursor/cursor#248]
Please keep input as comment in Edit Mode.
It will helpful when I review the code at couple of days.

**Comment by Sanger2000** [comment]
What exactly do you mean by this? Do you want the suggested added code to be commented out? Or the prompt to be displayed as a comment?

**Comment by Jas-S** [comment]
My meaning is that when I use the edit mode now, every question I have entered will not be retained. 
When I want to edit the question I raised, I can only write it again from scratch. 
In addition, after a few days, I may forget the details of the question raised at that time. 

So I hope that my input content can be saved in the form of comments in the resulting code. 
This makes it easier for me to modify the questions raised and to look back at the results later and have a clearer understanding of the questions raised at that time.

**Comment by truell20** [comment]
Try hitting Ctrl + Shift + Up in the prompt bar to see your past prompts. 

This is an interesting idea! Thank you for sharing
