### ISSUE TITLE
Cursor unusable at 0.43 for me - need to revert back to 0.42, how to do it? 

### ISSUE THREAD

**Issue by hallodom** [getcursor/cursor#2487]
I recently updated Cursor to version 0.43, but unfortunately, it's not working well for me. The prompts it's suggesting are really hit or miss, it's missing files, not applying changes correctly. Unreliable suggestions. I cannot use this current version. 

I'd like to revert back to version 0.42, which was much more stable.

Does anyone know the best way to do this? Any guidance on where to find the older version and how to install it would be greatly appreciated!

Thanks in advance for your help! 😊

**Comment by hallodom** [comment]
Update from Cursor forum for people who need it 🙏 

> We’re adding a Downloads page to [cursor.com](http://cursor.com/) that will include all old builds. In the meantime, here are the build links for 0.42.5: Mac - https://downloader.cursor.sh/builds/24111460bf2loz1/mac/installer/universal Windows x64 - https://downloader.cursor.sh/builds/24111460bf2loz1/windows/nsis/x64 Linux x64 - https://downloader.cursor.sh/builds/24111460bf2loz1/linux/appImage/x64

<img width="834" alt="Screenshot 2024-12-14 at 14 56 25" src="https://github.com/user-attachments/assets/fe98675c-9c14-455f-aa11-87f3c4500731" />

**Comment by Aron-04Wang** [comment]
Thank U so much, this stupid issue ruined my whole day your advise and supply are really helpful! 0.43 really sucks!

**Comment by hallodom** [comment]
> Thank U so much, this stupid issue ruined my whole day your advise and supply are really helpful! 0.43 really sucks!

Happy it's helped you!
