### ISSUE TITLE
We're getting more traffic than we can handle right now. Please try again later.

### ISSUE THREAD

**Issue by wulie** [getcursor/cursor#255]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/17542512/227776081-192c6396-13fa-40c7-98f2-c4905c4a19f4.png">

**Comment by wewewexiao2008** [comment]
This product is too brilliant.

**Comment by 0xFFFF-maker** [comment]
me too！！！

**Comment by shendawei** [comment]
So did i just now! As rebooting it is so the case.

**Comment by LokerL** [comment]
我升级到了最新的版本也报这个错误。

**Comment by chipelly** [comment]
me too! so how to handle this problem? only wait?

**Comment by wewewexiao2008** [comment]
After encoutering this problem, I have to say, #208 is more urgent than any other UI features.

**Comment by zNightKidz** [comment]
下载的最新版本，遇到了同样的问题

**Comment by Fiyx0526** [comment]
me too

**Comment by planzq** [comment]
have the same problem

**Comment by Re-dorn** [comment]
same

**Comment by PengShiqiu** [comment]
me too

**Comment by windywater** [comment]
目前发现碰到此问题的都是中国网友

**Comment by zemin-piao** [comment]
Time is the healer :P

**Comment by Kungy** [comment]
it was caused by the chat api request which give a 504 api gateway error, is there someone could sovle it?

**Comment by D-Ayden** [comment]
Me too, and after I signed in the Copilot, nothing happened while I clicked the "Done" button.

**Comment by truell20** [comment]
Hi all apologies here! We've been getting more people using Cursor than expected. Everything should be normal now.
