### ISSUE TITLE
It has already been uninstalled and the more updates there are, the worse it gets.

### ISSUE THREAD

**Issue by zhaohai1024** [getcursor/cursor#258]
It has already been uninstalled and the more updates there are, the worse it gets.

**Comment by truell20** [comment]
hey @zhaohai1024 apologies here! could you describe the problem you're having a bit more? perhaps a screenshot would help?

**Comment by Blue2322** [comment]
me too ctrl + K often fails, and clicking the editor does not respond

**Comment by truell20** [comment]
Hi! Is this still a problem in the newest version?

**Comment by danperks** [comment]
Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!
