### ISSUE TITLE
Add more to the website (seems stuck as there is nowhere to scroll to)

### ISSUE THREAD

**Issue by abhinav2712** [getcursor/cursor#259]
When I first opened the website. it wasnt scrolling and was stuck, Later I realized this is how its build.
I would like to redesign the website, add relevant content and links, 
I request mentors of this Repo to assign this issue to me, will get it fixed

**Comment by Mikadifo** [comment]
I thought the website was loading at first, but yeah, it would be great to have more information in it.

**Comment by danperks** [comment]
As the app is still in development, nothing is really set it stone yet, so keeping a website up to date with every new feature could be tedious, but I agree more info is never a bad thing!

**Comment by abhinav2712** [comment]
@danperks If its possible, keep me in loop and I can update the website time to time, sounds fair?

**Comment by danperks** [comment]
As Cursor is now a subscription-based SAAS product with a free tier, I believe the team wants to keep the website developed in-house to ensure they don't say the app has features it doesn't and keeps in line with how the business wants to present itself. I'll leave the issue open and let @truell20 chime in his thoughts if he wants, I'm just assuming things from what I've heard 😄

**Comment by abhinav2712** [comment]
@Mikadifo Oh right, since the product is in its beta phase, maybe we can mention it first then add "upcoming features", Just an idea, it would be good for promotion purposes but yeah, all depends on the team to decide..

**Comment by truell20** [comment]
Hey! Appreciate the suggestion here. Once our features are a bit more built-out and set-in-stone, we'll add them to the website.

**Comment by truell20** [comment]
Changed the design a tiny bit so now shouldn't look like it's stuck 🙂
