### ISSUE TITLE
Maximum Capacity

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [getcursor/cursor#260]
why always alter 'We're getting more traffic than we can handle right now . please try againi later'。

**Comment by liuhuapiaoyuan** [comment]
![image](https://user-images.githubusercontent.com/8020726/227789239-f61d3f5e-1003-439b-a5a1-53a20d86d827.png)

**Comment by zengzhonggang** [comment]
I have the same problem.

**Comment by truell20** [comment]
hi @liuhuapiaoyuan @zengzhonggang apologies here! we've been getting more people using cursor than expected. should be back up now.

**Comment by bg3qt** [comment]
![image](https://user-images.githubusercontent.com/7579318/228414055-f6775074-737c-49cf-8c3b-8653fc69e3fd.png)
I've the same issue, Do I have to force an upgrade to continue using it？

**Comment by zengzhonggang** [comment]
> ![image](https://user-images.githubusercontent.com/7579318/228414055-f6775074-737c-49cf-8c3b-8653fc69e3fd.png) I've the same issue, Do I have to force an upgrade to continue using it？

I receive it too. You can use it for free, but there are limits. When you receive this message, you can try again or use it tomorrow

**Comment by Hspring322** [comment]
是需要$20/月才能继续使用吗
