### ISSUE TITLE
Vuejs support?

### ISSUE THREAD

**Issue by tinkerbaj** [getcursor/cursor#266]
Is it possible to use it with vuejs?
BTW The editor looks amazing.

**Comment by truell20** [comment]
should be possible! does something not work well? are the syntax highlight or language support for vuejs broken?

**Comment by tinkerbaj** [comment]
This is how it looks like  
 

![](https://user-images.githubusercontent.com/104729331/227810818-2d66724c-20ff-4395-b6f1-715c9bb1cdf8.png)
