### ISSUE TITLE
sshProblems accessing remote files with ssh

### ISSUE THREAD

**Issue by Gabriel-lin** [getcursor/cursor#269]
Use ssh to access the code folder in the server, can't display all files in the subfolder and Can't display file content.hope fix it.

**Comment by zoeeer** [comment]
same here.

seems only the top 1-2 depths of files/directories can be listed, and file content cannot show currectly. (file shown as empty)

**Comment by baoabaob** [comment]
+1

**Comment by aiyodiulehuner** [comment]
+1

**Comment by dddraxxx** [comment]
Same.

**Comment by danperks** [comment]
With v0.2.0, there are significant changes to the backend code that changes how SSH works altogether. At the moment, you can install the Remote SSH extension using my comment instructions on #489, but at least one user has been having issues with it. To keep discussion in one place, I will close this issue, so refer to #489 for the latest on SSH.
