### ISSUE TITLE
Chatbot stops streaming tokens when the chat is a bit long

### ISSUE THREAD

**Issue by off99555** [getcursor/cursor#27]
![image](https://user-images.githubusercontent.com/15215732/225730560-15daab8d-614c-4a60-a948-ff72a53a1831.png)
but the chat is not that long though as you can see from the scroll bar size on the right

**Comment by truell20** [comment]
Good point! We should automatically continue these. Adding to the roadmap

**Comment by truell20** [comment]
Should be in the newest version 🙂
