### ISSUE TITLE
Maximum Capacity

### ISSUE THREAD

**Issue by nxnyk** [getcursor/cursor#274]
![QQ截图20230327142724](https://user-images.githubusercontent.com/42330422/227858281-668b5188-4bde-45c4-ba3d-7a862a9453b9.png)

**Comment by ironny04** [comment]
me too

**Comment by droidYu** [comment]
me too since today 15:00

**Comment by comegithub** [comment]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/112402795/227874057-7f5817ba-e6d0-49ef-9327-fd1260be707e.png">

**Comment by FriskFreeman** [comment]
me too, still unsolved😔

**Comment by Gabriel-lin** [comment]
You are not alone,me too.

**Comment by szzhangge** [comment]
me too...still unsolved

**Comment by nxnyk** [comment]
> You are not alone,me too.

哈哈，老哥，可能美国那边还没起床

**Comment by nxnyk** [comment]
> 俺也一样 重启就行了

重启电脑?

**Comment by HuangZL20231010** [comment]
metoooooo

**Comment by chw19990722** [comment]
me too

**Comment by ktiays** [comment]
me too

**Comment by imgss** [comment]
me2

**Comment by szzhangge** [comment]
need money.....

**Comment by VXeffect** [comment]
主要还没说明交钱了之后限制上限，而且我用它写代码，比chatgpt错误率高非常多，基本没写成一个完整的需求，还有一个问题，ctrl+k，经常失灵，要反复重启

**Comment by leon37084762** [comment]
this issue only occurs in china?

**Comment by truell20** [comment]
Should be fixed in the latest version 🙂
