### ISSUE TITLE
I say hi,she say ...

### ISSUE THREAD

**Issue by weiguanglai** [getcursor/cursor#280]
![微信截图_20230327163639](https://user-images.githubusercontent.com/15008221/227888299-0bc0d233-97c4-4b68-b394-95c88aad524d.png)

**Comment by weiguanglai** [comment]
v0.1.7

**Comment by boxizen** [comment]
This problem should be fixed in v0.0.11, you can update the next version to confirm～

**Comment by truell20** [comment]
Should be fixed in the latest version 🙂
