### ISSUE TITLE
Sometimes the code is cut off

### ISSUE THREAD

**Issue by qyzhaojinxi** [getcursor/cursor#285]
When chat with cursor, sometimes the code is incomplete just like chatgpt. I need type continue more than once. 

And I also met another problem. The cursor show the code with bugs and then I type the errors. The cursor says sorry balala include the causes and just give the same code with bugs. just like infinite looping.

**Comment by truell20** [comment]
Should output much longer code in the newest version! Let me know if this is still an issue
