### ISSUE TITLE
Great editor!

### ISSUE THREAD

**Issue by 19890843006** [getcursor/cursor#286]

**Comment by comegithub** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/112402795/227932520-a6e2e592-41e0-4b9b-9dfe-161d1d01d2d7.png">

**Comment by alexwebdevs** [comment]
@truell20 need a pro plan upgrade link for the implementation.

**Comment by truell20** [comment]
appreciate it ❤️
