### ISSUE TITLE
There is a bug in handling subfolders under an open folder

### ISSUE THREAD

**Issue by stereoF** [getcursor/cursor#287]
There is a bug in handling subfolders under an open folder. For example, when I open folder "a" which contains some files and subfolders, sometimes the contents of the subfolders will not be displayed when I click on them in the left directory tree. I have to manually use the file search function to display them. However, after using the file search function once, the search box freezes and I have to restart the system to use the file search function again.

**Comment by truell20** [comment]
Should be fixed in the latest version 🙂
