### ISSUE TITLE
command+k doesn't work

### ISSUE THREAD

**Issue by Ipouyall** [getcursor/cursor#295]
In non empty files, at a new line or in a case I selected some codes, `command + k` or `Edit` option doesn't work.

**Comment by rtisne** [comment]
+1

I can only use ctrl + k one time

**Comment by Costly** [comment]
same. ctrl+k does only work occassionally

**Comment by zyxkad** [comment]
I have this problem too, but I found a way to solve it. Press `Cmd+someletter` first and then press `Cmd+K` it will work again. Idk why

**Comment by GroophyLifefor** [comment]
> same. ctrl+k does only work occassionally

If you press ESC, you'll have one more time.

**Comment by Yumat10** [comment]
I had a similar issue, and it turns out there were other shortcuts that also used  `command + k`.

You can search for `Cursor: Open Inline Edit and Generate Prompt Bar` in your Keyboard Shortcuts, and you can overwrite and set a new keybinding.
