### ISSUE TITLE
Create a Video Tutorial

### ISSUE THREAD

**Issue by alexec** [getcursor/cursor#296]
Please add a video demo front and center in the README.

I want to see how it works before I download it.

**Comment by MiletaA** [comment]
Hello man,
I have created short video demonstration with intro, that shows how its work, there are few features that are not included, but you can get picture of editor.  Currently video is unlisted.
If you take a look at video, it would be great to hear what do you think :)

https://youtu.be/TN2kzJ-0a44

**Comment by alexec** [comment]
Great video.

I don't want to use my mouse when editing. I want to use the keyboard. AI should understand code and suggestion completion. Tab to complete. Is that possible?

**Comment by MiletaA** [comment]
You don't have to use mouse while coding, there are shortcuts, they can seen in video for example Ctrl + k for edit, also there are basic shortcuts for example Shift + up arrow for selecting code.
After ai generate code you have shortcut to accept all or reject all generated code.
There are key binding if you are used to use vim or emacs.

I'm not sure that I've answered to you question. In the future I will probably record more detailed video.

**Comment by alexec** [comment]
Sure.  I really want to just to tab complete like Copilot.

**Comment by gerrywastaken** [comment]
If you want to see the number of users dramatically increase I suggest doing that. The docs do not do this tool justice and even after reading them a few times I'm still not sure how to use some of the features as there is a lot left unclear.

**Comment by MiletaA** [comment]
> If you want to see the number of users dramatically increase I suggest doing that. The docs do not do this tool justice and even after reading them a few times I'm still not sure how to use some of the features as there is a lot left unclear.

Thanks for the tip, I will create video ASAP.

**Comment by jakobFNF** [comment]
We will work on creating a detailed text guide. And a video could definitely be beneficial too.
