### ISSUE TITLE
app icon suggestion

### ISSUE THREAD

**Issue by Sekomer** [getcursor/cursor#298]
thanks for the editor, I've created a shortcut for myself, and I'm sharing it in case there are others looking maybe

**[ STEPS ]**
Create a file called `cursor.desktop` under `~/.local/share/application` folder and add the following lines

```
[Desktop Entry]
Name=Cursor
Exec=/home/<your_username>/Cursor-0.1.9.AppImage
Terminal=false
Type=Application
Icon=/home/<your_username>/.local/share/applications/cursor.png
```
don't forget to replace <your_username> with yours
then download the cursor logo from `getcursor` to make the icon pretty

```
$  cd ~/.local/share/applications
$  wget -q -O avatar.jpg https://avatars.githubusercontent.com/u/126759922?s=200&v=4
```

it will appear on your search menu after that, if not, open a terminal and run the following command
```
$  update-desktop-database ~/.local/share/applications
```

**Comment by truell20** [comment]
thanks for sharing this!! 🙏

(closing so I can sift through bugs, feel free to keep the convo going)
