### ISSUE TITLE
`cursor .` command line hook

### ISSUE THREAD

**Issue by truell20** [getcursor/cursor#3]
You should be able to open Cursor with a command line alias like `cursor path/to/folder`

**Comment by rayquaza7** [comment]
@truell20 how do u want the UX for this to be?
An option in Settings for 'CLI' above the other lang servers/copilot or separate from that?

**Comment by truell20** [comment]
Should be in the newest version 🙂

**Comment by pathikg** [comment]
Hey
I am able to do the same after opening cursor terminal but I'm unable to do so from my terminal 

Non cursor terminal:
```bash
$ cursor
cursor: command not found
```

but the same command works after using the same in the terminal opened inside cursor

version: cursor-0.11.8

**Comment by drewbitt** [comment]
Not seeing this with brew installed cursor. Of course, present with brew installed vscode.

**Comment by drewbitt** [comment]
You must launch cursor and run `Shell command: Install 'cursor' command`
