### ISSUE TITLE
Allow the AI to read/reference the internet

### ISSUE THREAD

**Issue by artemisep** [getcursor/cursor#300]
1. AI gave link for reference with given question
2. link returned page not found
3. notified AI
4. AI repeated the original answer with the same link
5. desired behavior: AI finds and returns updated link

**Comment by truell20** [comment]
cool idea! could you send some examples of your prompts and desired code?

**Comment by danperks** [comment]
At the moment, I don't believe the AI has the ability to query the internet, although I have registered this as a possible enhancement, as I could see the uses in this (auto-learn documentation, API formats, etc).

**Comment by danperks** [comment]
I'll rename this to something more clear, but still a good idea!

**Comment by jakobFNF** [comment]
Cursor has the custom documentation functionality now (@Docs).
