### ISSUE TITLE
bug like, when as for more examples, AI didn't follow with the immediate conversation

### ISSUE THREAD

**Issue by artemisep** [getcursor/cursor#303]
When I asked AI for more examples, AI didn't give me more examples of the question I just asked but the one I asked earlier maybe because that topic has more content.  
desired behavior, when asked for more examples without specify for what, AI should return more examples for the question just asked

**Comment by truell20** [comment]
Could you send some examples?

**Comment by danperks** [comment]
Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!
