### ISSUE TITLE
Cursor 0.1.9 only letting me prompt once to generate code using ctrl-k.

### ISSUE THREAD

**Issue by brianSalk** [getcursor/cursor#310]
after the first time, I need to explicitly click the generate button.  I am using ubuntu linux.

**Comment by keeganmccallum** [comment]
dupe: https://github.com/getcursor/cursor/issues/295

**Comment by Ashishyadav07** [comment]
@brianSalk even after clicking the generate button its still not working.

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
