### ISSUE TITLE
Some questions on the AI implementation

### ISSUE THREAD

**Issue by shanmur2706** [getcursor/cursor#314]
Hey there. This project looks pretty cool, but I'm wondering 2 things: What AI model is being used, is it in house or an existing model? And where is the dataset sourced from?
I'm conscious of the fact Copilot is made off of the backs of thousands of developers without their consent, and I'm concerned Cursor does the same.

**Comment by unixcow** [comment]
The website says `In partnership with OpenAI`, based on that, I think they're using the OpenAI api, the model is probably ` text-davinci-003`? Wonder if @truell20 can chime in an fact check me xD

**Comment by truell20** [comment]
GPT3.5 right now (unless you plug in an API key to use GPT4)

Soon it will be a mix of custom and OpenAI models!

**Comment by thelostv** [comment]
> GPT3.5 right now (unless you plug in an API key to use GPT4)
> 
> Soon it will be a mix of custom and OpenAI models!

What if i buy Pro Sub? Would it still be GPT3.5?
