### ISSUE TITLE
bug: AI cannot distinguish is and how questions, it gave back the same answer

### ISSUE THREAD

**Issue by artemisep** [getcursor/cursor#318]
When I ask two questions almost identical except one start with is and the other starts with how, it gave back the same answers for the is question

**Comment by truell20** [comment]
Could you paste or screenshot your prompts? Curiosu to understand how the ai is going wrong

**Comment by danperks** [comment]
Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!
