### ISSUE TITLE
bug:无法安装“meteorstudio.cursorcode”扩展，因为它与当前 Visual Studio Code 版本不兼容(版本 1.75.1)

### ISSUE THREAD

**Issue by noobwu** [getcursor/cursor#319]
无法安装“meteorstudio.cursorcode”扩展，因为它与当前 Visual Studio Code 版本不兼容(版本 1.75.1)
![1679965568664](https://user-images.githubusercontent.com/4328356/228100540-4f915516-e5b0-487d-a428-4a164c0bf222.jpg)

**Comment by WORFEW** [comment]
vscode下个system版的直接解决问题

**Comment by noobwu** [comment]
@WORFEW  谢谢！
