### ISSUE TITLE
docs 使用文档

### ISSUE THREAD

**Issue by zhengjiaao** [getcursor/cursor#320]
#docs 使用文档
https://blog.csdn.net/qq_41772028/article/details/129796435?spm=1001.2014.3001.5502

**Comment by danperks** [comment]
Hi, looks like you created some unofficial documentation for how to use Cursor. Thanks for creating that! Cursor v0.2.0 and above has a lot of changes to the old version, so unfortunately, your docs will not work for the latest version. As the app develops, the Cursor team will likely create and release documentation, so keep an eye on that in the future.

I'll close the issue for now, but thanks for trying to help more people understand and use Cursor!
