### ISSUE TITLE
improvement: AI added answer to a previous question besides replying with a relevant answer for the current question

### ISSUE THREAD

**Issue by artemisep** [getcursor/cursor#321]
AI added answer to a previous question besides reply a correct answer for the current question, maybe a post processing or a validation step can be added  before returning the answer to make sure all the content of the answer are relevant to the question.

**Comment by truell20** [comment]
could you send a screenshot of this happening?

**Comment by danperks** [comment]
Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!
