### ISSUE TITLE
The MacOS minimization shortcut keys were overwritten unexpectedly

### ISSUE THREAD

**Issue by hxy91819** [getcursor/cursor#323]
**Expected behavior:**
Minimize other app when using shortcut key cmd + m.

**Current behavior:**
Minimize Cursor no matter which app is actived. 

**Steps to reproduce:**
1. Open Cursor
2. Open Chrome. 
3. Try to minimize Chrome using cmd + m shortcut keys.
4. We will see Chrome failed to minimize and Cursor is minimized.

**Environment:**
Operating System: macOS Ventura 13.2.1
Cursor: version v0.1.7

**Additional Information:**
Nothing.

**Comment by raymond-ley** [comment]
Thank you for your feedback on this issue. I will fix the issue you mentioned, making Ctrl+M effective only when cursor is active, without overwriting the Ctrl+M of other applications:)

**Comment by raymond-ley** [comment]
Hello, this issue has been resolved by Merge # 329, and a global shortcut key Ctrl+Shift+Space has been added to globally call out/hide Cursor. All of these will take effect after the code is merged in the new version:）

**Comment by hxy91819** [comment]
> Hello, this issue has been resolved by Merge #329 , and a global shortcut key Ctrl+Shift+Space has been added to globally call out/hide Cursor. All of these will take effect after the code is merged in the new version:)

Well done. Thank you!
