### ISSUE TITLE
[Feature Request] Basic GoLang Support in IDE

### ISSUE THREAD

**Issue by dallenpyrah** [getcursor/cursor#324]
# 

### **Description**

I would like to request basic support for the Go programming language within our IDE. Currently, our IDE does not have any support for GoLang, which makes it difficult to write and develop Go programs using the IDE.

Specifically, I would like to see support for the following features:

- Syntax highlighting for GoLang code
- Autocomplete for GoLang code
- Basic code formatting for GoLang code
- Ability to run GoLang programs from within the IDE
- Integration with Go tools such as **`go fmt`**, **`go vet`**, and **`go test`**

By adding support for these basic features, our IDE can provide a better development experience for Go developers, allowing us to write and debug code more easily.

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
