### ISSUE TITLE
Generate New Code is not working properly. 

### ISSUE THREAD

**Issue by Ashishyadav07** [getcursor/cursor#327]

**Comment by Ashishyadav07** [comment]
after pressing the button explicitly sometime its don't open the prompt box,

**Comment by truell20** [comment]
Sorry about this! Is this still happening in the newest version?

**Comment by danperks** [comment]
As the new version has likely fixed this issue, I'll close it.

Feel free to open a new one if you have this, or any other issues, with the latest version.
