### ISSUE TITLE
Support install and update through Homebrew Cask on macOS

### ISSUE THREAD

**Issue by zhoujian-official** [getcursor/cursor#328]
Please support install and update through [Homebrew Cask](https://formulae.brew.sh/cask/) on macOS.

**Comment by alexwebdevs** [comment]
@truell20 it's possible for this request, but we would need to write the ruby script to be approved and merged Homebrew Cask to have cursor included in the main distribution of Homebrew Casks.

**Comment by zhoujian365** [comment]
> 

I think it's fine to use a custom Homebrew Tap. Included in the main distribution of Homebrew Cask Tap will be better :)

**Comment by jakobFNF** [comment]
Cursor is now available for installation through [Homebrew Cask](https://formulae.brew.sh/cask/cursor) on macOS. Thank you for your suggestion!
