### ISSUE TITLE
Is there any plan to support Terraform?

### ISSUE THREAD

**Issue by imtaji** [getcursor/cursor#333]
Black and white does not look nice 😄 

![image](https://user-images.githubusercontent.com/13151141/228185298-71a1fea4-82f7-4eb9-a758-d6aa4096c500.png)

**Comment by danperks** [comment]
With the release of v0.2.0 and up, Cursor now supports VSCode extensions. Check out the library to see if Terraform is there, or if not, follow the instructions in my comment on #489 for the Terraform extensions you want, and raise a new issue if you have any problems with this!
