### ISSUE TITLE
Ctrl + K not working in Ubuntu 22.04

### ISSUE THREAD

**Issue by hmthanh** [getcursor/cursor#337]
Ctrl + K not working in Ubuntu 22.04

![image](https://user-images.githubusercontent.com/8927701/228203648-2cf74aac-4d1c-47c6-bfec-d6172fe00306.png)

Sometimes it work, sometime none

**Comment by GainLee** [comment]
MacOS the same

**Comment by xiaomingcom-cs** [comment]
Sometimes it doesn't work on Windows

**Comment by LarsBingBong** [comment]
Everybody see whether the workaround mentioned in [#295](https://github.com/getcursor/cursor/issues/295) helps you. A new release is being worked on I can see.

**Comment by truell20** [comment]
Should work now! lmk if this issue shows up again, apologies here
