### ISSUE TITLE
Not working with Jupyter notebook

### ISSUE THREAD

**Issue by hemangjoshi37a** [getcursor/cursor#339]
I hope this will be added soon because so many of the data scientists are working on jupyter notebook.

Thanks

**Comment by raymond-ley** [comment]
How do you want to add Jupyter notebooks? Do you want to start Jupyter notebook in Cursor or do you want to do an integration?

**Comment by hemangjoshi37a** [comment]
@raymond-ley I want best of both worlds,  Cusrsor should have buildin jupyter opener for jupyter ans also an notebook extention for jupyter. However a VS Code extention is also posssible to add.

**Comment by hemangjoshi37a** [comment]
Currently it opens jupyter notebook like this
![Screenshot from 2023-03-30 16-07-51](https://user-images.githubusercontent.com/12392345/228811001-67783010-9474-481f-bbf3-65d96d037377.png)

**Comment by danperks** [comment]
With v0.2.0, Cursor supports Jupyter notebooks via the Juypter extension, which should work as you would expect in VSCode or other IDES.
As this probably resolves your issue, due to the major upgrade of v0.2.0, I'll close this for now, but feel free to comment again if there are issues in the latest version you'd like the devs to address.

**Comment by hemangjoshi37a** [comment]
Can you link me to jupyter extension?

**Comment by danperks** [comment]
I believe it's available within Cursors extension library. That's available using the icons at the top of the file panel, you may have to click the drop down arrow.

If you cannot find it, as a backup, you can visit this link, hit "Version History", download the latest .vsix
file and drag it into Cursor to install it:

https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

It may be that Cursor doesn't work correctly with the extension, but I am unable to try it myself, so let me know how you get on, and we can reopened the issue if it doesn't work as I hope it will!
