### ISSUE TITLE
这玩意真的是用GPT4？？

### ISSUE THREAD

**Issue by zngpng** [getcursor/cursor#34]
![image](https://user-images.githubusercontent.com/32975263/225784419-1f6beec1-04b8-4eab-8553-ba914bb481f4.png)

**Comment by truell20** [comment]
yessir

**Comment by jjdoor** [comment]
this is great!

**Comment by it-noob** [comment]
直接询问对方反馈是 GPT-4 没有访问，不确定 api 是不是调用的 gpt-4 的

**Comment by kbaicai** [comment]
测试了最大token是4100个左右，估计是3.5了

**Comment by NicoKam** [comment]
今天这样问了一下
![image](https://user-images.githubusercontent.com/6757303/226504103-c717a9cc-c9b2-48a3-b4bc-67a40dcc5813.png)
但是后面就再也问不出来了，他一直都说自己是CursorBot

**Comment by kbaicai** [comment]
> 今天这样问了一下 ![image](https://user-images.githubusercontent.com/6757303/226504103-c717a9cc-c9b2-48a3-b4bc-67a40dcc5813.png) 但是后面就再也问不出来了，他一直都说自己是CursorBot

回复是可以定制的，你看模型最大的输入就知道了。gpt3是2048，chatgpt3.5是4096左右，gpt4就是8k~32k

**Comment by idiomaticrefactoring** [comment]
> yessir

hello, is the cursor based on gpt-4?
I browse [the official website](https://www.cursor.so), but there seems to be no such description.
