### ISSUE TITLE
The remote folder cannot be opened after ssh is connected to the remote server

### ISSUE THREAD

**Issue by xiaomingcom-cs** [getcursor/cursor#340]
![image](https://user-images.githubusercontent.com/75123667/228249575-ebfbdada-ae3c-4a6e-b3f0-ea92c487f8ac.png)
the folder is not empty,but it can't be opened

**Comment by danperks** [comment]
I'm facing this same issue, folders and files do not load, only the top level file tree

**Comment by TapsHTS** [comment]
same for me
