### ISSUE TITLE
Shortcut not working once prompt submitted

### ISSUE THREAD

**Issue by Mathu-lmn** [getcursor/cursor#343]
Hey, I just downloaded the Cursor app, first off, I'm impressed by how clean it is and how fast it is.
However once I Generate some code, the "prompt page" is still detected as opened so my shortcuts don't work.
To fix it I press ESC and shortcuts work again.
I have no knowledge in TS / JS so I can't PR to fix it but hopefully someone will ! 

Thanks again for this insane job

**Comment by GroophyLifefor** [comment]
i had this problem too.

**Comment by danperks** [comment]
This is likely fixed in the latest version, let us know if this is the case! 😄

**Comment by GroophyLifefor** [comment]
> This is likely fixed in the latest version, let us know if this is the case! 😄

Yes fixed and UI is most of better, I hope it will come to better places, for example, it would be better if it generates code in csharp language instead of python by default in a .cs file
