### ISSUE TITLE
订购了cursor pro，几个疑问帮忙回答一下。Ordered cursor pro, have a few questions to ask

### ISSUE THREAD

**Issue by edision** [getcursor/cursor#344]
1. 是自动扣费吗？
2. 如果是自动扣费，怎么取消，我在官网上居然没有看到取消订阅的地方

Is it automatic payment?
If it is automatic payment, how to cancel? I didn’t find a place to cancel the subscription on the official website.

**Comment by piercashuang** [comment]
我也订购了 在淘宝找的代付 虚拟卡 里就20美元 不用担心什么

**Comment by HolmesZhao** [comment]
how to subscribe pro?

**Comment by edision** [comment]
> Adding a place to cancel today! Please dm me on our discord to cancel if you'd like to in the meantime.

Thank you for your reply, waiting for updates.
