### ISSUE TITLE
bug: AI crushed after entered a question

### ISSUE THREAD

**Issue by artemisep** [getcursor/cursor#346]
I entered a question, AI hanged, cannot close the window,  window showed white background after killing the process, ubuntu

**Comment by truell20** [comment]
Apologies here! Did this happen when you first used Cursor? Any other details of the state of the program to help us figure out what triggered this?

**Comment by danperks** [comment]
Is this still happening in the latest version? If so, how often, and on what types of requests?

**Comment by danperks** [comment]
As this is likely resolved either with the new version, or a Pro subscription, I'll close this for now.

Feel free to comment and we can reopen this if needed.
