### ISSUE TITLE
Support multiple terminals and focus on open

### ISSUE THREAD

**Issue by elanzini** [getcursor/cursor#350]
- Currently when the terminal is opened we are not focusing on it
- There is no support for multiple terminals

**Comment by m1chaelbarry** [comment]
Also using shortcut Ctrl+~ doesn't focus on terminal.

**Comment by elanzini** [comment]
> Also using shortcut Ctrl+~ doesn't focus on terminal.

This PR is also fixing that

**Comment by danperks** [comment]
With v0.2.0 and upwards, multiple terminals is now an available feature. I'll close this issue for now, but if you have any issue with terminals in the latest version of Cursor, feel free to open a new issue!
