### ISSUE TITLE
The company's intranet needs to go through a proxy to access the external network, which makes the software unusable

### ISSUE THREAD

**Issue by JasonDevStudio** [getcursor/cursor#352]
The company's intranet needs to go through a proxy to access the external network, which makes the software unusable.

Can you consider joining Proxy? ProxyHost, Port, username, password, access the network proxy through the above methods and then use it online

**Comment by raymond-ley** [comment]
Of course, association # 381

**Comment by danperks** [comment]
Closed in favour of #381. See my comment there for potential solutions and to continue discussions:
https://github.com/getcursor/cursor/issues/381#issuecomment-1502170243
