### ISSUE TITLE
After installation, there is a problem with the use

### ISSUE THREAD

**Issue by White-Friday** [getcursor/cursor#356]
we ran a problem

something unexpected happened. please try again. 

Can you configure a proxy? I need a proxy to access

Thanks

**Comment by truell20** [comment]
could you send a screenshot?

**Comment by danperks** [comment]
Cursor v0.2.0 and up _should_ have support for Proxy access, see here for a tutorial: https://github.com/getcursor/cursor/issues/381#issuecomment-1502170243
If it doesn't work, please continue the discussion in #381 to ensure the conversation is all in one place 😄
