### ISSUE TITLE
[Feature request] Include a toggle command for displaying the historical chat panel

### ISSUE THREAD

**Issue by yaohui-wyh** [getcursor/cursor#357]
IDE users frequently shift their focus and come back to check their chat history. Currently, the only options to access past chat history are to generate a new chat session or use the previous prompt to "re-chat". These options are not only inefficient but also costly.

**Comment by yaohui-wyh** [comment]
Oh, I found it in the Command Palette.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/3115235/228412178-11943cfe-fcf2-4a9e-811d-9d0191678abf.png">
Some minor enhancements:

- Assigning a default hotkey (such as <kbd>cmd</kbd>-<kbd>shift</kbd>-<kbd>L</kbd>) to "Open Chat History"
- Rearranging the command options and placing "Open Chat History" right after "Chat Selection" for easy access
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3115235/228412139-283d6ea7-8415-4b20-a9f6-15bfe8da0417.png">

This would minimize the necessity for additional searches (and eliminate redundant queries) when users simply require reviewing earlier chat conversations.

**Comment by raymond-ley** [comment]
@truell20 
Do you have any comments on this? If I feel this change is appropriate, I can implement it. :)
