### ISSUE TITLE
[Feature request] Allow deletion for previous chat/generate sessions

### ISSUE THREAD

**Issue by yaohui-wyh** [getcursor/cursor#358]
### Description

Allow users to manually delete local chat/generate sessions. 

This is useful for those who have privacy concerns, such as during a presentation with Cursor where they do not want certain chat sessions to be shown, or for those who want to keep their chat history organized by removing incomplete or faulty sessions.

### Implementation

1. Add a delete button to the Chat session list item
2. (Optional) Add a delete button to the Chat input when users navigate to previous Chat sessions

<img width="500" alt="image" src="https://user-images.githubusercontent.com/3115235/228413696-609ee31b-75ef-47be-a12e-ad03259865aa.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/3115235/228413521-a609f92d-ca59-4137-b2be-bd2537b80d2b.png">

**Comment by danperks** [comment]
With the release of v0.2.0, this feature is now built into the chat window, so I will close this as completed.
