### ISSUE TITLE
Bug: Generator doesn't stop when generating unit tests for specific code

### ISSUE THREAD

**Issue by leoninhub** [getcursor/cursor#361]
Generate unit tests for this code：
    private Date getMinDate(Date date1, Date date2){
        if(Objects.isNull(date1) && Objects.isNull(date2)){
            return null;
        }
        if(Objects.isNull(date1) && Objects.nonNull(date2)){
            return date2;
        }
        if(Objects.nonNull(date1) && Objects.isNull(date2)){
            return date1;
        }
        return date1.before(date2)?date1:date2;
    }

the generator keeps running and causes the editor to eventually freeze

**Comment by raymond-ley** [comment]
Can you provide your running environment (such as the operating system, Cursor version, the file suffix where this code is located,...)?
To ensure that we can reproduce the problem. :)

**Comment by danperks** [comment]
Assuming this is likely resolved in newer versions, feel free to repoen if you're still affected.
