### ISSUE TITLE
About subscription

### ISSUE THREAD

**Issue by txhuo** [getcursor/cursor#364]
I have upgraded to cursor pro, but I cannot find a way to cancel the subscription on the main page of cursor

**Comment by truell20** [comment]
hey! reach out to me @truell20 on discord and I can help you

**Comment by txhuo** [comment]
I have now found the entrance to manage my subscription plans on the homepage. Since I have too many paid subscriptions, I usually cancel the renewal plan directly after subscribing, and only renew it when I still need to use it after it expires. Thanks for your prompt response.
