### ISSUE TITLE
tab shift error

### ISSUE THREAD

**Issue by Sekomer** [getcursor/cursor#365]
pressing to the tab, even though you are at the end of the line, causes right shift xd

great editor btw!

**Comment by truell20** [comment]
thank you!  just to make sure i understand, what's the expected behavior

**Comment by Sekomer** [comment]
Shift whats on right of the cursor, not the left 😂

**Comment by danperks** [comment]
Assuming this bug was for the old version of Cursor. Updating to v0.2.0 has the effect as standard.
