### ISSUE TITLE
Combined analysis of multiple code files

### ISSUE THREAD

**Issue by baitianshi** [getcursor/cursor#369]
Place a complete project in the directory, which can be combined with other code files. Is the analysis result given?
Can I analyze the entire project?

**Comment by truell20** [comment]
hey! not sure I understand yet. Are you asking if we can do multi-file changes?

**Comment by baitianshi** [comment]
Yes, multi-file changes. Java code analysis and repair between multi-files.

**Comment by baitianshi** [comment]
It's not just limited to analyzing only one piece of code.

**Comment by raymond-ley** [comment]
> Yes, multi-file changes. Java code analysis and repair between multi-files.

> It's not just limited to analyzing only one piece of code.

This is a good idea and should be added in future versions. :)

**Comment by baitianshi** [comment]
> hey! not sure I understand yet. Are you asking if we can do multi-file changes?

Yes，I hope there will be further updates to the functionality

**Comment by danperks** [comment]
While you can use code from multiple files to help the AI understand what you want from it (see my comment here https://github.com/getcursor/cursor/issues/460#issuecomment-1501630408), there's no way to have the AI edit multiple files in one request, but it sounds like it may be on the horizon, so will triage as an enhancement.

**Comment by oersted** [comment]
In the meantime, it would be handy if there was a "Jump to File" or "Create File" button next to the copy button in code blocks returned by the chat. While the AI can't edit multiple files yet, this would make it a bit faster for the user to do it manually.

**Comment by jakobFNF** [comment]
While Cursor can't directly edit multiple files at once, you can add multiple files to the chat with the @ symbol and ask it to tell you what you need to do in each one. However, multi-file editing is an inevitable feature in the future.
