### ISSUE TITLE
Support the sidebar to display historical conversation records

### ISSUE THREAD

**Issue by ThisSeanZhang** [getcursor/cursor#37]
Is there a plan to support the sidebar to display historical conversation records? sometimes I want to look back at the records.

**Comment by truell20** [comment]
Try hitting the little history icon over the chat box. Will make this easier to find in the future!
![Screenshot 2023-03-16 at 9 51 06 PM](https://user-images.githubusercontent.com/4297743/225815510-68fff106-2665-485e-9e6d-0ff2ccf6ab6d.png)

**Comment by ThisSeanZhang** [comment]
Thank you

**Comment by ThisSeanZhang** [comment]
You know, the content returned in each chat is not fixed , if there is a particularly good one, can I keep a specific record.

I need to chat to open the interface, is there a specific button somewhere that I can open.

Thanks

**Comment by truell20** [comment]
sidebar to show chat history should be in the newest version 🙂
