### ISSUE TITLE
Access prompt history

### ISSUE THREAD

**Issue by Ahuge** [getcursor/cursor#372]
It would be awesome if we could see the history of our prompts and/or include the prompt at the top of the generated code.

This would allow me to fine tune the prompts

**Comment by truell20** [comment]
Command/control + shift + up should bring you to past prompts in the prompt bar. Does that work?

**Comment by Ahuge** [comment]
Ah thank you that works

**Comment by aleclarson** [comment]
What name does this command use in Keyboard Shortcuts?
