### ISSUE TITLE
sign in problem

### ISSUE THREAD

**Issue by zyc-bit** [getcursor/cursor#376]
![image](https://user-images.githubusercontent.com/61681538/228710248-eb6ca49a-559e-402c-9b81-356905979b46.png)
I sign up firstly, but when I got the last step, the button give me no reaction.
Then I click sign in button or sign up button, both get blank page below:
![image](https://user-images.githubusercontent.com/61681538/228710463-d3924433-c16b-4dd3-acd3-98b8aa938ecf.png)
my network error? I don't think so...
Any suggestions?

**Comment by xingzheng-github** [comment]
I had the same problem

**Comment by Sanger2000** [comment]
Apologies, we just fixed this issue. Let me know if you're still seeing this!

**Comment by zyc-bit** [comment]
> Apologies, we just fixed this issue. Let me know if you're still seeing this!

Tried and alreay solved, thank you alot.

**Comment by xiaozexuan** [comment]
nice!

**Comment by xingzheng-github** [comment]
Just verified, no problem, thank you
