### ISSUE TITLE
Generate code to add file reference

### ISSUE THREAD

**Issue by freewu32** [getcursor/cursor#378]
When generating code, you can select the code files in the project and place them in the context of gpt. This produces code that more closely matches the prompt word

**Comment by raymond-ley** [comment]
I think so, too. This can be added to TODO plan. Thank you very much for your suggestions. :)

**Comment by danperks** [comment]
This is already possible in the chat windows in v0.2.0 and up, by selecting a block of code in a file, clicking into the chat window, and click the "+ Add Snippet" button. I don't believe it's available in the code prompt yet, so will triage as a potential enhancement.

**Comment by jakobFNF** [comment]
You can now quickly add any file to the chat or inline edits with the @ symbol.
