### ISSUE TITLE
payment: the bill was deducted without upgrading to pro

### ISSUE THREAD

**Issue by GQY-479** [getcursor/cursor#379]
When I subscribed to pro, it told me that my zip code didn't match my card number, but the bill was deducted, and I reentered the program without upgrading to pro.
当我订阅pro的时候，它告诉我邮编与卡号不符，但是钱已经扣了。我重新进入程序并没有升级到pro

**Comment by raymond-ley** [comment]
Please don't worry, your account will be upgraded to pro as soon as possible, at least you are not alone in this problem at present. :)
Please pay attention to this issue, similar to #380 @truell20 .

**Comment by truell20** [comment]
please reach out to michael@cursor.so! will fix this for you, apologies.
