### ISSUE TITLE
pro version payment

### ISSUE THREAD

**Issue by why2not** [getcursor/cursor#380]
1. The account registered on March 27 has been upgraded to the pro version, and the fee has been deducted. Login today shows that the account does not exist.
2. After re-registering the account according to the previous email address, it has not been upgraded to the pro version

**Comment by raymond-ley** [comment]
Oh no! I think this is a major accident. Please pay attention to this issue @truell20 .

**Comment by truell20** [comment]
please contact me at michael@cursor.so with the email you used! will fix this apologies
