### ISSUE TITLE
In my environment, I cannot directly connect to the internet. How can I set up a proxy for the software?

### ISSUE THREAD

**Issue by Runbacktoo** [getcursor/cursor#381]

**Comment by danperks** [comment]
The latest version of Cursor, since v0.2.0, is based upon VSCodium and therefore has alot of the same features. If you can, give this a try and see if everything still functions as expected:
https://code.visualstudio.com/docs/setup/network

**Comment by danperks** [comment]
This is a duplicate of #128, and more discussion has occurred there, so I'll close this issue in favour for that one. 😄
