### ISSUE TITLE
Error reported during execution of "npm i" process

### ISSUE THREAD

**Issue by digcore** [getcursor/cursor#383]
DigCore@DigCore-PC MINGW64 /e/Software/cursor
npm WARN EBADENGINE   required: { node: '>=14.18.0', npm: '>=8.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.19.1', npm: '7.0.0' }
npm WARN EBADENGINE }
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated core-js@3.18.3: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DigCore\AppData\Local\npm-cache\_logs\2023-03-30T06_28_57_682Z-debug.log

**Comment by raymond-ley** [comment]
Regarding the warning message you received, it seems like you are using a version of Node.js and npm that are not compatible with the required versions for your project. The warning message suggests that you need to have Node.js version 14.18.0 or higher and npm version 8.0.0 or higher. However, your current version of Node.js is 16.19.1 and your current version of npm is 7.0.0.
You can update your npm >=8.0.0. :)

**Comment by danperks** [comment]
As this issue is likely regarding the v0.1.0 codebase, I'll close it for now to keep the issues clean.

Feel free to comment and we can reopen this if you still want support using the older codebase, but note it isn't support or updated anymore.
