### ISSUE TITLE
Font cannot be enlarged or shrunk freely (without changing the window size)

### ISSUE THREAD

**Issue by Clearzero22** [getcursor/cursor#386]
The font cannot be changed when viewing the code. You want to increase CTRL + wheel to enlarge and shrink the font

**Comment by danperks** [comment]
Holding `CTRL` and pressing either the `+` or `-` key should change the font size (in v0.2.0).
To bind the scroll wheel to zoom, you can use this solution:
https://stackoverflow.com/questions/30192884/is-it-possible-to-configure-control-scroll-wheel-to-increase-decrease-zoom-in

Will close, as this seems to answer the query, but feel free to comment if you have any issues with this.
