### ISSUE TITLE
Need a direct way to open chat history

### ISSUE THREAD

**Issue by yuchen9** [getcursor/cursor#389]
thanks for your splendid job,  the cursor really boost my development. I have a small suggestion for you.

At present, if you want to  look at history of chat, you must take two steps: 
1. open the chat command line and input something to popup the chat box
2. then you can click the clock icon to see the history.

Hope: there is a command or other operation which can popup the chat box directly without input anything.

maybe can change the present logic of  cmd+L to pop up the chat box directly rather than the input bar.

**Comment by WinGo0** [comment]
Finally met the same doubts. And also want to manage chat history

**Comment by rajhlinux** [comment]
Same here, I restarted cursor and it did not load the hour long chat history and started a new one... would like to access the chat history.
