### ISSUE TITLE
Why reinvent the wheel?

### ISSUE THREAD

**Issue by LukeSamkharadze** [getcursor/cursor#391]
We are just losing features of the most stacked IDE called vscode.

This should have been made as vscode extension, which I would happily install

**Comment by truell20** [comment]
Hey Luke! Appreciate the feedback. Most of what we want to build in the future isn't possible as a VSCode extension, which is why we went the route of rolling our own editor. If there's anything from VSCode you'd especially like to see in Cursor, let me know. We might be able to add it in.

**Comment by duc-gp** [comment]
what do you think about copilot x? do you think cursor will be obsolete since one of your first points in "what differs cursor from copilot" is that cursor has a "much smarter AI". do you think with copilot x this statement is still true?

**Comment by fjun99** [comment]
I think standalone cursor is a better choice than a vscode extension.

 I am always use cursor with vscode these days and I think a standalone IDE is very helpful.

**Comment by truell20** [comment]
> @truell20 could you share what some of those future ambitions are?

Some of them are in the README 🙂 I want to write a long form blog / article on our thoughts here

**Comment by truell20** [comment]
Newest version of Cursor reinvents the wheel a bit less! Lmk if you love it/hate it/have any feedback

**Comment by truell20** [comment]
(Also gonna close this for now so I can sort through bugs, but please keep the convo going)
