### ISSUE TITLE
Cursor (v 0.1.12) with OpenAI API key not responding on Mac M2

### ISSUE THREAD

**Issue by Deep0Thinking** [getcursor/cursor#392]
**Mac M2 (13.2.1) , Cursor v 0.1.12** 

Cursor is not responding after I inputted my OpenAI API key in the setting and asked it for generating contents (neither ⌘K nor ⌘L worked) (it just kept loading all the time): 

<img width="1325" src="https://user-images.githubusercontent.com/103571424/228950112-4e973f9e-d26c-40b0-a701-28bdd0b8f127.png">

**Comment by Microbion** [comment]
Same to me in win11

**Comment by arunkumar1997** [comment]
This occurs when the OpenAI account has no remaining quota or token. When this happens, the response in the code snippet provided at https://github.com/getcursor/cursor/blob/main/src/features/chat/chatThunks.ts#L610 will look like this:

```sh
data: ""
data: "\n"
data: "edit"
data: "\n"
data: ""
data: "\n"
data: ""
data: "\n"
data: [DONE]
```

I believe this issue may be causing the application to become unresponsive.

**Comment by cs-fisha** [comment]
same to me in win11

**Comment by Ha0ran2001** [comment]
same to me in win10

**Comment by LHC8888** [comment]
also in mac m1

**Comment by Ha0ran2001** [comment]
Still not working.
Version: 0.2.2
Commit: e8b34ac28f297eb86df40a0545ee06519b653263
Date: 2023-04-07T23:36:06.588Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by ckchmod** [comment]
> 

same issue. Nothing has worked since inputting OpenAI API Key:

Version: 0.2.2
Ubuntu 22.04.2 LTS

**Comment by Charry0520** [comment]
因为openai免费的key已经用不了了

**Comment by Ha0ran2001** [comment]
> 因为openai免费的key已经用不了了

啥意思，只能是plus用户的key才能用？

**Comment by truell20** [comment]
Hey! Closing this out because I believe API key support has been stable in Cursor for a while.

If you run into any problems and [these guidelines](https://forum.cursor.sh/t/my-openai-key-isnt-working-in-cursor/30/2) don't work, please open a new issue!
