### ISSUE TITLE
Auto Retry Failed Requests

### ISSUE THREAD

**Issue by Legionof7** [getcursor/cursor#393]
When a server error occurs there should be an option to just retry the action instead of having to type in the request again

<img width="525" alt="CleanShot 2023-03-30 at 13 31 52@2x" src="https://user-images.githubusercontent.com/6224601/228957392-94e3ad97-6681-4096-97e2-a2f37d639d29.png">

**Comment by truell20** [comment]
Are you still getting persistent server errors? Do you have any sense of what triggered this?

**Comment by Legionof7** [comment]
Not sure, it happens pretty often though.

**Comment by danperks** [comment]
v0.2.0 has some significant changes and this error shouldn't be anywhere near as common. To avoid hitting limits, the Pro subscription can be purchased.

To keep the Issues clean, I'll close this for now, but feel free to comment and it can be reopened!
