### ISSUE TITLE
Using GPT-4 with an OpenAI API Key

### ISSUE THREAD

**Issue by arhatcn** [getcursor/cursor#394]

**Comment by userfrommerck** [comment]
I also like this proposal.

**Comment by longfuxu** [comment]
Like this idea. Hope to hear from the develper team soon.

**Comment by JaRLenZhang** [comment]
I also have the same proposal.

**Comment by danperks** [comment]
This should already be possible, according to the devs, but I can't say I know how it would be done as I don't use an API key myself.

If anyone's having issues with this still, let us know

**Comment by overage-waif-cocoon** [comment]
This is not working for me.  I am unable to select gpt-4 in any capacity using an openai api key.

**Comment by samj** [comment]
Note that when I ask Cursor itself "Can I use GPT-4 with my own API key in Cursor?", it says:

Yes, you can use GPT-4 with your own API key in Cursor. You just need to set up your API key in the settings of Cursor. Here's how you can do it:

1. Open the settingseditor file.
2. Look for the section related to GPT-4.
3. You should see a field for the API key. Enter your API key there.
4. Save the changes and close the file.

Now, Cursor should use your API key when making requests to GPT-4. Please note that the exact steps might vary depending on the version of Cursor you're using. If you can't find the settings, please refer to the documentation or contact the support.

**Comment by glasgowm148** [comment]
What is the `settingseditor` file?

In settings there appears to be no obvious slot to enter the API key, `settings.json` also doesn't contain any field relating to API keys.

**Comment by samj** [comment]
It took me longer than it should have to work this out but there's a gear at the top right… they may want to fix that even if just by replicating those settings in the main settings dialogs.

Sent via Superhuman ( ***@***.*** )

**Comment by glasgowm148** [comment]
Thanks, I had just found it myself and came here to post the solution 😅

**Comment by Nicholas0350** [comment]
Where is this elusive gear in the top right ?


<img width="1799" alt="Screenshot 2023-08-22 at 11 45 20" src="https://github.com/getcursor/cursor/assets/2359476/d74956d6-768a-4e8d-945d-e7a2cb8fb811">

**Comment by PajkeGit** [comment]
Can't find the gear icon in the top right

**Comment by sigreyo** [comment]
cmd + shift + J

**Comment by sigreyo** [comment]
> Can't find the gear icon in the top right, also there's no GPT-4 section in settings

cmd + shift + J

**Comment by sgerogia** [comment]
I have access to the GPT-4 API  
![image](https://github.com/getcursor/cursor/assets/1963182/843a0e63-50af-4756-baf8-af936f2cb85b)

...and have set my own key.  
Yet Cursor only makes GPT-3.5 available??  
![image](https://github.com/getcursor/cursor/assets/1963182/fdcaa07d-6a85-4eeb-b698-d79df0b292ba)

Why? 
How can I enable GPT-4?
Am I missing something basic here?

**Comment by sidsarasvati** [comment]
<img width="157" alt="image" src="https://github.com/getcursor/cursor/assets/2634859/fcf32371-236c-4f0c-9c39-580911664333">

**Comment by mandrade2** [comment]
That's it! You have to minimize the window

**Comment by erdem** [comment]
is it possible to use gpt4 without the pro subscription? I have access to gpt4 but it's not listed in the settings. Only 3-5-turbo available.

**Comment by jmch0700** [comment]
Why does it limit you to gpt 3.5 when using your own API key. API keys can use gpt 4 no problem

**Comment by eonist** [comment]
Was this resolved? You can use gpt4 now?

**Comment by eonist** [comment]
Is there no way to use GPT4? with my own ChatGPT plus account?

**Comment by sgerogia** [comment]
For anyone interested: this has been resolved for me.
See the community topic I also raised: https://forum.cursor.sh/t/enabling-gpt-4-in-cursor-using-own-key/140

**Comment by eonist** [comment]
The dance didn't work for me. My observation: I'm not sure it fixes it but, I just discovered that I have chatgpt plus. Which is not the right package for a gpt4 key. I need to pay for that As I go. Have not payed for it yet, but will in a few days. Just have to get the company card etc. Will report back if that changes things.

**Comment by pbrisson** [comment]
![image](https://github.com/getcursor/cursor/assets/3892766/29dd2ce8-8c3d-47e5-9fca-de1a2120d228)

I use to see a "Model" section in there.  Just like @sgerogia. It's gone now. What's going on?

**Comment by eonist** [comment]
For me it was that I had the wrong payment structure at openAI. I paid for chat gpt plus. But I had to get the pay as you go plan that gets you the GPT4 key.

**Comment by pbrisson** [comment]
@eonist Thanks for your follow-up. I already had the pay as you go plan. My cursor was working fine with GPT-4 as of last friday. I updated this morning and this is when weird things started to happen. As you can see on the screenshot above, I can't even select the model. Typing my key doesn't do anything. Clicking on the arrow next to the textbox doesn't do anything. Toggling the "Using key" option on and off doesn't do anything. Uninstalling / Reinstalling won't fix it either.

**Comment by pbrisson** [comment]
Since using GPT-4 within my IDE is the main reason why I switched to Cursor, it is mandatory for me get back to a version that supports that feature. I had the Windows binary for 0.7.3 handy in my Downloads folder and confirm downgrading fixes the issue. I made it available here if it can help anyone: https://github.com/pbrisson/cursor/releases/tag/0.7.3

**Comment by truell20** [comment]
@pbrisson You can control the model in chat or Cmd-k. Do you see gpt-4 in the dropdown?

<img width="332" alt="Screenshot 2023-10-11 at 11 15 06 PM" src="https://github.com/getcursor/cursor/assets/4297743/5ed69103-1e97-4b7f-aab8-799bd3e89716">

**Comment by pbrisson** [comment]
Thanks @truell20 - I'm speechless!

Never saw that I could use it from there! I confirm I can select gpt-4 from there (both Cmd-k and Cmd-l) and that everything seems to be working. I will report I stumble upon anything else.

**Comment by jakobFNF** [comment]
Looks like all issues in here have been resolved, and the initial feature has been implemented, so I will close this issue. Thank you for your suggestion!

**Comment by paddymccallan-izon** [comment]
> For me it was that I had the wrong payment structure at openAI. I paid for chat gpt plus. But I had to get the pay as you go plan that gets you the GPT4 key.

How do you change the plan? I can't see the option anywhere

**Comment by MichaelReaNZ** [comment]
> 1. settingseditor

OMG it took me ages to find the icon too.

**Comment by zook111** [comment]
surely its cheaper to pay for cursor pro - still have access to latest openai models without need for separate openai subscription.?
