### ISSUE TITLE
We run into a problem 

### ISSUE THREAD

**Issue by nxnyk** [getcursor/cursor#396]
Because I didn't buy the pro?
<img width="373" alt="微信截图_20230331092345" src="https://user-images.githubusercontent.com/42330422/228999754-42eca762-f486-49f2-a30b-f1f54221778b.png">

**Comment by Ihuangmi** [comment]
me too，It suddenly stopped working today

**Comment by chenkunlong** [comment]
用免费的崩溃很正常吧

**Comment by truell20** [comment]
Are you still getting persistent server errors? Do you have any sense of what triggered this (e.g. did you try putting in a large prompt)?

**Comment by nxnyk** [comment]
> Are you still getting persistent server errors? Do you have any sense of what triggered this (e.g. did you try putting in a large prompt)?

yes, I downloaded it and got a service error not putting in a large prompt

**Comment by danperks** [comment]
This should be resolved in v0.2.0, but you may still hit limits without the Pro subscription.

Try the new version and feel free to create a new Issue if you face any more issues.
