### ISSUE TITLE
data security

### ISSUE THREAD

**Issue by gongbudaizhe** [getcursor/cursor#40]
will my data be used for training the gpt-4 model?
will my code be safe?

**Comment by truell20** [comment]
thanks for asking this! none of your data will be used for training OpenAI's models. when you invoke the AI, we store parts of the code in your immediate file in an analytics service for improving the product. will soon be releasing a setting where absolutely no code is stored even in this analytics service.

**Comment by truell20** [comment]
(gonna close this so I can prioritize bugs, but please lmk if you have any more questions her! either in this thread or on discord @truell20 or over email at michael@cursor.so)
