### ISSUE TITLE
Is it possible to make chat window bigger?

### ISSUE THREAD

**Issue by pretend-busy** [getcursor/cursor#401]
I want a bigger chat window view, seems i can't find  a setting option to set the size of chat window.

**Comment by yuchen9** [comment]
maybe the  Zoom-In can help you
<img width="287" alt="2023-04-01 17 13 43" src="https://user-images.githubusercontent.com/97930813/229277256-d2070b97-4870-412e-9c70-f1b2c23ed8bb.png">

**Comment by danperks** [comment]
The chat window in v0.2.0 is now scalable, so that should be better for you.
I'll close the issue, assuming the new version resolves this for you, but feel free to comment again and I can reopen it if you would still like more customisation.
