### ISSUE TITLE
Cannot login to Cursor on Ubuntu 22.04

### ISSUE THREAD

**Issue by ilovenuclearpower** [getcursor/cursor#403]
Specifically, I am using ubuntu 22.04 on x11, and using appimagelauncherd to manage my AppImage applications - when I click the "login" button, it correctly redirects me to the cursor site - but when I sign in with github, the operating system can't handle the redirect and correctly send it to the running cursor application, see screenshot:
![image](https://user-images.githubusercontent.com/42021038/229222222-3444e42e-11e1-441d-baf1-c517c29364af.png)

Is there another way to log in?

**Comment by urasmutlu** [comment]
+1 on this on Ubuntu 20.04. Sign in redirection to the app is not working and nothing is happening. I don't even see the pop-up in the screenshot, simply nothing happens.

**Comment by danperks** [comment]
Have you tried this with v0.2.0 or above? Not sure what version you are running here, but you may find different behaviour with newer versions. Will list as a bug unless I hear back 😄

**Comment by danperks** [comment]
I'll leave this open as it appears to be a different bug, but other Ubuntu users are having issues at #97 for reference.

**Comment by urasmutlu** [comment]
I can verify that v0.2.x solves this.

**Comment by hemangjoshi37a** [comment]
same problem #1323
have you found any solution? if yes please let me know.
