### ISSUE TITLE
Cursor cuts off code in its query to GPT-3.5

### ISSUE THREAD

**Issue by elanzini** [getcursor/cursor#406]
I highlighted my entire file: `Command + A` (231LOC) and then with `Command + K` asked `find code duplication and create a shared function`.

For context, those are all calls to the backend and they share some boilerplate to send the auth token in the header and so on.

I got this:
<img width="1285" alt="Screenshot 2023-04-01 at 14 25 28" src="https://user-images.githubusercontent.com/37532050/229291782-e5830638-4ed2-43f8-b82d-d3d5705b7c63.png">

**Comment by danperks** [comment]
Note that your screenshot is of the old version of Cursor, but I will leave this open as I believe the issue may still exist.

**Comment by jakobFNF** [comment]
There have been some major changes to the inline edits feature since this issue was created. If the issue still persists for you, please open a new issue. We will close this one for now due to inactivity.
