### ISSUE TITLE
bug: app hanged when trying to answer a prompt, cannot restart after the process is killed

### ISSUE THREAD

**Issue by artemisep** [getcursor/cursor#408]
previously I can restart the app by clicking on it after it hanged and killing the process
now I cannot restart the app by clicking on the app. It recovered after I restart my computer

**Comment by danperks** [comment]
Were you running the newer version of Cursor, v0.2.0 or above, when this occurred? 
If not, the update has changed a lot, so it may be worth updating and seeing if you face the same issue.

**Comment by danperks** [comment]
I believe is an issue regarding the older versions of Cursor, so I'll close this for now. Feel free to comment or make a new issue if you have any other problems or suggestions a
