### ISSUE TITLE
Cursor is using the URL Scheme occupied by Electron Fiddle

### ISSUE THREAD

**Issue by ktiays** [getcursor/cursor#409]
We found that Cursor is using the same URL Scheme as Electron Fiddle, which may cause conflicts when both apps are installed simultaneously.

Electron Fiddle: https://github.com/electron/fiddle/blob/c184e429b2716f394ec1cd5af6574601137809d7/forge.config.js#L85
Cursor: https://github.com/getcursor/cursor/blob/ac07586de50bdacf0b43b5afca32594ad7a19933/forge.config.js#L15

**Comment by truell20** [comment]
Good catch! I think this is fixed in the newest version. @Sanger2000 can you confirm?
