### ISSUE TITLE
About code privacy

### ISSUE THREAD

**Issue by hongbo-miao** [getcursor/cursor#41]
The tool is amazing! I am wondering what data does it collect? Thanks! 😃

**Comment by truell20** [comment]
Hey! Everytime you invoke the AI, we store some of the code from the current file in a hosted analytics service called HumanLoop. This lets us improve the AI. We also store your prompts in Posthog, an open source analytics tool.

We're thinking of adding an option where absolutely no code is stored anywhere. Lmk if that'd be helpful! Want to see where people prefer to be on the spectrum of product improvement and not-storing-anything.

**Comment by Hongbo-Miao** [comment]
@truell20 adding that option would be very helpful! The more transparent, the better. ☺️

**Comment by truell20** [comment]
This is super helpful feedback! Will add into the editor.

**Comment by MatthewAry** [comment]
> We're thinking of adding an option where absolutely no code is stored anywhere. Lmk if that'd be helpful! Want to see where people prefer to be on the spectrum of product improvement and not-storing-anything.

The absolutely no code stored option would be a must if the tool is going to be used on IP restricted projects.

However, some orgs might be willing to allow the AI to consume their entire code base (sans secrets of course) when interacting with it if there are legally binding guarantees of IP ownership and non-disclosure from Cursor. This is because developers should understand that the more that an AI knows about the problem being worked on and the context around it, the more helpful it could potentially be.

**Comment by djpecot** [comment]
Might be a bit of a technical implementation, but could the code be minified on the input side to prevent leakage of specific names, while still learning from the overall structure? I'm wondering if that would allow for a trade-off between the two, cause it's not like you can just run a PII cleaner over a code-base..

**Comment by otto-dev** [comment]
> we store some of the code from the current file in a hosted analytics service called HumanLoop

Is that also the case if you enter your own API key and pay for the model usage yourself? What about a paid option on cursor's side @truell20?

Would absolutely love to use cursor, but it gets nowhere near my confidential code under current conditions, as regrettable as it it.

**Comment by truell20** [comment]
> Might be a bit of a technical implementation, but could the code be minified on the input side to prevent leakage of specific names, while still learning from the overall structure? I'm wondering if that would allow for a trade-off between the two, cause it's not like you can just run a PII cleaner over a code-base.

This is a really interesting idea.

> Also couldn't find a privacy policy anywhere...

This is now up on the site! https://www.cursor.so/privacy

**Comment by truell20** [comment]
> The absolutely no code stored option would be a must if the tool is going to be used on IP restricted projects.

This is now up. Just click on the settings gear in the top right, then Advanced, then Local/Ghost mode.

**Comment by truell20** [comment]
> Is that also the case if you enter your own API key and pay for the model usage yourself? What about a paid option on cursor's side @truell20?
> 
> Would absolutely love to use cursor, but it gets nowhere near confidential code under current conditions, as regrettable as it it.

Anyone can turn on the no-storage mode. No need to pay. No need to use your own API key (unless you want to ofc!)

**Comment by roark** [comment]
Is it possible to specify that cursor ignore config files that may contain API secrets?

**Comment by MatthieuToulemont** [comment]
I might be blind, but I cannot see the advanced button in the settings, was it removed ? (I am using chrome)


![Screenshot 2023-10-02 at 12 23 12](https://github.com/getcursor/cursor/assets/75613333/61df7295-a82f-406a-9265-1476a3d9c79e)

**Comment by MatthieuToulemont** [comment]
It is also not visible on safari ( cc @truell20 )

**Comment by jakobFNF** [comment]
@MatthieuToulemont You can find the local mode in the app under settings.
![image](https://github.com/getcursor/cursor/assets/74077124/3c82883b-285a-4713-b12f-f8c9adb0fd26)
