### ISSUE TITLE
Add the ability to relocate Chat window

### ISSUE THREAD

**Issue by HaleNing** [getcursor/cursor#415]
Here is My Problem, I have a 4K monitor when I Use "chat" with cursor.  "chat" window always display on the right of the screen.
but code on the center or left of the screen. It's hard to read.

I hope the developer team can consider this situation, and make "chat" window can move around.

**Comment by danperks** [comment]
Nice idea, I have an ultrawide monitor so I know what you mean!

**Comment by jakobFNF** [comment]
You can now use the 'Open Chat in Editor Tab' button to have more control over the chat's position. Thank you for your suggestion!

![image](https://github.com/getcursor/cursor/assets/74077124/3f758c35-9994-4a3b-93e9-b1ae267fcad8)

**Comment by OgDev-01** [comment]
Hello @jakobFNF 👋 

How can i revert back to the default... I'm stuck with the chat in the center of my editor?

**Comment by elviskahoro** [comment]
New link for the page in the docs for changing the activity bar:
https://docs.cursor.com/get-started/migrate-from-vs-code#why-is-the-activity-bar-in-cursor-horizontal

**Comment by OciCekov** [comment]
And just how good would it be, if the chat worked like the copilot, just being part of the activity bar, not some window in the middle of everything... line between stupid and unique is a bit dodgy here
