### ISSUE TITLE
Add Support for Non-English Chat with the AI

### ISSUE THREAD

**Issue by zixi010** [getcursor/cursor#418]
里面的chat跟她发汉语，结果用英语回
而且里面的好多设置都不可以下载，有点反应慢

**Comment by KAWAKO-in-GAYHUB** [comment]
你让它“用中文回复”就行了

**Comment by Gao-Vidor** [comment]
“用中文回复” 时灵时不灵

**Comment by jakobFNF** [comment]
You can now use the 'Rules for AI' feature to create persistent rules for the AI, such as 'You must always reply in Chinese.' Thank you for your suggestion!

![image](https://github.com/getcursor/cursor/assets/74077124/e297f79c-17a2-4026-8da5-211c3a814a6e)
