### ISSUE TITLE
terminal current directory doesn't change when Opening the New Folder

### ISSUE THREAD

**Issue by EV-OD** [getcursor/cursor#419]
When I open cursor current directory in terminal shows the right path, but when I open another new folder and look at terminal current directory is previous directory 

So to change the current directory, either I have use "cd" command or restart cursor 

![image](https://user-images.githubusercontent.com/64152903/229351717-98f30dfd-b6e3-4288-a52e-474bee488827.png)
![image](https://user-images.githubusercontent.com/64152903/229351738-ae72615b-c3b8-46f4-8d35-224f6831d1e6.png)

**Comment by EV-OD** [comment]
When I open terminal after opening the other folder, terminal state doesnot resets

![image](https://user-images.githubusercontent.com/64152903/229411899-4270b865-5662-48e4-8d4a-5bbe2a1c3587.png)

**Comment by truell20** [comment]
Think this should work in the newest version!
