### ISSUE TITLE
terminal on Mac should use user preferred shell.

### ISSUE THREAD

**Issue by dongyuwei** [getcursor/cursor#420]
I always use `fish` instead of `bash` or `zsh`. I hope  terminal of cursor can detect the  default shell of the system.

I asked ChatGPT 4, how to get the default shell of Mac system? It get it correctly!
```
dscl . -read /Users/$(whoami) UserShell

## the output
UserShell: /usr/local/bin/fish
```

**Comment by dongyuwei** [comment]
And I just verified the following code works on both Mac and Linux (Ubuntu 18.10 ) .

```
#!/bin/sh

# Detect the user's default shell
if [ "$(uname)" = "Darwin" ]; then
    # macOS
    DEFAULT_SHELL=$(dscl . -read /Users/$(whoami) UserShell | awk '{print $2}')
else
    # Linux
    DEFAULT_SHELL=$(getent passwd $(whoami) | awk -F: '{print $7}')
fi

echo "Your default shell is: $DEFAULT_SHELL"
```

**Comment by truell20** [comment]
Think this should work in the newest version!
