### ISSUE TITLE
What's Language Server?

### ISSUE THREAD

**Issue by flyingSnow-hu** [getcursor/cursor#421]
So how can add a server like Lua or something?

**Comment by alwaystest** [comment]
Better ask GPT 😁

**Comment by flyingSnow-hu** [comment]
> Better ask GPT 😁

Thanks. She explained to me, but seems I can't use a Lua Server in Cursor yet. /(ㄒoㄒ)/~~

**Comment by truell20** [comment]
should be fixed in newest vesrion 🙂
