### ISSUE TITLE
Feature request : need config to set module version used

### ISSUE THREAD

**Issue by clipsheep6** [getcursor/cursor#422]
HI, since th API key feature is enable , I wonder if we could add the module version in setting to let user control the module version they need

**Comment by truell20** [comment]
Hey! What do you mean by module version?

**Comment by danperks** [comment]
I assume you want the ability to set the model used when using an OpenAI API key?

This is being discussed in #394, but if you mean something else, feel free to open a new issue or comment here and we can reopen this one.
