### ISSUE TITLE
Add more affordable subscription options

### ISSUE THREAD

**Issue by verybigorange** [getcursor/cursor#429]
$20 per month is expensive for countries with lower incomes.

**Comment by Microbion** [comment]
I'm worried about whether cursor will terminate my count unexpectedly some day, like chatgpt

**Comment by danperks** [comment]
For now, I'd suggest using your own OpenAPI key, as this will likely be cheaper if your usage isn't intense.

**Comment by danperks** [comment]
Also discussed in #463, but with more detailed discussion there.

**Comment by jakobFNF** [comment]
Thank you for your feedback. We'll take localized pricing into consideration. We are closing this issue for now due to inactivity.

**Comment by truell20** [comment]
Would love to be able to support this in the future. For the time being, our LLM inference costs are too high to support lower prices.

**Comment by MoAbbasid** [comment]
I also second this, for someone in Africa the 20$ is alot
