### ISSUE TITLE
You're going a bit fast...

### ISSUE THREAD

**Issue by DesignsByVanessa** [getcursor/cursor#430]
Can we use our own open ai key?

As of now, there's not even a pro option on the webpage.... so even if I wanted to buy, I cant.

I like your product, but help, please.

![image](https://user-images.githubusercontent.com/124464640/229936699-b57119f8-5512-42c9-891a-df0bcb5babc6.png)

**Comment by yuchen9** [comment]
Hi, you can use your own open api key and upgrade to the pro on Cursor.
<img width="367" alt="6" src="https://user-images.githubusercontent.com/97930813/229958333-e40f194b-4a63-42a7-9269-f1c6931653d3.png">

**Comment by DesignsByVanessa** [comment]
@yuchen9,

Awesome, it's absolutely there. 

Probably just me, but I was looking under the file/edit dropdowns for the settings... not on the right. Just a heads up as to why I didn't find it.

Thanks again
