### ISSUE TITLE
是不是有几个人用就开始飘了，非要登录

### ISSUE THREAD

**Issue by sisz168** [getcursor/cursor#431]
是不是有几个人用就开始飘了，非要登录

**Comment by Ha0ran2001** [comment]
登录很费劲吗？

**Comment by mtk380** [comment]
我的写了openai key后点击submit没反应啊

**Comment by hordaway** [comment]
收费没有问题，别有bug呀，抓紧时间修吧。

**Comment by Ha0ran2001** [comment]
> 我的写了openai key后点击submit没反应啊

一样，https://github.com/getcursor/cursor/issues/392，这里有个issues提了

**Comment by TangleLin** [comment]
登录不了。。。

**Comment by mirrorange** [comment]
您别搁着丢人。软件都是开源的，就收个 API 的钱。OpenAI 的 GPT-4 接口收费可不低，你是指望人家做公益呢？

**Comment by danperks** [comment]
Seems to be a duplicate of #392, maybe not just MacOS, while mark as a duplicate as the source of the issue is likely the same. 
@sisz168 Can you confirm what platform you are using?
