### ISSUE TITLE
Does it automatically retrieve the source code of other imported classes?

### ISSUE THREAD

**Issue by sfz009900** [getcursor/cursor#433]
For example, I asked him to explain the test function. Can it automatically open the source code of test001Service to find out what test001Service does?
import 111.111.111.test001Service;

   @Service
public class MyTestService extends Constant {
   @Resource
   test001Service test001;	
	
	   public void test(String test) {
      TestDetail temp1 = this.test001.gettest(test);
   }
}

**Comment by danperks** [comment]
Currently, Cursor does not fetch code from other files as context to a query. Look at my response below, where I explain how you can send code with your request (at least in the chat window) as context for the AI to work with:

https://github.com/getcursor/cursor/issues/460#issuecomment-1501630408

Not being a developer, I can't make any promises, but this has been a highly requested feature so far, so I can imagine more development will be done surround this in the future.

**Comment by danperks** [comment]
I'll close this as answered, as the enhancement is being discussed elsewhere.
