### ISSUE TITLE
希望能同时支持打开多个文件夹

### ISSUE THREAD

**Issue by Seifon** [getcursor/cursor#438]
如题

**Comment by danperks** [comment]
As with VSCode, you can use the "Workspace" feature to work in multiple folders simultaneously. This works similarly to a project in Visual Studio, which allows multiple folders in different places to be worked on in the same window. To learn more about workspaces, check out the VSCode docs here:

https://code.visualstudio.com/docs/editor/workspaces

If this is what you were looking for, feel free to close the issue.

**Comment by danperks** [comment]
I'll consider this as resolved, as the "Workspaces" feature _should_ do what you are looking for.

If not, feel free to comment and I can reopen this.
