### ISSUE TITLE
好用个鬼，给我一段10年前的代码

### ISSUE THREAD

**Issue by Ray507** [getcursor/cursor#439]
import pybacnet
from pybacnet import bacnet

![image](https://user-images.githubusercontent.com/45837161/230263195-5af26e1c-8b56-41bd-9ccc-37967f126d8d.png)

**Comment by liliwen365** [comment]
master分支在哪里？7个分支里没有
![image](https://user-images.githubusercontent.com/76478019/230317048-6257892b-d329-4429-83c1-e8a143d054ae.png)

**Comment by Ray507** [comment]
我说的是 示例代码给的这个包 。  pybacnet  
还让我用 pip 安装， 就找不到这个。

**Comment by danperks** [comment]
Unfortunately, the responses given by the AI are out of the control of the Cursor team to some extent, as it's based on what and how OpenAI have trained GPT-3.5. I'd recommend adjusting your query to tell it not to suggest that package, but do keep in mind that isn't magic, and can only suggest things based on what it knows 😆

**Comment by danperks** [comment]
Following from my previous answer, as the AI is somewhat out of the control of Cursor developers, I'll close this issue to keep things clean.

Feel free to comment and we can reopen this for you!
