### ISSUE TITLE
界面ui 重叠问题 ：当进行Command+K 描述时 提示语与包路径重叠

### ISSUE THREAD

**Issue by topsuder** [getcursor/cursor#440]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/69955165/230263684-a344ce09-682f-4b9f-a399-c1783e5e2175.png">
当进行Command+K 描述时 提示语与包路径重叠

**Comment by danperks** [comment]
This looks to be a bug with v0.1.X. I'd highly recommend trying the latest version, as this is likely fixed in that.

I'll close this as resolved, but feel free to open a new issue if you still have issues!
