### ISSUE TITLE
Chat Responses are sometimes cut off/limited

### ISSUE THREAD

**Issue by liliwen365** [getcursor/cursor#441]
chat聊天返回的字数有限，我提出让其继续时，它没有继续，而是重复之前的回答，因返回字数受限，所以，后面回答我看不到

**Comment by WaitAKennyJ** [comment]
遇到了同样的问题

**Comment by markwave** [comment]
对的，早就发现了，这个问题不解决，怎么付费pro会员呢

**Comment by digger-yu** [comment]
+1

**Comment by danperks** [comment]
This is likely resolved in later versions, but feel free to open a new issue if not.
