### ISSUE TITLE
When I upgrade to 2.0, problem occurs

### ISSUE THREAD

**Issue by a950701zz** [getcursor/cursor#444]
How to solve this, I can't genertate or chat with the IDE
![image](https://user-images.githubusercontent.com/52117735/230350010-fad9ef2d-0f6a-495c-bcc0-e85e92c516ac.png)

**Comment by WaitAKennyJ** [comment]
I have the same problem

**Comment by BarleyXu** [comment]
me too

**Comment by ricky52529** [comment]
me too， what happened~

**Comment by FukoH** [comment]
same problem here

**Comment by qiangyongyang** [comment]
me too

**Comment by qiangyongyang** [comment]
俺也一样

**Comment by lengkq** [comment]
我干脆打不开了

**Comment by coderweiwei** [comment]
I hava the same problem

**Comment by Gao-Vidor** [comment]
是的 我也是这样

**Comment by lynhsiong** [comment]
me too!

**Comment by Kurt-Shiwz** [comment]
+1

**Comment by xcloudx12345** [comment]
![image](https://user-images.githubusercontent.com/40192522/230356023-2d81fe08-c136-49d4-a0b3-7e79076867e4.png)
dev answer

**Comment by coderweiwei** [comment]
I have soleved the problem. and you should open a folder and create a file to get cursor-ai helping

**Comment by truell20** [comment]
Sorry about this! You needed to open a folder/file to get chat to work. This is fixed and made more clear in the newest update (version 0.2.1). Thanks for reporting this problem 🙏
