### ISSUE TITLE
Cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by Gao-Vidor** [getcursor/cursor#445]
When I attempt to Chat or  Gnerate in the latest version Cursor(Cursor 0.2.0-x64) 
![image](https://user-images.githubusercontent.com/23260976/230353595-adb08b8b-1760-4e37-8ed1-cd4727e3873e.png)

**Comment by Kurt-Shiwz** [comment]
+1

**Comment by Joker-jiajiahui** [comment]
+1

**Comment by 1457634627** [comment]
+1

**Comment by liugd2018** [comment]
+1

**Comment by bisslot** [comment]
+1

**Comment by 2353709203** [comment]
+1

**Comment by tyhbfgbfg** [comment]
fuck  metoo

**Comment by HNUrookie1** [comment]
wish today

**Comment by HNUrookie1** [comment]
wsm

**Comment by BIG9MONKEY** [comment]
fuckk,me too

**Comment by Collapsar-X** [comment]
It seems we have the same problem

**Comment by yeuyuetou** [comment]
> 似乎我们有同样的问题
How did you solve it, going crazy

**Comment by Nieleop** [comment]
+1

**Comment by BIG9MONKEY** [comment]
hey,sorry,i have no idea now, i going crazy too







                       
Original Email
                       
                     

Sender:"yeuyuetou"< ***@***.*** &gt;;

Sent Time:2023/4/6 20:09

To:"getcursor/cursor"< ***@***.*** &gt;;

Cc recipient:"BIG9MONKEY"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [getcursor/cursor] Cannot read properties of undefined (reading&#39;uri&#39;) (Issue #445)




  
似乎我们有同样的问题
 How did you solve it, going crazy
  
&mdash;

**Comment by Collapsar-X** [comment]
> > 似乎我们有同样的问题
> > How did you solve it, going crazy

You can first create a folder in Cursor to store the relevant files, then create a new file in this folder, and finally use the shortcut ctrl+K/L on this file to run it successfully.

**Comment by Collapsar-X** [comment]
A simple solution is provided: you can first create a folder in Cursor to store the relevant files, then create a new file under this folder, and finally use the shortcut ctrl+K/L on this file to run it successfully.

**Comment by yeuyuetou** [comment]
Thank you so much!

**Comment by tyhbfgbfg** [comment]
> 提供了一个简单的解决方案：您可以先在 Cursor 中创建一个文件夹来存储相关文件，然后在该文件夹下创建一个新文件，最后在此文件上使用快捷键 ctrl+K/L 成功运行它。

thank you so much! my bro

**Comment by ewxi** [comment]
+1

**Comment by jdgod** [comment]
> When I attempt to Chat or Gnerate in the latest version Cursor(Cursor 0.2.0-x64) ![image](https://user-images.githubusercontent.com/23260976/230353595-adb08b8b-1760-4e37-8ed1-cd4727e3873e.png)

You can just use the 'Explorer' (Ctrl+Shift+E) in Cursor, open any folder, and then make new file or open file there.

**Comment by ewxi** [comment]
怎么创建文件夹啊？cursor中只有创建文本文件啊？

**Comment by ygywzb** [comment]
> A simple solution is provided: you can first create a folder in Cursor to store the relevant files, then create a new file under this folder, and finally use the shortcut ctrl+K/L on this file to run it successfully.

有用！多谢兄弟！

**Comment by almacaro** [comment]
me too

**Comment by 1457634627** [comment]
> 

确实可以用了

**Comment by truell20** [comment]
Hey! Sorry about this! You needed to open a folder/file to get chat to work. This is fixed and made more clear in the newest update (version 0.2.1). Thanks for reporting this problem 🙏
