### ISSUE TITLE
Cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by YY-nb** [getcursor/cursor#448]
After I update my cursor, I meet this problem when either generating code or chatting. How to solve it?

**Comment by Kurt-Shiwz** [comment]
+1

**Comment by Joker-jiajiahui** [comment]
+1

**Comment by Joker-jiajiahui** [comment]
+1

**Comment by lllllaurel** [comment]
+1

**Comment by wangjun92** [comment]
+1

**Comment by wangjun92** [comment]
俺也一样

**Comment by gefengyougong** [comment]
me too

**Comment by khachoangpt** [comment]
I fixed it by creating a new folder.

**Comment by linuxht** [comment]
me too

**Comment by linuxht** [comment]
> I fixed it by creating a new folder.

Request detailed operation

**Comment by YY-nb** [comment]
![image](https://user-images.githubusercontent.com/74820657/230362911-8e15bba0-d357-4074-a595-b1716de9e36e.png)
Click "Open Folder" and choose or create a folder

**Comment by icjking** [comment]
我也是

**Comment by syoryu** [comment]
选择一个工作区，或者新建个文件夹就可以了😁

**Comment by linuxht** [comment]
3x

**Comment by onlyKta24** [comment]
3x

**Comment by skyxiaobai** [comment]
Maybe needs to add a toast.

**Comment by truell20** [comment]
Sorry about this! You needed to open a folder/file to get the AI features to work. This is fixed and made more clear in the newest update (version 0.2.1). Thanks for reporting this problem 🙏
