### ISSUE TITLE
VSCode Config (Font, Settings, etc) Reverting to Default in Certain Situations

### ISSUE THREAD

**Issue by p1s1lver** [getcursor/cursor#449]
I have noticed that the font in my application reverts back to the default font in certain situations. Specifically, I have observed this behavior when [select code to chat].

Environment:
- Operating System: windows11
- Application Version: Cursor newest version

Let me know if you need any further assistance!

**Comment by febnine29** [comment]
I had the same issue, the font will be returning back to default when im open the new window, i've tried to change font in settings.json, but the issue still there

**Comment by jiyingxin** [comment]
same issue, version 0.2.2
win11

**Comment by JasonLamv-t** [comment]
same issue, every version even at 0.2.10
macOS

**Comment by jakobFNF** [comment]
This issue should have been fixed. If it still persists for you, please open another issue. Thank you for reporting this bug!
