### ISSUE TITLE
After upgrading and installing Cursor Setup 0.2.0-x64.exe, my computer cannot normally start

### ISSUE THREAD

**Issue by children1987** [getcursor/cursor#450]
The symptoms are a crash immediately upon opening.

**Comment by ly415925488** [comment]
me too! When I started cursor, the program just flashed by without responding

**Comment by truell20** [comment]
Could you send a screenshot or recording? What operating system are you on? Does this persist if you redownload the program from cursor.so?

**Comment by children1987** [comment]
![image](https://user-images.githubusercontent.com/9018733/230524904-ad4cd8a4-7677-4860-8985-b7c2d737aa60.png)

**Comment by aying0818** [comment]
My problem has been solved, and the upgraded Cursor needs to be paid for better use.

**Comment by children1987** [comment]
Uploading QQ录屏20230407100255.mp4…

**Comment by children1987** [comment]
> My problem has been solved, and the upgraded Cursor needs to be paid for better use.Thank you.

How did you fixed?

**Comment by danperks** [comment]
Looking at other issues, this happens when an anti-virus called 360 seems to intercept some of Cursor's needed files. If you have that installed, try disabling it and rerunning Cursor. If you don't have 360, let us know, and someone will try to help you out further.

**Comment by danperks** [comment]
Will close as the issue appears to be resolved, but feel free to comment and we can reopen this if needed.

**Comment by children1987** [comment]
> Looking at other issues, this happens when an anti-virus called 360 seems to intercept some of Cursor's needed files. If you have that installed, try disabling it and rerunning Cursor. If you don't have 360, let us know, and someone will try to help you out further.

Yes. I think it was incompatible with 360. My Cursor is OK when I closed 360. Thank you so much!
