### ISSUE TITLE
我干脆打不开了

### ISSUE THREAD

**Issue by crazythinking** [getcursor/cursor#451]
我干脆打不开了

_Originally posted by @lengkq in https://github.com/getcursor/cursor/issues/444#issuecomment-1498855513_
      me too

**Comment by liuzh825** [comment]
me too

**Comment by syoryu** [comment]
me three

**Comment by Cynthia10101** [comment]
open a folder and a file, then it works

**Comment by copywrite** [comment]
me five

**Comment by syoryu** [comment]
thanks！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月06日 19:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [getcursor/cursor] 我干脆打不开了 (Issue #451) |

open a folder and a file, then it works

**Comment by truell20** [comment]
should be fixed in newest vesrion 🙂
