### ISSUE TITLE
Changelog for Cursor

### ISSUE THREAD

**Issue by ichoosetoaccept** [getcursor/cursor#454]
Hi

I only found out about Cursor some time last week and it didn't take long to pay for Cursor Pro. It's a very promising product I'm happy to support.
Things are moving fast, too! This repo is super active and lots of things are going on. I was wondering if you guys are keeping track of incoming changes to Cursor? I'd love to scan a changelog when I update my copy of Cursor to see what's new or what has changed.
Normally I'd expect that in the section "Relases" in a Github repo but yours is empty.

**Comment by truell20** [comment]
Right now we keep our change log on discord. I'll include one on github in the future as well 🙂

**Comment by sisrfeng** [comment]
I think the UI of discord is too complex !
Maybe github is a better place.
