### ISSUE TITLE
Can't open Cursor after v0.2.0 update

### ISSUE THREAD

**Issue by FSWei** [getcursor/cursor#455]
刚刚更新之前还好好的，更新之后ctrl k和ctrl l说完需求之后都没反应了/(ㄒoㄒ)/~~

**Comment by FSWei** [comment]
文件也打不开

**Comment by FSWei** [comment]
发现可以打开文件夹，并且打开文件夹之后什么操作都可以进行了。

**Comment by Jupyter-X** [comment]
mac版占用内存非常高，风扇呼呼的吹，运行jupyter文件也卡的不行

**Comment by meethigher** [comment]
> Cannot read properties of undefined (reading 'uri')
> 
> Hello, can you tell me what caused this?

**Firstly, you need to create a project folder and open it. Only then can you use it normally**

**Comment by JuliaWangZhu** [comment]
> > Cannot read properties of undefined (reading 'uri')
> > Hello, can you tell me what caused this?
> 
> **Firstly, you need to create a project folder and open it. Only then you can use it normally**

Very useful. Thank you.

**Comment by zzall** [comment]
> > Cannot read properties of undefined (reading 'uri')
> > Hello, can you tell me what caused this?
> 
> **Firstly, you need to create a project folder and open it. Only then you can use it normally**

我新建了文件夹跟文件，都没用

**Comment by JuliaWangZhu** [comment]
从官网下载app安装重新进入。打开后会有一个open folder，如果还记得上一个版本的默认workspace 就能打开对应的文件夹，直接出来之前的文件。这两个截图是我地这边操作，或许这种方法可以帮助你。
昨天我第一次更新不能用，我就直接回退找到我之前workspace文件夹，然后重新安装尝试新建文件，我是只要新建文件之后就能用。







在 2023-04-07 11:40:30，"小阵不悲催" ***@***.***> 写道：

Cannot read properties of undefined (reading 'uri')
Hello, can you tell me what caused this?

Firstly, you need to create a project folder and open it. Only then you can use it normally

我新建了文件夹跟文件，都没用

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
