### ISSUE TITLE
Would you like to share why you chose to develop based on vscode.

### ISSUE THREAD

**Issue by rangoack** [getcursor/cursor#456]
At the very beginning, I was very much expecting you guys to make something new, something very different editor. I knew vscode is very successful. It has a very rich extensions market.

**Comment by truell20** [comment]
Shared some thoughts in Discord! 

tldr: We want to focus on building great AI features, not reinventing the wheel with normal text editing features, we heard from many users of the product that they loved VSCode's text editing abilities

<img width="807" alt="Screenshot 2023-04-06 at 2 11 41 PM" src="https://user-images.githubusercontent.com/4297743/230494894-b88fefa7-0ffb-49b1-9668-5602462f0d9a.png">

**Comment by truell20** [comment]
Please let me know if there's anything you dislike about the switch!

**Comment by rangoack** [comment]
The presentation of generation is not as good as before. The code is inserted does not have the  same contrast effect as before. And the chat, I always like to talk with it. I prefer the old version, plus a light theme.
