### ISSUE TITLE
Windows 0.2.0-x64 Version program cannot start

### ISSUE THREAD

**Issue by ly415925488** [getcursor/cursor#457]
When I start the program, a pop-up window will appear and immediately disappear without any prompts.

**Comment by truell20** [comment]
Could you send a screen shot?

**Comment by truell20** [comment]
Screen recording would be even better. Would help a ton for fixing this 🙏

**Comment by ly415925488** [comment]
https://user-images.githubusercontent.com/17976231/230496479-10c20e3e-0ade-48d5-83c2-e1def94a7f91.mp4

Run the program, a pop-up window appears and immediately disappears, no useful information is visible.

 My computer system version is Windows 11
![QQ截图20230407052741](https://user-images.githubusercontent.com/17976231/230497649-dccce2c9-1c96-4b6b-96ed-47aabc647ccd.png)

**Comment by appdutao** [comment]
same with @ly415925488 I run in cmd，show this error
![image](https://user-images.githubusercontent.com/11690387/230523679-6fe0983b-ab93-40b4-b71a-223923d7720d.png)

**Comment by truell20** [comment]
Does this happen in 0.2.2 if you redownload from the site?

**Comment by ly415925488** [comment]
I think I have found the reason. In China, it was intercepted by an antivirus software called 360. When I exit the antivirus software, cursor can be opened normally.

**Comment by danperks** [comment]
Closed due to the solution being found: disabling 360 anti-virus software.
