### ISSUE TITLE
Focused/broad multiple file understanding for chat and generation?

### ISSUE THREAD

**Issue by djpecot** [getcursor/cursor#460]
I'm curious how cursor is inputting data into the AI and if it is able to "see" connections across different files. For example, I'm working on a code base that has some structure like this:

```jsx
- data
    - dataset_cities.csv
    - dataset_restaraunts.csv
    - dataset_random.csv
- src
    - thing.py
    - thing2.py
    - utils
        - thing3.py
- modules
    - openai
- main.py 
```

Where let’s say for example I want to chat about the current file in `thing.py` that references any imported modules/libraries at the head of the file (i.e. `openai`, `utils.thing3`, etc.), pulls that into the “context” of a code generation or chat task. Based on what I’m reading, it seems like the current version only accesses the “active” file that I have open. 

[Readme](https://github.com/getcursor/cursor) just says `Chat: ChatGPT-style interface that understands your **current** file`

Also looked over [this issue](https://github.com/getcursor/cursor/issues/369) but this seems more like a cross-file `Ctrl + Shift + F`.

Similar to [this issue](https://github.com/getcursor/cursor/issues/433)

If this isn’t part of the logic, is there a way to manually “force” other code context into a chat? This seems like a really important feature to give the AI a higher-level understanding of all the files in a given code base (or to focus on specific functions within a file or modules)

I peeked in the [package.json](https://github.com/getcursor/cursor/blob/main/package.json) but didn't detect any open-source AI modules, so not sure how the actual AI logic is processed ;)

Example. Using Ctrl + K to generate code, I gave it this prompt in `main.py`
```
# Load the rest of the files from the data folder as pandas DataFrames
```
To which it responded:
```
data_files = ['file1.csv', 'file2.csv', 'file3.csv']  # Replace with your actual file names
data_frames = [pd.read_csv(f'data/{file}') for file in data_files]
```
This is actually a pretty good output except.... that my underlying csv files were not named `file1`, `file2`, etc.

Now if I change the directory name from `data` to `some_data_folder`, it hallucinates a response:
```
import pandas as pd

# Load the rest of the files from the data folder as pandas DataFrames
import os

data_folder = "data"
data_files = [f for f in os.listdir(data_folder) if f.endswith('.csv')]

dataframes = {}
for file in data_files:
    file_path = os.path.join(data_folder, file)
    dataframes[file] = pd.read_csv(file_path)
```
It DID create the dynamic file names suprisingly this time, but missed on the actual directory name.

It seems like the underlying LLM is "unaware" of context outside of the current file?

**Comment by danperks** [comment]
Many of these features are now including, with the ability to specify context from multiple files to a query, and with Composer's multi-file changes, so I'll close this as done!
