### ISSUE TITLE
v2.0 bug - update popup loop, but never updates 

### ISSUE THREAD

**Issue by DesignsByVanessa** [getcursor/cursor#461]
Significant updates in v2!

Still stuck on an update popup loop that can't complete.
![image](https://user-images.githubusercontent.com/124464640/230496142-d8ac45c8-7d87-49ae-9a8a-3231a8e3975c.png)

This warning is in the terminal:
```bash
$ cursor
[main 2023-04-06T21:13:49.110Z] update#ctor - updates are disabled as there is no update URL
```
cursor verson:
![image](https://user-images.githubusercontent.com/124464640/230495848-497a7212-e971-4c2f-ad78-f61d3412c07b.png)

```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

How is it being run?
Cursor appimage was chmod 755, then moved to `/usr/local/bin/cursor`. Launching from terminal.

Any insight into how to get this resolved would be greatly appreciated.

Keep up the good work

**Comment by truell20** [comment]
Looking into this, just rolled back the autoupdate change for mac/linux to investigate further. Thanks for reporting!

**Comment by Himanshu4776** [comment]
Hi @truell20 , I want to work on this bug. Can you please assign it to me?

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
