### ISSUE TITLE
定价极不合理

### ISSUE THREAD

**Issue by xiebao** [getcursor/cursor#463]
定价极不合理，建议你免费的应当延续以前的版本，付费分个等级，一下20刀你真是够狠

**Comment by jon-leun** [comment]
主要是生产力不匹配吧 ，我觉得20$ 真的顶不住 ， 因为我也在用copilot ， 在国外20$ ，也就一顿饭 ， 但是对于我们来说可能。。。

**Comment by danperks** [comment]
Duplicate of #429, but will keep it open to make sure your queries are heard.

**Comment by liangvim** [comment]
建议在低收入国家，定价5＄比较合理

**Comment by jakobFNF** [comment]
Thank you for your feedback. We'll take localized pricing into consideration. We are closing this issue for now due to inactivity.

**Comment by truell20** [comment]
Would love to be able to support this in the future. For the time being, our LLM inference costs are too high to support lower prices.

**Comment by DingSoung** [comment]
天天推广，搞半天是收费的啊，建议做成 VScode 插件。

**Comment by andy90s** [comment]
定价有点高了。

**Comment by kabda** [comment]
如果使用cursor帮你提升效率而节约的时间成本 > 20美金/月，那你值得入手；反之，不建议；
