### ISSUE TITLE
cursor 0.2.0 cannot be used. "Cannot read properties of undefined (reading 'uri')"

### ISSUE THREAD

**Issue by PanZ12580** [getcursor/cursor#464]
OS：macOS 12.5.1，Apple M1 Pro
cursor version：cursor 0.2.0

When I try to generate or chat, the following error msg occurred.

"Cannot read properties of undefined (reading 'uri')"
<img width="917" alt="image" src="https://user-images.githubusercontent.com/53255743/230531229-6a78e184-963c-4f63-ac65-f25ec00df518.png">

**Comment by JaRLenZhang** [comment]
I also have the same problem.

**Comment by jiyb** [comment]
> OS：macOS 12.5.1，Apple M1 Pro cursor version：cursor 0.2.0
> 
> When I try to generate or chat, the following error msg occurred.
> 
> "Cannot read properties of undefined (reading 'uri')" <img alt="image" width="917" src="https://user-images.githubusercontent.com/53255743/230531229-6a78e184-963c-4f63-ac65-f25ec00df518.png">
How do you solve this problem?

**Comment by PanZ12580** [comment]
> > OS：macOS 12.5.1，Apple M1 Pro cursor version：cursor 0.2.0
> > When I try to generate or chat, the following error msg occurred.
> > "Cannot read properties of undefined (reading 'uri')" <img alt="image" width="917" src="https://user-images.githubusercontent.com/53255743/230531229-6a78e184-963c-4f63-ac65-f25ec00df518.png">
> > How do you solve this problem?

Don't open file directly. Open a folder first, then open the file from the folder. 
It's a bug.

**Comment by jiyb** [comment]
谢谢大佬

**Comment by Microbion** [comment]
为什么要强制更新啊，0.1.12用的挺稳定的

**Comment by ilikeelec** [comment]
> 
In my cursor, i cannot find any file after open folder

**Comment by truell20** [comment]
should be fixed in the latest version, this happened when you didnt have a file or folder open

**Comment by DotDotGeng** [comment]
Hope to fix this bug quickly, otherwise it will be too difficult to use.
