### ISSUE TITLE
最新2.0之后连cmd+l 和cmd+k都没反应了

### ISSUE THREAD

**Issue by zzall** [getcursor/cursor#466]
![image](https://user-images.githubusercontent.com/32048580/230536121-d9e08540-235a-4ba8-8ba0-370ab976badb.png)

**Comment by Pu-nk** [comment]
同

**Comment by FSWei** [comment]
我也遇到了相同的问题，文件打不开，ctrl l ctrl k都没反应，
后来我发现文件夹可以打开，并且打开文件夹后一切都可以正常运行

**Comment by Pu-nk** [comment]
我打开文件夹以后好像chat也是没有任何反应，不知道有没有朋友有遇到同样的问题

**Comment by zzall** [comment]
> 

我发现不用自己的openai的key可以

**Comment by Jumper9665** [comment]
> 
使用免费的api是不也要填付款信息？

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
