### ISSUE TITLE
Is it possible to add a multilingual version to the cursor software?

### ISSUE THREAD

**Issue by wangjianpro999** [getcursor/cursor#467]
Is it possible to add a multilingual version to the cursor software?

**Comment by truell20** [comment]
sure! what would you want in a multilingual version? is this about making the ai outputs multilingual? or the inputs to the ai

**Comment by wangjianpro999** [comment]
I mean that the UI of the APP itself should support multiple languages.

Michael Truell ***@***.***> 于 2023年4月8日周六 14:47写道：

**Comment by danperks** [comment]
To change the UI of the app, you should be able to follow this guide, which should work the same in Cursor:

https://code.visualstudio.com/docs/getstarted/locales

Let us know if this doesn't work for you.

**Comment by danperks** [comment]
Closing as Cursor supports language changes like VSCode, so this should likely work.
