### ISSUE TITLE
更新0.2.1后直接打不开了

### ISSUE THREAD

**Issue by YepYuYu** [getcursor/cursor#468]
软件都打不开，闪一下就没了

**Comment by shengwusuoxi** [comment]
+1

**Comment by pitera2020** [comment]
同样的问题，不知怎么解决呢？

**Comment by zyhyuheng** [comment]
关闭360

**Comment by ZhangMH2000** [comment]
关闭360真的就好了

**Comment by truell20** [comment]
is this fixed after you quit and restart the app? is it fixed if you reinstall? could you send a screen recording -- would help for fixing this

**Comment by YepYuYu** [comment]
> is this fixed after you quit and restart the app? is it fixed if you reinstall? could you send a screen recording -- would help for fixing this

使用了[360杀毒软件](https://www.360.cn/)后会出现这个问题，关闭后就好了,在最新版0.2.2中也会出现这个问题

**Comment by danperks** [comment]
Closed as disabling anti-virus fixes the issue.
