### ISSUE TITLE
之前用GitHub登录，现在我都不知道我登录的什么号而且copilot支持了没我也不知道

### ISSUE THREAD

**Issue by Horrah123456** [getcursor/cursor#472]

**Comment by Microbion** [comment]
气的说都不会话了，beta版的玩玩就好，千万别认真

**Comment by zihanm** [comment]
哈哈哈是的，我也不知道我用什么账号登陆。忘记密码也没有邮件发给我

**Comment by truell20** [comment]
Feel free to log in with whatever account you want! If you need help locating your pro account, dm me on discord.
