### ISSUE TITLE
The newest version could not received any chat result, but empty.

### ISSUE THREAD

**Issue by vikotse** [getcursor/cursor#473]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/5728396/230589294-16cddaaa-c03e-402f-8c08-fe9697206502.png">
<img width="254" alt="image" src="https://user-images.githubusercontent.com/5728396/230589359-f473ac6e-37c2-4edc-b918-fc8fc27acf68.png">

**Comment by truell20** [comment]
Should be fixed in latest version
