### ISSUE TITLE
Issues with cursor update to 0.2.1

### ISSUE THREAD

**Issue by pitera2020** [getcursor/cursor#474]
After updating cursor to version 0.2.1, double-click to open the flash back, and then uninstall and directly install this version, which is also the case. What is the reason for this?

**Comment by truell20** [comment]
Hey! Apologies about this, what platform is this on (Windows/Mac/Linux)?

**Comment by pitera2020** [comment]
Hello, it's Windows 11 Professional Edition

**Comment by truell20** [comment]
could you send a screen recording? would help a ton for investigating this

**Comment by pitera2020** [comment]
> could you send a screen recording? would help a ton for investigating this

Thank you very much for your enthusiasm. My question has been resolved, and I will just turn off 360 Security Guard.

**Comment by danperks** [comment]
Closed due to resolution.
