### ISSUE TITLE
How Can I avoid the "END_interrupt" after Pro Subscribed?

### ISSUE THREAD

**Issue by stephsix** [getcursor/cursor#479]
I'm using Cursor to convert struct definitions from C# to go, there are 700+ code lines in the C# definition.
Firstly I got the "END_interrupt" by the free plan, as follow:

![image](https://user-images.githubusercontent.com/23513086/230699967-5518c8f5-57da-4c2c-b8b5-9edd50c26cf4.png)

I upgrade Cursor to Pro Sub for the purpose of "Unlimited" as described, BUT "END_interrupt" happened again.

**Comment by danperks** [comment]
I've been facing this, too, seems like a slight issue with the prompting/parsing of the requests.

**Comment by danperks** [comment]
This seems to have been resolved, so I'll close this for now.
