### ISSUE TITLE
Cannot see the input box in command-line mode when using the Vim plugin

### ISSUE THREAD

**Issue by lng2020** [getcursor/cursor#482]
When using the Vim plugin in Cursor, I am unable to see the input box while in command-line mode. This issue makes it difficult to enter Vim commands within the editor.
### Steps to reproduce:
1. Install the Vim plugin for Cursor.
2. Open a file in Cursor.
3. Press the Esc key to ensure you are in normal mode.
4. Press the : key to enter command-line mode.
### Additional information:
Cursor version: 0.2.2
Vim plugin version: v1.25.2
Operating System: Windows11

**Comment by truell20** [comment]
Thanks for reporting! Hope to fix this soon.

**Comment by danperks** [comment]
This is likely resolved in later versions.
