### ISSUE TITLE
auto-update or latest version check

### ISSUE THREAD

**Issue by IwfWcf** [getcursor/cursor#483]
I would like to request a feature that allows the app to auto-update itself or at least check for the latest version and notify the user.

**Comment by IwfWcf** [comment]
I never saw this happened. I have to run the installer to manual check and update.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dan Perks ***@***.***>
发送时间: Monday, April 10, 2023 5:28:16 PM
收件人: getcursor/cursor ***@***.***>
抄送: IwfWcf ***@***.***>; Author ***@***.***>
主题: Re: [getcursor/cursor] auto-update or latest version check (Issue #483)


While the app should auto-update, I don't believe Cursor v0.2.0 can check for the latest version. For now, launching the app on a solid internet connection will check for updates, and a popup in the lower right will show, stating a new update will install when you next close Cursor.

Will leave this open for now as a potential enhancement.

―

**Comment by IwfWcf** [comment]
I opened the version 0.2.0 yesterday but there was no prompt for an update.
I still had to run the installer manually to be prompted to update to
version 0.2.2.

Dan Perks ***@***.***> 于2023年4月10日周一 20:02写道：

**Comment by danperks** [comment]
Ahh I see, will list as a bug and let a developer chime in when they get the chance.

**Comment by dpkirchner** [comment]
In my case, I get update notifications many times a day, usually while typing. Is there a way to move the notifications to a pop-up like the extension recommendations in the bottom right corner?

**Comment by jakobFNF** [comment]
Cursor auto-updates itself, and you can manually check for an update by calling the "Cursor: Attempt Update" action (Ctrl + Shift + P => type "Cursor: Attempt Update" => press enter).
