### ISSUE TITLE
刚刚使用的时候程序自动删除了？？

### ISSUE THREAD

**Issue by FSWei** [getcursor/cursor#484]
刚刚使用的时候按ctrl k，提示我登录，但是我已经登录了
然后退出程序，结果再点快捷方式的时候发现程序没了

**Comment by FSWei** [comment]
发现文件夹里出现了0.0.11版本的Cursor，是版本回滚了吗？

**Comment by TeddyHuang-00** [comment]
两天前就 0.2.2 了，可能是老的API正式弃用了，升级一下版本吧

**Comment by truell20** [comment]
This is so odd! Does it work if you reinstall the software?

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!

**Comment by dabaix11** [comment]
确实我也是这样什么鬼，退出软件就Cursor自己卸载

**Comment by Kevinye0116** [comment]
我也遇到这个问题了，好奇怪啊

**Comment by Juicycodeteam** [comment]
25年1月30日，也遇到这个问题，点击登录后Chrome授权，但未能成功登录，随后程序自己卸载了。

**Comment by shayuaidoudou** [comment]
+1 2025-01-31也是退出自动卸载

**Comment by lingshui1** [comment]
2/1/2025 ,some problem,auto uninstall

**Comment by liushengxin** [comment]
前天发生了一次。今晚重启后再一次自动卸载。

**Comment by peizhouhuang** [comment]
report the same issue here, Does anyone know why?

**Comment by icebearmako** [comment]
same problem

**Comment by xiaoken8713** [comment]
我也是，为什么会这样

**Comment by JUST-Limbo** [comment]
装个老版本就好了大伙儿

**Comment by wolfdan666** [comment]
2025年2月6日16:30 也遇到了，吓到了，甚至 cursor [下载页面](https://download.todesktop.com/230313mzl4w4u92/Cursor%20Setup%200.45.8%20-%20Build%20250201b44xw1x2k-x64.exe)也是 Error 1101 Ray ID: 90d9e9f7baccf918 • 2025-02-06 08:54:09 UTC
Worker threw exception

**Comment by LimLex** [comment]
> 2025年2月6日16:30 也遇到了，吓到了，甚至 cursor [下载页面](https://download.todesktop.com/230313mzl4w4u92/Cursor%20Setup%200.45.8%20-%20Build%20250201b44xw1x2k-x64.exe)也是 Error 1101 Ray ID: 90d9e9f7baccf918 • 2025-02-06 08:54:09 UTC Worker threw exception

same

**Comment by xiaoken8713** [comment]
> 装个老版本就好了大伙儿

安装哪个版本好点啊，使用时间久了关掉之后直接文件全删除了

**Comment by hepzanechen** [comment]
GUI点击没有反应，关闭程序后发现被删除，系统无其他杀毒软件只有windows defender.

**Comment by appsong** [comment]
v0.45.10 关闭后，自动卸载，可能是自动更新BUG引起的问题。

解决办法：
1，断开网络安装Cursor
2，安装完成后，在设置->更新，Enable Windows Background Updates 去掉√。
3，联网，打开Cursor

**Comment by congkee** [comment]
有没有可能是自动更新了，过会安装好就重新出现了

**Comment by wuwenrufeng** [comment]
通过 Windows 安全中心界面
1 打开 Windows 安全中心：
按下 Windows 键，然后输入“Windows 安全中心”并打开它。
或者，右键点击任务栏右下角的安全图标，选择“打开 Windows 安全中心”。
2 进入病毒和威胁防护设置：
在 Windows 安全中心界面中，点击“病毒和威胁防护”。
3 管理设置：
在“病毒和威胁防护”页面中，点击“管理设置”。
4 关闭实时保护：
在“实时保护”部分，将“实时保护”切换为“关闭”。
如果需要完全关闭 Windows Defender，可以点击“关闭 Windows Defender 安全中心”（此选项可能需要管理员权限）。

**Comment by HugoWang232608** [comment]
我也出现了

**Comment by shuanshuan** [comment]
昨天晚上关机，今天中午开机发现cursor被卸载了

**Comment by fdsgfdh5561** [comment]
自动卸载了

**Comment by AbbotBrew** [comment]
2025/11/06 自动卸载了

**Comment by lly277365** [comment]
2025/12/03自动卸载了
