### ISSUE TITLE
Cannot launch when double click the cursor.exe

### ISSUE THREAD

**Issue by wzq0806** [getcursor/cursor#486]
I can't launch the cursor.exe after I updated the latest version. My operation system is WIN10, and I can't find cursor task or processor in the task manager.

**Comment by howl2023** [comment]
你是不是使用了360杀毒软件，把软件关掉就能正常使用了。

**Comment by yinhe** [comment]
正解

**Comment by danperks** [comment]
Did disabling your anti-virus resolve the issue? If not, let us know if you've tried anything else.

**Comment by wzq0806** [comment]
> Did disabling your anti-virus resolve the issue? If not, let us know if you've tried anything else.

Yes, issue resolved after I closed anti-virus.
