### ISSUE TITLE
无法用中文回答我的问题？

### ISSUE THREAD

**Issue by chengpeng2015** [getcursor/cursor#487]
![image](https://user-images.githubusercontent.com/13881307/230809706-01c5ea67-b194-4650-a6fb-2cfc6293b98f.png)

![image](https://user-images.githubusercontent.com/13881307/230809755-4ad5bdee-a643-4650-a20c-89a44e5bf20d.png)

**Comment by xiaoheng21** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/39369984/230867312-9cc24ddd-3c33-49ea-9f7d-ac8056b7510b.png">

**Comment by danperks** [comment]
Not sure how the prompting works here, whether it is set up to respond specifically in English. Will need a developer to chime in.

**Comment by zmyjs** [comment]
提问题的时候带上用中文回复即可，例如：帮我添加中文注释

**Comment by Chunyfong** [comment]
其實跟網頁版的類似, 加上 # Zh-CN/ZH-TW 就好了:

![image](https://user-images.githubusercontent.com/50175081/232051228-d4f0765f-c34d-42b1-b876-59436c9920b2.png)

效果圖(英文input 問, 全中文回應):

![image](https://user-images.githubusercontent.com/50175081/232051390-9f49e831-f1d5-4001-86af-8e0f55c6aa1c.png)

**Comment by truell20** [comment]
@xiaoheng21 and @Chunyfong are exactly right. The way to handle this is with the "MORE" tab.
