### ISSUE TITLE
"Failed to Fetch" error when attempting Login to Cursor account 

### ISSUE THREAD

**Issue by hustzxf12** [getcursor/cursor#490]

**Comment by cantops** [comment]
Turn off antivirus software such as 360 Security Guard, or add Cursor to the whitelist

**Comment by hustzxf12** [comment]
> Turn off antivirus software such as 360 Security Guard, or add Cursor to the whitelist

already turn off，but still doesnt work，early version   work well，donot know how to solve this issue

**Comment by hustzxf12** [comment]
> Turn off antivirus software such as 360 Security Guard, or add Cursor to the whitelist

already turn off，but still doesnt work，early version   work well，donot know how to solve this issue

**Comment by danperks** [comment]
This has been mentioned in #128 and #507, so assuming this is a bug, potentially regarding proxy usage. Will mark as such.

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
