### ISSUE TITLE
cursor icon in task bar

### ISSUE THREAD

**Issue by icyzhe** [getcursor/cursor#491]
I fixed cursor icon in my task bar, but when I open cursor it appear another cursor icon in the task bar. It is not a big problem but it is  not very pretty.

**Comment by danperks** [comment]
I’d suggest a full uninstall and reinstall. It’s possible you have a shortcut to the old version which, while still opening the new version when you click it, is made for an older version and therefore doesn’t merge in the task bar.

**Comment by truell20** [comment]
Made the icon a bit more pretty!

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!
