### ISSUE TITLE
When can  have a dev container plugin like vscode

### ISSUE THREAD

**Issue by wiilruo** [getcursor/cursor#493]
When can  enter a container and edit code like in VS Code

**Comment by danperks** [comment]
This sounds very similar to #489. You can install the VSCode Containers plugin manually, as I describe in that thread, but I can’t guarantee it would work as expected, due to the modifications of Cursor.

Give it a try, as I describe in #489 , and let us know how you get on.

**Comment by wiilruo** [comment]
I tried to do that, but an error occurred

**Comment by wiilruo** [comment]
I tried to translate for me, but an error occurred
![image](https://user-images.githubusercontent.com/130130871/234751230-54fea344-c82d-40a9-9c58-14918f9decce.png)

**Comment by wiilruo** [comment]
I tried to do that, but an error occurred
![image](https://user-images.githubusercontent.com/130130871/234751365-368c8994-2539-4a4f-a014-e7259959e37a.png)

**Comment by tonydavis629** [comment]
I want this feature so bad! I think the issue is VScode server is not compatible with Cursor.

**Comment by wjhrdy** [comment]
I know that the de-microsofted version of vscode vscodium doesn't work with devcontainers because it is a non-opensource extension. Cursor might have the same issue.

**Comment by truell20** [comment]
Devcontainers should work now! If you run into issues, please let us know.
