### ISSUE TITLE
0.2.2Windows版本都不能用，jupyter一直安装不上，右边Chat聊天框如果有代码出现都会自动折叠，代码都被文字提示遮挡了

### ISSUE THREAD

**Issue by Jupyter-X** [getcursor/cursor#494]
0.2.2Windows版本都不能用，jupyter一直安装不上，右边Chat聊天框如果有代码出现都会自动折叠，代码都被文字提示遮挡了，上新版本时候可以上心一点吗？还不如一开始的版本

**Comment by bruceye777** [comment]
只能用0.1.X的老版本了。

**Comment by danperks** [comment]
Hi, thanks for the feedback.

Juypter support has not yet been tested, but give it a go with the steps here and let us know how it goes: https://github.com/getcursor/cursor/issues/339#issuecomment-1502648982

**Comment by danperks** [comment]
It's been a while with no feedback, so I'll close for now
