### ISSUE TITLE
Does the Pro Edition use the interface of gpt4?

### ISSUE THREAD

**Issue by sfz009900** [getcursor/cursor#495]
Does the free version use gpt3.5, and the $20 Pro version use the gpt4 interface?

**Comment by beiming-org** [comment]
I have the same problem～

**Comment by danperks** [comment]
I don’t believe Cursor supports GPT-4 out the box, even with an API key, but this has been mentioned a few times.

Currently all your requests are done with GPT-3.5

 Closed in favour of #394
