### ISSUE TITLE
ctrl+k code generation BUG

### ISSUE THREAD

**Issue by sfz009900** [getcursor/cursor#496]
I use ctrl+k in test.vue to prompt it to create a new function, TestPost. It does create a TestPost function, but it outputs code that repeats the original file in addition to the new function

**Comment by sfz009900** [comment]
I continue to test it. ctrk+k on an empty line causes this problem, but if I select some of the original code and ctrl+k, I just add a new TestPost function

**Comment by danperks** [comment]
I’ve seen this a few times too actually

**Comment by seeflood** [comment]
+1
I can't use cursor now. It always repeats all the code

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Inline edits and generation have undergone significant updates since then. If this issue still persists for you, please open another issue!
