### ISSUE TITLE
如何修改活动栏的位置？

### ISSUE THREAD

**Issue by LuoSK** [getcursor/cursor#499]
如何修改活动栏的位置呢？活动栏的位置在顶部，宽度有限，使用起来很不方便，我希望能和vscode一样放置在左右两侧
![image](https://user-images.githubusercontent.com/35609202/231643250-a1ab450b-d161-4237-bb30-740c1cf7cc65.png)

**Comment by Mr-Nobody-li** [comment]
same question
and this not work
```
  "workbench.sideBar.location": "left",
```

**Comment by jakobFNF** [comment]
If you prefer the vertical activity bar, you can go to settings, set ‘workbench.activityBar.orientation’ to ‘vertical’, and restart Cursor. Then, you’ll see the vertical activity bar that you’re used to from VSC.

**Comment by Geoseanlee** [comment]
No
‘workbench.activityBar.orientation’ to ‘vertical’
does not work
the result of it is another horizontal vertical
![image](https://github.com/user-attachments/assets/060139b2-8444-4488-8f7c-fb08eea29edf)

**Comment by weiyanggod** [comment]
> 没有 'workbench.activityBar.orientation'到'vertical' 不起作用 它的结果是另一个水平垂直 ![图像](https://private-user-images.githubusercontent.com/141626855/402251653-060139b2-8444-4488-8f7c-fb08eea29edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NDMxODUsIm5iZiI6MTczNjg0Mjg4NSwicGF0aCI6Ii8xNDE2MjY4NTUvNDAyMjUxNjUzLTA2MDEzOWIyLTg0NDQtNDQ4OC04ZjdjLWZiMDhlZWEyOWVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNFQwODIxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGFiMTI1MmJhZmZmNTE4MjJjMjJmY2FiMDI2NzJkYTM2ZDA4ZDZlZWZkMmVkOWNmZGQ3NDQ3ZjdkZjA0YzcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DtPDHJ70Q8-FgT9awfEzEidSIPIMakk752Z0zH7Z3jI)
 I succeeded
![image](https://github.com/user-attachments/assets/4a4c4c8e-5626-4d1b-abb2-c0aa1728bd01)

**Comment by johnhom1024** [comment]
需要这两个设置配合：
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/34555a64-47f8-43f9-ab57-7b6d2c10b1a0" />

**Comment by ericpen12** [comment]
> No ‘workbench.activityBar.orientation’ to ‘vertical’ does not work the result of it is another horizontal vertical ![image](https://github.com/user-attachments/assets/060139b2-8444-4488-8f7c-fb08eea29edf)

It works, thank you

**Comment by jiangqiming** [comment]
> If you prefer the vertical activity bar, you can go to settings, set ‘workbench.activityBar.orientation’ to ‘vertical’, and restart Cursor. Then, you’ll see the vertical activity bar that you’re used to from VSC.

thank you, it works
