### ISSUE TITLE
修改setting.json成功保存并生效之后，下次打开某些项目会重置会默认值。

### ISSUE THREAD

**Issue by BraisedAlice404** [getcursor/cursor#500]
```
    "editor.fontFamily": "MonoLisa, Menlo, Monaco, 'Courier New', monospace, 'JetBrains Mono',霞鹜文楷",
    "workbench.statusBar.visible": true,
```
这两项保存修改之后，重新打开会变回
```
    "editor.fontFamily": "Consolas, 'JetBrains Mono', monospace",
    "workbench.statusBar.visible": false,
```
其他的设置保存正常

**Comment by Atomadeus** [comment]
我也碰到这种问题了，最明显的是"workbench.statusBar.visible"设置为true之后，下次重启又会变成false。

I am facing a similar issue, where the 'workbench.statusBar.visible' setting is reverting to false upon restarting after being set to true previously.

**Comment by danperks** [comment]
I believe someone else mentioned their font or language settings resetting every so often also, will try find that bug later.

**Comment by Atomadeus** [comment]
感谢你的回复，期待这个BUG能被尽快地修复。

@danperks Thanks for your reply. I look forward to this bug being fixed as soon as possible.

**Comment by danperks** [comment]
For reference, #449 duplicates this
