### ISSUE TITLE
升级 0.2 之后界面不好看，有点难用了。今天生成代码丢失，一个页面代码都要重写。还是原来的好用，聊天窗口友好

### ISSUE THREAD

**Issue by qilecms** [getcursor/cursor#502]
升级 0.2 之后界面不好看，有点难用了。今天生成代码丢失，一个页面代码都要重写。

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
