### ISSUE TITLE
how to use remote-ssh

### ISSUE THREAD

**Issue by Jeremy-J-J** [getcursor/cursor#503]
I have installed remote-SSH, but I do not know how to use ssh to remote connection, I can not find the remote connection button like vscode, how to use remote-SSH in cursor?
<img width="744" alt="image" src="https://user-images.githubusercontent.com/56668275/231718120-e706688e-221e-4ba5-aa80-06252623834e.png">

**Comment by Microbion** [comment]
等开发优化吧，现在还不好用呢

**Comment by Jeremy-J-J** [comment]
> 等开发优化吧，现在还不好用呢

嗯嗯

**Comment by danperks** [comment]
This is an ongoing bug, I’ll close this issue for #489

**Comment by diogobaltazar** [comment]
- **open ssh remote** extension download [here](https://open-vsx.org/extension/jeanp413/open-remote-ssh) `jeanp413.open-remote-ssh-0.0.48.vsix`
- Uninstall all **.\*remote.\*** extensions in the cursor marketplace (unsure it's needed)
- Drag and drop `jeanp413.open-remote-ssh-0.0.48.vsix` directly to cursor's marketplace
