### ISSUE TITLE
Edit and chat buttons misplacing

### ISSUE THREAD

**Issue by Mathu-lmn** [getcursor/cursor#504]
Hey, as you can see in this image, when selecting some code, the Chat and Edit buttons are placed under the path of the opened file

![image](https://user-images.githubusercontent.com/80094438/231748560-5afb0ea7-c15a-4a3f-afdf-109f84457f8d.png)

**Comment by danperks** [comment]
Feel like this might be a duplicate but can’t find it, so will leave this open for now!

**Comment by delayhsiao** [comment]
maybe you can type many empty line before your first line code 😂

**Comment by jakobFNF** [comment]
Looks like this has been fixed so I'll close this issue for now. If this issue still persists for you, please open another issue!

![image](https://github.com/getcursor/cursor/assets/74077124/1fc9c861-bb0d-4b19-b467-305feae93835)
