### ISSUE TITLE
能不能支持支付宝或者微信付款

### ISSUE THREAD

**Issue by sunjia44** [getcursor/cursor#505]
我们没有visa卡 没法付款啊 能不能支持支付宝或者微信支付？

**Comment by crazybber** [comment]
alipay or wechat-pay should be supported ,huge amount developers from china.

**Comment by crazybber** [comment]
alipay or wechat-pay should be supported ,huge amount developers from china.

**Comment by danperks** [comment]
Closed in favour of #390, please continue the discussion there, and if possible, in English so we don’t loose anything in translation.

**Comment by imarvinle** [comment]
wildcard 这个卡可以支付， 先从支付宝充值到虚拟卡里面，再用虚拟卡去订阅

https://chatgptzh.com.cn/go/wildcard/

**Comment by DIYer22** [comment]
招行的visa信用卡，默认不能正常支付，但如果用 google pay 绑定招行的卡，再用 google pay 支付就成功了（测试于 2025-02 ）

**Comment by tlouni** [comment]
> 招行的visa信用卡，默认不能正常支付，但如果用 google pay 绑定招行的卡，再用 google pay 支付就成功了（测试于 2025-02 ）

支付方式没看到 goolge pay呀
