### ISSUE TITLE
Edit 'New Chat' History Name

### ISSUE THREAD

**Issue by Chunyfong** [getcursor/cursor#508]
Is it possible to rename chat histories when there are multiple ongoing chats? It can be difficult to keep track of which chat is which, especially when there are multiple conversations happening simultaneously

![Chat_1](https://user-images.githubusercontent.com/50175081/231963387-f2a25056-0ad0-46be-bda0-bcd49b3637e2.PNG)

**Comment by truell20** [comment]
think this should now be fixed :)
