### ISSUE TITLE
Why name it as cursor, a terrible name for a software ?

### ISSUE THREAD

**Issue by sisrfeng** [getcursor/cursor#509]

**Comment by Microbion** [comment]
Because the icon is a cursor

**Comment by maimate-dev** [comment]
The name is not user friendly while searching the web, get a lot of links for cursors but not the cursor

**Comment by sisrfeng** [comment]
what about "AIde" ?   Meaning "a IDE", "AI IDE", and easy to speak out and recognize

**Comment by sisrfeng** [comment]
Again, I search in bing and get lots of irrelevant results. What a terrible production name!

**Comment by szamanr** [comment]
i second the suggestion for AIde, seems like a perfect name for this. take it while it's available. :wink:

**Comment by sisrfeng** [comment]
I've renamed it: 
![image](https://github.com/getcursor/cursor/assets/53520949/8445d7bb-9aa4-45fb-b39e-d3eb066d6f69)
😂

**Comment by abu-sufyan1** [comment]
It's just not renaming the project. They also have domain for documentation and whole lot of stuff.
https://www.cursor.so/

**Comment by sisrfeng** [comment]
With the name "cursor", it is hard to search the project's related content

**Comment by jakobFNF** [comment]
This project probably won't be renamed anytime soon, so I will close this issue for now. Thank you for your feedback!
