### ISSUE TITLE
Clarity on if the future of cursor is MIT open source? 

### ISSUE THREAD

**Issue by DesignsByVanessa** [getcursor/cursor#510]
Hi,

Congrats on supplanting VSCode for so many people so quickly. You've succeeded in weeks where many others have tried for years with a lot more budget and manpower. 

Have any decisions about the future of Cursor source code on github have been made?

The leap from `0.1` -> `0.2.2` is phenomenal in terms of UX. 

In trying to help diagnose bugs such as #489, the community has a limited ability to help(and submit a PR) because the public code is still on `.1`. It also prevents meaningful forks or fixing features on your own.

It's completely understandable(and fantastic) if:
- your pace is too fast and internal code quality too high to want PR's
- the license is changing past `0.1`
- OSS is a limited subset of Enterprise features
- the OSS version is going to stay a release behind the enterprise.

Any insight into what to expect moving forward would give the community better direction on how to interact with bugs and features. 

It would also go a long way to build loyalty and trust to understand what future limitations that OSS version will carry.

Congrats and hoping for the best future for Cursor.

**Comment by dergachoff** [comment]
Yes. We're getting updates without release notes, they have commit ids in About page, but apparently they're in different repository, so are useless. Editor is really nice (from the perspective of myself, not dev, but hobbyist, who is not yet commited to a ton of custom vscode workflows), but I would also love the team to be more clear about the future. Will we be able to use our own openai API or it will turn into this premium token thing?

**Comment by truell20** [comment]
Hey @DesignsByVanessa -- thanks for you kind words and all the feedback you given so far on Cursor! For now, the VSCodeium based versions of Cursor will be closed-source, though we'd be open to changing this in the future. I've moved the old code to a new repo and changed the READMEs to make this more clear.

**Comment by truell20** [comment]
> would also love the team to be more clear about the future. Will we be able to use our own openai API or it will turn into this premium token thing?

This is a pretty early product, so I want to be upfront: there's definitely *some* chance that this will change. Wouldn't want to make any hard promises I can't back up.

That said, our current strongly held stance is that anyone should be able to use their own API key as long as OpenAI models power the editor. This kind of gets at our business model for Cursor: like other great dev tools companies (Github, Jetbrains), we plan to make money off of enterprises, not individual developers. With this in mind, our plan is that individual developers should always be able to use the AI features at-cost.
