### ISSUE TITLE
之前网站说是用的gpt4 (Translation: The previous website said it was to use gpt4)

### ISSUE THREAD

**Issue by TankingCao** [getcursor/cursor#511]
第一次在这个网站下载的时候说是gpt4，怎么现在没了

**Comment by 245869874123ljh** [comment]
eee

**Comment by 245869874123ljh** [comment]
因为成本太高了啊

**Comment by siyang318** [comment]
![image](https://user-images.githubusercontent.com/15090752/232127654-18d988d4-5f13-42b5-a419-3ae97d996ef6.png)

**Comment by danperks** [comment]
As @245869874123ljh has said, GPT-4 is just too expensive to run during development, even for Pro users, but this is by no means set it stone.

To use GPT-4 right now, you should be able to use your own OpenAI key instead of a Cursor account.

Closing as answered to try keep the Issues clean :)

**Comment by TankingCao** [comment]
> 如前所述，GPT-4 在开发过程中运行成本太高，即使对于 Pro 用户也是如此，但这绝不是一成不变的。
> 
> 要立即使用 GPT-4，您应该能够使用自己的 OpenAI 密钥而不是 Cursor 帐户。
> 
> 按答案关闭以尝试保持问题清洁:)

我并没有贬低的意思哦，cursor还是很好用的，回复的速度快的惊人呢，一直在用，期待能做得越来越好
