### ISSUE TITLE
bug：无法问问题

### ISSUE THREAD

**Issue by fangxiao** [getcursor/cursor#512]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/582263/232066632-f1a4266c-b456-48fa-992c-cd42c19f13a0.png">
更新最新版本后，每次聊天都会出现这个

**Comment by delayhsiao** [comment]
卸载重装试试看

**Comment by danperks** [comment]
As a free tier user, you are not guaranteed server access if usage is high at the moment. To ensure you can use the Cursor server, you can pay for the Pro subscription, or add your own OpenAI key to bypass Cursor servers altogether.

Closing as answered :)
