### ISSUE TITLE
Translation: What's going on? After being forced to upgrade, it prompts networ error as soon as it is opened. I use Tokyo IP or Hong Kong IP to climb the wall like this.

### ISSUE THREAD

**Issue by tank3v3** [getcursor/cursor#513]
怎么回事啊，被强制升级后，一打开就提示 networ error。我用东京ip或者香港ip翻墙的都是这样。

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
