### ISSUE TITLE
Will you prevent things like CursorCode and CodeCursor?

### ISSUE THREAD

**Issue by sisrfeng** [getcursor/cursor#518]
https://github.com/Helixform/CodeCursor
https://github.com/Meteo-Pig/CursorCode

For me, sticking with vscode is better than learning a new editor, so I prefer vscode extension, but I'm afraid that they will be prevented.

**Comment by danperks** [comment]
As mentioned in a few other Issues (#233 #18 and a few others), Cursor is intended to be a standalone product, not an API or an extension for VSCode itself. I don't believe either extension supports the log in system for the API, so will likely stop working sooner or later, if they haven't already. 

The latest version of Cursor is based on the same codebase as VSCode, so is very similar to use. As Cursor is still very much in development, there are of course bugs to iron out and new features to add, but a lot of the features you know and love about VSCode should work the same in Cursor, including many of the extensions!

If there's something specific you'd like to see in Cursor, do let the team know, as it's likely someone else wants the same thing!

**Comment by riggy2013** [comment]
I found current Cursor(0.2.7) missed features like:

Multiple python interpretators.
python testing.

**Comment by jakobFNF** [comment]
Cursor is intended to be a standalone product and will frequently update its VSCode version to make the experience as close as possible to VSCode. I will close this issue for now due to inactivity.
