### ISSUE TITLE
Cursor version in this repo vs version on Cursor.so

### ISSUE THREAD

**Issue by Inoria-cn** [getcursor/cursor#519]
I have not found any documentation to imply this repository, and cannot found any explanation of this. Plz tell us the difference, shall we use this local deploy version or the download version?

**Comment by danperks** [comment]
The latest version of code published here is for the v0.1.X release of Cursor, using an IDE made from scratch.

v0.2.X is based on the same codebase as VSCode, and is has a lot more of the core features of an IDE out the box. However, the code for this version is not yet (and may never be) publicly available. 

As the v0.1.X APIs are seemingly been deprecated for the newer version, the code in this repository is just a timestamp of the older version. Keep an eye for more info on if the v0.2.X code will be released!

**Comment by truell20** [comment]
Thanks for flagging this confusion! I made the README much more clear that this is an issues-only repo. I moved the old code for our 0.1.x branch into a new repo and added a note about this in the README.
