### ISSUE TITLE
[v0.1.x] Errors with code generation

### ISSUE THREAD

**Issue by wangyang135** [getcursor/cursor#521]
![image](https://user-images.githubusercontent.com/5113303/232665238-1bceb24e-10c3-4e01-acd3-92b69d35603a.png)

**Comment by zzall** [comment]
你这个怎么打开控制台的？

**Comment by sendking** [comment]
这个会有泄露代码的风险吗？

**Comment by danperks** [comment]
Hey, looks like you are trying to use an old version, which is likely no longer supported in the back end servers.
This repository currently holds v0.1.x code, which has since been updated to v0.2.x.
To use this, download the latest version from https://cursor.so.

**Comment by danperks** [comment]
Closing as this is an old and unsupported version.
The latest version can be downloaded from https://cursor.com
