### ISSUE TITLE
fail to upgrade after successful payment

### ISSUE THREAD

**Issue by flyyyy45** [getcursor/cursor#522]
I want to upgrade, but after paying with Visa, it still shows the free version and the upgrade fails. Checking my billing statement shows that the payment was successful. What should I do and how can I contact customer service to resolve this issue?

**Comment by danperks** [comment]
@truell20 In need of a Dev to help here

**Comment by truell20** [comment]
Please reach out to admin@cursor.so! We can refund you for the trouble and help you get access to your pro account.
