### ISSUE TITLE
Support for Chinese language within the UI

### ISSUE THREAD

**Issue by lhw828** [getcursor/cursor#523]
什么时候能出中文界面？

**Comment by AutumnFrosti** [comment]
Have you not used vscode before? This is the same as the multi-language interface settings in vscode, and since you're already writing code, why not learn English?

**Comment by CharlesTHN** [comment]
和VSCode一样，装个中文包扩展不就行了

**Comment by Mrliao0120** [comment]
When to remove the Great Wall Firewall？

**Comment by Mrliao0120** [comment]
**who  are you？**

**Comment by 1715260699** [comment]
yes！

**Comment by TankingCao** [comment]
其实在扩展商店可以下载中文的插件，搜索Chinese就可以找到

**Comment by mxtao1234** [comment]
这个可以装vs里面的任何插件包括中文插件

**Comment by danperks** [comment]
Sounds like this has been solved in later versions, and should match the behaviour of VSCode in this sense. Raise a new issue if you still have any issues :)
