### ISSUE TITLE
Auth0 Account Verification Failing

### ISSUE THREAD

**Issue by flyyyy45** [getcursor/cursor#524]
when i try to reply, it shows

Address not found
--
Your message wasn't delivered to no-reply@auth0user.net because the address couldn't be found, or is unable to receive mail.

so I can't verify my account yet

**Comment by LailaiMaster** [comment]
+1

**Comment by truell20** [comment]
What email provider do you use? Gmail? qq.com?

**Comment by flyyyy45** [comment]
I use both of them, and I made the payment using Gmail with the email
address ***@***.***, while for QQ.com, I used ***@***.***
I have provided you with proof of successful payment. Please refund the
amount to my Visa card as soon as possible and reply to me promptly. Thank
you.

**Comment by truell20** [comment]
Happy to refund! Believe you reached out over email and we fixed this there.

**Comment by truell20** [comment]
Could you send a screenshot of the verification email you got from auth0? I'm surprised they didn't just have you verify with a verification link.

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!
