### ISSUE TITLE
Change Cursor's desktop icon (to avoid confusion with other apps)

### ISSUE THREAD

**Issue by politicalcode** [getcursor/cursor#528]
Hello, can developers consider modifying Cursor's desktop icon ICON? For example, directly using Cursor as ICON would be great, as current icons, such as map navigation, are easily confused.

**Comment by truell20** [comment]
Hey! Which map navigation app are you thinking of?

**Comment by Alex-94** [comment]
![image](https://user-images.githubusercontent.com/30484546/233330152-c48aaf1f-2e7f-4fbd-b355-7536962fdebf.png)

**Comment by truell20** [comment]
Oh wow that screenshot is super helpful. Will plan to change this.

**Comment by jakobFNF** [comment]
The cursor's desktop icon has slightly changed since then, but it's still a cursor. Your situation seems to be unusually unlucky. I will close this issue for now due to inactivity.
