### ISSUE TITLE
I have paid, but I cannot use 付了20美元却用不了gpt-4,骗钱啊

### ISSUE THREAD

**Issue by xjqx2z** [getcursor/cursor#533]
付了20美元，升级了，提第一个问题弹窗提示我没有gpt4的额度了，让我升级

**Comment by xjqx2z** [comment]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/9669854/233289127-6d87b619-54c3-469a-8372-44ae6dc0b857.png">
说我的额度已经用完了，泥马我刚下载安装付完钱，第一个问题

**Comment by xjqx2z** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/9669854/233289407-a69ce218-1812-43ae-9108-75e0e7fc67a3.png">
还找不到地方退款

**Comment by xjqx2z** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/9669854/233292284-dbb0501a-5ff3-42e3-809b-60036ef5dadd.png">

**Comment by Microbion** [comment]
升级到pro也只是能用3.5吧。要用gpt4得在openAI充钱，然后用apikey(我的理解)。但是gpt3.5你应该是没有次数限制了啊

**Comment by xjqx2z** [comment]
> 升级到pro也只是能用3.5吧。要用gpt4得在openAI充钱，然后用apikey(我的理解)。但是gpt3.5你应该是没有次数限制了啊

20美元交了，3.5依然只能用100次/月，这正常？

**Comment by jiangjun0105** [comment]
诶？哪里看的pro可以用gpt4啊？我看只有说次数限制变了。

> Cursor Pro Billed monthly based on usage
> See details
> First 150,000 used $0.00 per unit
> 150,001+ used $0.00006 per unit

**Comment by jiangjun0105** [comment]
但是没准你可以联系一下他们退款，如果你买pro是为了用gpt4的话

**Comment by yunhaizhu** [comment]
Pro
$20
/month
150K free GPT-4 tokens, then
$0.06 / 1K GPT-4 tokens
Access to all features
Unlimited GPT-3.5 prompts
Usage-based GPT-4 access

it seems GTP3.5 is unlimited to use, is it correct?

**Comment by flh155** [comment]
重新打开一下软件重新登录一下试试呢？支付了可能还没有刷新，我的刷新了一下3.5就没有限制了

**Comment by truell20** [comment]
Hey! Sorry for missing this thread. 

An hour or so after we launched GPT-4 support, we had a bug that prevented people from using it. It was patched about an hour later.

Feel free to email admin@cursor.so if you'd like a refund or if you need help accessing GPT-4 or your pro account.

**Comment by truell20** [comment]
> 诶？哪里看的pro可以用gpt4啊？我看只有说次数限制变了。

To switch between gpt-4 and gpt-3.5 in pro, just hit the settings gear on the top right of the app and then go to the model dropdown.

**Comment by truell20** [comment]
Closing for now because I think this is addressed, but please reopen an issue or email admin@cursor.so if you have any issues.

**Comment by null-man** [comment]
> 付了20美元，升级了，提第一个问题弹窗提示我没有gpt4的额度了，让我升级

我也是，能退吗

**Comment by xingdem108** [comment]
一定要点那个logout 不然连接的还是旧账号
