### ISSUE TITLE
repeated answer

### ISSUE THREAD

**Issue by TankingCao** [getcursor/cursor#534]
He would always answer the previous question (and the current one, of course), but I just wanted him to answer the current one.

**Comment by danperks** [comment]
Hey, are you referring to the answers given by the AI in the chat window? If you don't want it to take into account your previous chat history when talking with it, you can start a new chat with the plus symbol, and it will start a new conversation.

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!
