### ISSUE TITLE
翻譯錯誤

### ISSUE THREAD

**Issue by sao-coding** [getcursor/cursor#535]
Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/58339015/233408411-e0a5d9d3-e679-40db-9fc2-713fad39d1b4.png)
![image](https://user-images.githubusercontent.com/58339015/233408647-9864ccf6-bc4e-44c5-952a-f31eb7342d78.png)
應該翻譯叫 新增 AI 專案

Chinese (Traditional) Language Pack for Visual Studio Code
Extension version: 1.76.0
VS Code version: Cursor 0.2.7 (f9c29d73ab9f4d88cff4de986247553b5d60e71e, 2023-04-20T01:51:46.916Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (23.88GB free)|
|Process Argv|C:\\Users\\jeter\\Desktop\\YTCSS|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by vicacheung** [comment]
翻譯問題應該發Extension那邊吧？
[Issues·microsoft/vscode-loc](https://github.com/microsoft/vscode-loc/issues)

**Comment by sao-coding** [comment]
可是 VScode 本身並沒有這個按鈕吧？
所以他沒辦法翻譯？

**Comment by vicacheung** [comment]
雖說是這樣，不過Cursor這邊完全沒有翻譯相關的內容，更不相干~~相比來說還是 Language Pack那邊更貼合實際情況。

**Comment by danperks** [comment]
Assuming this is solved in newer versions, but feel free to raise an issue if there are translation problems in the latest versions that are unique to Cursor (e.g. not in VSCode).
