### ISSUE TITLE
If I purchase a $20 upgrade, can I directly use GPT-4 or do I need to buy a separate OpenAI key?

### ISSUE THREAD

**Issue by jian1929** [getcursor/cursor#536]
If I purchase a $20 upgrade, can I directly use GPT-4 or do I need to buy a separate OpenAI key?

**Comment by truell20** [comment]
No need to input an OpenAI API key if you upgrade to pro. Alternatively, instead of upgrading to pro, you're welcome to use an OpenAI key to use GPT-4 in the editor.
