### ISSUE TITLE
Importing custom languages to Cursor

### ISSUE THREAD

**Issue by zengxiaowengit** [getcursor/cursor#537]
now i use a low-code language such as [magic-api](https://www.ssssssss.org/magic-api/pages/module/db/#select), how can i write a extension to intergrate into cursor OR open AI ? 

thanx.

:）

**Comment by danperks** [comment]
Hi, I like the idea. As OpenAI's models power the AI, if the model isn't trained on the language, it won't be available out the box by the AI. However, I'll leave it as a possible future feature as it is plausible to import documentation files that Cursor can learn from.

**Comment by jakobFNF** [comment]
Cursor has the custom documentation functionality now (type `@Docs` in the chat). Thank you for your suggestion!
