### ISSUE TITLE
Mac下载客户端安装之后找不到安装到哪了

### ISSUE THREAD

**Issue by wuzhipeng1991** [getcursor/cursor#54]
Mac下载客户端安装之后找不到安装到哪了

**Comment by tianbowen14300** [comment]
我点的download for mac 下载下来的是exe

**Comment by Ellioben** [comment]
> Mac下载客户端安装之后找不到安装到哪了

解压后，就可有看到.app文件了。仔细看看

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
