### ISSUE TITLE
Update README to make it more clear that current release is v0.2.x, and this repo's code (v0.1.x) is no longer used

### ISSUE THREAD

**Issue by cointastical** [getcursor/cursor#541]
A comment from Issue #519:

"the code in this repository is just a timestamp of the older version."

Nowhere in the README does it say that the current release from Cursor.so is v0.2.x and the v0.1.x code in this repo is no longer used.

And, while updating that ... another item.  Is this repo still the right place to report new issues with v0.2.x? (It's especially confusing since the Help -> Report  Issue option appears it will submit an Item on the Microsoft/VSCode repo).

**Comment by truell20** [comment]
Sorry about this! I moved the old code to another repo and made the README much more clear. This is the right place to file 0.2.x issues. Thanks for flagging this.
