### ISSUE TITLE
How to cancel the text that is being generated?

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [getcursor/cursor#543]
Often the AI gets it wrong. I need to wait till it completes to undo the code. Is there a way to cancel the text that is being generated? 

By the way, I am curious to know, if you people are using Cursor for the development of Cursor. I mean, do you write Cursor code in Cursor? If so, it would be nice, if you share some of the best practices to get best out of Cursor.

**Comment by stephsix** [comment]
You could use ` CTRL + Backspace` to cancel code generations.

**Comment by danperks** [comment]
As @stephsix mentioned, those key combinations should cancel the generation for you. Will close to keep things neat, but you have any more queries, feel free to comment again :)
