### ISSUE TITLE
GitHub Copilot was deleted, then cannot find in extensions market

### ISSUE THREAD

**Issue by qifengwangye** [getcursor/cursor#545]
GitHub Copilot was deleted, then cannot find in extensions market

**Comment by CiaoHe** [comment]
same issue

**Comment by meguoe** [comment]
https://marketplace.visualstudio.com/items?itemName=GitHub.copilot  
Download and drag and drop to cursor

**Comment by CiaoHe** [comment]
> https://marketplace.visualstudio.com/items?itemName=GitHub.copilot Download and drag and drop to cursor

I've downloaded the `GitHub.copilot-1.84.51.vsix` from the above link. What do you mean "drag and drop to cursor"? 
I'm using MacOS, where should I put the extension to? Thx a lot

**Comment by meguoe** [comment]
cursor window

**Comment by truell20** [comment]
Try this guide: https://www.cursor.so/how-to-install-extension
