### ISSUE TITLE
Press the "ESC" key during chat, and the conversation history will be cleared

### ISSUE THREAD

**Issue by YidaHu** [getcursor/cursor#55]
## What happened?

During a chat, if you accidentally click the ESC key, the CHAT window will be closed, and then the conversation history will be cleared when you reopen it

## What did you expect to happen?

Close the Chat window, save the conversation history, and you can re-enter the conversation scene.
Because the entire conversation process is very valuable, it can be time-consuming to repeat the conversation.

**Comment by truell20** [comment]
Thanks for reporting this! Agree we should use something other than escape for closing chat. 

In the meantime, try command shift p to open the command palette and then search for "open chat history."

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
