### ISSUE TITLE
Wrong link to anysphere/control in License info?

### ISSUE THREAD

**Issue by PeterDaveHello** [getcursor/cursor#551]
Not sure if this is based on https://github.com/anysphere/control or something like that.

If you click the menu `Help` > `View License`:

![image](https://user-images.githubusercontent.com/3691490/234079748-5eb1b524-fa75-433c-bb80-399062b5db21.png)

It links to https://github.com/anysphere/control/license.txt?lang=en

Which is:

> Not Found

**Comment by danperks** [comment]
Does seem to be a non-existent or private repository, thanks for flagging it!

**Comment by PeterDaveHello** [comment]
Did you guys originally fork cursor from some projects like that 🤣

**Comment by jakobFNF** [comment]
"View License" now links to https://cursor.sh/license.txt?lang=en which is found. Thank you for your bug report!

**Comment by RokeJulianLockhart** [comment]
@jakobFNF, is a ToS a license, per se? [^1]

[^1]: [`issues/846#issuecomment-3467683915`](https://github.com/cursor/cursor/issues/846#issuecomment-3467683915)
