### ISSUE TITLE
GPT version

### ISSUE THREAD

**Issue by Jhangsy** [getcursor/cursor#553]
I have subscribed and I found following statements:

"gpt-3.5-turbo
You've used 41K tokens of this model. You have no monthly quota.
gpt-4
You've used no tokens out of your 150K monthly quota."

How can I check which version GPT  is been using?

**Comment by flh155** [comment]
open setting，under the “OpenAI Setting”， there is a “Model”，you can choose 'gpt-3.5-turbo' or 'gpt-4'

**Comment by truell20** [comment]
> open software's setting，under the “OpenAI Setting”， there is a “Model”，you can choose 'gpt-3.5-turbo' or 'gpt-4'

Yep! Try clicking on the settings gear in the top right
