### ISSUE TITLE
Inline AI Bug Detection/Suggestions

### ISSUE THREAD

**Issue by dallenpyrah** [getcursor/cursor#554]
For this issue I am thinking we can add in functionality that will underline a piece of code if the AI model decides that it could possibly create bugs and then offer to fix it. We can think of this how Jetbrain IDEs handle things when the namespace is off and it offers to fix it for you.

**Comment by dallenpyrah** [comment]
Adding in that you could iterate on this, it could fix that specific issue but then down the line we can alter it to fix all issues in the project where it matches the same criteria.

**Comment by jakobFNF** [comment]
Cursor has the "@Lint errors" command in chat now, which tries to find bugs in the current file. In the future, we will automate this process further.
