### ISSUE TITLE
MAC 使用openAI-key 无效

### ISSUE THREAD

**Issue by vaevas** [getcursor/cursor#555]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/51769860/234453079-53fef559-0b17-4bd8-9e4b-021ddecb2ac3.png">
每次提问都没有对应的返回
<img width="572" alt="image" src="https://user-images.githubusercontent.com/51769860/234453170-021c8487-8ba7-44a1-9501-be8cb047d575.png">
填写了自己对用的openai-key

**Comment by UCanSeeeeee** [comment]
> Accessing the OpenAI API interface in China requires the use of a VPN

没用哦，哪里的vpn都不行

**Comment by vaevas** [comment]
> 

没用开着vpn也没用

**Comment by zzall** [comment]
退出账号重新登陆就可以了

**Comment by turtleeeeee** [comment]
开了VPN还得确保cursor也挂上了才行，像clash之类的软件只会让浏览器翻，cursor是没翻的。补充用一下proxifier

**Comment by UCanSeeeeee** [comment]
> 开了VPN还得确保cursor也挂上了才行，像clash之类的软件只会让浏览器翻，cursor是没翻的。补充用一下proxifier

朋友，你说的是正确的，我已经解决了这个问题。thx！
