### ISSUE TITLE
chat always repeat  

### ISSUE THREAD

**Issue by shouyuxinyan** [getcursor/cursor#557]
while i start a new chat or continue a chat insider cursor, the last N answer are repeated again and again.    However, the answer maybe days before,  i can not clear them, it is so borning.  I think it is better for one question an answer.

**Comment by danperks** [comment]
When you start a new chat, the previous chat messages should not be there without going via the chat history menu. Can you explain what happens when you start a new chat and what you expect to happen?

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!
