### ISSUE TITLE
Why not develop based on the latest version of VSCodium?

### ISSUE THREAD

**Issue by meguoe** [getcursor/cursor#559]
Why not develop based on the latest version of VSCodium?

**Comment by truell20** [comment]
We'll periodically merge in the upstream changes from VSCode/VSCodeium. What are you missing in our current version that exists in the latest version of VSCodeium?

**Comment by danperks** [comment]
@stefanolsenn This has been discussed many times, but the decision was made not to go down the route of a VSCode plugin as the Cursor team have plans for the IDE that a VSCode plugin would not be the best route to go down. The idea is, in the future, that the AI is increasingly integrated into every feature of the IDE, and a plugin wouldn't be able to do this very easily. 

See more of this discussion at #492 #18 #465

**Comment by danperks** [comment]
As this issue has been answered, in that the Cursor team make period updates to the underlying VSCodium version, I'll close this for now. If there are any features missing in later VSCodium versions you want to see, feel free to comment here or open a new issue for them!
