### ISSUE TITLE
Clarification on Cursor AI limitations (100/month usage limit)

### ISSUE THREAD

**Issue by FangAk** [getcursor/cursor#562]
What happens when you use it 100 times a month？

**Comment by 20000627** [comment]
I have also used up the 100 times quota, and now it seems that I should either add openai api or recharge to pro version, but I don't know when the 100 times per month started to count.

**Comment by Alpha1970** [comment]
I also want to know when the 100 times per month started to count.

**Comment by jakobFNF** [comment]
The quotas should start when the account is created (for free users) or when a subscription is purchased (for paid users). If you have any other questions, please refer to the pricing page.
=> https://cursor.sh/pricing
