### ISSUE TITLE
If you use CTRL+K or other

### ISSUE THREAD

**Issue by Bizarrus** [getcursor/cursor#563]
Type: <b>Bug</b>

If you try to say to the AI "Please update the code with XYZ", the file will not updated. On Chat, the output is there and on Editor, the Code will only appended

VS Code version: Cursor 0.2.8 (d6a5ac3d20b79bca0b2a8540cd514a1744ceb9ce, 2023-04-30T03:21:35.654Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.34GB (22.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by danperks** [comment]
Using CTRL+K should edit the code but will not produce a chat output.
Alternatively, using CTRL+L should let you chat about the code, but will never edit your code automatically.

Is this not what you are seeing?

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity.
