### ISSUE TITLE
Chat no longer works, code generation works fine.

### ISSUE THREAD

**Issue by eldare** [getcursor/cursor#564]
For some reason Chat stopped working after recent login.
There is no way to write in the Chat, and cmd+L has no effect.

<img width="352" alt="Screenshot 2023-05-03 at 0 25 03" src="https://user-images.githubusercontent.com/40336237/235789608-fb88bb97-e1c4-4766-82ae-55e296efde65.png">

Cursor about:
```
Version: 0.2.8
Commit: d6a5ac3d20b79bca0b2a8540cd514a1744ceb9ce
Date: 2023-04-30T03:21:35.654Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
```

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
