### ISSUE TITLE
Increase GPT-4 Token Quota (potentially via additional purchase?)

### ISSUE THREAD

**Issue by ruojingO** [getcursor/cursor#566]
hi. cursor team ,very thanksgiving your service . 
   I'm a pro user (i haven't openAI key ) , default use the gpt4 model ,but now cursor report the prompt:
"
you have reached the maximum nuber of tokens for gpt-4
to increase your limites ,pls press here 
"
when i press here ,display 
"
gpt-4
You've used no tokens out of your 150K monthly quota.
gpt-3.5-turbo
You've used 20K tokens of this model. You have no monthly quota.
"
I can accept increase payment ,but how to do this ? 
thanks .
   --China user  ruoJing .

**Comment by danperks** [comment]
Currently, the quota for GPT-4 tokens is set in stone, with no way to increase it. I could see the idea of being able to purchase additional tokens being something that could come in the future, but there's, unfortunately, no solution for now. I'll leave this issue open for future discussions.

**Comment by jakobFNF** [comment]
Looks like [there will be a new plan soon](https://forum.cursor.sh/t/gpt4-when-limits-are-used-up/1095/2) that offers the option to purchase additional fast requests, so I will close this issue for now. Thank you for your suggestion!

![image](https://github.com/getcursor/cursor/assets/74077124/afca721d-d7d2-402c-b70d-dbf3489f263a)
