### ISSUE TITLE
Without the pro plan, you do not have access to this feature/model.

### ISSUE THREAD

**Issue by antungchen** [getcursor/cursor#567]
After updating to the new version, the cursor won't let me use my own API key to access the GPT-4 model. Just a few minutes ago, I was able to use my API to access the GPT-4 model, but after updating, it no longer allows me to use it.
![20230505133635](https://user-images.githubusercontent.com/21006766/236372998-c368ea72-c79f-4ebc-b0ec-1c2eeb19e9db.png)

**Comment by danperks** [comment]
Will need a dev to see if this is a bug behind the scenes.

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!
