### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by qubitpercy** [getcursor/cursor#568]
though appearing information "You may now proceed back to Cursor", when back to Cursor App on windows, i'm not in the logged in status.
![image](https://user-images.githubusercontent.com/68458392/236389638-25d0ca5c-1e44-4a18-b3da-a1d8237175fb.png)

**Comment by liulian701** [comment]
I meet the same situation

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!

**Comment by musilimu** [comment]
I have this issue
