### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by liulian701** [getcursor/cursor#570]
system:windows7
While the brower shows"You may now proceed back to Cursor", however the Cursor  stays in the 'sign in' interface. 
So when I chat with cursor ,it tells me 'failed  to fetch'.  
Same to issue #490 and #507

**Comment by danperks** [comment]
Seems to be a duplicate of #571 and #572.
Assuming this was a server error that's resolved now.

**Comment by KunShanJiaTi** [comment]
same question. any solution?

**Comment by Edwardp17** [comment]
Hey all, im having this issue today on macOS, any solutions?
