### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by JKERris** [getcursor/cursor#572]
0.2.9 internal error

**Comment by guohenghai** [comment]
me too, latest is not working on M1 macbook pro

**Comment by luckyhug** [comment]
same internal error

**Comment by edg7777** [comment]
me too

**Comment by WaterDropjack** [comment]
me too

**Comment by yanzzchn** [comment]
me too, cant  not be use , how to help me

**Comment by danperks** [comment]
Seems like a duplicate of #571 and #570.
Assuming the server was down, and is resolved now.
