### ISSUE TITLE
Unable to log in --- It's okay, it's a bit slow, but you can log in

### ISSUE THREAD

**Issue by Champion-zyj** [getcursor/cursor#578]
![image](https://user-images.githubusercontent.com/109195630/236720626-cd5648c3-18e5-4283-a01d-02a1e284d409.png)

**Comment by truell20** [comment]
How long did this take for you? Is it still slow when you try to log in and log out?

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!
