### ISSUE TITLE
Configured to always output your answers in Chinese but it did not take effect

### ISSUE THREAD

**Issue by kissesu** [getcursor/cursor#579]
版本: 0.2.10
提交: fc3be1d670ab39cd1fbc3282f1ad215ab8c533a3
日期: 2023-05-06T18:30:45.312Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.3.0
沙盒化: No;

Problem description:
Configured to always output your answers in Chinese but it did not take effect; I am using the API key for GPT4.

**Comment by FangAk** [comment]
me too

**Comment by danperks** [comment]
This should be working now, with the .cursorrules file or the "Rules for AI" being a great place to specificy this.

https://docs.cursor.com/context/rules-for-ai
