### ISSUE TITLE
Cursor detected as a virus

### ISSUE THREAD

**Issue by TugdualDek** [getcursor/cursor#580]
## Description:

After the latest auto update of Cursor IDE, Bitdefender is blocking the process and indicating that it has detected Cursor as a virus. This is causing major inconvenience for me, and possibly other users.

## Expected:

Cursor IDE should function normally after the auto update, without any virus warnings or blocks from Bitdefender.

## Actually:

Bitdefender is blocking Cursor IDE and indicating that it has detected the software as a virus.

## Additional Information:

The version of Cursor IDE being used is 0.2.10. Please investigate and provide a solution as soon as possible.

### Report from Bitdefender :

![image](https://user-images.githubusercontent.com/35851118/236802487-a23dfe69-4494-45c5-a5fa-0546f3e93bf0.png)

Feature:
Advanced Threat Defense

You need to restart your device to complete the cleanup process.
Bitdefender has detected a potentially malicious behavior and has blocked all involved applications.
Detection ID: SuspiciousBehavior.545D43CC103F10B7

Infected file detected

Feature:
Antivirus

The item C:\Users\{USER}\AppData\Roaming\Cursor\Crashpad\settings.dat was restored at the user's request.Feature:
Feature:
Antivirus

The item C:\Users\{USER}AppData\Roaming\Cursor\Crashpad\settings.dat was detected as a malicious file

**Comment by truell20** [comment]
Thanks for reporting this! I will contact Bitdefender about this. Just to be sure, what antivirus software do you use @yinjg1997 @YangYidaaa?

**Comment by YangYidaaa** [comment]
> 

Thanks for your attention. My antivirus software is Lenovo Anti-Virus powered by Huorong Security...
----------------------------------------------------------------------------------------------------------------------------------------- 
But now I had a new problem: when Cursor modified the code to suit my further needs, it would iterate and rewrite over and over again  my previous code as it generated the results. My Cursor version is 0.2.11.
 Thanks in advance!

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!

**Comment by The-Lone-Druid** [comment]
I'm facing this issue now, I'm using an antivirus software "Norton", Even if I disable my antivirus software, once Cursor is started my PC freezes, and OfCourse it's a windows machine.

![Image](https://github.com/user-attachments/assets/93b710f6-ac5c-4363-a814-d4f5ea48dbde)

**Comment by rturluck** [comment]
> I'm facing this issue now, I'm using an antivirus software "Norton", Even if I disable my antivirus software, once Cursor is started my PC freezes, and OfCourse it's a windows machine.
> 
> ![Image](https://github.com/user-attachments/assets/93b710f6-ac5c-4363-a814-d4f5ea48dbde)

Avast is flagging it as well 

![Image](https://github.com/user-attachments/assets/f28801b6-dd2c-44f5-b6c1-e65b2f49edd4)
