### ISSUE TITLE
does cursor support open custom api keys?

### ISSUE THREAD

**Issue by williammcdowell2** [getcursor/cursor#581]
im not currently not in the mood to pay for an offical openai API key so does cursor support custom  keys? or no?

**Comment by danperks** [comment]
Cursor does support OpenAI API keys, which you enter when setting up the software for the first time!
Note it does not support Azure keys, only OpenAI's own ones!

**Comment by cesdperez** [comment]
You can setup the API key at any moment by clicking the ⚙️ in the top right

**Comment by matbee-eth** [comment]
> You can setup the API key at any moment by clicking the ⚙️ in the top right

the top right of what?

**Comment by rajhlinux** [comment]
Doe Cursor provide their own API keys?

I'm trying to run Cursor AI on FreeBSD, maybe possibly on a VScode custom extension.
