### ISSUE TITLE
Infected application

### ISSUE THREAD

**Issue by tarzinio** [getcursor/cursor#582]
Your application, or rather the files it generates, are detected as infected :)
Whatever it saves, the antivirus detects the contamination.
![image](https://user-images.githubusercontent.com/29274594/236903042-d8b5c501-07f4-4315-9176-78e2beb1a1f0.png)

**Comment by truell20** [comment]
Thanks for reporting this! Could you send me a link to the file it generated at michael@cursor.so

**Comment by truell20** [comment]
Just checking here!

**Comment by jakobFNF** [comment]
I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!
