### ISSUE TITLE
Changing the account of GitHub Copilot extension

### ISSUE THREAD

**Issue by coder-czw** [getcursor/cursor#583]
There no github account entrance like vscode, I have no idea to change my github account for copilot.

**Comment by truell20** [comment]
What do you normally do with VSCode?

Try disabling and then enabling?

**Comment by coder-czw** [comment]
> What do you normally do with VSCode?
> 
> Try disabling and then enabling?

already disabling and enabling, I even try to uninstall and re-install, it still read my old github account

**Comment by trend-venkatesh-vuppala** [comment]
This is what worked for me:

1. Logout of cursor account
2. Uninstall Cursor application
3. Re-nstall Cursor
4. Reinstall Copilot extension
5. Sign-in with new account

Obviously this is not ideal, need account management on Cursor asap.

**Comment by JacobFV** [comment]
Manually setting the copilot auth token in settings.json didn't help either

**Comment by JacobFV** [comment]
Did the full process,

1. uninstall GH copilot extension
2. log out of cursor account in IDE
3. uninstall AppImage
4. download new nightly AppImage
5. integrate and run
6. log back into cursor account inside IDE
7. reinstall GH copilot extension

Still same error

![Screenshot from 2023-07-20 12-01-01](https://github.com/getcursor/cursor/assets/40343913/ee7516a8-270e-4164-a056-471eaa02c550)

**Comment by JacobFV** [comment]
During the above process, I also noticed that my openai api key was saved. This lead me to believe there must be a config file outside the AppImage that OAI, auth, and gh account info is being saved in. Looking into it

**Comment by JacobFV** [comment]
Fixed it, at least for cursor-nightly 2307198uj97n31o on Ubuntu 22.04.

So I found an sqlite database (?) saved at `~/.config/Cursor Nightly/User/globalStorage/state.vscdb`. I opened the database with DB Browser for SQLite and browsed the ItemTable  for any KV pairs that might have something to do with copilot. Then I set a couple of the fields to NULL. I don't remember all of them, but I think `github:copilot-github-user:email` was  the critical point. So anyway, after setting that key and its value to null along with a couple other pairs that included the word github in their key, I saved the db and relaunched cursor. Copilot asked me to sign in again. Problem solved

**Comment by huangmengzhi** [comment]
> Fixed it, at least for cursor-nightly 2307198uj97n31o on Ubuntu 22.04.
> 
> So I found an sqlite database (?) saved at `~/.config/Cursor Nightly/User/globalStorage/state.vscdb`. I opened the database with DB Browser for SQLite and browsed the ItemTable for any KV pairs that might have something to do with copilot. Then I set a couple of the fields to NULL. I don't remember all of them, but I think `github:copilot-github-user:email` was the critical point. So anyway, after setting that key and its value to null along with a couple other pairs that included the word github in their key, I saved the db and relaunched cursor. Copilot asked me to sign in again. Problem solved

how to find this db file in Macos

**Comment by JacobFV** [comment]
I think it's still an election like app so you might be able to extract and repeat the above. Haven't tried tho

On Aug 30, 2023, at 23:19, Casey Hicks ***@***.***> wrote:

﻿

Fixed it, at least for cursor-nightly 2307198uj97n31o on Ubuntu 22.04.

So I found an sqlite database (?) saved at ~/.config/Cursor Nightly/User/globalStorage/state.vscdb. I opened the database with DB Browser for SQLite and browsed the ItemTable for any KV pairs that might have something to do with copilot. Then I set a couple of the fields to NULL. I don't remember all of them, but I think github:copilot-github-user:email was the critical point. So anyway, after setting that key and its value to null along with a couple other pairs that included the word github in their key, I saved the db and relaunched cursor. Copilot asked me to sign in again. Problem solved

how to find this db file in Macos

**Comment by JacobFV** [comment]
> > Fixed it, at least for cursor-nightly 2307198uj97n31o on Ubuntu 22.04.
> 
> > 
> 
> > So I found an sqlite database (?) saved at `~/.config/Cursor Nightly/User/globalStorage/state.vscdb`. I opened the database with DB Browser for SQLite and browsed the ItemTable for any KV pairs that might have something to do with copilot. Then I set a couple of the fields to NULL. I don't remember all of them, but I think `github:copilot-github-user:email` was the critical point. So anyway, after setting that key and its value to null along with a couple other pairs that included the word github in their key, I saved the db and relaunched cursor. Copilot asked me to sign in again. Problem solved
> 
> 
> 
> how to find this db file in Macos

I think it's still an election like app so you might be able to extract and repeat the above. Don't know if it's packaged as an appimage tho

**Comment by tigerzhang** [comment]
This works for me. https://github.com/getcursor/cursor/issues/782#issuecomment-1691000657

**Comment by WaysToGo** [comment]
MacOS location `~/Library/Application Support/Cursor/User/globalStorage`
and delete `state.vscdb` 

the only catch is we need to log in to cursor again, hope this helps.

**Comment by huangmengzhi** [comment]
> 

thanks a lot!!

**Comment by flyjgh** [comment]
is this a joke? is there still no better way than deleting a random db file to change the set github account?

**Comment by goportaldevelopment** [comment]
> is this a joke? is there still no better way than deleting a random db file to change the set github account?

Found the solution here: https://github.com/getcursor/cursor/issues/782
