### ISSUE TITLE
Seeing irrelevant (other users?) conversations in the chat feature

### ISSUE THREAD

**Issue by groundcat** [getcursor/cursor#585]
**Description:** While using the chat, I noticed that the chat feature displays conversations possibly belonging to other users that are not relevant to my prompt or code. This issue occurred in the Cursor Linux AppImage version of the app. I was using my own OpenAI API key.

I'm not sure if this is other user's data (hopefully not) or a built-in example prompt.

Here's a screenshot of the problem:
![](https://i.ibb.co/0mRN22B/photo-2023-05-10-00-42-16.jpg)

**Expected behavior:** The chat feature should only display conversations relevant to my prompt and code.

**Steps to reproduce:** I was using the Cursor Linux AppImage version. I'm currently not able to reproduce this issue. It only happened once when I noticed that the chat window shows conversations that are not related to your prompt or code.

Version: 0.2.11
Commit: 089994861982da4f5555ef3f09d044ae1b16f997
Date: 2023-05-09T09:12:52.091Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-71-generic
Sandboxed: No

**Impact:** This issue could be a privacy concern as users might unknowingly view conversations that are not meant for them.

**Request:** If this is not a built-in example prompt, please investigate and fix this issue as soon as possible to ensure the privacy and security of users using the AI code generator app.

**Comment by truell20** [comment]
Should be fixed in the latest version! Thanks for reporting. Let me know if you see anything crop up again.
