### ISSUE TITLE
Support API keys for the Azure OpenAI Service

### ISSUE THREAD

**Issue by dolphinsboy** [getcursor/cursor#588]
Support azure openai

**Comment by danperks** [comment]
Hey, the Cursor team currently works directly with OpenAI to build the service, so I believe it would be unlikely for them to support Azure OpenAI any time soon. However, I'll leave your issue open as a potential future enhancement.

**Comment by truell20** [comment]
We could probably offer this! What sort of info would you need to specify? The API version, API base, and API key? Do your python scripts with azure look like this:
<img width="565" alt="Screenshot 2023-05-18 at 10 56 24 PM" src="https://github.com/getcursor/cursor/assets/4297743/3b8d40de-0008-498b-b039-cae9ff016353">

**Comment by dolphinsboy** [comment]
Yes, I am very excited about this feature. @truell20

**Comment by HusainMkd** [comment]
> We could probably offer this! What sort of info would you need to specify? The API version, API base, and API key? Do your python scripts with azure look like this: <img alt="Screenshot 2023-05-18 at 10 56 24 PM" width="565" src="https://user-images.githubusercontent.com/4297743/239449971-3b8d40de-0008-498b-b039-cae9ff016353.png">

Hi @truell20 - yes azure scripts look like this - has this been implemented yet? I can't seem to input my azure api key for it to work

**Comment by Damianjsp** [comment]
I will like that too, mostly because I had already setup this and I get it working

**Comment by z4656207** [comment]
I have configured the correct Azure API, but it does not work
![微信图片_20230822091335](https://github.com/getcursor/cursor/assets/7494898/4f3f8b04-d584-46d8-913f-394d44dfba3b)
![微信图片_20230822091137](https://github.com/getcursor/cursor/assets/7494898/c33419da-eba0-4a3b-9c7f-e57b848ecffa)

**Comment by seancswanson** [comment]
As of https://changelog.cursor.sh/#0233---azure-support this is implemented... Is there any plan to create documentation around this?

**Comment by blacksmithop** [comment]
You can use Azure OpenAI by following these steps

1. Click the settings icon on the top right
2. Scroll down to Advanced and you will see such an option

**Comment by gijigae** [comment]
> I have configured the correct Azure API, but it does not work ![微信图片_20230822091335](https://user-images.githubusercontent.com/7494898/262192689-4f3f8b04-d584-46d8-913f-394d44dfba3b.png) ![微信图片_20230822091137](https://user-images.githubusercontent.com/7494898/262192695-c33419da-eba0-4a3b-9c7f-e57b848ecffa.png)

Azure OpenAI Service can be used for the chat and edit. However, as @z4656207 pointed out, it is not yet compatible with the "New AI Project". It hangs at the Step 0.

**Comment by thejackwu** [comment]
> > I have configured the correct Azure API, but it does not work ![微信图片_20230822091335](https://user-images.githubusercontent.com/7494898/262192689-4f3f8b04-d584-46d8-913f-394d44dfba3b.png) ![微信图片_20230822091137](https://user-images.githubusercontent.com/7494898/262192695-c33419da-eba0-4a3b-9c7f-e57b848ecffa.png)
> 
> Azure OpenAI Service can be used for the chat and edit. However, as @z4656207 pointed out, it is not yet compatible with the "New AI Project". It hangs at the Step 0.

Can confirm this is the case.

**Comment by illgitthat** [comment]
Another issue is that it seems that currently only one deployment/model is supported.

If I want to use gpt-4o via Azure for chat and gpt-4o-mini via Azure for in line editing it does not work I think.

**Comment by mallapraveen** [comment]
is there way where we can set custom headers for Azure OpenAI in cursor models ? headers like `Ocp-Apim-Subscription-Key` .. etc.

**Comment by illgitthat** [comment]
@truell20 if you have the time, it would be great to get a comment from the team on plans for further azure support.

**Comment by alkampfergit** [comment]
It would be nice to add support for multiple deployment. For standard OpenAI a single api key let you use all models, for azure OpenAI we need to create a deployment for each model. Maybe using comma separated values in deploymentname field?

Also I'd like to know when I use chat when I'm using model from azure, it would be nice if the model name is called azure-{deploymentname}
