### ISSUE TITLE
How to prevent underline _ being interpreted as Italic format in reply

### ISSUE THREAD

**Issue by ljhm** [getcursor/cursor#589]
The underline _ in my question is part of normal text, it is not for italic font. But it is interpreted as italic in reply.

![Screen Shot 2023-05-11 at 7 12 54 PM](https://github.com/getcursor/cursor/assets/9011764/1cd95594-2acc-4c31-b5c4-3f6e232edb6d)

Version: 0.2.11
Commit: 089994861982da4f5555ef3f09d044ae1b16f997
Date: 2023-05-09T09:12:52.091Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

**Comment by truell20** [comment]
Thanks for reporting this. Should be fixed in the next build.

**Comment by truell20** [comment]
Cursor.sh should work for you!
