### ISSUE TITLE
cursor cannot expand its gpt-4 token capacity

### ISSUE THREAD

**Issue by NOVOLAND749** [getcursor/cursor#591]
I receive a message that "You've hit your limit of 600K tokens" so I login in cursor to Increase usage for gpt-4. but it doesn't work when I press the confirm button, and it seems there is an error "TokenUsage must be between 1 and 1,000,000". I don't know if it's my problem.

By the way , how the gpt-4 calculate the tokens? it used up so quick.

**Comment by truell20** [comment]
Thanks for reporting this! Should be fixed now.

**Comment by truell20** [comment]
Let me know if you run into any trouble
