### ISSUE TITLE
Cursor cannot save Window "hosts" file

### ISSUE THREAD

**Issue by mieuf** [getcursor/cursor#592]
when i modify [c:\Windows\System32\drivers\etc\hosts] , i can't save this file

error info
`"C:\Users\abc\AppData\Local\Programs\Cursor\bin\cursor.cmd" --file-write 
"c:\Users\abc\AppData\Roaming\Cursor\code-elevated-OVRHTuZH" 
"c:\Windows\System32\drivers\etc\hosts" The system cannot find the path specified.`

**Comment by danperks** [comment]
Hi, the hosts file is very protected in Windows, so I'd ensure you are running Cursor as an admin. Does this work in VSCode, or any other IDE app like that?

**Comment by mieuf** [comment]
yes，i had try as admin to save but fail. it's work on vscode when i am running as admin

**Comment by danperks** [comment]
I'm guessing this is probably resolved or no longer an issue, so will close to tidy up.
