### ISSUE TITLE
[Bug/API] Cursor doesn't continue the conversation

### ISSUE THREAD

**Issue by WillXProject** [getcursor/cursor#594]
Cursor doesn't continue the conversation on a topic, for example if I send an error I get when running the app it makes, then tell it what is happening, it talks about something else.

**Comment by truell20** [comment]
Thanks for flagging this. Could you send a screenshot?

**Comment by truell20** [comment]
I think this is likely fixed in the latest version. Let me know if it's still persisting for you!

**Comment by WillXProject** [comment]
Alright, bet
