### ISSUE TITLE
Reopen Crash

### ISSUE THREAD

**Issue by SkipGip** [getcursor/cursor#596]
![image](https://github.com/getcursor/cursor/assets/94594502/4ddeeb64-69e9-49a6-b8bb-1c42b1f2a8cf)

After installation, it can be opened, but after closing, the above error will be reported

**Comment by truell20** [comment]
Does this error persist if you redownload Cursor from cursor.so?

**Comment by truell20** [comment]
Just checking here?

**Comment by SkipGip** [comment]
It happens all the time, there is no problem just after downloading, but there is a problem after closing it and opening it again

**Comment by danperks** [comment]
This is probably sorted now, so I'll close this issue, but if you still have problems, please open a new issue :)
