### ISSUE TITLE
If window.nativeTabs is true, the settings gear at the top right of the cursor is not visible.

### ISSUE THREAD

**Issue by 9j** [getcursor/cursor#597]
If **window.nativeTabs** is true, the settings gear at the top right of the cursor is not visible.

[true]
![CleanShot 2023-05-14 at 00 53 31](https://github.com/getcursor/cursor/assets/11691670/0f649796-8c66-4166-8c61-d3237e07ecbc)

[false]
![CleanShot 2023-05-14 at 00 53 52](https://github.com/getcursor/cursor/assets/11691670/677640ec-3e5f-46cd-a5c6-110816740630)

**Comment by truell20** [comment]
Ah, to open up the settings when you have that enabled, try command + shift + p "Open AI Settings." We may tweak the UI here in the future.
