### ISSUE TITLE
New AI Project gets Stuck

### ISSUE THREAD

**Issue by JeoCrypto** [getcursor/cursor#601]
Hi there, I need help with the Cursor Editor when starting a new AI project. It often becomes unresponsive, leaving me unable to move forward with my work. I have yet to receive any error messages or find any solutions to this issue. What should I do next? Your help would be greatly appreciated. And some Bonus on subscription would also be great since, most of the time; it Burns a lot of OpenAI Tokens on GTP4.

**Comment by truell20** [comment]
Should be fixed in the latest version! Let me know if you still have issues. What do you use the New AI Project for?

**Comment by JeoCrypto** [comment]
I already had three updates, always on the VSCode-based version.

05/05/2023

**Comment by JeoCrypto** [comment]
Since today's update, the Cursor gets stuck in all attempts to build an AI Project on this part: 
<img width="828" alt="cursor2" src="https://github.com/getcursor/cursor/assets/96849883/cb893ded-fc91-405b-b556-cf5d07963e3f">

**Comment by Sato-Isolated** [comment]
> Since today's update, the Cursor gets stuck in all attempts to build an AI Project on this part: <img alt="cursor2" width="828" src="https://user-images.githubusercontent.com/96849883/239685056-cb893ded-fc91-405b-b556-cf5d07963e3f.png">

yeah i got the same

**Comment by b4sh3r** [comment]
not fixed in new ver (0.22.2)

**Comment by Sato-Isolated** [comment]
I managed to do 4-5 generations and then I get this message that pops up every time and gets stuck at step 0.

![image](https://github.com/getcursor/cursor/assets/12450341/c717626e-ad65-41e6-910a-03a094d38ed2)

**Comment by truell20** [comment]
Apologies about this! We did a change to our infrastructure that impacted New AI project generation. Believe it's been fixed for a few days. Please let me know if you run into any issues.

**Comment by JeoCrypto** [comment]
It is partially fixed. If you receive an update not during the job, the project stops, and you can't make it continue. It would be best if you found a way to continue an AI Project when something happens at its contains. Otherwise, you must keep yourself in Yoga mode, praying that even the mouse doesn't move.

**Comment by dynamiccode00** [comment]
still having the issue

**Comment by JavierElBene** [comment]
@truell20 same is happening to me during a New AI Project initialization. It has been unresponsive for more than an hour and nothing is shown in the Output view. I'm paying the Pro subscription and the Settings section is stating that I haven't used any GPT-4 fast requests and only 55 GPT-3.5 ones. Could you please advice how to move forward here?  
![Screenshot 2024-04-02 at 11 59 24 AM](https://github.com/getcursor/cursor/assets/13079286/d4bb3f6e-d7fd-4752-9144-0b0b536f2fdc)

**Comment by viperadnan-git** [comment]
> @truell20 same is happening to me during a New AI Project initialization. It has been unresponsive for more than an hour and nothing is shown in the Output view. I'm paying the Pro subscription and the Settings section is stating that I haven't used any GPT-4 fast requests and only 55 GPT-3.5 ones. Could you please advice how to move forward here? ![Screenshot 2024-04-02 at 11 59 24 AM](https://private-user-images.githubusercontent.com/13079286/318733690-d4bb3f6e-d7fd-4752-9144-0b0b536f2fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTkwODMsIm5iZiI6MTcyMDI1ODc4MywicGF0aCI6Ii8xMzA3OTI4Ni8zMTg3MzM2OTAtZDRiYjNmNmUtZDdmZC00NzUyLTkxNDQtMGIwYjUzNmYyZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA5Mzk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYmVjMjNmNzkyYjJkZmM5NzQwOTFmZjlmYTI3ZmZjNmYyMDI0MzgzNTBjOTAzMmU4OWMzODJlYTg4YjU0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nq7leVGr3mTY1v8usGktdnCKeYI6clGfQvDN7LPUz_E)

got same problem here, stuck at step 65
