### ISSUE TITLE
stuck，Unable to continue working

### ISSUE THREAD

**Issue by zjh708** [getcursor/cursor#602]
![image](https://github.com/getcursor/cursor/assets/51907613/0ea503d7-d5db-4c28-81bd-8fee86a1fe94)

**Comment by leo81122** [comment]
same issue after update to latest version

**Comment by leo81122** [comment]
> ![image](https://user-images.githubusercontent.com/51907613/239180574-0ea503d7-d5db-4c28-81bd-8fee86a1fe94.png)

I fix this with: logout and relogin

**Comment by zjh708** [comment]
> > ![image](https://user-images.githubusercontent.com/51907613/239180574-0ea503d7-d5db-4c28-81bd-8fee86a1fe94.png)
> 
> I fix this with: logout and relogin

Thank you. I took care of that just like you said

**Comment by truell20** [comment]
Fixed in the latest update! Thank you for reporting
