### ISSUE TITLE
Vectorise whole codebase

### ISSUE THREAD

**Issue by mrf-redwood** [getcursor/cursor#604]
I think ability to vectorise the whole codebase would be interesting because it can write/edit code while considering every file that might be relevant as well. This can:

1. Let developers not even needing to select the necessary files to implement a change. Basically chatting with the project instead of code. 
2. Write much better code 
3. Might change other files if necessary based on the changes in the current file (I think this one is similar to your refactoring feature roadmap)

**Comment by jakobFNF** [comment]
Full codebase indexing is now a feature, and you can reference the most relevant snippets from your entire codebase in the chat by using the "Ctrl + Enter" shortcut. Thank you for your suggestion!
