### ISSUE TITLE
Can't switch to GPT-4?

### ISSUE THREAD

**Issue by fclof** [getcursor/cursor#608]
In [this](https://github.com/getcursor/cursor/issues/533#issuecomment-1529171177) thread you said there is a "Model" option, but I just can't find it...
![issue](https://github.com/getcursor/cursor/assets/43123988/b90912df-e3b9-49b4-add1-e1e50c5b0a78)

**Comment by truell20** [comment]
Hitting the "Not using key" toggle should switch Cursor to using you API key. If you have API access to GPT-4, then a model drop down will show up with GPT-4 in it. Otherwise, you'll need to upgrade to pro to use GPT-4.

**Comment by fclof** [comment]
I have already upgraded both cursor pro and chatgpt plus, but still can't see a model dropdown.

**Comment by fclof** [comment]
So, even though I've paid 20 dollars to Cursor, I still have to give it my API key?

**Comment by fclof** [comment]
![issue2](https://github.com/getcursor/cursor/assets/43123988/75490a37-5abd-47b0-a74b-a4ed1369ca20)

**Comment by fclof** [comment]
I've already paid 20 dollars to Cursor yesterday.
I tried to logout and then login, the model dropdown finally appeared.
