### ISSUE TITLE
Why do I need to subscribe again after I subscribed once today?

### ISSUE THREAD

**Issue by webLiu** [getcursor/cursor#609]
Why do I need to subscribe again after I subscribed once today? Can't use GPT4 anymore.

**Comment by ssdadsl** [comment]
me too，I subscribe today,but need still subscribed once,my github id is 2631599879@qq.com

**Comment by truell20** [comment]
Apologies here! Looking into this problem now. 

@webLiu Could you DM me the email that you used to pay?

@ssdadsl It looks like your subscription payments didn't go through. Let me know if you need any help with paying through Stripe.

**Comment by webLiu** [comment]
> Apologies here! Looking into this problem now.
> 
> @webLiu Could you DM me the email that you used to pay?
> 
> @ssdadsl It looks like your subscription payments didn't go through. Let me know if you need any help with paying through Stripe.

Hello, My email address is a1125075101@gmail.com.

**Comment by webLiu** [comment]
> 

I have successfully subscribed but still cannot use GPT4, can you help me look at the problem?😔

**Comment by truell20** [comment]
Of course. Will send you a refund for the trouble. Apologies for the incredibly late reply here.

Is this problem still happening?

If so, could you tell me whether you used Github to sign in or Google or email? Did you use email to sign in?

**Comment by truell20** [comment]
Please email michael@cursor.so if you'd rather not send this info publically!

**Comment by webLiu** [comment]
> Please email [michael@cursor.so](mailto:michael@cursor.so) if you'd rather not send this info publically!

I have sent an email, please check this issue for me, thanks! 🙏🏻

**Comment by walnutwaldo** [comment]
SOLUTION for future people looking at this thread

If you are running into this issue, please make sure you are logged into the **correct** account. If you sign in with email / password, GitHub, or Google, those are all separate accounts. It is likely you have made the payment for one of these but are logged into a different one. Double check and if you are still facing issues, you can always reach out to hi@cursor.so and we can help.

**Comment by danperks** [comment]
Subscriptions have been redone to use Stripe behind the scenes, so this is likely no longer an issue!
