### ISSUE TITLE
Chat输出问题

### ISSUE THREAD

**Issue by yeqiu741** [getcursor/cursor#61]
当问的问题可能需要chat回答很多内容的时候就只会显示一部分。大概只会展示六七百字的样子。这个是软件设定还是软件漏洞？

**Comment by Domain** [comment]
OpenAI的限制吧，输入continue就可以继续

**Comment by Anopia** [comment]
中文让他生成超多代码的时候会这样，英文描述我尝试是正常的。

**Comment by truell20** [comment]
Cursor should output more code / text in the newest version 🙂

**Comment by truell20** [comment]
Let me know if this is still an issue!
