### ISSUE TITLE
Why does the font revert back to its original setting every time I modify it and exit the software, only to restart it again?

### ISSUE THREAD

**Issue by 0xFFFF-maker** [getcursor/cursor#610]
1) If you can, please include a screenshot of your problem
![1](https://github.com/getcursor/cursor/assets/90913009/eb60ac67-0bbf-44e1-94a4-260bd67d7450)
![2](https://github.com/getcursor/cursor/assets/90913009/daeb5adb-86b0-4096-8575-a001cd3c8f48)
![4](https://github.com/getcursor/cursor/assets/90913009/8df599f4-d276-42e8-8e2a-f186ef968d80)
![3](https://github.com/getcursor/cursor/assets/90913009/a28318d1-8e62-4d1c-8c39-64b4931422db)

2) Please include the name of your operating system
My operating system is the windows11

3) If you can, steps to reproduce are super helpful
Every time I change the font, it reverts back to its original setting when I close and reopen the software.

**Comment by p1s1lver** [comment]
same

**Comment by BYJRK** [comment]
My current workaround is to set the settings.json file as readonly to prevent it from reverting everytime the app starts.

Settings file location: C:\Users\<username>\AppData\Roaming\Cursor\User\settings.json

**Comment by arvid220u** [comment]
this is fixed! thank you for reporting
