### ISSUE TITLE
continuously reporting network errors and could not use AI copilot

### ISSUE THREAD

**Issue by z-rrr** [getcursor/cursor#611]
![20230520161637](https://github.com/getcursor/cursor/assets/97387929/8e53f3be-28ac-4b96-a4d1-076fc30bacae)

Hello, my cursor editor beta for Windows continued to report networking errors during use today, but i'm sure my internet connection is OK.

This bug occurs both when 'chat' and 'generate code'.

my editor information is:

Version: 0.2.17
Date: 2023-05-19T03:20:56.933Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Thank you

**Comment by z-rrr** [comment]
reinstalled and it fixed :-)

**Comment by truell20** [comment]
What version of the software are you on now?

**Comment by z-rrr** [comment]
now it's 0.2.18. today the problem occurs only once and fixed by reopen cursor editor

**Comment by nongmo007** [comment]
I am unable to access the official website of Cursor right now, and also unable to log in to my account when using Cursor.

**Comment by fy894684862** [comment]
I am unable to access the official website of Cursor too.

**Comment by Alexrenhan** [comment]
我也是，突然就登录不上账号了，官网也打不开了，在线等
！

**Comment by z-rrr** [comment]
emmm, maybe because of the GFW?
![屏幕截图 2023-05-22 181546](https://github.com/getcursor/cursor/assets/97387929/e43ba96b-0ec5-48d9-8612-4e367c8152e6)

**Comment by Todd5129** [comment]
look this plz
![image](https://github.com/getcursor/cursor/assets/132825782/96379d37-35b9-4fa6-a32b-0fa3688702b5)

**Comment by truell20** [comment]
Try downloading the latest version from cursor.sh if you haven't already updated.

**Comment by Yareda21** [comment]
Also "npm install" doesn't work either,
