### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by UCanSeeeeee** [getcursor/cursor#612]
what happened with "Something unexpected happened..Please check your internet connection and try again."?

**Comment by truell20** [comment]
Is this error still present for you?

**Comment by UCanSeeeeee** [comment]
> Is this error still present for you?

Yes, and no one answered me on Discord.

**Comment by cecicxy** [comment]
so as me.

**Comment by Rebely22** [comment]
same for me. 
maybe it's a China-specific issue

**Comment by qhl123456** [comment]
maybe it's a network issue， try  again Wait a few minutes

**Comment by truell20** [comment]
Is this persistent? What app versions are you on? What operating system? Do you have any insight into when this happens or not?

Apologies here. Any debugging information is incredibly useful.

**Comment by truell20** [comment]
Any chance anyone would be up to hop on a Zoom call so I could debug this? If so, please email michael@cursor.so 🙂

**Comment by KunShanJiaTi** [comment]
Same problem here
