### ISSUE TITLE
can not connect the web https://cursor.so/ to log in

### ISSUE THREAD

**Issue by Qjy9508** [getcursor/cursor#613]
1) If you can, please include a screenshot of your problem
https://cursor.so/ can not be loaded;

2) Please include the name of your operating system
mac
3) If you can, steps to reproduce are super helpful

**Comment by willamyu** [comment]
I can't log in to the https://cursor.so/ at the same time, is this a bug?

**Comment by UCanSeeeeee** [comment]
so as me.

**Comment by truell20** [comment]
I think we were blocked by the Great Firewall ☹️ You should be able to access cursor.so with a VPN. Otherwise, I believe cursor.sh will still work in China.

**Comment by nocardriver** [comment]
Use "cursor.sh" instead while log in, it work in my computer.

**Comment by rexzeng68** [comment]
the same

**Comment by indomitableXiaoNan** [comment]
> cursor.sh
Really useful, thank you very much


> Use "cursor.sh" instead while log in, it work in my computer.

Really useful, thank you very much

**Comment by mingzitainanxuan** [comment]
the same

**Comment by jxayly123** [comment]
any1 tell me where curso.sh file is ?

**Comment by willamyu** [comment]
> 

use ----> https://www.cursor.sh/loginDeepPage
