### ISSUE TITLE
The answer converges too quickly, and it cannot "jump" out after receiving the error message, should I reopen a session at this time, or is the problem with the AI algorithm causing it to converge too quickly?

### ISSUE THREAD

**Issue by byrTony-Frankzyq** [getcursor/cursor#614]
For example, I asked it to complete the construction of a search binary tree, but found that some of its function implementations obviously misunderstood the meaning of the problem, and I pointed out that it would still output the same answer, which bothered me.

**Comment by truell20** [comment]
What features are you using to generate this code? The chat window or the inline edits? If you need to go back and forth with the AI on the implementation, the chat window may be best for now.

**Comment by truell20** [comment]
Let me know if you have any other questions here! Here to help 🙂
