### ISSUE TITLE
AI settings window indicates I have logged in, but login window always pops up and stopped me from using

### ISSUE THREAD

**Issue by ziranyang0** [getcursor/cursor#615]
![屏幕截图 2023-05-23 201150](https://github.com/getcursor/cursor/assets/97387929/6ae29efb-0ab2-450f-b9fd-4fc824a8adbc)
![屏幕截图 2023-05-23 201214](https://github.com/getcursor/cursor/assets/97387929/d9332aa1-2e3c-4e77-9ea3-a266d1a1745f)
Whenever I use it, this login window will pop up. Clicking on "login in", redirecting to the webpage, and logging in finished on webpage suggesting "You may now proceed back to Cursor"--these are all normal, but still unable to use Cursor, the login window will still pop up

I wander if it's because of app updating, I am using a Windows system, and this issue seems to appear every time accompanied by a small "update" prompt in the bottom left corner. Btw, clicking on the "update" prompt window and there seems nothing will happen, instead of  updated immediately. a feature or bug?

**Comment by SinishaDjukic** [comment]
Still doesn't work on Win10 with Cursor 0.12.3

**Comment by danperks** [comment]
This is a screenshot from quite an old version, so I'll assume this is resolved for now!
