### ISSUE TITLE
Why can't I log in to the desktop app in China and it has been automatically deleted?

### ISSUE THREAD

**Issue by weiouyang** [getcursor/cursor#617]
Why can't I log in to the desktop app in China and it has been automatically deleted?

**Comment by pax200409** [comment]
重新下载一下就好了，应该是个bug

**Comment by truell20** [comment]
You should be able to log into the newest version of the app in China. cursor was blocked by the Great Firewall, so we switched to cursor.sh.

If you can't login, try downloading the latest version at https://cursor.sh.

**Comment by truell20** [comment]
Sometimes the autoupdate behavior on Windows is removes app shortcuts, which is what I think you're running into. This is a known bug, and we're investigating a fix.

**Comment by your-grace** [comment]
That's right.Visit https://cursor.sh/.Reload cursor and can login in.Old version login in to https://cursor.so/

**Comment by snow101300036** [comment]
I'm also experiencing the same issue. Downloading the latest version hasn't solved it. Can you please advise on how to resolve it?
