### ISSUE TITLE
based on gpt-3 not gpt-4

### ISSUE THREAD

**Issue by rayshen92** [getcursor/cursor#62]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/38471614/225915036-331f965a-a27e-4cbe-9816-58f2de4f6333.png">

**Comment by ramblezhang** [comment]
### I agree with you, I think it should be GPT3.5
![image](https://user-images.githubusercontent.com/36092557/226092527-3d934b91-03f9-4122-9c7f-41f2794005ad.png)

**Comment by tiratira** [comment]
Yes, the model is apparently gpt3.5 turbo because of its output speed.

**Comment by MichaelToLearn** [comment]
So the description on the website is a bit of overpromotion ?

**Comment by sol87** [comment]
他们是懂四舍五入的‘’😂

**Comment by truell20** [comment]
Cursor is based on gpt3.5, soon you'll be able to pay for gpt4 if you'd like!

**Comment by flazerain** [comment]
填了api key 能用gpt-4吗？
