### ISSUE TITLE
Can you use the language of the question in your answer

### ISSUE THREAD

**Issue by qhl123456** [getcursor/cursor#620]
When I ask questions in Chinese, the answer is always in English. I need to tell GPT to ask him to answer me in Chinese every time. Is there any way to change the language according to the language of my question when answering？

**Comment by svallory** [comment]
If you add "answer in Chinese" it will probably work

**Comment by truell20** [comment]
You can also add an "always use chinese" instruction in the "More" tab!

**Comment by truell20** [comment]
Adding in a "Language" option to the onboarding flow, so this is more discoverable. Should be in the next build 🙂 Thanks for reporting this

**Comment by qhl123456** [comment]
ok，thanks

**Comment by Jukeman9** [comment]
@truell20 Hey :) This was a great idea to add the language to the onboarding. I used that to add polish. But now all the comments made by gpt are in polish and I would like to change that or delete polish support entirely. Could you help me out, how to do that?

**Comment by filipw01** [comment]
For anyone looking, you can open `Cursor -> Settings... -> Cursor Settings` and change `Rules for AI`
