### ISSUE TITLE
I can't create a project with new ai project

### ISSUE THREAD

**Issue by Robingao666** [getcursor/cursor#624]
I have tried many times to create through the new ai project, he always reminds me that there is the same folder duplication, no matter which path I put him in and what kind of file name he always says that my path is duplicated, I re-download the software and it is still the same question
![image](https://github.com/getcursor/cursor/assets/75795463/d7368271-3337-4752-9b81-055654afc6a0)
![image](https://github.com/getcursor/cursor/assets/75795463/cfdbee7d-e333-4b2a-b3bd-59d11241021d)
![image](https://github.com/getcursor/cursor/assets/75795463/824ede13-df6b-4728-a457-7658b6b4cd2c)
![image](https://github.com/getcursor/cursor/assets/75795463/c31c6ead-4506-4888-9949-c2be62f5040e)

**Comment by SingularityLab** [comment]
Same here! Any fix?

**Comment by truell20** [comment]
Fixed in the latest update! Just released it.
