### ISSUE TITLE
Jupyter Interactive can not run，please fix it 

### ISSUE THREAD

**Issue by bravekingzhang** [getcursor/cursor#626]
1) If you can, please include a screenshot of your problem
<img width="691" alt="image" src="https://github.com/getcursor/cursor/assets/4476322/c296f656-106a-4254-95cb-a5bbd02d5cb8">

2) Please include the name of your operating system
<img width="264" alt="image" src="https://github.com/getcursor/cursor/assets/4476322/5ed29b4a-d03a-4a8c-b71d-2b510d016cb3">

3) If you can, steps to reproduce are super helpful

**step1.** install plugin **Jupyter**

<img width="678" alt="image" src="https://github.com/getcursor/cursor/assets/4476322/28a835ec-e9a5-466b-8672-51bf0dae18d9">

**step2.** new any python file

**step3.** use  `shift`+`enter` run with interactive mode ,then you will reproduce the error, **But it is ok on vscode!**

**Comment by hugh-min** [comment]
same problem here, is there any fix now?

**Comment by truell20** [comment]
Temp fix here: https://github.com/getcursor/cursor/issues/576

Working on a more permanent fix.

**Comment by arvid220u** [comment]
Should be fixed in version 0.2.25!
