### ISSUE TITLE
Cursor pro deducts fees at will

### ISSUE THREAD

**Issue by charmby** [getcursor/cursor#627]
I am a professional user. I used 
20230406 for the first time, and I was charged 20 dollars, but at 20230410, I canceled the renewal, but one month after my first use, that is, 20230506, he deducted I paid $20 (theoretically, there is no such deduction after I cancel), and then on 20230528, my project restarted using cursor and upgraded pro. At this time, I was deducted another $20. I don’t know why there is no charge. Random deduction without details, and I hope this fee can be refunded

![WechatIMG3410](https://github.com/getcursor/cursor/assets/6927947/06d342f1-d037-4f61-ac05-37f35f29b27a)
![WechatIMG3411](https://github.com/getcursor/cursor/assets/6927947/d7baa957-04bf-43e4-a4bf-885345eb4db0)
![WechatIMG3412](https://github.com/getcursor/cursor/assets/6927947/311742b4-42ff-41d4-8c3a-d7431433221a)

**Comment by CHTUZKI** [comment]
I didn't expect you to be able to use a bank card for payment. I tried using 6 bank cards but all failed,

Various issues: CVC errors, unsupported bank cards, bank cards with no expiration date,

In the end, I gave up using cursor. Maybe I can continue using it 100 times next month😂😂😂.LOL！

**Comment by truell20** [comment]
@charmby Replied to you over email! Not sure why stripe didn't register your cancellation, but I refunded you $40. Let's figure out why your pro isn't connected to your account over that email thread.

@CHTUZKI Apologies here -- we rely on Stripe for payment processing. What would be your preferred method of payment?

**Comment by charmby** [comment]
What would be your preferred method of payment?
Thank you very much for your investigation and reply to the problem, it's
hard work
Can the over-deducted money be refunded directly to the account? In this
way, when I continue to use your products next month, he can directly use
the refunded amount?

Michael Truell ***@***.***> 于2023年5月29日周一 03:02写道：
