### ISSUE TITLE
Do Cursor have any plans to add new payment methods？

### ISSUE THREAD

**Issue by CHTUZKI** [getcursor/cursor#628]
HI.
Does Cursor have any plans to add new payment methods for Chinese users. If so, about when will it be launched.

**Comment by truell20** [comment]
Not immediately on the roadmap, but what payment method would you prefer? Would either Wechat or Alipay help?

**Comment by CHTUZKI** [comment]
yes.

Wechat or Alipay can make payments more conveniently. And these two payment methods are most commonly used in China, almost everyone uses them.

For Chinese users, cursor can only be used 100 times. Although there is a way to upgrade to the Pro version, not every bank card in China supports this payment method, and you need to try many bank cards.

**Comment by Jaswand** [comment]
is paypal also a option
