### ISSUE TITLE
part of result code is losted when the generated code is too long

### ISSUE THREAD

**Issue by assmdx** [getcursor/cursor#63]

**Comment by 173770346** [comment]
The GPT would recieve context, so maybe you can just input 'continue' to get the rest of the code

**Comment by wzbooks** [comment]
> The GPT would recieve context, so maybe you can just input 'continue' to get the rest of the code

Hello, I replied 'continue', but to no avail

**Comment by 173770346** [comment]
If it doesn't work, you can describe more exactly about the problem in GPT.

**Comment by 173770346** [comment]
> > The GPT would recieve context, so maybe you can just input 'continue' to get the rest of the code
> 
> Hello, I replied 'continue', but to no avail

If it doesn't work, you can describe more exactly about the problem in GPT.

**Comment by wzbooks** [comment]
> 

Thank you. I sent 'continue to print code' and it continued to print

**Comment by tinkerbaj** [comment]
If try to send 'continue to print code' it continues and then starts repeating the code from the beginning of my file.

**Comment by danperks** [comment]
I believe changes were made to try resolve this, but #479 has begun to occur for some users. 
As this bug is unlikely to occur again, I'll close this issue for now.

**Comment by napter** [comment]
When using generate, if I type "continue" as the follow up it erases all the existing output and starts again. Is there any way to have it continue from where it left off?
