### ISSUE TITLE
Regarding the issue of the file scope that the cursor checks when answering questions.

### ISSUE THREAD

**Issue by CHTUZKI** [getcursor/cursor#630]
HI.

When I use the cursor to open a project consisting of multiple files, I find that the cursor can only retrieve information from the currently opened file and answer questions based on that file. For example, if I want to know if a certain function in the currently opened file is called in other files, the cursor cannot answer. Is there a way to make the cursor search the entire open project instead of just the currently opened file, I believe the cursor should be able to answer questions more accurately.

Best regards.

**Comment by jakobFNF** [comment]
You can now add multiple files to the chat with the @ symbol. And full codebase indexing is now a feature. You can reference the most relevant snippets from your entire codebase in the chat by using the "Ctrl + Enter" shortcut.
