### ISSUE TITLE
Something unexpected happened....

### ISSUE THREAD

**Issue by CHTUZKI** [getcursor/cursor#634]
HI.

When the cursor answers my question, it keeps outputting characters to tell me the answer, but sometimes the cursor will stop halfway and give an error, as shown in the figure below.

![_~ CQZ)H@IDJLP92R Y8``N](https://github.com/getcursor/cursor/assets/42321222/42be8db8-5634-48c2-a4e6-17ceb1a95658)

**Comment by CHTUZKI** [comment]
Before I started using my own OpenAI API, this phenomenon rarely occurred. However, since I couldn't upgrade to the pro version through the cursor's default payment method, I started using an OpenAI API obtained through unofficial channels, which caused this error to occur frequently.

Is this a problem with my OpenAI API?

Best wishes.

**Comment by truell20** [comment]
We're looking into this. Have heard several user complaints.

> I started using an OpenAI API obtained through unofficial channels

What does this mean?

**Comment by bhaskoro-muthohar** [comment]
I am experiencing the same issue with codebase but not with a single file

**Comment by jakobFNF** [comment]
It has been some time and I think this issue has been fixed. I will close this issue for now due to inactivity. If this issue still persists for you, please open another issue!
