### ISSUE TITLE
AI Code Editing (Whole file, not selection) limited to 110 lines

### ISSUE THREAD

**Issue by danperks** [getcursor/cursor#636]
For some reason, when doing file-wide AI edits, the generation seems to give up at 110 lines every time.
Using GPT3.5, not on pro. Everything from 111 onwards is shown to be removed in the diff.
On the latest version as of the time of posting this.

Screenshot:
![Screenshot 2023-05-31 at 21 47 06](https://github.com/getcursor/cursor/assets/49082234/e5df6edc-c5d6-4259-bc13-ec5ae871455b)

**Comment by truell20** [comment]
File-wide edit support isn't great right now. Hope to improve in the future!

**Comment by danperks** [comment]
Sounds good! The annoying thing, at least with Vue components, is usually I want a small change at multiple places (e.g. a method added near the bottom, and the method being used at the top) so I don't actually want the whole file to be edited.

Two suggestions:
1. The chat can work with the diff to highlight where you should make code changes
2. You can select multiple sections of code and the prompt can edit both
