### ISSUE TITLE
We had a problem querying OpenAI

### ISSUE THREAD

**Issue by Kaldrogh** [getcursor/cursor#637]
Can't use the sidebar widget since at least 15 days to get answers from chatGPT. In the previous version, i've encountered an error saying that a problem was occuring while trying to fetch openAI. Now, i get this error :

![image](https://github.com/getcursor/cursor/assets/22390211/f4e3268a-0cb1-4f4b-9d17-d10519eb1423)

**Comment by truell20** [comment]
Are you using an API key? Is this just for GPT-4 or both GPT-4 and GPT-3.5?

**Comment by Kaldrogh** [comment]
I'm using an api key. I can't even select GPT-4 on the sidebar, the option is frozen, can't switch:

![Cursor_5WcOO5xlgi](https://github.com/getcursor/cursor/assets/22390211/db0deccd-737d-4fe0-acec-55e67d225026)

**Comment by LuuKhoaHoc** [comment]
I have the same error

**Comment by DavidHalcyon** [comment]
I have the same error

**Comment by woshizhangbowen** [comment]
same
and if i don't use the apikey,i can get the answer.
But the promble is that when i open a single .py .No chat,But when i open a file.The chat will show to me.
At last,the default path of cursor is in C.I want change in other disk.

**Comment by RabbitFly89** [comment]
Is it fixed now. Encountering same problem.

**Comment by woshizhangbowen** [comment]
> Is it fixed now. Encountering same problem.现在修复了吗。遇到同样的问题。

no,but you can do it in my way

**Comment by yeshenlin** [comment]
I encountered the same issue, has anyone fixed it yet?

**Comment by danperks** [comment]
Likely resolved in later versions
