### ISSUE TITLE
Can't install any plugin

### ISSUE THREAD

**Issue by xh542428798** [getcursor/cursor#638]
I can't install any plugin; it had shown installing for one hour.
![image](https://github.com/getcursor/cursor/assets/49368033/9cdf9c14-e55e-4c94-b93b-d2b3136d848f)
when I install plugins manually from vscode market, it reported error “plugin does not compatible with VS Code '1.76.2'”.

**Comment by multics** [comment]
I would rather seeing a cursor plugin for VS Code but a wrap of old vscode which cause lots of compatibility issues.

**Comment by xh542428798** [comment]
> I would rather seeing a cursor plugin for VS Code but a wrap of old vscode which cause lots of compatibility issues.

Yes, me too.

**Comment by g413164351** [comment]
Me too, I have been installing, and I want to sync to the cursor from vs code, but it doesn’t work

**Comment by LLVLVZI** [comment]
Plug-ins downloaded offline also cannot be installed

**Comment by isencher** [comment]
me too

**Comment by g413164351** [comment]
i find something,but it still usefuless.https://github.com/microsoft/vscode-python/discussions/20184

**Comment by arvid220u** [comment]
should be fixed in version 0.2.25! please reply here if it doesn't work ◡̈
