### ISSUE TITLE
I paid money for the right to use gpt-4, but the model tells me it is based on gpt-3, can you explain?

### ISSUE THREAD

**Issue by miaokela** [getcursor/cursor#640]
<img width="1020" alt="image" src="https://github.com/getcursor/cursor/assets/30903265/12af8a75-f327-4e3d-af33-a75853cc49e7">

**Comment by arvid220u** [comment]
Language models typically don't give accurate answers when you ask them what model they are based on. If it says gpt-4 under your input box (which it does!) then it is using gpt-4.

This is a common thing people get confused about for gpt-4. (see eg https://www.reddit.com/r/ChatGPT/comments/11rdc4q/gpt4_thinks_its_gpt3/)
