### ISSUE TITLE
Cursor cannot synchronize repository.

### ISSUE THREAD

**Issue by CHTUZKI** [getcursor/cursor#643]
HI.

I upgraded cursor today and saw in the changelog that cursor has improved the context of the code. I still have some doubts about the usage logic of Codebase Context v2. If I want to use Codebase Context v2, do I need to first create a repository on my GitHub with all the code and then synchronize it with cursor?

"When I click on 'Connect GitHub' in the settings of cursor, nothing happens. It just keeps showing 'loading repos...' and I'm not sure if this is normal or not.
![G1P8K9A73VUMCXO5(T@ (H0](https://github.com/getcursor/cursor/assets/42321222/3030acf9-f2e4-4b29-83a0-8ef74886be5b)

Best Wishes

**Comment by truell20** [comment]
Do you have a git repo open in Cursor? I believe you need to have the root folder git repo open for this to show repos. Apologies for this confusing UI, should be changed in the latest version.

**Comment by CHTUZKI** [comment]
The problem is now resolved. Since my local project did not have a GitHub repository, it failed. I opened the GitHub repository in VSCode and the problem was solved.

thanks~~
