### ISSUE TITLE
Support open source LLM models like starchat in the future.

### ISSUE THREAD

**Issue by BoQsc** [getcursor/cursor#644]
https://huggingface.co/spaces/HuggingFaceH4/starchat-playground

**Comment by truell20** [comment]
We will look into this! Could you say a bit more about why you'd want us to add starchat? Do you think starchat is better at coding than the OpenAI models?

**Comment by BoQsc** [comment]
It's not better, but it's a start to adopt open source LLM models that highly likely will be more specialized and efficient at solving specific problems. It's not something that is currently very useful when GPT4 and GPT3.5 exist.

**Comment by Sanger2000** [comment]
We definitely plan on incorporating more open-source models on our backend. Thanks for the suggestion!

**Comment by FarisHijazi** [comment]
when will we be getting support for this? this should be really easy and we should be able to plug it into Azure API, however there is an error saying "invalid credentials. Please try again." when the URL is localhost

Could you please remove the validation for this? and all the problems would be solved. I love cursor but I can't use it for confidential code, so this would solve the issue. @truell20

**Comment by jjfantini** [comment]
+1

**Comment by FarisHijazi** [comment]
+1

**Comment by FarisHijazi** [comment]
+1

**Comment by danperks** [comment]
Multiple 3rd party LLM providers are now supported!
