### ISSUE TITLE
Modern GUI Text Editor

### ISSUE THREAD

**Issue by MadBomber** [getcursor/cursor#645]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
**Additional context**

As currently configured - which may be my own fault for not understanding the normal use case for cursor - this is a throw back to the bad 'ol days of having to memorized thousands of keybindings to edit text as if I were working on a command line.  I was expecting a modern GUI text editor with full mouse and menu support.  I don't want to take my hands off the mouse to make a command selection.  The only time my fingers should be on the keyboard is when I'm typing code.

Is that on the road map?

**Comment by truell20** [comment]
What are you unable to do with a mouse in Cursor?
