### ISSUE TITLE
Project-wide AI Edits/Refactor

### ISSUE THREAD

**Issue by Vandivier** [getcursor/cursor#652]
**Is your feature request related to a problem? Please describe.**
Two problems:
1. Sometimes I want to update logic and I don't know which file(s) contain that logic
2. Even if I know exactly where the logic is, it could be faster and easier for AI to run the update(s) for me

**Describe the solution you'd like**
Similar to when I "Create New AI Project" and the Cursor AI proceeds to create many files, I'd like an option to "Refactor Project" where the AI proceeds to update any files in the current workspace (it would be nice to have a way to specify certain files for inclusion or exclusion too)

**Additional context**
If it already exists, please just make it clearer how to do that. I asked the Chat function and it basically told me to go through the files that I want to update 1-by-1, streamed at:
https://www.youtube.com/watch?v=j-A-wxWF50U&t=5090s

**Comment by sualehasif** [comment]
This is super helpful. we appreciate the feedback. This is certainly on the roadmap but due to reliability is not at the top. we will get to it soon though :)

**Comment by BSN4** [comment]
@sualehasif any news on this issue
