### ISSUE TITLE
OpenAI key stopped working

### ISSUE THREAD

**Issue by willyw0nka** [getcursor/cursor#654]
1) If you can, please include a screenshot of your problem
![image](https://github.com/getcursor/cursor/assets/47634918/eeed010c-2b75-4211-9f5b-72a6d0364094)

2) Please include the name of your operating system
`Ubuntu 22.04.2`

3) If you can, steps to reproduce are super helpful
1. Open cursor settings
2. Enter a new generated OpenAI API key
3. Get the error

**Comment by Grezor** [comment]
Hi @willyw0nka do you still have this error? I also have this error at the moment.

**Comment by Bonswar-Lilian** [comment]
Same here. date: 01/07/2023
![image_2023-07-01_193133775](https://github.com/getcursor/cursor/assets/90867075/89f88c83-ba9b-443b-b07a-1530d1d1f82e)

**Comment by arvid220u** [comment]
@Grezor @Bonswar-Lilian What OS are you on? Also Linux?

**Comment by arvid220u** [comment]
Thanks for reporting by the way!! We will fix

**Comment by arvid220u** [comment]
@Grezor @willyw0nka @Bonswar-Lilian could you all try running the below command in the terminal? Please replace `sk-youropenaikey` with your key. This will show if there are any problems with Cursor, or if the problem may be a API key misconfiguration.

```
curl https://api.openai.com/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer sk-youropenaikey" -d '{
  "messages": [
    {
      "role": "system",
      "content": "You are a test assistant."
    },
    {
      "role": "user",
      "content": "Testing. Just say hi and nothing else."
    }
  ],
  "model": "gpt-3.5-turbo"
}'
```

**Comment by willyw0nka** [comment]
It seems that OpenAI restricted the API usage for free users. ChatGPT works with my account but the API keys generated by me don't.
```
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

**Comment by willyw0nka** [comment]
We can find a bit more info about this behaviour on this [stackoverflow question](https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please#:~:text=Did%20you%20sign%20up%20some%20time%20ago%3F).
This error is not related to cursor so I'm closing the issue.
