### ISSUE TITLE
Alternate macos icon

### ISSUE THREAD

**Issue by dave-hawkins** [getcursor/cursor#655]
I've made a couple of alternate macos icon for cursor:

<img width="690" alt="Screenshot 2023-06-20 at 12 18 47" src="https://github.com/getcursor/cursor/assets/14091192/c34260c6-f055-4e63-af15-b382316cc251">

If anyone at cursor wants to request any changes to use them for real, feel free to reply here or email me. I made it very quickly so if it's going to be used for real i'd like to improve it.

[Cursor Icons.zip](https://github.com/getcursor/cursor/files/11800142/Cursor.Icons.zip)

**Comment by danperks** [comment]
Really nice, think I might give these a try myself lol

**Comment by pzgz** [comment]
way much better than current one, thanks
