### ISSUE TITLE
GPT-4-32K Support

### ISSUE THREAD

**Issue by duffpop** [getcursor/cursor#656]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem, just a plain ol' feature request.

I would like to see if GPT-4-32K support is viable, and if so, if the additional token context-length would improve any of Cursor's features, aside from the obvious benefits.

To be clear, I would expect GPT-4-32K support for self-service tokens rather than you folks providing access. I am fortunate enough to have been provided access via Azure and it has been incredibly useful to date.

**Describe the solution you'd like**
The ability to select the GPT-4-32K model for self-service Azure users.

**Additional context**
You have created a wonderful product ❤️

**Comment by uraniumCoder** [comment]
Thank you for your feedback! We've added support for GPT-4-32k. It'll be released in our next update.

**Comment by truell20** [comment]
@duffpop What happens when you try to use a 32k deployment with our Azure API support? Do you get any kind of error?

<img width="772" alt="Screenshot 2023-06-28 at 3 38 12 PM" src="https://github.com/getcursor/cursor/assets/4297743/97600ff5-c013-44a2-a593-f55f6661ffeb">

**Comment by truell20** [comment]
If your deployment is for the 32k model, Cursor should automatically use that.

**Comment by duffpop** [comment]
> @duffpop What happens when you try to use a 32k deployment with our Azure API support? Do you get any kind of error?
> 
> <img alt="Screenshot 2023-06-28 at 3 38 12 PM" width="772" src="https://user-images.githubusercontent.com/4297743/249630144-97600ff5-c013-44a2-a593-f55f6661ffeb.png">

No errors here; I have just pasted a ~16k token block of code into the chat, and it successfully replied with the speed of Azure's models. 

Thank you & the Cursor team for getting this out so quickly; let me know if you want close this issue!

<img width="519" alt="SCR-20230629-mxzn" src="https://github.com/getcursor/cursor/assets/45819703/354e5575-35a2-4e87-aa6b-8f609bd59a16">

**Comment by danperks** [comment]
Will close as support is available in the latest version :)

**Comment by Mijawel** [comment]
I'm on version 0.7.3 and using an azure 32k api key, however there is no option in the dropdown list to choose 32k as in @duffpop's screenshot above. 

Here is my dropdown:
 
![Screenshot 2023-08-22 at 11 56 35 am](https://github.com/getcursor/cursor/assets/52743180/13276e65-6f8a-4e0c-96ee-da249793e90a)

**Comment by duffpop** [comment]
> I'm on version 0.7.3 and using an azure 32k api key, however there is no option in the dropdown list to choose 32k as in @duffpop's screenshot above.
> 
> Here is my dropdown:
> 
> ![Screenshot 2023-08-22 at 11 56 35 am](https://user-images.githubusercontent.com/52743180/262198044-13276e65-6f8a-4e0c-96ee-da249793e90a.png)

I accidentally discovered the new method of switching models upon mistyping a command. Try opening the Command Palette -> type `switch to `, and you'll see the available models[1]. I presume these are Cursor-related as they are sourced from  `System`[2] as per Cursors's other commands. I was incredibly confused when the option of gpt-4-32k went missing, but once you switch via the command, the option appears in the Cursor Settings modal[3].

1. <img width="623" alt="image" src="https://github.com/getcursor/cursor/assets/45819703/9bcb5f21-802a-4488-a9b0-ab6f09b1180d">

2. <img width="1385" alt="image" src="https://github.com/getcursor/cursor/assets/45819703/9226020a-f5aa-49a3-b41a-77cff2f5bf70">

3. <img width="486" alt="image" src="https://github.com/getcursor/cursor/assets/45819703/e80db482-c2e4-4f6e-a238-2a6aa2695795">

**Comment by Mijawel** [comment]
Thanks that worked!

In the process I worked out a reason why it might disappear. When you are on gpt-4-32k neither of the gpt-4 or gpt-3.5 buttons in the chat pane are highlighted. But when you click one of them, it causes gpt-4-32k to disappear from settings again.
