### ISSUE TITLE
Request to choose which type of files can be auto associated by program

### ISSUE THREAD

**Issue by marvelous007x** [getcursor/cursor#659]
Is there any way to disable this program automatically setting itself as default open method for commonly used programming file types? Such as .cs, .py, .json,etc. 
If this can be done, can you tell me how to do this? I did not find it in any settings.
If not, please give us an option to choose which file types can be associated.

**Comment by truell20** [comment]
Believe this is specific to the OS? If you're on Windows, I think [this tutorial might help?](https://www.lifewire.com/how-to-change-file-associations-in-windows-2624477)

**Comment by marvelous007x** [comment]
> Believe this is specific to the OS? If you're on Windows, I think [this tutorial might help?](https://www.lifewire.com/how-to-change-file-associations-in-windows-2624477)

I know how to change associations,I just do not want to cursor change itself to default for all programming languages without asking.

**Comment by tjwelde** [comment]
on mac it associates itself automatically with all kinds of dev related files. there is no easy way to fix that. Other IDEs do not associate themselves with file types automaticaly and I think it is good that way.

**Comment by tjwelde** [comment]
the fix for me was to unregister cursors file associations with `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -u /Applications/Cursor.app`. After that restart finder with `killall Finder`

**Comment by unknownue** [comment]
This is a really annoying problem.
Basically you have no way to restore the file association after install Cursor.

Hope the dev team to fix this problem. [Related issuse](https://github.com/microsoft/vscode/issues/8687). [Possible fix](https://github.com/microsoft/vscode/commit/d4fac8e98e4bcaa928ffa37988e115f4328bc169).

**Comment by dkampien** [comment]
I'd like to know this as well. I uninstalled cursor and went back to vscode because of this.

**Comment by sinbino** [comment]
In my case, during an automatic update that cursor ran in the background, it associated for cursor without prompting.
This is not a desirable behavior.
