### ISSUE TITLE
Stop charging me!!

### ISSUE THREAD

**Issue by taojiastanford** [getcursor/cursor#661]
I registered a cursor pro, $20 per month, with my credit card ending in 3175. It kept charging me and I did not find where to stop. When I log in via my github account, it shows that I did not upgrade. Yet it kept charging. Need quick response; or I will need to change my credit card number and get another card to prevent it. Please contact me via 562668243@qq.com.
<img width="537" alt="image" src="https://github.com/getcursor/cursor/assets/9204976/11c7df08-6ee0-4bdb-b99b-c134b5b58c41">

**Comment by arvid220u** [comment]
Hi! I responded to you via email. I'm so sorry for the problem here — it's probably a bug on our end, and I've cancelled your subscription and refunded your last payment.

**Comment by kaykenj** [comment]
Hello. I am getting charges also. How can I fix this

**Comment by jiwantadhital** [comment]
@arvid220u my credit card keeps geting declined

**Comment by matthewk** [comment]
I am having the same issue; please resolve it.

**Comment by saifeddin1** [comment]
How do I remove a payment method

**Comment by Hassanmustafa-beyond** [comment]
There was no option to remove the card. While they may believe this is a clever approach, it is causing developers to have a more negative view of the product. Consequently, we will not recommend Cursor to others, as they continued to charge me after I cancelled my subscription and I discovered there is no way to remove my payment information.

**Comment by DeogratiasNiyitanga** [comment]
Please I am having the same issue. How this can be resolved? I am charged all the time, please resolve this ASAP

**Comment by itsallaboutthecheddar** [comment]
Same issue, they charge these crazy prices and then interrupt your prompt to request more money. Honestly hope these people get beaten to death by blacks. Then do this crazy scam shit with your bank. CANCELLED DISPUTED EVERY CHARGE, f u cursor staff and employees

**Comment by ZahidChandio** [comment]
@arvid220u  I am having the same issue as well; it keeps charging me when I have already canceled the subscription.
email: zahidchandio240@gmail.com

**Comment by Pum482930** [comment]
Hi

**Comment by samuelGodad** [comment]
I also faced the same issue. Shame on you, Cursor team—this is an act of theft. There is no way to remove the payment method. I have never seen such nonsense in the modern era of startups. Are you some outdated monopoly, or who are you, that you do not allow me to manage my payment method?
