### ISSUE TITLE
Get stuck while generating an ai project

### ISSUE THREAD

**Issue by Faccococo** [getcursor/cursor#662]
While I'm generating a new ai project, cursor often get stuck at the "Finding related files for ..." step. 
My operating system is MacOS Ventura 13.4
Thanks! 
<img width="1023" alt="Screenshot 2023-06-26 at 22 18 23" src="https://github.com/getcursor/cursor/assets/105764948/c15a3a00-f0d1-4bb3-ac78-d35fccdd7640">

**Comment by sualehasif** [comment]
this is fixed for now. the ai project is on an older server machine and hasnt been ported to our more permanent architecture. we will try to do it soon.
