### ISSUE TITLE
Failed to run Copilot due to self signed certificate

### ISSUE THREAD

**Issue by tomisacat** [getcursor/cursor#663]
- I can not use Copilot any more even after re-install the extension several times, it still fails to work. The OUTPUT says:
    ```
    [INFO] [default] [2023-06-27T02:12:32.583Z] [fetchCompletions] engine https:copilot-proxy.githubusercontent.com/v1/engines/copilot-codex
  [ERROR] [default] [2023-06-27T02:12:33.096Z] Request Error: (FetchError) self signed certificate in certificate chain
    [ERROR] [ghostText] [2023-06-27T02:12:33.097Z] Error on ghost text request: (FetchError) self signed certificate in certificate chain
    ```
    Here's the screenshots:
    
    ![error_1](https://github.com/getcursor/cursor/assets/1179735/3bf55876-4169-4d86-b6f1-87adeeec7c74)
    and
    ![error_2](https://github.com/getcursor/cursor/assets/1179735/265d28bb-cdf6-4af7-83e9-9f7c7ab5bde9)

- My env:
    ```
    Version: 0.2.35
    VSCode Version: 1.79.2
    Commit: e80c1cdffebf532ae90863712f039d6b3c644ea8
    Date: 2023-06-24T21:28:14.549Z
    Electron: 22.3.10
    Chrome: 108.0.5359.215
    Node.js: 16.17.1
    V8: 10.8.168.25-electron.0
    OS: Darwin arm64 22.4.0
    ```

- Steps to reproduce: 
    ```
    1. Open a random source file
    2. Move cursor to a new line to trigger Copilot working
    3. Copilot icon in the bottom right first turns to loading spinner and then turns to exclamation mark, and prompts the above error message.
    ```

**Comment by arvid220u** [comment]
Do you have a corporate proxy in place? Check out this thread: https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot

**Comment by arvid220u** [comment]
Does this happen only in Cursor or also in VSCode?

**Comment by tomisacat** [comment]
> Do you have a corporate proxy in place? Check out this thread: https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot

Not work on my Home Ethernet either, not only my cooperate network. And Cursor failed to search `Win-CA` and prompts:
```
Error while fetching extensions. XHR failed
```
meanwhile VSC found it successfully.

> Does this happen only in Cursor or also in VSCode?

Only in Cursor, VSC works fine.

**Comment by truell20** [comment]
Apologies about this @tomisacat! 

I'm having a hard time reproducing on my end. Is this persistent if you reinstall cursor from cursor.so?

**Comment by tomisacat** [comment]
@truell20 Thanks for you reply. It's persistent after reinstalling the latest release.

**Comment by danperks** [comment]
I doubt it will help, but make sure Cursor is set to be allowed through your firewall if you are on Windows. Not sure where else such an issue could occur considering the feature works for you in VSCode but not Cursor :/

**Comment by tomisacat** [comment]
@danperks Thanks for your suggestion. Actually I'm running Cursor on macOS by copying all of VSC's configuration and installed extensions at first launch, I'm confusing about the behavior difference too.

**Comment by danperks** [comment]
Seems like there is a fix for this, and its not just a Cursor bug, so I'll close this for now.
