### ISSUE TITLE
I can't switch to emacs or "none" editor when I using vim for cursor

### ISSUE THREAD

**Issue by Lyapunova-cd** [getcursor/cursor#664]
![image](https://github.com/getcursor/cursor/assets/71243659/d998aa07-10d0-41a1-93a6-65426611b757)

I'm using cursor on win11 and I didn't take care to choose vim as my editor, then I find cannot switch to another editor once I choosed vim editor
I tried to reinstall cursor by multiple times but cursor always remembered my editor setting.
I only want to switch to a editor that I can use `ctrl+c` normally

**Comment by truell20** [comment]
If you navigate to extensions and uninstall vim, does that work?
<img width="312" alt="Screenshot 2023-06-28 at 2 36 19 PM" src="https://github.com/getcursor/cursor/assets/4297743/0996affa-2
<img width="656" alt="Screenshot 2023-06-28 at 2 37 09 PM" src="https://github.com/getcursor/cursor/assets/4297743/e2d5bd17-6439-432b-a725-28616ec71cab">
0f1-4c9b-befe-4db8bddb2757">

**Comment by Lyapunova-cd** [comment]
> If you navigate to extensions and uninstall vim, does that work? <img width="312" alt="Screenshot 2023-06-28 at 2 36 19 PM" src="https://github.com/getcursor/cursor/assets/4297743/0996affa-2 <img alt="Screenshot 2023-06-28 at 2 37 09 PM" width="656" src="https://user-images.githubusercontent.com/4297743/249620895-e2d5bd17-6439-432b-a725-28616ec71cab.png"> 0f1-4c9b-befe-4db8bddb2757">

Thanks, it works!

**Comment by danperks** [comment]
Will close as resolved :)
