### ISSUE TITLE
cursor怎么关闭问题警告弹框？

### ISSUE THREAD

**Issue by LI-JUIY** [getcursor/cursor#666]
1) 使用cursor 每次保存都会弹出警告 提示  我希望他关闭

![image](https://github.com/getcursor/cursor/assets/68423495/fc3fec5b-5e18-4849-9210-70056fc77122)

**Comment by toryangchen** [comment]
+1，被这个功能折磨了好多天了，找了好久没找到解决方法；
只要有波浪线的提示，都会出现这个弹窗，而且还不会自动消失，非常难用

**Comment by arvid220u** [comment]
Thanks for reporting! I will look into this ASAP

**Comment by arvid220u** [comment]
This should be fixed in the new release, 0.2.39, which is coming out in a few hours! Thanks for reporting.
