### ISSUE TITLE
How to use global context in chat?

### ISSUE THREAD

**Issue by Wooks08** [getcursor/cursor#667]
I'm using cursor for quite a time and I've seen this function that allows chat to ask questions in global context, but now, I cannot see it. Has it been removed or I'm just blind?

**Comment by arvid220u** [comment]
Can you send a screenshot of what the chat looks like for you?

**Comment by Wooks08** [comment]
![image](https://github.com/getcursor/cursor/assets/82082212/b32ca683-3a23-45e8-9997-fc3c11e324c0)

**Comment by arvid220u** [comment]
I see! If you start typing in the "Ask anything... " box, then there should be two buttons in the lower right of the box that say "chat" (enter) and "chat with codebase" (ctrl/cmd-enter). you can use ctrl/cmd enter to submit with codebase context

but this tells me we should make the onboarding experience better wrt codebase context!

(if you still cannot see the chat with codebase option, please re-open the issue)

**Comment by Wooks08** [comment]
is codebase the global context? Because it doesn't sound like this, it more sounds like: "chat with code snippet"
