### ISSUE TITLE
Allow the AI to create files and directories 

### ISSUE THREAD

**Issue by rayshen92** [getcursor/cursor#67]
无法自动创建目录和文件夹

**Comment by gdbless** [comment]
Use 'Enter' key.

**Comment by truell20** [comment]
could you send some example prompts where you'd want cursor to create files and directories for you?

**Comment by danperks** [comment]
This is now a feature, using the AI project generation feature!

**Comment by MultiUpGame** [comment]
No matter what I write in the cursor, it Doesn't Create Files!!!! In Composer
Generate File, Create File, don't write text but generate code in the file, etc.
