### ISSUE TITLE
can't entering characters with cmd+K

### ISSUE THREAD

**Issue by volcanomao** [getcursor/cursor#670]
When I press cmd+K to open the input box, pressing a letter key automatically triggers a shortcut, such as pressing F to directly pop up the search box, which has the same effect as cmd+K. This prevents me from entering characters with cmd+K.

: 0.2.43
: 1.79.2
: 56ee7fce302518f7d8904603a5b0b7e37312e2ce
Electron: 2023-07-05T20:28:36.918Z
Chromium: 22.3.10
Node.js: 108.0.5359.215
V8: 16.17.1
OS: 10.8.168.25-electron.0
<img width="1119" alt="截屏2023-07-06 16 40 00" src="https://github.com/getcursor/cursor/assets/26328908/cc74d922-ab72-44ba-9604-923ef93b1368">

**Comment by truell20** [comment]
Should be fixed in the latest version (released ~6 hours ago)! Thanks for reporting this. Please let me know if you run into any difficulties.
