### ISSUE TITLE
error of top menu bar

### ISSUE THREAD

**Issue by qwert-f** [getcursor/cursor#674]
on fedora38 two menu bar show  and while system exit button is useful the editor still show me a same button

**Comment by Sanger2000** [comment]
Could you attach a screenshot of what this looks like?

**Comment by qwert-f** [comment]
> Could you attach a screenshot of what this looks like?

![mmexport1689116730672.jpg](https://github.com/getcursor/cursor/assets/50124761/48a70bb8-d032-4998-a9bf-756cf453f5f7)

**Comment by qwert-f** [comment]
> Could you attach a screenshot of what this looks like?

problem still not fix on 0.2.47，Could you tell me this problem cause by Cursor or vscodium

**Comment by yurenchen000** [comment]
meet same appearance on ubuntu22, cursor 0.35.0.

I just avoid this problem via vscode settings:
- `window: menu bar visibility` = toggle //have to use alt toggle menu, but native menu will not display now
- `window: title bar style` = custom
