### ISSUE TITLE
Need customizing the API server address

### ISSUE THREAD

**Issue by tcmonster** [getcursor/cursor#675]
I have openai API key but the access is very unstable. In daily use, I will build my own forwarding server. I need cursor support to let me enter a custom address to send the API key.

**Comment by truell20** [comment]
Thanks for writing in! I want to help fix this problem for you.

To clarify, are you looking to have the editor send requests directly to your forwarding server? Or have our backend send requests to your forwarding server?

Do you have any request ids or error screenshots from when you get instability? Absolutely want to patch any issues you're seeing here.

**Comment by tcmonster** [comment]
Actually, I can't access api.openai.com stably due to some network issues. all I just need is a way to set up a custom server address like other tools offers. so I can send my API Key to a proxy server there.
<img width="725" alt="2023-07-09 18 05 12" src="https://github.com/getcursor/cursor/assets/34400653/4fcb0fbc-c9a1-43e5-9d5e-dba73b693908">

it's not a bug but a feature request. thank you so much if there's any plan to provide this feature.

**Comment by SkyStarKing** [comment]
+1

**Comment by Sanger2000** [comment]
I dont think we'll have the bandwidth to build this out in the short term. Do you see similar instability issues when you use Cursor's GPT-4 (rather than an OpenAI API Key?)

**Comment by tcmonster** [comment]
> I dont think we'll have the bandwidth to build this out in the short term. Do you see similar instability issues when you use Cursor's GPT-4 (rather than an OpenAI API Key?)

Thank you for the reply. I thought it's actually simpler than you imagine. Given that you offer the features to use our own API Keys, there must be a part of code where each AI request is sent to the domain "api.openai.com". Now it just need to open the configuration for this domain, without even an UI, we can simply set it through a config file manually

**Comment by Sanger2000** [comment]
Closing this to continue the thread in #635
