### ISSUE TITLE
Unknown method $provideTextSearchResults on actor ExtHostTask

### ISSUE THREAD

**Issue by benherve** [getcursor/cursor#678]
Error message when searching strings.

![image](https://github.com/getcursor/cursor/assets/121860265/5e31cba1-5882-4b35-8a31-08ddcaeb6856)

![image](https://github.com/getcursor/cursor/assets/121860265/ea6d78b2-4f68-49d9-9867-3c7349895d41)

**Comment by truell20** [comment]
Could you reach out to hi@cursor.so? We can send you a build that we think has a fix.

**Comment by learno** [comment]
After installing the WSL extension using the method in the link [https://github.com/getcursor/cursor/issues/660#issuecomment-1630025267](https://github.com/getcursor/cursor/issues/660#issuecomment-1630025267), I encountered the same problem when I upgraded from version 0.2.38 to 0.2.44. 
By replacing the files  `Cursor\resources\app\out\vs\workbench\workbench.desktop.main.js` and `Cursor\resources\app\out\vs\workbench\api\node\extensionHostProcess.js` from version 0.2.38 to the new version, it was work for me, although it would display "Your Cursor installation appears to be corrupt. Please reinstall."

Here is the download link for the replacement files. After unzipping, overwrite the resources folder in the Cursor installation directory. [[https://drive.google.com/file/d/1XdaFmAKIcTiQ4-PIQQJmvaLpqCYU1RiO/view](url)](https://drive.google.com/file/d/1XdaFmAKIcTiQ4-PIQQJmvaLpqCYU1RiO/view)

**Comment by benherve** [comment]
thanks, and for the futurs updates, do we need, to apply again the files ?

**Comment by learno** [comment]
> thanks, and for the futurs updates, do we need, to apply again the files ? and, i tried to delete server-env-setup then restart cursor, problem already present
Yes, it's sad until the official bug fix. This issue has nothing to do with server-env-setup.

**Comment by benherve** [comment]
> > thanks, and for the futurs updates, do we need, to apply again the files ? and, i tried to delete server-env-setup then restart cursor, problem already present
> > Yes, it's sad until the official bug fix. This issue has nothing to do with server-env-setup.

but you talk about https://github.com/getcursor/cursor/issues/660#issuecomment-1630025267
and he modify server-env-setup

**Comment by truell20** [comment]
Should be fixed latest version! Apologies about this. A recent update had introduced this bug on WSL and SSH connections.
