### ISSUE TITLE
Cmd + K shouldn't trigger when terminal is focused

### ISSUE THREAD

**Issue by MaxMusing** [getcursor/cursor#679]
I regularly use Cmd + K to clear my terminal. Cursor overrides this with the generate command, even if the terminal is focused. I would expect the generate command to only trigger when my cursor is in the main code editor, allowing me to use Cmd + K to clear the terminal when the terminal is focused.

# Solution
Change the "when" expression for the `Open Edit` command from `!isPromptModalOpen` to `editorTextFocus && !isPromptModalOpen` (or alternatively, `!terminalFocus && !isPromptModalOpen`).

**Comment by Sanger2000** [comment]
Patched! Will be out in tonight's release!
