### ISSUE TITLE
Only enable history navigation when input field is bank

### ISSUE THREAD

**Issue by Fire-** [getcursor/cursor#68]
via Discord: 
> When I'm writing a longer prompt, if I accidentally press the up arrow key to move to an earlier line of the prompt I'm writing, it goes back to the previous prompt instead but then when I press the down arrow key to come back, because I haven't submitted the new prompt, it's lost.

This affects the the command window and the chat. 
Desired outcome: history navigation should be disabled when there's text in the input field. At present editing multi-line messages or prompts is impractical.

**Comment by Sanger2000** [comment]
Fixed in the newest version. Thanks for reporting!
