### ISSUE TITLE
Local Codebase Indexing

### ISSUE THREAD

**Issue by awfuel** [getcursor/cursor#680]
**Is your feature request related to a problem? Please describe.**
I work on things that I cannot trust statements of "We do this without storing your code on our servers!" 

It should be no problem to store these in a local vectordb (plugin authors, here is your chance to shine!).

**Describe the solution you'd like**
I want to store embeddings of a git repo locally.

**Additional context**
![image](https://github.com/getcursor/cursor/assets/139133236/ba988273-afb3-47d0-b484-7fff2eb4109b)

**Comment by Sanger2000** [comment]
We are planning on supporting this soon. Probably in the next two weeks.

For now, the way it works is we store only the embeddings and filenames in a vector database (pinecone) and everything else locally.

**Comment by mrcodechef** [comment]
This issue was closed, but it doesn't seem to have actually been implemented. Embeddings still seem to be stored in the cloud. https://forum.cursor.com/t/file-ignore-lists-and-auditable-security/2507/4
