### ISSUE TITLE
The cursor is not as smart as it used to be

### ISSUE THREAD

**Issue by CHTUZKI** [getcursor/cursor#681]
HI.

Recently, I found that the cursor is not as smart as it used to be. Even after switching from GPT3.5 to GPT4.0, I didn't notice much difference. Now the cursor prefers to use more generalized language to answer your questions, and the answers are not accurate. It also tends to repeat itself. The responses from GPT3.5 and GPT4.0 are basically the same.

I have been using chatPDF recently, which is a website that allows you to upload PDF files and answer questions based on the content of the file. I found that chatPDF is much smarter. For example, if I have a sample program and I want chatPDF to modify or rewrite some of the code based on the content I provide, I need to copy the code to a Word document, export it as a PDF file, and then upload it to chatPDF. ChatPDF can provide very accurate answers. However, if I copy the same code to the cursor, the results are very disappointing. If chatPDF could upload .txt files, it could even replace the cursor.

I wrote a program in Python that can copy all the code in all the code files of a project into one file, which can then be converted to a PDF and uploaded to chatPDF. ChatPDF's ability to handle context is far better than the cursor's, but it is not as convenient to use, at least for programmers. So I am providing feedback in the hope that the cursor can become better.

Best regards.

**Comment by truell20** [comment]
Hi @CHTUZKI, apologies that you're seeing issues here. Do you have any idea how to reproduce these problems? Are they only on the chat or also cmd-k? Do they happen for all conversations or especially long ones? If you're not sure, some screenshots of the conversations could help. If they contains sensitive info, then feel free to msg us at hi@cursor.so. Do you use an API key or?

We still use the same models and I believe OpenAI has promised not to change the weights of the models behind their tagged API keys, so not immediately sure what's going on. Perhaps this is from a change from our prompt building process, though I'm not sure much has changed recently there for normal chats.

Either way, want to figure out what's going wrong here and fix it for you.

**Comment by CHTUZKI** [comment]
For example:
![BY8O3@8(NSG3)PN7XGBY0R7](https://github.com/getcursor/cursor/assets/42321222/ae936e4a-6a0c-42ac-891c-af361b2b575e)
![(Q~MBRPH}QSK99IF FZ(6PR](https://github.com/getcursor/cursor/assets/42321222/dadc62c6-9f38-45c4-a0ac-779ca60b1522)
![YKL0$VNY(%U08R@5@0`JWTL](https://github.com/getcursor/cursor/assets/42321222/e0030450-0f75-4495-bcab-9e5a11206e3a)

**Comment by Sanger2000** [comment]
It looks like these were all generated with gpt-3.5. What happens if you click `gpt-4` then try again?
<img width="99" alt="Screen Shot 2023-07-17 at 7 34 33 PM" src="https://github.com/getcursor/cursor/assets/17725268/db0d5cd1-bd89-438c-a923-dcdd261857c7">
