### ISSUE TITLE
No way to exit vim mode

### ISSUE THREAD

**Issue by awfuel** [getcursor/cursor#682]
I need a way to exit vim mode (I don't like it) and there is no obvious way to change this post install.

**Comment by truell20** [comment]
You should be able to turn off vim mode by disabling it in settings. If you don't see it in the bar, try typing '@builtin' in the inputbox.

<img width="291" alt="Screenshot 2023-07-17 at 5 00 56 PM" src="https://github.com/getcursor/cursor/assets/4297743/bf2aa71c-6550-42b0-87dc-f7d792b78324">
<img width="257" alt="Screenshot 2023-07-17 at 5 01 02 PM" src="https://github.com/getcursor/cursor/assets/4297743/93d82719-0db2-4a5b-8131-21629bd14622">

To check to see if there was a bug here on our end: did you install the vim extension, import vim through the "import vscode extensions" feature, or set the vim keybindings on the first onboarding screen?

**Comment by BARMPlus** [comment]
It was added through the settings during initialization, and the extension was moved later. I think this is the reason why most people can't find it。

**Comment by imddc** [comment]
Is the support of vim in cursor implemented through the extension function of vscode? Is there only one way?
