### ISSUE TITLE
"window.commandCenter" setting always change back to 1 after restart/reload cursor

### ISSUE THREAD

**Issue by MobsMao** [getcursor/cursor#683]
1) If you can, please include a screenshot of your problem
First, change the setting to 0.
<img width="404" alt="image" src="https://github.com/getcursor/cursor/assets/9639541/7842d622-5407-4889-b49f-bf750ad992da">

Then close all the cursor windows (don't need to be quit cursor)

Then, open cursor, setting back to 1
<img width="442" alt="image" src="https://github.com/getcursor/cursor/assets/9639541/f37cbfe4-ef6f-4f03-ae58-860e8b78f6cd">

2) Please include the name of your operating system
MacOS 13.4.1 
3) If you can, steps to reproduce are super helpful
See in Step 1

**Comment by truell20** [comment]
@sualehasif Could you provide context on why we set this default? Is this something we should revert?

**Comment by Sanger2000** [comment]
This will be fixed in our new release today
