### ISSUE TITLE
Scrollbar issue in the chat dialog of the cursor

### ISSUE THREAD

**Issue by CHTUZKI** [getcursor/cursor#684]
HI.

I am having cursor change the code for me and the cursor's chat window has provided me with a long code. I tried to drag the scrollbar, but there is an issue with the minimum value of the scrollbar. When I drag the scrollbar all the way to the left, the window displaying the code still cannot show the entire code.

![image](https://github.com/getcursor/cursor/assets/42321222/3fdd7b54-b18b-4fc2-a469-520ca895a484)
![image](https://github.com/getcursor/cursor/assets/42321222/4e8828fb-0739-4d2c-9afc-7a88eae73df9)

**Comment by truell20** [comment]
Apologies about this. I've never seen this on my end before. Do you have any tips on how to reproduce? Any idea on which codeblocks it shows up on for you?

**Comment by CHTUZKI** [comment]
I have tried many times, but I have not been able to reproduce this error. It may be an issue with my Windows system, or perhaps some very unusual coincidence.≡(▔﹏▔)≡≡(▔﹏▔)≡≡(▔﹏▔)≡
