### ISSUE TITLE
Cannot access to OpenAI API

### ISSUE THREAD

**Issue by JochenLee666** [getcursor/cursor#686]
since last month I cannot use my API to access gpt. I make sure the api key is valid but always shows this error. What can I do?

**Comment by truell20** [comment]
Deleting this message so you don't leak your key

**Comment by truell20** [comment]
Your image contained your API key. Please cancel your API key, so people don't abuse your key for their own purposes.

**Comment by truell20** [comment]
Back to the Cursor questions: What do you see when you run the cURL command we tell you to run? Do you get an error or does it go through? This cURL command hits OpenAI's API and should give you the ground truth on whether your key works.

If your key does work, please let me know. That means we have a bug.

**Comment by JochenLee666** [comment]
![image](https://github.com/getcursor/cursor/assets/97000701/254b78fc-ced9-4195-899f-03704fcb94b9)
Please find the error code. Sorry about that in Chinese. The error is the value of **System.ArgumentOutOfRangeException** must be larger or equal to 0, and must be smaller than the size of the console buffer in that dimension. But the real value is -5.

When I try to call this API key in cursor, it shows up on the website as having been invoked.

**Comment by JochenLee666** [comment]
I use the same API on the previous version 0.2.7, it works perfectly. But in the latest version 0.2.51, it always reports an error.

**Comment by truell20** [comment]
If you're comfortable, you temporarily send me your key at michael@cursor.so? This will help me debug this issue.

**Comment by truell20** [comment]
Just checking in here

**Comment by JochenLee666** [comment]
Already sent it to you. Thanks for your check.

**Comment by truell20** [comment]
Just checked. Seemed like the key was out of quota. Replied to your email.
