### ISSUE TITLE
no theme

### ISSUE THREAD

**Issue by oricou** [getcursor/cursor#688]
I have seen that there should be themes in the new version, but I cannot find how to select one. The AI help of the home page suggest that the VSCode theme I choosed will be used. No, it does not. Any hint?

Version: 0.2.48
VSCode Version: 1.79.2
Commit: 96d30293dc5f2f08c5f73965c746b982d5994f43
Date: 2023-07-16T07:47:12.489Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-70-generic

**Comment by truell20** [comment]
Apologies about this. We've identified the bug here, and this will be fixed in the next version of Cursor. Thanks for reporting.

**Comment by truell20** [comment]
In the meantime, you can find the theme menu by doing Cmd+Shift+P and then by typing "theme"

**Comment by truell20** [comment]
Think this issue is fixed!
