### ISSUE TITLE
"New AI Project" completely broken after update

### ISSUE THREAD

**Issue by jamesheinlein** [getcursor/cursor#689]
Prompt around 5000 tokens (just a project description). Getting this incorrect output:
<img width="541" alt="Screen Shot 2023-07-19 at 2 40 35 PM" src="https://github.com/getcursor/cursor/assets/12645111/2d9e9058-22d4-4ebc-959a-eec79629df99">

**Comment by jamesheinlein** [comment]
0.2.49 btw

**Comment by truell20** [comment]
Thanks for reporting this! Could you send your prompt to me? If you'd like to do it privately, please email michael@cursor.so.

**Comment by danperks** [comment]
Feature is removed, the Composer can be used instead :)
