### ISSUE TITLE
hope the model selection can directly fill in the model name or provide more model options to choose from

### ISSUE THREAD

**Issue by FantasicMo** [getcursor/cursor#690]
The current model has been upgraded to gpt-35-turbo-16k. I hope the model selection can directly fill in the model name or provide more model options to choose from.

**Comment by sualehasif** [comment]
We upgrade to the 16k model :) In general, we will always be using the bleeding edge of the available models.

**Comment by FantasicMo** [comment]
> We upgrade to the 16k model :) In general, we will always be using the bleeding edge of the available models.

I'm referring to the configuration of Azure API or OpenAI API, Right now I want to use my own Azure API configuration, but the model only has 3.5 turbo available, not 35-turbo-16k for me to choose from.
