### ISSUE TITLE
Add Claude 2 instead of GPT-3.5

### ISSUE THREAD

**Issue by kuatroka** [getcursor/cursor#695]
**using Claude 2 felt better than GPT-4. It's not a scientific or statistic statement, but since trying Claude 2, I found myself not wanting to use GPT-4. At least not for coding.

**Describe the solution you'd like**

**Additional context**

**Comment by arvid220u** [comment]
Interesting! Do you have any examples where Claude 2 is better than GPT-4? 

If it's useful, we definitely want to add Claude 2 for people.

**Comment by kuatroka** [comment]
As I said, it's more of a nonscientific feeling that I use it more often than GPT-4, but here is one example

PROMPT START:
add a column to calculate value per quarter for every cik
```
SELECT
    quarter,
    (COUNT(DISTINCT cik))::integer as num_ciks_per_quarter,
    (COUNT(DISTINCT cusip))::integer as num_cusip_per_quarter,
    (SELECT COUNT(DISTINCT cik) FROM main.main WHERE accession_number != 'SYNTHETIC-CLOSE')::integer as total_ciks,
    ROUND((COUNT(DISTINCT cik) - LAG(COUNT(DISTINCT cik)) OVER (ORDER BY quarter)) / LAG(COUNT(DISTINCT cik)) OVER (ORDER BY quarter),2)*100 AS prc_change_cik,
    ROUND((COUNT(DISTINCT cusip) - LAG(COUNT(DISTINCT cusip)) OVER (ORDER BY quarter)) / LAG(COUNT(DISTINCT cusip)) OVER (ORDER BY quarter),2)*100 AS prc_change_cusip,
FROM main.main
WHERE accession_number != 'SYNTHETIC-CLOSE'
GROUP BY quarter
ORDER BY quarter DESC
```
PROMPT END:
#####################
GPT-4 SOLUTION:  DOESN'T WORK
```
SELECT
    quarter,
    (COUNT(DISTINCT cik))::integer as num_ciks_per_quarter,
    (COUNT(DISTINCT cusip))::integer as num_cusip_per_quarter,
    (SELECT COUNT(DISTINCT cik) FROM main.main WHERE accession_number != 'SYNTHETIC-CLOSE')::integer as total_ciks,
    ROUND((COUNT(DISTINCT cik) - LAG(COUNT(DISTINCT cik)) OVER (ORDER BY quarter)) / LAG(COUNT(DISTINCT cik)) OVER (ORDER BY quarter),2)*100 AS prc_change_cik,
    ROUND((COUNT(DISTINCT cusip) - LAG(COUNT(DISTINCT cusip)) OVER (ORDER BY quarter)) / LAG(COUNT(DISTINCT cusip)) OVER (ORDER BY quarter),2)*100 AS prc_change_cusip,
    AVG(value) OVER (PARTITION BY cik ORDER BY quarter) as value_per_cik_per_quarter
FROM main.main
WHERE accession_number != 'SYNTHETIC-CLOSE'
GROUP BY quarter
ORDER BY quarter DESC
```

Error:
"Binder Error: column "value" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(value)" if the exact value of "value" is not important.
LINE 8:     AVG(value) OVER (PARTITION BY cik ORDER BY quarter) as value_per_cik_per_quarter
FROM main.main
WHERE accession_number != 'SYNTHETIC-CLOSE'
GROUP BY quarter
ORDER BY quarter DESC."


############
CLAUDE 2 SOLUTION: WORKS FROM THE GET GO
```
SELECT
    quarter,
    (COUNT(DISTINCT cik))::integer as num_ciks_per_quarter,
    (COUNT(DISTINCT cusip))::integer as num_cusip_per_quarter,
    (SELECT COUNT(DISTINCT cik) FROM main.main WHERE accession_number != 'SYNTHETIC-CLOSE')::integer as total_ciks,
    ROUND((COUNT(DISTINCT cik) - LAG(COUNT(DISTINCT cik)) OVER (ORDER BY quarter)) / LAG(COUNT(DISTINCT cik)) OVER (ORDER BY quarter),2)*100 AS prc_change_cik,
    ROUND((COUNT(DISTINCT cusip) - LAG(COUNT(DISTINCT cusip)) OVER (ORDER BY quarter)) / LAG(COUNT(DISTINCT cusip)) OVER (ORDER BY quarter),2)*100 AS prc_change_cusip,
    SUM(value) / COUNT(DISTINCT cik) AS value_per_cik 
FROM main.main
WHERE accession_number != 'SYNTHETIC-CLOSE'
GROUP BY quarter
ORDER BY quarter DESC
```

**Comment by kuatroka** [comment]
There are some score metrics and interpretation for both GPT-4 and Claude 2 in this Twitter post.

https://twitter.com/DrJimFan/status/1678809539846770688?s=20

**Comment by jakobFNF** [comment]
[Regarding Claude 2:](https://forum.cursor.sh/t/integration-of-claude2-into-cursor/739/4)

![image](https://github.com/getcursor/cursor/assets/74077124/bf0d0675-ee93-4e77-aa7e-ba144bf71096)

[Regarding using other AI models:](https://discord.com/channels/1074847526655643750/1132959501474082928/1145935934588723220)

![276773960-fe3b199d-71b6-4673-b7ac-b251bb0d79fd](https://github.com/getcursor/cursor/assets/74077124/7ed113de-1e34-46b7-812e-389eaa72512a)

**Comment by kuatroka** [comment]
Got it. I agree, the code is generation can be tricky. When it's good , it's very good and from the get go, from the first try (SQL in my experience), but if it's bad...no way to bring it to writing something congruent.

**Comment by deepakgupta33** [comment]
What are your thoughts on the new Claude-3 Opus model? I think it is even better than GPT-4.
