### ISSUE TITLE
Jupyter is till broken in 0.3.1

### ISSUE THREAD

**Issue by xl0** [getcursor/cursor#696]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

On Linux

![image](https://github.com/getcursor/cursor/assets/439415/e3e3342f-1f85-49ef-a5ae-02032769f8d8)

The generated text includes pieces of both previous cells' output and just random code for previous cells.
(I was using openai python library in my code, this openai stuff is not coming from your end)

**Comment by truell20** [comment]
Looking into this right now!

**Comment by truell20** [comment]
Are you using GPT-3.5 or GPT-4?

**Comment by truell20** [comment]
Just pushed a backend fix that should improve this (for GPT-3.5 and GPT-4!). Please let me know if the problem is still showing up for you. If so, I'll want to dig in further. Thanks for reporting this.

**Comment by xl0** [comment]
Thank you for the quick reply. I will give it a try in a bit. I was using gpt-4.

Maybe Jupyter deserves a more structured format when it comes to using it as context. Maybe you could treat each cell in a way that is similar to treating separate files?

**Comment by xl0** [comment]
Ok, just gave it a try, and it seems to work! Thank you.

<img width="376" alt="image" src="https://github.com/getcursor/cursor/assets/439415/ed220b4b-6047-4a07-a2ea-394d889e34c7">
