### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by eventualbuddha** [getcursor/cursor#697]
1) If you can, please include a screenshot of your problem
<img width="743" alt="typo" src="https://github.com/getcursor/cursor/assets/1938/7f609364-b3ae-4f23-83f1-c47e987e9a14">

2) Please include the name of your operating system
macOS

3) If you can, steps to reproduce are super helpful
Install the app, view README.md on first launch.

**Comment by truell20** [comment]
Thanks for reporting! Will be fixed in next version (see [here](https://github.com/getcursor/tutor)).
