### ISSUE TITLE
Prompt responses containing '#' are cut off

### ISSUE THREAD

**Issue by LiZhouhang** [getcursor/cursor#698]
Such as:
![c77e7f23-f2b8-4989-9756-f92c2ef86448](https://github.com/getcursor/cursor/assets/25278392/d9981876-6370-46d2-983f-b2ad6f689bec)
![image](https://github.com/getcursor/cursor/assets/25278392/872cc86f-c621-4af7-bdbb-940eb03270f0)
![image](https://github.com/getcursor/cursor/assets/25278392/b87ca9e8-5550-4ff2-9db8-ecdd6f3aa6e2)
It losts the '#' and the font size of the context after becomes bigger.

**Comment by arvid220u** [comment]
Thanks for reporting this! We have pushed a fix to our nightly release and will include this in our next production release in the next few days.
