### ISSUE TITLE
cannot install C/C++ extension

### ISSUE THREAD

**Issue by filwab** [getcursor/cursor#699]
1) cannot install C/C++ extension
2) windows

when i use cursor in a c++ project, i install c/c++ extention. then warningh:
Can't install 'ms-vscode.cpptools' extension because it is not compatible with thecurrent version of VSCodium (version 1.80.1).
version conflict problem like this ,how should i solve it , thanks in advance

**Comment by arvid220u** [comment]
Thanks for reporting this! I am looking into this right now and will have a fix for you very soon.

**Comment by arvid220u** [comment]
@filwab We believe we have a fix for this! Could you install the nightly version of Cursor and try again? If it doesn't work for you, please just reopen this issue.

Nightly download link: https://www.cursor.so/nightly
Email that you can use: download_nightly@cursor.so
