### ISSUE TITLE
Copilot Sign-in not working

### ISSUE THREAD

**Issue by Sanger2000** [getcursor/cursor#7]
For some reason, the copilot login flow isn't initialized when starting up the application

**Comment by flutterhue** [comment]
same!

**Comment by musitafa0032** [comment]
Same, it is not initialized.

**Comment by glon** [comment]
Same

**Comment by OnePieceJoker** [comment]
Same. my cursor version is v0.1.7

**Comment by OnePieceJoker** [comment]
#91

**Comment by OnePieceJoker** [comment]
#112

**Comment by TitanRob16** [comment]
The sign in button does nothing for me at the moment.

**Comment by truell20** [comment]
Should be in the newest version 🙂
