### ISSUE TITLE
How do I make the suggestion sort order not be stupid?

### ISSUE THREAD

**Issue by malcolmocean** [getcursor/cursor#701]
For some reason I can't use tab-completion at all. I'm coming from Sublime, where it would grab only items from the same file. I'm all for smarter systems, but instead these systems are stupid — they prioritize grabbing irrelevant functions from other files.

eg here I'm looking for setUpVideo and setUpCanvas, but instead it shows me setTimeout and setup from some completely unrelated projects. I tried turning on editor.suggest.localityBonus but it didn't help at all!

<img width="682" alt="image" src="https://github.com/getcursor/cursor/assets/788384/b728ecd8-97f5-4619-8447-f30b71829d18">

If there's a better place to direct questions than this, let me know!

**Comment by arvid220u** [comment]
Maybe setting `editor.suggest.localityBonus` to true could help? (open the settings pane with cmd-comma, and then type that into the search bar)

You can also explore other suggestion settings by just searching for "suggest" in the settings pane.

Lmk if that solves or doesn't really solve the problem!

**Comment by jakobFNF** [comment]
Due to inactivity and the fact that this issue doesn't appear to be specific to Cursor, I will close this issue for now.
