### ISSUE TITLE
I click on the end of the current line, the cursor is not where it should be

### ISSUE THREAD

**Issue by sunday20120713** [getcursor/cursor#711]
![微信截图_20230802100038](https://github.com/getcursor/cursor/assets/52777293/8d89365e-ea0f-4ca8-a00a-0133bc43ca40)

**Comment by arvid220u** [comment]
Thank you for reporting this! This is fixed in the latest nightly release (0.7.2-nightly) and we will be pushing this out to the main release very soon.
