### ISSUE TITLE
Adding a new @Doc results in an error message

### ISSUE THREAD

**Issue by sammykumar** [getcursor/cursor#716]
1) If you can, please include a screenshot of your problem

Please refer to the attached loom video: https://www.loom.com/share/776dbeada9ed47beace656e0c1d1b618?sid=cc103077-fbab-4527-8339-de9ea858fbec

2) Please include the name of your operating system

MacOS Sonoma Version 14.0 Beta (23A5301h)

**Cursor.so Info**
Version: 0.6.0
VSCode Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-31T23:16:37.262Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.0.0

_Note_ I am using my own GPT4 API KEy

3) If you can, steps to reproduce are super helpful
Please refer to the attached loom video: https://www.loom.com/share/776dbeada9ed47beace656e0c1d1b618?sid=cc103077-fbab-4527-8339-de9ea858fbec

It appears I can add my own custom doc source, but a connection failed error modal appears behind the new @doc modal. I believe this prevents me from saving the new @doc source and, thus not allowing me to use it. At first, I thought my prompt was using it, but on closer inspection, it is using the built-in `PHP Docs`, not the `PHP Debug Bar` docs I added. This occurs regardless of the documentation that I am trying to add.

**Comment by truell20** [comment]
Apologies about this! Should be fixed now. Please let me know if you run into any further issues.

**Comment by sammykumar** [comment]
> Apologies about this! Should be fixed now. Please let me know if you run into any further issues.

Thanks @truell20...Is this update server side, or do I need to update my Cursor.so app client side? I still get the error this morning.

**Comment by truell20** [comment]
Sorry for prematurely closing this. Are you still getting the same error?

**Comment by sammykumar** [comment]
No worries @truell20. It's working post your update. The update functionality within Cursor never worked for me but I just downloaded the installer and reinstalled it that way.  Thanks for checking in.
