### ISSUE TITLE
Dev - containers extension not working

### ISSUE THREAD

**Issue by notbogdan** [getcursor/cursor#718]
Whenever I try and open my devcontainer with the extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

I get an error: Failed to connect to the remote extension host server (Error: Connection error: Client refused: version mismatch)

**Comment by notbogdan** [comment]
Closed in favour of thread on https://discord.com/channels/1074847526655643750/1138372403404214313

**Comment by notbogdan** [comment]
Closed in favour of thread on https://discord.com/channels/1074847526655643750/1138372403404214313

**Comment by shankscoder** [comment]
I would like to reopen this as the outcome of that thread should be tracked here in Github so that anyone else facing a similar issue would be able to see the resolution on Github directly. As of August 18, 2023, there hasn't been a resolution yet, so this still is an open issue.

This is a blocker to using Cursor with any Devcontainer based project, which for a lot of us is the base requirement.

**Comment by bamps53** [comment]
+1 waiting for dev container support. Especially for attaching to remote dev container.

**Comment by robertavram-md** [comment]
+1 - Cant use Cursor with remote docker container

**Comment by adharm** [comment]
+1

**Comment by oswaldoo** [comment]
+1

**Comment by chrisrickard** [comment]
+1

**Comment by hanw** [comment]
+1 This is a must-have feature.

**Comment by NevoleMarek** [comment]
+1

**Comment by daniel-merrick** [comment]
+1

**Comment by andyg5000** [comment]
Here's where mine starts to fall apart. I'm using an alpine dev container and VSCode works fine. I did some debugging on this, but didn't get far unfortunately. 

```
[4076 ms] [13:38:46] Extension host agent started.
[4109 ms] [13:38:46] No uninstalled extensions found.
[4113 ms] [13:38:46] Started initializing default profile extensions in extensions installation folder. file:///root/.cursor-server/extensions
[4121 ms] [13:38:46] ComputeTargetPlatform: alpine-arm64
[4130 ms] [13:38:46] Completed initializing default profile extensions in extensions installation folder. file:///root/.cursor-server/extensions
[4346 ms] Port forwarding 62105 > 32901 > 32901 stderr: Connection established
[4359 ms] Port forwarding connection from 62117 > 32901 > 32901 in the container.
[4359 ms] Start: Run in container: /root/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node -e 
[4361 ms] Start: Reconnection attempt 1
[4361 ms] Start: Run: docker inspect --type container 05d3c0b0890654075869f778aa395145ee73f0e5cbfd5dac92ad1547f7d938ba
[4362 ms] Port forwarding 62105 > 32901 > 32901 stderr: Remote close
[4374 ms] Port forwarding 62105 > 32901 > 32901 terminated with code 0 and signal null.
[4375 ms] Port forwarding 62105 > 32901 > 32901: Local close
[4536 ms] Port forwarding 62117 > 32901 > 32901 stderr: Connection established
[4548 ms] Port forwarding 62117 > 32901 > 32901 stderr: Remote close
[4549 ms] Port forwarding connection from 62130 > 32901 > 32901 in the container.
```

**Comment by bagavi** [comment]
Our whole company of 20 developers is currently blocked by this.

**Comment by benharrell** [comment]
+1 I just had to install DEV tools on my ACTUAL machine like I woke up in the 90s 🤣

**Comment by EntropyFails** [comment]
+1

**Comment by andyg5000** [comment]
Been trying to figure this out all day with no luck :(  However, here are some more relevant logs from the net connection that the extension tries to create with the code-server running in the container. I believe the error stems from the fact that the code-server is doing a version comparison and aborting with "Client refused: version mismatch" . 

```
[3264 ms] Port forwarding 59621 > 41063 > 41063 stderr: �~��{"type":"sign","data":"RWT/5W0FKK+UyZAWrXuNObeCjS8tl3yW05tDaA82MBE=","signedData":"527ojdTHPQxKocoRxWUaSH0qxFJqLBXBakiFYggC74mlOM="}
[3267 ms] Port forwarding 59621 > 41063 > 41063 stderr: �I<{"type":"error","reason":"Client refused: version mismatch"}
[3269 ms] Start: Reconnection attempt 4
[3269 ms] Start: Run: docker inspect --type container 03b65debd799b24223c187ac75b2131bb841c3e2d948c5bf34710e06f301aec4
[3270 ms] Port forwarding 59621 > 41063 > 41063 stderr: Remote close
[3271 ms] Port forwarding connection from 59626 > 41063 > 41063 in the container.
[3271 ms] Start: Run in container: /root/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node -e 
[3287 ms] Port forwarding 59621 > 41063 > 41063 terminated with code 0 and signal null.
[3287 ms] Port forwarding 59621 > 41063 > 41063: Local close
[3446 ms] Port forwarding 59626 > 41063 > 41063 stderr: Connection established
[3449 ms] Port forwarding 59626 > 41063 > 41063 stderr: HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: 0HZaMDJofx68oUUj3dKtzxpE5uc=
```

**Comment by garrettlancaster** [comment]
+1

**Comment by tonydavis629** [comment]
I'm also part of the 'love cursor but need this feature' club

**Comment by francovp** [comment]
I'm receiving a diferent error when trying to create a new dev container, the extension tries to install the VS Code server but fails with HTTP 404 error

```sh
[6000 ms] Installing VS Code Server for commit 30d21e59529ff0a52d8a847c419e668f2fd2d620
[6000 ms] Start: Run in container: /bin/sh
[6002 ms] Start: Downloading VS Code Server
[6002 ms] 30d21e59529ff0a52d8a847c419e668f2fd2d620 linux-x64 stable 
[7718 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:30d21e59529ff0a52d8a847c419e668f2fd2d620/server-linux-x64/stable): HTTP 404 - Not Found
[7719 ms] Retrying to download VS Code Server.
[9315 ms] Start: Run: docker rm -f a202221d48855a296a34ee0195bc695355a855da50a69d641eaa3dbe340251e1
[9319 ms] Error: Server returned 404
    at g (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:844:30614)
    at e.DownloadService.download (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:845:1567)
```

In VScode latest version works fine

**Comment by qcynaut** [comment]
> 

Facing same issue

**Comment by 510carlos** [comment]
+1

**Comment by timojokinen** [comment]
+1

**Comment by ryanktt** [comment]
+1

**Comment by brandonarrindell** [comment]
+1

**Comment by maurim96** [comment]
+1

**Comment by Rjvs** [comment]
@truell20 is this something that you would like to have working?

**Comment by taylars** [comment]
+1

**Comment by shaal** [comment]
+1

**Comment by nicholasq** [comment]
Here to add my 2 cents. I can't spin up a new dev container or start a previously created dev container (there is no option to this at all)

**Comment by takan1** [comment]
Same issue. Would be great if Cursor supports it!

**Comment by mtizim** [comment]
+1, devcontainer support is the difference between unusable and perfect, I'll be glad to pay for the editor once it is there

**Comment by shunyooo** [comment]
+1 I am cancelling my subscription because this problem has not been resolved for over a month. I will purchase a subscription again when it is resolved.

**Comment by ianbruton** [comment]
Bumping as I am having this issue

**Comment by noibar** [comment]
+1

**Comment by shirgur** [comment]
+1

**Comment by chemitaro** [comment]
+1

**Comment by skuam** [comment]
+1

**Comment by AlbinHjalmas** [comment]
+1 I cancelled my subscription due to this issue. Are there any plans to resolve this?

**Comment by adishimoni8** [comment]
+1

**Comment by zivrm** [comment]
+1

**Comment by daniellaharon** [comment]
+1

**Comment by iraadit** [comment]
+1

**Comment by domci** [comment]
+1

**Comment by takuma-competition** [comment]
I hope this problem gets resolved
この問題を解決していただきたいです。

**Comment by 1mrat** [comment]
Yes! The new 0.22 fixes this! See [changelog](https://changelog.cursor.sh/#0220---dev-containers) .

I had to reinstall 0.22 (was on 0.22.1 for some reason) to get it to work - but its working!!

![CleanShot 2024-01-08 at 09 59 35@2x](https://github.com/getcursor/cursor/assets/1105579/a7b529dc-d56b-4468-b325-e9edc43e41c2)

Referencing related issues below:
#976 #1140 #1040 #493

**Comment by tonydavis629** [comment]
Are dev containers only supported on Windows? I'm still not able to connect on Mac.

**Comment by jakobFNF** [comment]
Update [0.22.0](https://changelog.cursor.sh/#0220---dev-containers) added support for Dev Containers.

**Comment by tonydavis629** [comment]
> Update [0.22.0](https://changelog.cursor.sh/#0220---dev-containers) added support for Dev Containers.

I'm still unable to connect to Dev containers from a Mac.

**Comment by js4000all** [comment]
Container images based on Alpine Linux may not be supported yet.
In my case, using `FROM alpine` `FROM node:alpine` doesn't work (results in an HTTP 404 error), but it works with `FROM debian` `FROM node:slim`.

**Comment by natohutch** [comment]
+1

**Comment by upaulnight** [comment]
> > Update [0.22.0](https://changelog.cursor.sh/#0220---dev-containers) added support for Dev Containers.
> 
> I'm still unable to connect to Dev containers from a Mac.

+1

**Comment by kouyaman345** [comment]
> Version: 0.29.1 VSCode Version: 1.86.2 Commit: a962ca5721e80876320cb6a3a500cbc1cf679150 Date: 2024-03-02T20:35:34.996Z Electron: 27.2.3 ElectronBuildId: undefined Chromium: 118.0.5993.159 Node.js: 18.17.1 V8: 11.8.172.18-electron.0 OS: Darwin x64 23.2.0
> 
> I'm trying to test the cursor, but the "dev containers" plugin doesn't work. I run all my projects in "dev containers" on a remote connection, but when I try to open in a dev container in the cursor, nothing happens. When I look at the logs, I see the error "port 22: Connection refused". There is no such problem in vs code. Even if I want to use the cursor and upgrade my membership to a paid membership, this feature is a must for me.

I probably am having the same problem.

You mean connecting to a remote server via ssh and then initiating a connection with devcontainer on that remote server. 

I am also having the same problem in my environment, when I click "Reopen in Devcontainer" on the ssh connection, nothing happens. and also There is no such problem in vs code.

**Comment by masakaya** [comment]
+1

**Comment by jbohnslav** [comment]
I get the following error, trying to open devcontainers on a remote server: 

```bash
[error] [resolveAuthority(dev-container,1)][56ms] returned an error Exec server was not available for ssh-remote+HOSTNAME
```

**Comment by kouyaman345** [comment]
> I get the following error, trying to open devcontainers on a remote server:
> 
> ```shell
> [error] [resolveAuthority(dev-container,1)][56ms] returned an error Exec server was not available for ssh-remote+HOSTNAME
> ```

Same error I have.

Version: 0.31.3
VSCode Version: 1.86.2
Commit: fcd6e551d6f014d13071eac9bd4904e7e0346720
Date: 2024-04-02T20:20:11.019Z
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by RemarkVisions** [comment]
Same error on mac - have tried everything. Works fine on VS code but fails to build on latest version of cursor. If I use bullseye instead of alpine it does build but the workspace is empty. If I am able to get my workspace in, I do not have permissions to run bundle install or rails console. I did hack a way to get my server running in docker but after a few days of not being able to run migrations I decided to tear it apart again. That was 12 hours ago and my eyes are bleeding. I guess I'll go back to VS Code? I was really enjoying coding with 50% of my brain though. 

I should note the docker container fired right up a separate rails api-only app of mine with the following:
ARG VARIANT=3-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/ruby:0-${VARIANT}

**Comment by daniellopez-2** [comment]
I'm still unable to connect to Dev containers from a Mac.

+1 waiting for dev container support. Especially for attaching to remote dev container.

**Comment by artsparkAI** [comment]
I can't say for certain what fixed it, but I was able to fix a broken devcontainer, because I fortunately had a similar working one to compare it to. 

If I narrow the cause further I will update. This is what was different:

1) connected to docker container (outside vscode) and deleted .cursor_server
2) Disabled all cursor features in vscode settings
3) AND these changes in .devcontainer:


```

diff --git a/.devcontainer/localstack/devcontainer.json b/.devcontainer/localstack/devcontainer.json
index 886575d..ea72f91 100644
--- a/.devcontainer/localstack/devcontainer.json
+++ b/.devcontainer/localstack/devcontainer.json
@@ -14,14 +14,14 @@
         "vim.useSystemClipboard": true,
         "vim.useCtrlKeys": true,
         "vim.hlsearch": true,
-        "keyboard.dispatch": "keyCode",
+        // "keyboard.dispatch": "keyCode",
         "vim.insertModeKeyBindings": [
           {
             "before": ["j", "j"],
             "after": ["<Esc>"]
           }
         ],
-        "vim.leader": "<space>",
+        // "vim.leader": "<space>",
         "vim.handleKeys": {
           "<C-a>": false,
           "<C-f>": false
@@ -50,11 +50,11 @@
       },
       "extensions": [
         "golang.go",
+        "vscodevim.vim",
         "github.copilot",
         "ms-python.python",
         "redhat.vscode-yaml",
         "esbenp.prettier-vscode",
-        "mtunique.vim-fcitx-remote",
         "ms-azuretools.vscode-docker",
         "github.vscode-pull-request-github",
         "ms-vscode-remote.remote-containers",
@@ -77,7 +77,8 @@
         "version": "latest",
         "dockerDashComposeVersion": "v2"
     },
-    "ghcr.io/devcontainers-contrib/features/localstack:2": {},
+    "ghcr.io/devcontainers-contrib/features/kind:1": {}
+    // "ghcr.io/devcontainers-contrib/features/localstack:2": {},
   },
```

**Comment by vitalyal** [comment]
I'm trying to open devcontainer and get the following error

```
5581 ms] Installing VS Code Server for commit a915e3254b1192ce240c078da83fc1768a6e3e90
[5583 ms] Start: Downloading VS Code Server
[5583 ms] a915e3254b1192ce240c078da83fc1768a6e3e90 linux-x64 stable
[6541 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:a915e3254b1192ce240c078da83fc1768a6e3e90/server-linux-x64/stable): HTTP 404 - Not Found
[6541 ms] Retrying to download VS Code Server.
[7196 ms] Error: Server returned 404
    at h (vscode-file://vscode-app/c:/Users/vitaliilytovskyi.V2C2/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:1187:29331)
    at S.download (vscode-file://vscode-app/c:/Users/vitaliilytovskyi.V2C2/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:1188:1737)
```

Sysytem info:
```
Version: 0.35.1
VSCode Version: 1.89.1
Commit: a915e3254b1192ce240c078da83fc1768a6e3e90
Date: 2024-06-21T23:14:50.455Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045
Docker engine is running in WSL, but this does not seem to be relevant to error
```

**Comment by iRonin** [comment]
Same here.

**Comment by GindaChen** [comment]
+1

**Comment by sortiz-hub** [comment]
+1

**Comment by wuye9036** [comment]
Failed to connected to docker, 

[539 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:297991d169fa3a11975c5aa95adc69be73250c70/server-linux-x64/stable): HTTP 404 - Not Found

**Comment by jiseongg** [comment]
@wuye9036, I am facint the exactly same situation! Including the commit hash in VS Code Server Download URL. I am working on M1 Macbook

**Comment by pageagency** [comment]
Is there a way to use remote ssh with dev containers like in vscode?

**Comment by orrin-naylor-owner-built** [comment]
+1 here. Love to tool, but I need codespaces support.

**Comment by marcusmotill** [comment]
hilarious this issue is marked closed

**Comment by orrin-naylor-owner-built** [comment]
Everyone go comment here
https://github.com/getcursor/cursor/issues/2395

**Comment by athatheo** [comment]
Would be extremely helpful to have.

**Comment by gblikas** [comment]
bump

**Comment by sameersegal** [comment]
bump

**Comment by krebso** [comment]
bump

**Comment by elabbarw** [comment]
bump

**Comment by kamiljano** [comment]
bump

**Comment by Fr34k9** [comment]
Is there still no solution to this? Works in vscode but no success in cursor. Cant even see any **Devcontainer** tab.

**Comment by arulandu** [comment]
Welp this is kindof a deal breaker :(

**Comment by kayuzee** [comment]
I cannot believe this issue is marked as closed, this has been infuriating me for a while. I found a workaround:

- Open the dev container in VS code
- Close VS code 
- Open the Repo in cursor and launch in dev container - it will attach to the container created by VS code and you don't need to have both open.

Used this yesterday successfully, stupid, but usable.

**Comment by s-smits** [comment]
It's finally working natively with Cursor 0.45+, as Dev Containers has been updated by bumping their VSCode fork version.

**Comment by iRonin** [comment]
Version: 0.45.4 broke the containers completely for me.

**Comment by kayuzee** [comment]
They seem to be working for me now
Cheers,

Qayyum Rajan, CFA
(250) 859-6140
***@***.***

**Comment by domenic-donato** [comment]
Does it also work with GitHut Codespaces now?

**Comment by gblikas** [comment]
I have had success with Ubuntu and Debian based images, but it still seems to be failing with `*alpine*` images. It makes build times kinda annoying on first-pull but not a huge issue. A fix would still be very appreciated 🙏🏼

**Comment by leadbox-ryan** [comment]
Devcontainers do not work on mac. I am running them fine in VS Code beside Cursor and only one has an issue.

**Comment by gblikas** [comment]
> Devcontainers do not work on mac. I am running them fine in VS Code beside Cursor and only one has an issue.

Not true.

**Comment by tomascufaro** [comment]
I still have this issue when I try to attach cursor to a n8n container that's arm64 based using both devcontainer from Anysphere and from microsoft without success.

**Comment by kayuzee** [comment]
Works fine for me. Once I give docker permissions it seems totally fine.

Sometimes I just start the container in VS code and close it and then it
reopens in container fine from cursor

Cheers,

Qayyum Rajan, CFA
(250) 859-6140
***@***.***
