### ISSUE TITLE
Install using Homebrew

### ISSUE THREAD

**Issue by sarincasm** [getcursor/cursor#719]
**Is your feature request related to a problem? Please describe.**
Its a pain to have to download a software manually.

**Describe the solution you'd like**
I would like to be able to install it using homebrew cask.

**Additional context**
Maybe it is already possible, but I couldn't find such information after a 'cursor'y search.

**Comment by nikpivkin** [comment]
@sarincasm This is the first position in Google search results for `cursor homebrew`: https://formulae.brew.sh/cask/cursor

**Comment by sarincasm** [comment]
Awesome !
