### ISSUE TITLE
Cannot modify openAI API.

### ISSUE THREAD

**Issue by CHTUZKI** [getcursor/cursor#725]
HI.

Open the CURSOR SETTINGS window, change the existing openAI API in this window, but after the change, the cursor still displays the old openAI API.

**Comment by truell20** [comment]
To be clear, you're unable to change your API key? Are you sure the new key is valid?

**Comment by skrish13** [comment]
@truell20 How to change the API key?

**Comment by jakobFNF** [comment]
Are you also clicking this button to verify your key?

![image](https://github.com/getcursor/cursor/assets/74077124/2351d1e2-3445-47b2-b5d3-387ac3ff827f)

**Comment by skrish13** [comment]
@jakobFNF i'm not sure how to get to the screen you have shown.

**Comment by jakobFNF** [comment]
@skrish13 
![image](https://github.com/getcursor/cursor/assets/74077124/2352fb76-cc0b-4b39-9880-46696041b6b6)
