### ISSUE TITLE
Allow moving "Chat" and "More" between panels

### ISSUE THREAD

**Issue by hasparus** [getcursor/cursor#731]
**Is your feature request related to a problem? Please describe.**

Currently, AI sidebar can't be dragged to be merged in primary sidebar nor dragged to become one of the tabs of the panel that usually holds the Terminal and Output. This is a bit inconvenient, because screen real estate can often be limited when working on design for example.

**Describe the solution you'd like**

Standard pieces of Code's UI like the Terminal behave in an expected way, and can be moved between panels.
Extensions like GitHub Copilot Chat also work this way.

**Additional context**

**Problem:**

https://github.com/getcursor/cursor/assets/15332326/e9a8f797-2c47-4cf8-8ed7-f8fa8c777ef1

**Expected behaviour:**

https://github.com/getcursor/cursor/assets/15332326/ae2069f4-56a4-40a1-9866-e6b7e27a2c76

**Comment by truell20** [comment]
Try clicking the chat-in-tab button that's in the top right. Right next to the click icon.

**Comment by hasparus** [comment]
> Try clicking the chat-in-tab button that's in the top right. Right next to the click icon.

Do you mean this one?

<img width="459" alt="image" src="https://github.com/getcursor/cursor/assets/15332326/6a4a406e-6a19-4dd3-833c-14fc44bc3af0">

The Cursor AI tab still can't be dragged next to the terminal.

<img width="638" alt="image" src="https://github.com/getcursor/cursor/assets/15332326/1979ee35-4bf5-4b65-8bd1-e6b815a80dad">

**Comment by rajhlinux** [comment]
Please provide a way which we can have the chat window and file explorer window side by side located on the left side of the cursor editor.

Thanks.

**Comment by LucasKuhn** [comment]
For those getting here with no solution, I found a hack to get them both on the same side.
1. [Change the activity bar orientation to vertical](https://docs.cursor.com/get-started/migrate-from-vscode#why-is-the-activity-bar-in-cursor-horizontal)
2. Now you can drag the Chat from the sidepanel to the main panel
3. Revert the activity bar to horizontal

![image](https://github.com/user-attachments/assets/2a177f6e-f787-4e1b-85a0-8c6efaafd525)

Optional: Change the CMD+L Shortcut to not open the sidepanel anymore by adding this to `keybindings.json`
```json
[
    {
        "key": "cmd+l",
        "command": "runCommands",
        "args": {
            "commands": [
                "aichat.newchataction",
                "aichat.close-sidebar"
            ]
        }
    },
]
```
Would be great to see an official option to support the chat on the main sidebar like most VSCode things

**Comment by elviskahoro** [comment]
@truell20 Can you help me understand why this issue was closed?

**Comment by Nezteb** [comment]
Regarding the secondary sidebar still opening:
- https://github.com/getcursor/cursor/issues/1415
- https://github.com/getcursor/cursor/issues/1585

Nevertheless, @LucasKuhn's workaround using `"aichat.close-sidebar"` worked for me! Hopefully the sidebar opening bug gets addressed. 😄

**Comment by JCharante** [comment]
@LucasKuhn thanks this was perfect!

**Comment by Recodify** [comment]
@LucasKuhn thanks so much for that! So much better now.
![image](https://github.com/user-attachments/assets/1eeec234-22b2-4bb5-bb5c-d9bd95829cc4)

**Comment by ChuckJonas** [comment]
Is there anyway to change the Icons?  When I add these to the left Activity bar, Chat and Compose look identical to "Explorer".

<img width="434" alt="Image" src="https://github.com/user-attachments/assets/f448aff8-19a4-422b-99ca-b92563734ccb" />

**Comment by suxscribe** [comment]
Have just updated to 0.46.8 and the fix doesn't work anymore =(
When I move Chat tab to the Activity bar no icon appears there

**Comment by hasparus** [comment]
Confirming — Composer tab used to work when next to terminal, but the new Chat is back being weird and can't be moved at will.

**Comment by migalv** [comment]
Yes, I cannot move to the right side.

**Comment by davidzetterdahl** [comment]
+1 would like this feature very much, it's a feature in vscode.

**Comment by Novack** [comment]
Still no workaround this?

The blocking of moving the chat bar feels like the kind of whimsy enforced things we often see from big tech, no idea why they are doing this.

**Comment by merlinaudio** [comment]
Please allow moving the chat tab to the left again. I don't want two sidebars.
