### ISSUE TITLE
Disable the "Ctrl+L to chat, Ctrl+K to Generate" Hint

### ISSUE THREAD

**Issue by marcelo-mason** [getcursor/cursor#733]
**Is your feature request related to a problem? Please describe.**
"Ctrl+L to chat, Ctrl+K to Generate" hint when clicking a new line was useful the first hour of using Cursor, after that it has become an annoyance that doesn't let me think, it polutes the mind when I'm trying to think about code.

**Describe the solution you'd like**
Ability to disable it via settings

**Comment by truell20** [comment]
This exists in settings right now :) Click the settings gear and scroll down to advanced

**Comment by marcelo-mason** [comment]
Oh not that one, that popup is pretty useful. I meant this hint:

![image](https://github.com/getcursor/cursor/assets/577340/b045bd19-4cdb-4600-9fa6-49ea57aba583)

**Comment by seagreen** [comment]
I would also like a setting to remove the `Ctrl+L to chat, Ctrl+K to generate` (actually I'd suggest to remove it entirely, it's pure noise to anyone who's been using cursor more than a few minutes).

**Comment by nathanneuro** [comment]
agreed

**Comment by igormalaes** [comment]
Is it still not possible to remove it?

**Comment by godfatherjohn** [comment]
In order to disable the "CTRL+L to chat, CTRL+K to generate" message next to the cursor in Cursor's editor, click on the cogwheel in the top-right --> Features --> disable "Show chat/edit tooltip".

**Comment by seagreen** [comment]
> In order to disable the "CTRL+L to chat, CTRL+K to generate" message next to the cursor in Cursor's editor, click on the cogwheel in the top-right --> Features --> disable "Show chat/edit tooltip".

That worked, thank you.

**Comment by rfhtorres31** [comment]
> In order to disable the "CTRL+L to chat, CTRL+K to generate" message next to the cursor in Cursor's editor, click on the cogwheel in the top-right --> Features --> disable "Show chat/edit tooltip".

thank you!

**Comment by mxmlnkn** [comment]
Seems to have been moved to cog wheel (Cursor Settings (Ctrl+Shift+J)) ->Chat -> Toolbar on Selection in Cursor 1.0.0.

**Comment by harsh-merufintech** [comment]
> Seems to have been moved to cog wheel (Cursor Settings (Ctrl+Shift+J)) ->Chat -> Toolbar on Selection in Cursor 1.0.0.

This work for newer Cursor version, Thank you
