### ISSUE TITLE
你好，这是一个关于模型的反馈

### ISSUE THREAD

**Issue by UKendall** [getcursor/cursor#74]
不知道什么原因，我觉得0.1.0更新到0.1.1之后的模型非常差劲，虽然速度很快，但是其内容非常劣质

**Comment by weilingkang** [comment]
是的，同样的答案回答内容完全不同

**Comment by yshy6809** [comment]
应该是从4切回3.5了，试着问点能区分4和3.5的问题可以看出来

**Comment by luckyhug** [comment]
> 应该是从4切回3.5了，试着问点能区分4和3.5的问题可以看出来

还能换回原版本吗？

**Comment by yshy6809** [comment]
> > 应该是从4切回3.5了，试着问点能区分4和3.5的问题可以看出来
> 
> 还能换回原版本吗？
这得问开发者了呀

**Comment by yshy6809** [comment]
> > 应该是从4切回3.5了，试着问点能区分4和3.5的问题可以看出来
> 
> 还能换回原版本吗？

这得问开发者了呀
