### ISSUE TITLE
Auto focus search field

### ISSUE THREAD

**Issue by knowbee** [getcursor/cursor#746]
**Is your feature request related to a problem? Please describe.**

It would be helpful if you could implement this feature as it normally works in vscode
**Describe the solution you'd like**

As i click the search icon on my editor, I expect the search input to auto focus and not having to manually click in the search field to start typing

**Additional context**

Cursor | Vscode
![Screenshot 2023-08-19 at 01 59 19](https://github.com/getcursor/cursor/assets/31471062/8a422741-f84b-437e-a8d7-7006418f7f24)

![Screenshot 2023-08-19 at 01 59 34](https://github.com/getcursor/cursor/assets/31471062/3c49c14a-25ad-4ca7-853d-6d02fbdfa04d)

**Comment by arvid220u** [comment]
thanks for reporting! this is fixed in nightly and will be out in stable tomorrow morning
