### ISSUE TITLE
edit or remove custom @Docs

### ISSUE THREAD

**Issue by ajaykarpur** [getcursor/cursor#748]
**Is your feature request related to a problem? Please describe.**
I added custom docs like so:
```
Entrypoint: https://docs.aws.amazon.com/cdk/api/v2/
Prefix: https://docs.aws.amazon.com/cdk/api/v2/
Name: AWS CDK
```

I think I put in the wrong URL for the entrypoint, though, so I'd like to change it to the following:
```
Entrypoint: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-construct-library.html
Prefix: https://docs.aws.amazon.com/cdk/api/v2/
Name: AWS CDK
```

I can't seem to find a way to edit the custom docs I added. (When I try to just add new docs with name `AWS CDK`, it won't let me, because I already added custom docs with the same name.)

**Describe the solution you'd like**
It would be helpful if there were some obvious way for me to edit or remove custom docs that I've added. Maybe in the settings menu, there could be a list of all the custom docs added?

**Additional context**
As an aside, I'm not sure why the original URL I provided didn't work. The chat just wasn't able to see the relevant documentation even when I added it to the context. That's why I wanted to edit it-- so I could test a different entrypoint URL to see if that would work better.

**Comment by paschaldev** [comment]
Found myself stuck with this same problem

**Comment by truell20** [comment]
This is now supported! At least the ability to delete docs, edit their name, and see what pages were indexed.

**Comment by suuunly** [comment]
> This is now supported! At least the ability to delete docs, edit their name, and see what pages were indexed.

How do you do this? I have supposedly deleted my custom doc entries.
But when I try to add it again, with the same display name, I am told that it already exists.

I did use the share with team members. Do I have to delete it somewhere else then? 
Or is this maybe a bug, where it deletes it, but does not free up the name?
