### ISSUE TITLE
Jetbrains shortcut Ctrl + Shift + A does not open commands panel

### ISSUE THREAD

**Issue by deanpress** [getcursor/cursor#753]
![image](https://github.com/getcursor/cursor/assets/31391056/1ef2412e-0a8b-46fc-b507-fe492ef042a1)

Using with Jetbrains shortcuts enabled, but pressing Ctrl + Shift + A (configured as `Show & Run Commands`) does not appear to do anything. Other shortcuts do work, though.

**Comment by deanpress** [comment]
Looks like the reason is that one of the native AI shortcuts is also Ctrl + Shift + A by default:

![image](https://github.com/getcursor/cursor/assets/31391056/cad3b97a-9be0-471c-be16-ab6d0a0ec041)

It would probably be a good idea to have an "alternative" keybind for this if the user selects Jetbrains shortcuts.

**Comment by arvid220u** [comment]
Thank you for reporting! This was an experiment that we ran, and we forgot to take it out. Fix should be out today.
