### ISSUE TITLE
Add hostname dropdown for remote ssh

### ISSUE THREAD

**Issue by rtaori** [getcursor/cursor#756]
When connecting to remote ssh, it'd be nice to have a remote host dropdown (automatically pulled from `~/.ssh/config`) that the user can select.

For example, in VSCode it looks like this: 
<img width="729" alt="image" src="https://github.com/getcursor/cursor/assets/6610670/73f9f995-a97e-43b4-b3e9-89c4c14d0490">

Whereas the cursor interface just exposes a textfield:
<img width="727" alt="image" src="https://github.com/getcursor/cursor/assets/6610670/cd2327b8-a64d-44df-a330-f4085facce2c">

**Comment by arvid220u** [comment]
thank you for reporting! this is out in nightly, and will be coming to stable tomorrow morning

**Comment by rtaori** [comment]
How do I update Cursor?
