### ISSUE TITLE
settings.json option to restore .activitybar.part.sidebar.left.bordered to VSCode default

### ISSUE THREAD

**Issue by JettIsOnTheNet** [getcursor/cursor#757]
**Is your feature request related to a problem? Please describe.**
Cursor uses a new menu in place of ActivitybarPanel placed atop the sidebar element. The original implementation is alongside the sidebar as .activitybar, "split-view-view" inside "split-view-container".

**Describe the solution you'd like**
Having a checkbox/dropdown inside Settings or settings.json override would be welcome to a lot of users. Especially because the re-implementation of the Activitybar does not give notifications and hides UI elements by default, removing visual UX cues. It also does not seem to always function when using hotkeys, requiring a mouse click.

I do not have access to the Cursor fork, else I would add this feature in by toggling the original Activitybar panel element  for /src/vs/workbench/browser/parts/activitybar.

**Additional context**
Thx. Good job on Cursor so far. Keep at it. 👍

![image](https://github.com/getcursor/cursor/assets/81721/8cd6472e-98dd-474a-984b-2bc80abaf204)
![image](https://github.com/getcursor/cursor/assets/81721/66a8b196-fd36-49ef-ba52-69d87cf7332d)
![image](https://github.com/getcursor/cursor/assets/81721/9f616f3e-2a1b-4c1e-977a-e1fe531f7cde)

**Comment by arvid220u** [comment]
thank you for reporting! this is out in nightly (you can set `workbench.activityBar.orientation` to `vertical`), and will be coming to stable tomorrow morning

**Comment by JettIsOnTheNet** [comment]
Awesome. Thanks. You guys rock. 👍

**Comment by cloudstudio** [comment]
@arvid220u was released ? I can't find it :(

**Comment by ILS07** [comment]
@arvid220u Same as @cloudstudio.  I hunted in the options before finding the issue reported here.   The workbench orientation shows as "unknown configuration setting" in 0.8.6.

**Comment by JettIsOnTheNet** [comment]
Yes, it does not appear to be in the release. I have a feeling it did not make the cut for build. I do not know why. I was going to wait a while to re-open this issue as they were very quick to jump on it the first time.

![image](https://github.com/getcursor/cursor/assets/81721/80511796-f9a7-4bf0-895b-22c414a70653)

**Comment by arvid220u** [comment]
Ah, yes, sorry about this. It was part of the original release that we had to quickly revert because of this: https://github.com/getcursor/cursor/issues/775

A build should be coming out today which has this added back!

**Comment by JettIsOnTheNet** [comment]
Thanks. Appreciate. That is why I was going to wait. ;)

Quick Q: How to enable pre-release dev channel? Is there a config flag? I do not see one. I don't mind being on dev channel.

**Comment by arvid220u** [comment]
Yes! Add me on Discord (arvid220u) and I'll invite you to the nightly release channel.
