### ISSUE TITLE
No response when clicking "Install python Language Server"

### ISSUE THREAD

**Issue by ruiqurm** [getcursor/cursor#76]
![example](https://user-images.githubusercontent.com/24454448/226089636-9c90392a-802d-4431-badb-ee6a3a34e65a.png)
The problem happens on other buttons too.   

By the way, I think it may be not a good idea to re-build another IDE. Build a plugin for popular IDEs like Vscode seems more easy.

**Comment by slayeryahu** [comment]
With the same problem.
Anything resolution?

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
