### ISSUE TITLE
"Report Issue" feature isn't working

### ISSUE THREAD

**Issue by AlmogCohen** [getcursor/cursor#763]
1) Click "Help" -> "Report Issue"
2) Fill out the details
3) Click "Preview on GitHub"
4) **Boom**, a 404 GitHub page is opened ([Link](https://github.com/anysphere/cursor-feedback/issues/new?title=Cannot%20report%20issues&body=%0AType:%20%3Cb%3EBug%3C/b%3E%0A%0AWhen%20reporting%20an%20issue%20via%20the%20%22Issue%20Reporter%22%20it%20opens%20a%20404%20GitHub%20page%0A%0AVS%20Code%20version:%20Cursor%200.7.3%20(74f6148eb9ea00507ec113ec51c489d6ffb4b771,%202023-08-13T20:30:52.292Z)%0AOS%20version:%20Darwin%20arm64%2022.6.0%0AModes:%0A%0A%3Cdetails%3E%0A%3Csummary%3ESystem%20Info%3C/summary%3E%0A%0A%7CItem%7CValue%7C%0A%7C---%7C---%7C%0A%7CCPUs%7CApple%20M1%20Pro%20(10%20x%2024)%7C%0A%7CGPU%20Status%7C2d_canvas:%20enabled%3Cbr%3Ecanvas_oop_rasterization:%20disabled_off%3Cbr%3Edirect_rendering_display_compositor:%20disabled_off_ok%3Cbr%3Egpu_compositing:%20enabled%3Cbr%3Emetal:%20disabled_off%3Cbr%3Emultiple_raster_threads:%20enabled_on%3Cbr%3Eopengl:%20enabled_on%3Cbr%3Erasterization:%20enabled%3Cbr%3Eraw_draw:%20disabled_off_ok%3Cbr%3Evideo_decode:%20enabled%3Cbr%3Evideo_encode:%20enabled%3Cbr%3Evulkan:%20disabled_off%3Cbr%3Ewebgl:%20enabled%3Cbr%3Ewebgl2:%20enabled%3Cbr%3Ewebgpu:%20enabled%7C%0A%7CLoad%20(avg)%7C7,%206,%209%7C%0A%7CMemory%20(System)%7C32.00GB%20(0.29GB%20free)%7C%0A%7CProcess%20Argv%7C%7C%0A%7CScreen%20Reader%7Cno%7C%0A%7CVM%7C0%25%7C%0A%3C/details%3E%3Cdetails%3E%3Csummary%3EExtensions%20(2)%3C/summary%3E%0A%0AExtension%7CAuthor%20(truncated)%7CVersion%0A---%7C---%7C---%0Ang-template%7CAng%7C16.1.8%0Acopilot%7CGit%7C1.105.350%0A%0A%0A%3C/details%3E%0A%3C!--%20generated%20by%20issue%20reporter%20--%3E))

Comment: It is clearly an easy bug to fix. The base url points to another github repo: https://github.com/anysphere/cursor-feedback/issues

https://github.com/getcursor/cursor/assets/3888998/7b5b441d-b53e-4086-947e-6021e6a3f06f

**Comment by arvid220u** [comment]
ah! our bad. should be fixed now!
