### ISSUE TITLE
Analysing images with Cursor

### ISSUE THREAD

**Issue by albertovidalrod** [getcursor/cursor#773]
Hi everyone,

I'm aware that ChatGPT with gpt-4 can be used to analyse images. This can be done by passing the url to the chat.

I was expecting a similar functionality in Cursor since we have access to gpt-4. I tried doing it by asking a question about one of the pictures in my repo and by sharing the url to a wikipedia picture and both failed (see image below).

Is it the case that prompting the chat about images isn't possible or am I doing something wrong?

Best regards,

Alberto
![cursor-images](https://github.com/getcursor/cursor/assets/130750341/5c1b8a88-f8fc-470a-bf2b-1e5002e75f73)

**Comment by jakobFNF** [comment]
Cursor utilizes the OpenAI API, which currently does not have vision capabilities. Even when the API gains vision capabilities, it doesn't automatically mean you can send images to Cursor. That functionality would need to be implemented first.

Vision capabilities [were added to ChatGPT+ on September 25th](https://openai.com/blog/chatgpt-can-now-see-hear-and-speak), allowing image inputs. So you can try out some things in there. But ChatGPT+ and the API are different things. ChatGPT+ gets early features.

**Comment by rohan-uiuc** [comment]
Hello, I’m also interested in using Cursor to analyze images with gpt-4. I have access to the `gpt-4-vision-preview` model on OpenAI APIs, but I don’t know how to use it with Cursor. Could this feature be supported now or in the future? I think it would be very useful for many applications. Thank you for your work on this project.

**Comment by jakobFNF** [comment]
@rohan-uiuc Version [0.17.0](https://changelog.cursor.sh/#0170---image-support-interpreter-mode-beta--folders) added Vision support.

**Comment by InsightfulFuture** [comment]
When using a custom api key if the model is gpt-4-vision-preview and I submit an image it doesn't respond but doesn't error
