### ISSUE TITLE
[MacOs Ventura 13.0] All features with the Cursor is unable.

### ISSUE THREAD

**Issue by gordon95** [getcursor/cursor#775]
<img width="1181" alt="image" src="https://github.com/getcursor/cursor/assets/41887873/39134936-27a0-41fe-8a58-6549f5d3f599">
I was updated Cursor to newest version, then all the features is unable, no respond with the single/double click. I'm also re-download the Cursor, it doesn't help.  Please give me some help or fix it asap.

**Comment by eldelentes** [comment]
Same with me.

Macbook Pro 2021 M1 Pro
Ventura 13.4.1

![CleanShot 2023-08-22 at 22 19 13](https://github.com/getcursor/cursor/assets/1761145/eb2dcda3-b81f-4054-a0e1-3e5a780aabeb)

**Comment by arvid220u** [comment]
so sorry about this! we're scheduling a new build to revert

**Comment by truell20** [comment]
If you download again from cursor.so or cursor.sh, this should have the old version. Could you let us know if reinstalling again fixes the issue?

**Comment by eldelentes** [comment]
Yes, now its fixed,  but I had to uninstall and install again.

**Comment by arvid220u** [comment]
If you haven't upgraded yet, you can also find the logs in `~/Library/Application\ Support/Cursor/logs`. We will delete your logs as soon as we have debugged the issue.

**Comment by eldelentes** [comment]
Email sent 👍

**Comment by bairubing-xenera** [comment]
Me too, but reinstalling doesn't fix it.
MacBook Pro   2017
macos  13.5

**Comment by truell20** [comment]
@bairubing-xenera Could you email your logs to hi@cursor.so? This will help us fix the issue.

**Comment by bairubing-xenera** [comment]
> @bairubing-xenera您可以通过电子邮件将您的日志发送`~/Library/Application\ Support/Cursor/logs`到[hi@cursor.so](mailto:hi@cursor.so)吗？这将帮助我们解决问题。

Email sent

**Comment by bairubing-xenera** [comment]
> @bairubing-xenera Could you email your logs in `~/Library/Application\ Support/Cursor/logs` to [hi@cursor.so](mailto:hi@cursor.so)? This will help us fix the issue.

Email sent

**Comment by gordon95** [comment]
> If you download again from cursor.so or cursor.sh, this should have the old version. Could you let us know if reinstalling again fixes the issue?

**Comment by truell20** [comment]
@gordon95 Any chance you could send us your logs?

**Comment by truell20** [comment]
And a zip of a zip of `~/Library/Application\ Support/Cursor` if possible?

**Comment by gordon95** [comment]
> @gordon95 Any chance you could send us your logs?

Yes, I was install cursor from cursor.so, and now the problem was fixed, and Email send.
