### ISSUE TITLE
black screen after upgrade

### ISSUE THREAD

**Issue by alittleRound** [getcursor/cursor#778]
- 

![Uploading image.png…]()

- my system : Apple M1 Pro, macOS Ventura 13.4.1

**Comment by arvid220u** [comment]
@alittleRound Sorry about this. Is this on Cursor nightly (https://cursor.sh/nightly) or on the main version you get from installing on https://cursor.sh?

**Comment by alittleRound** [comment]
I downloaded again from https://www.cursor.sh/, it works now, but I don't know why
![image](https://github.com/getcursor/cursor/assets/42506324/00ac9b56-5b38-4a59-abcd-3184588d94e7)
