### ISSUE TITLE
Remove cursor from path when typing `code .` in Windows

### ISSUE THREAD

**Issue by deadcoder0904** [getcursor/cursor#785]
I would love to remove cursor when I do `code .` in Windows 10.

I accidentally used it but for now, would like to disable it.

Haven't been on Windows for 5 years now so don't know where to remove it from. Assuming it's a path somewhere. Would love to know if there's an option in cursor. Or have to remove it manually editing some files.

**Comment by truell20** [comment]
Does installing the code command from within VSCode work?

<img width="837" alt="Screenshot 2023-08-23 at 10 29 34 PM" src="https://github.com/getcursor/cursor/assets/4297743/08f5c88b-0565-4b0c-8386-0f2e0b3d6669">

**Comment by deadcoder0904** [comment]
Naah, there isn't an option in Windows like that. Only Mac. See https://code.visualstudio.com/docs/editor/command-line

I did remove it though from Environment Variables. So if I removed cursor's path that looked like `C:\Users\<USERNAME>\AppData\Local\Programs\cursor\resources\app\bin` & automatically VSCode worked after closing the existing terminals.

Cool Project! Will give it a shot soon :)
