### ISSUE TITLE
are is repeated twice in the What are fast and slow uses? section of the Pricing page https://www.cursor.so/pricing

### ISSUE THREAD

**Issue by kumardeepam** [getcursor/cursor#787]
The following sentence:
Fast uses of GPT-4 are are given first priority by our backend and are served ~3x faster than OpenAI's public API.

Should be corrected to:
Fast uses of GPT-4 are given first priority by our backend and are served ~3x faster than OpenAI's public API.

Reference screenshot:

<img width="1280" alt="Screenshot 2023-08-24 at 3 53 48 PM" src="https://github.com/getcursor/cursor/assets/82027/17267580-e9b4-41f1-aa7a-86fef493e97e">

**Comment by truell20** [comment]
Thanks! Fixed.
