### ISSUE TITLE
Bug: terminal stuck when using `tab` to autocomplete

### ISSUE THREAD

**Issue by elanzini** [getcursor/cursor#79]
See the screen recording below:

https://user-images.githubusercontent.com/37532050/226099054-74f29e4e-9f52-4a3a-9bd8-acff031a9124.mov

**Comment by truell20** [comment]
Thanks for reporting this edoardo. What operating system / processor are you on, again?

**Comment by elanzini** [comment]
> Thanks for reporting this edoardo. What operating system / processor are you on, again?

macOS Ventura 13.1 - intel chip

**Comment by elanzini** [comment]
I tried to reproduce this but I think it has been fixed

**Comment by zentala** [comment]
Same ;/ Win11, i7-14700.
