### ISSUE TITLE
Add model fallbacks

### ISSUE THREAD

**Issue by ishaan-jaff** [getcursor/cursor#791]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

When OpenAI is unreachable can you use an alternative model like Claude, llama 2 etc
<img width="680" alt="Screenshot 2023-08-24 at 1 38 29 PM" src="https://github.com/getcursor/cursor/assets/29436595/04d92ac7-e2ad-4929-9858-e069c9e3356b">

**Comment by jakobFNF** [comment]
You can find some comments from the developers regarding the use of other AI models [here](https://github.com/getcursor/cursor/issues/838#issuecomment-1771820356). Thank you for your suggestion!
