### ISSUE TITLE
Word Wrap only works on one side of diff views

### ISSUE THREAD

**Issue by JHarrisGTI** [getcursor/cursor#800]
Word Wrap only works on the right-hand side of diff views. The left-hand side remains unwrapped, regardless of whether Word Wrap is enabled.

As you scroll down the page, the two sides become increasingly desynchronized from each other, making it a challenge to determine which changes on the left correspond to those on the right.

![Screenshot 2023-08-25 at 3 49 55 PM](https://github.com/getcursor/cursor/assets/127752973/4bcf60cf-5f74-44c5-b6d4-015976775b3b)

I'm on MacOS Ventura 13.5.1 on an Intel chip.

Reproduction steps:
1. Open a git repo that has long lines of code in it.
2. In Settings, enable Word Wrap. (User or Workspace, doesn't matter.)
3. Make some changes.
4. In the Source Control side panel, click the file you changed to open a side-by-side diff view.

**Comment by jakobFNF** [comment]
This was fixed.

**Comment by 101scholar** [comment]
Same issue. @jakobFNF 

Version: 2.1.50 (Universal)
VSCode Version: 1.105.1
Commit: 56f0a83df8e9eb48585fcc4858a9440db4cc7770
Date: 2025-12-06T23:39:52.834Z
Electron: 37.7.0
Chromium: 138.0.7204.251
Node.js: 22.20.0
V8: 13.8.258.32-electron.0
OS: Darwin arm64 24.6.0
