### ISSUE TITLE
Setting up Vim press and hold on cursor

### ISSUE THREAD

**Issue by rdilip** [getcursor/cursor#801]
**Is your feature request related to a problem? Please describe.**
When I set up cursor, the instructions for enabling key repeating aren't clear. In VS Code, we do

```
$ defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false              # For VS Code
$ defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false      # For VS Code Insider
$ defaults write com.visualstudio.code.oss ApplePressAndHoldEnabled -bool false         # For VS Codium
$ defaults write com.microsoft.VSCodeExploration ApplePressAndHoldEnabled -bool false   # For VS Codium Exploration users
$ defaults delete -g ApplePressAndHoldEnabled                                           
```

But that doesn't really change the defaults for Cursor. 

**Describe the solution you'd like**
I'd imagine a similar description like the above for Cursor would work well and should be doable!

**Comment by zkirby** [comment]
Following!

**Comment by puzzlepeaches** [comment]
Did anyone ever figure this one out?

**Comment by puzzlepeaches** [comment]
Got this working on Mac OS:

1. Execute `osascript -e 'id of app "Cursor"'`
2. Grab the output of the command. In my case, it's `com.todesktop.230313mzl4w4u92` (I am not sure if this is the same for everyone)
3. Execute the following with your output `defaults write com.todesktop.230313mzl4w4u92 ApplePressAndHoldEnabled -bool false`
4. Restart the application

**Comment by rdilip** [comment]
Fantastic -- that works for me (I have the same output of `osascript`, by the way). Thanks!

**Comment by HuangJiaLian** [comment]
> Got this working on Mac OS:
> 
> 1. Execute `osascript -e 'id of app "Cursor"'`
> 2. Grab the output of the command. In my case, it's `com.todesktop.230313mzl4w4u92` (I am not sure if this is the same for everyone)
> 3. Execute the following with your output `defaults write com.todesktop.230313mzl4w4u92 ApplePressAndHoldEnabled -bool false`
> 4. Restart the application

Thank you so much.

**Comment by namtonthat** [comment]
As a one liner

```
defaults write "$(osascript -e 'id of app "Cursor"')" ApplePressAndHoldEnabled -bool false && osascript -e 'quit app "Cursor"' && open -a "Cursor"
```
