### ISSUE TITLE
How to reset keybinding from IntelliJ to Vscode + cursor

### ISSUE THREAD

**Issue by dstollie** [getcursor/cursor#803]
When start I chose to takeover the keybinding of IntelliJ. I am not really statisfied with the keybindings and thus just want to reset them back to default vscode + cursors specific bindings. I tried looking everywhere and eve reinstalling cursor to get the intro back but I can not see anyway to reset the keybindings other than manually go trough every keybinding

Hope you guys can help me out with this.

**Comment by kamushadenes** [comment]
Search the extension marketplace for `@recommended:keymaps`, uninstall IntelliJ keymap and install the VSCode one.

**Comment by dstollie** [comment]
Only uninstalling The IntelliJ keymap plugin was sufficient for me, thanks!
