### ISSUE TITLE
How can I remove from the list of docs a doc that I've added?

### ISSUE THREAD

**Issue by xilopaint** [getcursor/cursor#808]
![F4ivRD7WgAASSvt](https://github.com/getcursor/cursor/assets/11052366/34c2e21e-dfd9-44fb-a5ea-769394483ce3)

I've added this doc and really don't know how to remove it from the list of docs. If there's no way to do it currently, I'll make this issue a feature request.

**Comment by truell20** [comment]
This is now supported!
