### ISSUE TITLE
The cursor remote ssh vscode server installer missing for 0.8.5 / arm64

### ISSUE THREAD

**Issue by MatrixDai** [getcursor/cursor#812]
Steps to reproduce the issue:
1. Upgrade cursor IDE to 0.8.5 on macOS (I think it doesn't matter, but I'm on macOS)
<img width="271" alt="Screenshot 2023-08-28 at 13 31 21" src="https://github.com/getcursor/cursor/assets/1191662/dbb2c87b-3aff-4498-b253-209c121d3859">

2. Cleanup the `.cursor-server` folder for you remote linux box (the old version obviously not work with upgraded cursor)
4. Now try to `Remote-SSH` to a linux server with ARM64 arch
5. Then I will hit the following error (it works fine on 0.8.4)
<img width="956" alt="Screenshot 2023-08-28 at 13 31 33" src="https://github.com/getcursor/cursor/assets/1191662/38c7caf0-c63b-4935-8d15-be377b1cbe54">

Additional:
- When I tried to manually download the link https://cursor.blob.core.windows.net/remote-releases/0.8.5-1.0.0/vscode-reh-linux-arm64.tar.gz, hit 404 BlobNotFound error
- If I tried to download the tarball for the x64 with link https://cursor.blob.core.windows.net/remote-releases/0.8.5-1.0.0/vscode-reh-linux-x64.tar.gz, then it works.
- Obviously the arm64 server installer is missing in the download server (or has not being built yet?)

**Comment by MatrixDai** [comment]
I upgraded the cursor to 0.8.6 today, the exact same issue there for 0.8.6 (arm64) too.

**Comment by BepfCp** [comment]
Same issue, but mine is a x86_64 machine.

**Comment by MatrixDai** [comment]
Update:

When I tried update the Cursor with `CMD+Shift P > Cursor: Attempt update`, I got Cursor version `0.9.1`, with this version, the remote SSH installation issue gone.

<img width="635" alt="Screenshot 2023-08-31 at 19 41 36" src="https://github.com/getcursor/cursor/assets/1191662/d92904d5-6b17-4192-bb6c-49d568576292">
<img width="258" alt="Screenshot 2023-08-31 at 19 41 15" src="https://github.com/getcursor/cursor/assets/1191662/1080f8c9-285c-444c-af80-8e6fad9652b9">

Therefore, closing this issue.
