### ISSUE TITLE
Input issue after chatting

### ISSUE THREAD

**Issue by PandaBalls** [getcursor/cursor#813]
Type: <b>Bug</b>

ctrl + L start chat.
mean while I am editing in editor.
while gpt finishing chat output, the editor will be locked, can not input. 

I need to focus on chat panel then focus in editor panel. then I can input again..

This happens after updating the latest Cursor.

VS Code version: Cursor 0.8.5 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-08-26T19:52:38.290Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900X CPU @ 3.50GHz (20 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|95.69GB (74.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|10.1.0
vuetify-snippets|Gai|0.1.2
gc-excelviewer|Gra|4.2.58
vue-snippets|hol|1.0.4
better-cpp-syntax|jef|1.17.2
volarjs-labs|joh|1.9.1
vscode-map-preview|jum|0.5.9
vsc-python-indent|Kev|1.18.0
nc-gcode|ML|0.13.0
vscode-docker|ms-|1.26.0
autopep8|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.6.40
cpptools|ms-|1.17.4
cpptools-extension-pack|ms-|1.3.0
vscode-serial-monitor|ms-|0.10.0
autodocstring|njp|0.6.1
platformio-ide|pla|3.3.1
p5-vscode|sam|1.2.14
pdf|tom|1.2.2
vscode-arduino|vsc|0.6.0
volar|Vue|1.8.8
vuetify-vscode|vue|0.2.0
luahelper|yin|0.2.24

(1 theme extensions excluded)

</details>

**Comment by JacobWeinbren** [comment]
The same happens to me - did you manage to find a fix?

**Comment by truell20** [comment]
Could you send a screenshot? Wondering if you have vim keys enabled.

**Comment by JacobWeinbren** [comment]
@truell20 Sure - I have never used Vim keys though. <img src="https://i.imgur.com/hnZglFZ.png"/>

**Comment by JacobWeinbren** [comment]
@truell20 It might not be able to solve this as it happens sort of randomly - sometimes when I have pasted code snippets. And otherwise, it just happens from time to time.

**Comment by truell20** [comment]
Think I've located the issue. Thank you both for reporting! Will push an update soon.

**Comment by truell20** [comment]
Think this should be fixed in the latest release

**Comment by JacobWeinbren** [comment]
@truell20 Thank you!!

**Comment by truell20** [comment]
JUst checking, are you still getting this issue at all?

**Comment by JacobWeinbren** [comment]
Yep - thanks a lot

Jacob

**Comment by jakobFNF** [comment]
@JacobWeinbren Could you please clarify if you're still experiencing this issue? You initially responded with 'Yep' but then followed it with 'thanks a lot' which left me a bit confused. Based on my own experience, I think this issue was fixed.

**Comment by danperks** [comment]
Issue is fixed
