### ISSUE TITLE
vim extension stopped working

### ISSUE THREAD

**Issue by remann2** [getcursor/cursor#816]
pressing ESC doesn't change the vim mode, the editor is always in editing mode. Before today, everything works. May be caused by the latest update?

**Comment by remann2** [comment]
Version: 0.8.5
VSCode Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-08-26T19:52:38.290Z (1 day ago)
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0

**Comment by truell20** [comment]
Do you have the vim extension installed?
