### ISSUE TITLE
i've upgrade to Pro but am still being shown the "upgrade to pro to use gpt4" dialog

### ISSUE THREAD

**Issue by lowellbander** [getcursor/cursor#824]
MacOS

easy repro: use "chat with codebase", see dialog, set up Pro subscription, go back to Cursor, try again, still get hit with dialog. persists after restarting the app

![image](https://github.com/getcursor/cursor/assets/3479724/4f727a25-d969-4f03-88d5-2c004c1d6254)
![image](https://github.com/getcursor/cursor/assets/3479724/88661565-ac9f-4152-91bb-9aa2796acd26)

1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system: MacOS
3) If you can, steps to reproduce are super helpful

**Comment by truell20** [comment]
Could you try signing out in the IDE and then signing back in?

**Comment by lowellbander** [comment]
did the trick!
