### ISSUE TITLE
Text cursor is not well aligned

### ISSUE THREAD

**Issue by bemic** [getcursor/cursor#828]
1st screenshot - VSCode

<img width="942" alt="vscode" src="https://github.com/getcursor/cursor/assets/50417294/222a8285-cc64-4d92-ac5f-5a88b8a89f08">

2nd screenshot - Cursor (the text cursor is more left, on top of 'd' char)

<img width="942" alt="cursor" src="https://github.com/getcursor/cursor/assets/50417294/05260c40-765a-45c6-ad1c-cb49e66941b7">

**Comment by truell20** [comment]
Ack, I think this comes from our use of Jetbrain's Mono font. Unfortunately, this may mean we need to switch back to Menlo or similar.

**Comment by truell20** [comment]
We switched fonts to fix this
