### ISSUE TITLE
A server error has occured

### ISSUE THREAD

**Issue by WormStan** [getcursor/cursor#83]
![Capture](https://user-images.githubusercontent.com/16974251/226109174-d2489d59-4273-4165-98f9-6dc114479de9.PNG)

**Comment by nCloser** [comment]
+1

**Comment by AdrianRonaldo10** [comment]
I don't know if that's because the server is busy, let me know if you got any clue.

**Comment by ChaosTh173** [comment]
+1

**Comment by 1071179133** [comment]
+1

**Comment by yeqijie6** [comment]
+1

**Comment by songtao2627** [comment]
+1

**Comment by haonan0x3a1** [comment]
> 我不知道这是否是因为服务器繁忙，如果您有任何线索，请告诉我。

应该是用的人太多了，服务器撑不住了

**Comment by monkeydone** [comment]
+1

**Comment by haonan0x3a1** [comment]
There should be a problem with the server. I have clicked the Generate Code button many times without any response.

**Comment by Gulang10783** [comment]
After entering a question, wait for a period of time without any response

**Comment by craftsliu** [comment]
> There should be a problem with the server. I have clicked the Generate Code button many times without any response.

I have the same question~

**Comment by lovzjoyy** [comment]
keep waiting

**Comment by lovzjoyy** [comment]
一只在缓冲，但是问题却没有回答

**Comment by huangjkai** [comment]
I have the same question

**Comment by zzering** [comment]
> 

I have the same question

**Comment by zzering** [comment]
> After entering a question, wait for a period of time without any response

I have the same question

**Comment by WormStan** [comment]
I did some SPIKE on this :
1. It's may not due to version upgrade from 0.1.0 to 0.1.1, but maybe due to many clients updating the software version pushing the server done.
2. I change another desktop to try, sometimes I can got response but most of try failed 
3. I don't think it due to openai server.

Unfortunately, I don't have access (Network block) to Discord to see whether anyone else discusses about this issue. If the team need a someone to do some testing, I can help with.

**Comment by dododcdc** [comment]
i also ran into this problem

**Comment by Veechar** [comment]
it is blocked ?

**Comment by Sanger2000** [comment]
We have fixed the main issue here, but we get intermittent failures as we run into rate limits with OpenAI. Let me know if more issues persist!

**Comment by Tongcheng** [comment]
Works for me now! Thx for fixing

**Comment by truell20** [comment]
Fix! Apologies here.

**Comment by remgoo** [comment]
2023.4.16，I have the same question

**Comment by tpln-github08** [comment]
2023年04月18日09:14:52 the same question , location China Beijing

**Comment by tpln-github08** [comment]
on the right up corner there is a setting button ，you can install your language server and restart your app
