### ISSUE TITLE
Open AND close AI sidebar with CTRL+L (or CMD+L), not only open

### ISSUE THREAD

**Issue by CesarERamosMedina** [getcursor/cursor#833]
**Is your feature request related to a problem? Please describe.**
CTRL+L only opens the AI sidebar. I would like to be able to close also with CTRL+L by default

**Describe the solution you'd like**
The keyboard shortcut CTRL+L (or CMD+L) to open and close the AI sidebar. Right now it is not trivial to do this just editing the Cursor Keyboard shortcut bindings

**Comment by tommyrharper** [comment]
Please add this!

**Comment by D-28** [comment]
+1, this would be great. 

I would add that there's a keyboard shortcut "Close AI Sidebar" that can be mapped to something like `shift+cmd+l`. 
The issue for me is that it only works when the cursor is inside the editor, not the chat.

**Comment by jakobFNF** [comment]
This works if you bind the 'View: Toggle Secondary Side Bar Visibility' to the same key. However, as someone has already noticed, shortcuts are currently being blocked when you're focused on a chat input field. We will address this issue. For now, I'll close this issue because the initial problem has been resolved.

![image](https://github.com/getcursor/cursor/assets/74077124/7d6b2655-02c8-4714-b1dc-f67a3c3d695b)

**Comment by shubhsharma19** [comment]
Thanks a lot for this 🔥

**Comment by IP0** [comment]
Not fixed.

**Comment by Minhhoang2606** [comment]
you can close the chat without opening a new chat simply by Cltr + Shift + L

**Comment by TheDataSeneschal** [comment]
```
  {
    "key": "shift+alt+2",
    "command": "aichat.insertselectionintochat"
  },

```

This the only thing that worked

**Comment by andfinally** [comment]
@TheDataSeneschal's binding does the trick for me – I kept the default keybinding `shift-command-L`.

**Comment by jameswilliamknight** [comment]
> ```
>   {
>     "key": "shift+alt+2",
>     "command": "aichat.insertselectionintochat"
>   },
> ```
> 
> This is the only thing that worked. For some reason, it acts as an actual toggle, and `View: Toggle Chat` does not 😆

That works! thank you!!!

**Comment by buildwithzephyr** [comment]
> ```
>   {
>     "key": "shift+alt+2",
>     "command": "aichat.insertselectionintochat"
>   },
> ```
> 
> This is the only thing that worked. For some reason, it acts as an actual toggle, and `View: Toggle Chat` does not 😆

This also worked for me.
