### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by AxcelXander** [getcursor/cursor#843]
Type: <b>Bug</b>

keeps crashing with code:5

VS Code version: Cursor 0.9.1 (30d21e59529ff0a52d8a847c419e668f2fd2d620, 2023-08-30T23:17:14.710Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 10, 9|
|Memory (System)|32.00GB (3.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Kotlin|mat|1.7.1

</details>

**Comment by arvid220u** [comment]
That seems concerning! Thank you for reporting.

Could you send a screenshot of what the error looks like?

**Comment by arvid220u** [comment]
If Cursor is mostly working, it would also be helpful if you could send a bug report using the icon in the top right corner. Helps us get more debug information.

<img width="293" alt="Screenshot 2023-08-31 at 1 54 15 PM" src="https://github.com/getcursor/cursor/assets/2716295/7965cd38-2b9b-462a-a97f-a074dd78e274">

**Comment by AxcelXander** [comment]
thanks for the quick response. Already sent a bug report with the error screenshot in it.

**Comment by arvid220u** [comment]
Thank you! We've identified the bug and will push a fix as soon as possible. Thank you so much for reporting

**Comment by truell20** [comment]
Pushed out a fix for this last night. Could you confirm that things work fine on your end @VonGrimm @AxcelXander if you uninstall and reinstall? If that doesn't work, could you try clearing your local Cursor cache?

```
rm -r ~/Library/Application\ Support/Cursor
```

**Comment by truell20** [comment]
@VonGrimm Did this happen even after you ran the above command?

**Comment by Sanger2000** [comment]
If it persists after running the above command, could you run:

`cursor --crash-reporter-directory /path/to/workspace` (You’ll need to have the cursor command installed. If it is not installed, please run cmd+shift+p > “Shell command install cursor command”)

Then look for a *.dmp file in that directory and send it to us

**Comment by sualehasif** [comment]
https://changelog.cursor.sh/#092---hotfix-large-persisted-state

shipped!
