### ISSUE TITLE
Unable to Authenticate Github to use Co-Pilot

### ISSUE THREAD

**Issue by robert-moore** [getcursor/cursor#851]
1) If you can, please include a screenshot of your problem
When authorizing via extension, a URL opens which sends me to a page that looks like this
![image](https://github.com/getcursor/cursor/assets/4934366/5641d896-ae10-4ef7-b7b4-5dbdbf5518d5)

2) Please include the name of your operating system
MacOS Ventura, M1
3) If you can, steps to reproduce are super helpful
1. Download co-pilot extension (or co-pilot labs, both same result)
2. Click Sign in to GitHub
3. Allow Github Copilot to sign in 
4. Sent to page listed above

![image](https://github.com/getcursor/cursor/assets/4934366/8804e03c-aaf6-4881-b7a5-67708faf0b34)
![image](https://github.com/getcursor/cursor/assets/4934366/349da168-ab6a-41da-9b55-c08afb3b5fe9)

**Comment by arvid220u** [comment]
Thank you for reporting this! We have found the bug, and are currently building version 0.9.3 which fixes this bug.

**Comment by arvid220u** [comment]
This is now in version 0.9.3. Please let me know if you continue to have problems.

**Comment by robert-moore** [comment]
Insane ship time. Works great now!
