### ISSUE TITLE
Switch GPT mode hot key don't work on windows OS

### ISSUE THREAD

**Issue by TJtangjun** [getcursor/cursor#853]
Switching the shortcut keys for GPT3.5/4 to win+shift+3/4 is intended to quickly open programs on the taskbar in the operating system, so it doesn't actually switch the GPT mode.

OS：Windows 10
About: Switch GPT model Hot key

**Comment by Sanger2000** [comment]
We can change the default settings in a future update, but if you run cmd+shift+p then "switch to gpt", you can press the settings icon to change the default keybindings
<img width="613" alt="Screen Shot 2023-09-01 at 6 33 31 PM" src="https://github.com/getcursor/cursor/assets/17725268/4f954819-3056-4fae-a7e6-135d334a94bf">

**Comment by TJtangjun** [comment]
thank you ,it work for me
