### ISSUE TITLE
It's becoming extremely expensive with the pages with long code.

### ISSUE THREAD

**Issue by mithatb** [getcursor/cursor#854]
Hi,

When i run ai inside my server.js file with gpt-4 i am easily reaching 10£ with my own key. I think it's because cursor is posting all the code to openai. Is there a way to prevent this happening and only sending selected words to openai api?

Thanks,

**Comment by jakobFNF** [comment]
Sadly, GPT-4 is very expensive right now. With the Pro subscription, you'll get unlimited GPT-4 requests (and the first 500 requests will be extra fast) for $20 per month.
