### ISSUE TITLE
Unable to login cursor on Ubuntu-22.04

### ISSUE THREAD

**Issue by dka58** [getcursor/cursor#855]
## 1) If you can, please include a screenshot of your problem
```bash
ubuntu:~/Downloads$ ./cursor-0.9.3.AppImage
[main 2023-09-02T12:21:11.879Z] update#ctor - updates are disabled as there is no update URL
[main 2023-09-02T12:21:12.083Z] [uncaught exception in main]: Error: SQLITE_CANTOPEN: unable to open database file
[main 2023-09-02T12:21:12.083Z] Error: SQLITE_CANTOPEN: unable to open database file

```
## 2) Please include the name of your operating system
Ubuntu 22.04.3 LTS
## 3) If you can, steps to reproduce are super helpful
When I try launching the appimage file from the terminal or by double clicking on it, it launches but unable to login. Also when trying to install code or cursor commands I get an error. And on the next screen both buttons, the sign in and sign up buttons don't do anything. Making  cursor unusable on my ubuntu

**Comment by hemangjoshi37a** [comment]
same problem #1323
have you found any solution? if yes please let me know.

**Comment by dka58** [comment]
> have you found any solution? if yes please let me know.
Unfortunately not entirely sure, as this was a while back, but yes, I did. I think it had something to do with the default browser or something like that, I switched it to another browser and the login page launched

**Comment by hemangjoshi37a** [comment]
```sh
(base) hemang@hemang-levono-15arr:~/Downloads$ sudo ./cursor-0.30.4x86_64.AppImage  --no-sandbox
[172619:0402/171007.329249:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[172619:0402/171007.329378:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[172619:0402/171007.329404:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[172619:0402/171007.329448:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[main 2024-04-02T11:40:08.263Z] update#setState disabled
[main 2024-04-02T11:40:08.289Z] update#ctor - updates are disabled as there is no update URL
[172619:0402/171008.303357:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[main 2024-04-02T11:40:08.473Z] [storage state.vscdb] error checking size of src.vs.platform.reactivestorage.browser.reactiveStorageServiceImpl.persistentStorage.workspaceUser: Error: Unexpected number of rows - 0
[main 2024-04-02T11:40:08.474Z] [storage state.vscdb] error checking size of workbench.panel.aichat.view.aichat.chatdata: Error: Unexpected number of rows - 0
[main 2024-04-02T11:40:11.560Z] vscode-file: Refused to load resource /tmp/.mount_cursoreQ9gi7/resources/app/extensions/theme-seti/icons/seti.woff from vscode-file: protocol (original URL: vscode-file://vscode-app/tmp/.mount_cursoreQ9gi7/resources/app/extensions/theme-seti/icons/seti.woff)
[main 2024-04-02T11:40:20.159Z] [uncaught exception in main]: Error: net::ERR_NETWORK_CHANGED
[main 2024-04-02T11:40:20.161Z] Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:50076)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)

```

this is the output i am getting in the terminal while running cursor through the terminal.

**Comment by celikemir** [comment]
This may be due to a certification error. Could you try connecting to a different network first, then logging in?

**Comment by hemangjoshi37a** [comment]
at this point i have lest cursor for the `cline` and `aider` project and they work very well for me.  this is due to closedness  of cursor and lack of support for ubuntu and linux systems. 
https://github.com/cline/cline
https://github.com/Aider-AI/aider

**Comment by yumemio** [comment]
> > have you found any solution? if yes please let me know.
> 
> Unfortunately not entirely sure, as this was a while back, but yes, I did. I think it had something to do with the default browser or something like that, I switched it to another browser and the login page launched

Right, the login button does not work unless your default browser is Google Chrome. You can use `xdg-settings` to fix this:

```console
$ # In my environment (Ubuntu 22.04) Firefox is the default browser
$ # in which case the login button does not work
$ xdg-settings get default-web-browser
firefox.desktop

$ # Make sure Google Chrome is installed
$ ls /usr/share/applications | grep chrome
goole-chrome.desktop

$ # Set Google Chrome as the default browser
$ xdg-settings set default-web-browser google-chrome.desktop
$ xdg-settings get default-web-browser
google-chrome.desktop

$ # Relaunch Cursor
$ /path/to/the/Cursor.AppImage
```

**Comment by awg-ashish** [comment]
I have google chrome as my default browser and the login button on cursor takes me to the auth page on chrome but even after signing in on the cursor auth page in browser I am not getting "logged in" in the cursor App. I have ubuntu 22.04 and trying to run cursor through its AppImage
