### ISSUE TITLE
无法切换中文

### ISSUE THREAD

**Issue by 1538739551** [getcursor/cursor#86]

**Comment by Code-Agitator** [comment]
IDE语言似乎确实没办法切换，不过作为程序员还是可以接受的  但是ai语言你可以对她说 说中文

**Comment by truell20** [comment]
Hi! Our dev team is only composed of fluent English speakers. Did you mean "Can't switch to Chinese"? Could you elaborate on that?

**Comment by 1538739551** [comment]
yes

**Comment by ICML8** [comment]
Can I expect a release with Chinese packages in the next release

**Comment by NeverMore93** [comment]
> 

please learning English u self
