### ISSUE TITLE
AI acting like ChatGPT

### ISSUE THREAD

**Issue by danimesq** [getcursor/cursor#862]
Type: <b>Bug</b>

![Screenshot from 2023-09-03 03-02-27](https://github.com/getcursor/cursor/assets/6765277/7f772f1b-f76f-4546-bdab-28480f8f0c63)

VS Code version: Cursor 0.9.3 (e83fb25fe9144aa8b230e6f9ee2056e20fb24c70, 2023-09-01T18:24:49.940Z)
OS version: Linux x64 6.2.0-31-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 2187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|9.64GB (5.09GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by sualehasif** [comment]
sorry, that looks really bad. can i ask what model you were using here (3.5 or 4?)

**Comment by havietisov** [comment]
I see this behaviour too, as well as retrieval doesn't seem to work on some repos : https://github.com/getcursor/cursor/issues/859

**Comment by danimesq** [comment]
@sualehasif 

> sorry, that looks really bad. can i ask what model you were using here (3.5 or 4?)

gpt-4.
Didn't tested 3.5, but as @havietisov pointed above, probably too.

**Comment by danimesq** [comment]
![Screenshot from 2023-09-03 19-08-52](https://github.com/getcursor/cursor/assets/6765277/93be5c28-d781-4ac6-857b-0f2981730b76)

Happening again, but this time the AI claiming to be able to read the file (while in practice seems that it's not).

**Comment by sualehasif** [comment]
Ah! Its codebase context. What email are you using. I can try to inspect logs if you are not using local mode.

We are pushing a better indexing engine on Tuesday! Hopefully that helps alleviate some of these

**Comment by danimesq** [comment]
> What email are you using. I can try to inspect logs if you are not using local mode.

mesquitadaniella@proton.me
Thanks

> We are pushing a better indexing engine on Tuesday! Hopefully that helps alleviate some of these

🚀

**Comment by havietisov** [comment]
@sualehasif is it possible to specify fully local, DIY indexing engine? Like, without editing the source code of the app of course.

**Comment by danimesq** [comment]
@sualehasif 

> We are pushing a better indexing engine on Tuesday! Hopefully that helps alleviate some of these

Was it postponed or already shipped with the latest release?

**Comment by sualehasif** [comment]
delayed a bit but its my focus to ship this. sorry for the delay!

**Comment by danimesq** [comment]
Solved.
