### ISSUE TITLE
Ability to remap AI commands ctrl+k

### ISSUE THREAD

**Issue by jordaniza** [getcursor/cursor#866]
Hi there,

I'm trying out cursor but also using vim shortcuts. I want to use ctrl+k and ctrl shift L for navigation and can't work out if it's possible to remap the AI chat commands to other keybindings?

**Comment by jakobFNF** [comment]
Yes, you can!
1. Type Command/Ctrl + Shift + P.
2. Go to “Preferences: Open Keyboard Shortcuts”.
3. Edit the "aipopup.action.modal.generate" action to remap the inline edits/generation keybinding.
4. Edit the "aichat.newchataction" action to remap the new chat command.

**Comment by tjx666** [comment]
try https://marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience
