### ISSUE TITLE
Spelling mistake on website ("pottencially" should be "potentially")

### ISSUE THREAD

**Issue by jakeboone02** [getcursor/cursor#868]
This is a report for the website (https://www.cursor.so/), not the editor itself. I was curious if this misspelling was intentional? Should be "potentially":

![image](https://github.com/getcursor/cursor/assets/366438/d4042f65-d929-4d8f-a5a1-63474ea2c518)

**Comment by jakobFNF** [comment]
😂 This was fixed. Thank you!

![image](https://github.com/getcursor/cursor/assets/74077124/4ce315b5-81a6-4db9-9113-445fc4e33768)
