### ISSUE TITLE
Search casing selection is not persisted

### ISSUE THREAD

**Issue by kaumac** [getcursor/cursor#869]
1) If you can, please include a screenshot of your problem:
<img width="847" alt="Captura de Tela 2023-09-04 às 04 16 42" src="https://github.com/getcursor/cursor/assets/1170740/32d19d72-8a9c-49f0-accb-8054d0bf1068">

2) Please include the name of your operating system:
MacOS Monterey 12.6.2

3) If you can, steps to reproduce are super helpful:
Search for some text in your code (CMD+F or CMD+SHIFT+F) and disable the "Match case" and "Match whole word" options/toggle. After a while the casing always comes back.

This to me is super annoying because most of the time I'm looking for generic matches in the code and not so often I look for exact matches. I'm almost going back to "vanilla" VSCode because of this because it definitely slows down development 🙁

**Comment by maktouch** [comment]
oof, thank god for this issue. I was encountering the same thing and it's driving me nuts. I thought I did something wrong

**Comment by jakobFNF** [comment]
That's definitely annoying. I will note this down. Thank you for your report!

**Comment by truell20** [comment]
Huh this is a bit confusing to me, not sure how would be causing. Does this happen if you disable your extensions?

**Comment by kaumac** [comment]
Hey all, this has now been fixed as of version ***0.16.0***
