### ISSUE TITLE
In the generated code, there is ``` such content,

### ISSUE THREAD

**Issue by TJtangjun** [getcursor/cursor#872]
- OS:win11
- version:0.9.3
- model:GPT 3.5

In the generated code, there is ``` such content
which should not be displayed ,unnecessarily.

![image](https://github.com/getcursor/cursor/assets/23148245/9bf3832f-4fb9-474b-94ea-a37e095e8c7d)

**Comment by sualehasif** [comment]
i believe we found the issue and deployed a fix.
