### ISSUE TITLE
Can I use custom chatGPT api endpoint?

### ISSUE THREAD

**Issue by chatGPTxx** [getcursor/cursor#874]
**Is your feature request related to a problem? Please describe.**
My company has built our own Azure chatGPT, which has different way of calling it. wondering if there's a way to customize the API call

**Describe the solution you'd like**
expose custom config for chatGPT api endpoint

**Comment by sualehasif** [comment]
mmm we already support the azure endpoints.

**Comment by sublimator** [comment]
OpenAI are investors so seems unlikely

**Comment by jakobFNF** [comment]
Azure endpoints are supported (under Settings => Advanced).

![image](https://github.com/getcursor/cursor/assets/74077124/3a3b9921-347d-4133-ba0f-6f4131ba54d6)
