### ISSUE TITLE
⌘+K key bindings don't work like in VSCode - they are mapped to ⌘+R (macOS)

### ISSUE THREAD

**Issue by AshConnolly** [getcursor/cursor#887]
The default ⌘+K key bindings found in VSCode don't work in Cursor because ⌘+K it is set to the "AI hotkey".

There are 100+ ⌘+K default key bindings in VSCode users will be used to and this change makes it difficult to use Cursor without remapping loads of keybindings.

## Potential solution

Provide a way of setting the "AI hotkey" on install.

I've set mine to ⌘+I, which conveniently aligns with the 'inline' wording in the command name: "Cursor: Open Inline Edit and Generate Prompt Bar". ⌘+R could work well too. 

1) If you can, please include a screenshot of your problem.   
VSCode on left, Cursor on right:
![Screenshot 2023-09-07 at 11 15 55](https://github.com/getcursor/cursor/assets/6549140/97db056d-8a5d-467a-8f4f-73d71926eb6a)

2) Please include the name of your operating system: macOS Monterey

3) If you can, steps to reproduce are super helpful: Install Cursor on Mac.

**Comment by arvid220u** [comment]
If you search for "keychord.leader" in the keyboard shortcut settings, and remap that, does that help?

It should remap all keychord starting with Cmd+R.

**Comment by AshConnolly** [comment]
Ah brilliant! Thanks mate, appreciate it! 👍

**Comment by AshConnolly** [comment]
Solved by @arvid220u, closing! 🙂

**Comment by tjx666** [comment]
Or you can try:

https://marketplace.cursorapi.com/items?itemName=YuTengjing.vscode-classic-experience
