### ISSUE TITLE
Enhancement proposal: Add launch script directly in context menu

### ISSUE THREAD

**Issue by WormStan** [getcursor/cursor#89]
It may be useful for end-users if we add a context menu with a menuitem called "run in terminal" , then user can debug the generated code directly without copy/paster to other IDE or manually input the command.

For example: 
1. Create a file test.py -- a python file
2. Generate some script with Prompts
3. Right click on the script window, and select menu item "Test via Terminal"

It seems help.

![image](https://user-images.githubusercontent.com/16974251/226147411-3a91347b-b7d0-4266-93cf-21a881006690.png)

**Comment by danperks** [comment]
With the move to Cursor v0.2.0, it's likely that a similar feature is available with one of the many plugins.
If more interest is gathered, this can be reopened and discussed further.
