### ISSUE TITLE
cannot visit official websie

### ISSUE THREAD

**Issue by jli113** [getcursor/cursor#896]
1) If you can, please include a screenshot of your problem
![image](https://github.com/getcursor/cursor/assets/33822210/0c22fe94-8b92-45ed-91d2-cabc405c09bf)
cannot visit or ping https://cursor.so/ 
![image](https://github.com/getcursor/cursor/assets/33822210/b755c4ae-106d-403f-b939-e1db95592927)

2) Please include the name of your operating system
win11

3) If you can, steps to reproduce are super helpful

**Comment by jli113** [comment]
相关部门屏蔽了

**Comment by truell20** [comment]
cursor.sh
