### ISSUE TITLE
can't chat

### ISSUE THREAD

**Issue by LycheeC** [getcursor/cursor#899]
Type: <b>Bug</b>

can't chat

VS Code version: Cursor 0.9.5 (73afd26947c390db3ddc73858adffaef3d09bdd0, 2023-09-08T06:08:45.482Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.18GB (3.36GB free)|
|Process Argv|--updated|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.14.0
remote-wsl|ms-|0.80.2
java|red|1.21.0
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0

</details>

**Comment by truell20** [comment]
Could you post a screenshot or steps to reproduce?
