### ISSUE TITLE
终端无法拖动文件路径进去，软件ai回答还是初始版好

### ISSUE THREAD

**Issue by zhaohai1024** [getcursor/cursor#90]
终端无法拖动文件路径进去，软件ai回答还是初始版好，更新后很智障这个ai

**Comment by truell20** [comment]
Hi! Our dev team is composed only of native english speakers right now. Did you mean "The terminal cannot drag the file path into it"? Could you expand on this?

**Comment by Jussick** [comment]
> Hi! Our dev team is composed only of native english speakers right now. Did you mean "The terminal cannot drag the file path into it"? Could you expand on this?

yes , it is. And he also think the AI in new version is less than the old version. But I don't think so.

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
