### ISSUE TITLE
Extension 'eamodio.gitlens' CANNOT use API proposal: treeItemCheckbox

### ISSUE THREAD

**Issue by codebycarlos** [getcursor/cursor#917]
1) If you can, please include a screenshot of your problem
![image](https://github.com/getcursor/cursor/assets/91962855/fef1c264-5d9a-4cb2-b63c-8053a4455a56)

`Extension 'eamodio.gitlens' CANNOT use API proposal: treeItemCheckbox. Its package.json#enabledApiProposals-property declares: [] but NOT treeItemCheckbox. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api eamodio.gitlens. Note that the cursor and control proposals are only available for built-in extensions`

![image](https://github.com/getcursor/cursor/assets/91962855/a724b2e1-dd62-45f2-ac0f-13b8b3fe3ff9)

2) Please include the name of your operating system **macOS**

3) If you can, steps to reproduce are super helpful
Whenever I try to toggle the dropdown arrow within source control to compare a branch I get this error. Not sure if it's Cursor only or a Gitlens issue in general. Putting this here in case others come across it.

**Comment by codebycarlos** [comment]
Update: seems to work in VSCode

**Comment by aselunar** [comment]
It also doesn't work in Cursor for me, but does work in VSCode.

**Comment by wjhrdy** [comment]
same issue here. sounds like cursor is being not strict enough with vscode versions declared by the extension as requirements.

**Comment by codebycarlos** [comment]
It's pretty annoying, now I have to keep going back to VSCode any time I want to compare branches :(

**Comment by sualehasif** [comment]
Sorry! This will be resolved today or over the weekend! We are also working on infrastructure to make sure it doesnt happen again!!

**Comment by codebycarlos** [comment]
This is now fixed on the latest version. Great work Cursor team!
