### ISSUE TITLE
Don't always remind me to upgrade every conversation

### ISSUE THREAD

**Issue by TJtangjun** [getcursor/cursor#921]
I am a paying user and I ran out of 500 GPT4 requests. Don't always remind me to upgrade every conversation.
The official website says that after using up the quota, you can still use it, but it is slower. But I always get such tips.
![image](https://github.com/getcursor/cursor/assets/23148245/e0f0adbe-98af-49e0-8a5d-83ebed14edc7)

![image](https://github.com/getcursor/cursor/assets/23148245/0518d478-8f02-4cbc-9ff3-f0d535ba495a)

**Comment by truell20** [comment]
Apologies about this and thank you for reporting it! We will fix. Just to be sure, could you make sure you're logged into your pro account locally?

**Comment by truell20** [comment]
This should now be fixed. Let me know if you ever see something like this again.

**Comment by TJtangjun** [comment]
Thanks, you solved the problem, I didn't notice it reappearing
