### ISSUE TITLE
Add option to move 'Primary side bar' to the right

### ISSUE THREAD

**Issue by ghost** [getcursor/cursor#926]
VSCode has an option to move the 'Primary sidebar' to the right. Would be great to allow that in Cursor too. Thanks!
<img width="422" alt="image" src="https://github.com/getcursor/cursor/assets/131650302/cd2eaef3-3bfb-4c0f-abb7-072cf8563fa0">

**Comment by jjfantini** [comment]
This is already present in `View > Appearance`

**Comment by mimumo** [comment]
Thanks. When you move primary sidebar to right the other one moves to left!
I would want not to have any sider on the left which is possible with VSCode.
Would be great to have it in Cursor too.

**Comment by jjfantini** [comment]
You can just close the AI sidebar?

**Comment by jakobFNF** [comment]
You can use the 'Open Chat in Editor Tab' button to have more control over the chat's position.

![276761196-3f758c35-9994-4a3b-93e9-b1ae267fcad8](https://github.com/getcursor/cursor/assets/74077124/65abdfad-4e52-4484-a956-42de36642ecd)

That makes this layout possible.

![image](https://github.com/getcursor/cursor/assets/74077124/0c4e39c7-a2b9-4bc9-b111-bbbda3a815d9)

**Comment by zhukovgeorge** [comment]
This is not a solution, as it makes you eat up all the space with three i windows which is unreasonable.

I appreciate the idea of integrating multiple features into one place, but the current implementation falls short. Having three separate windows (e.g., terminal, explorer, chat) takes up too much space.

A better approach would be to allow users to move all necessary features to one side of the editor, enabling dynamic switching between them via hotkeys while keeping the code editing window static. This would effectively split the editor into two parts: one for code and the other for auxiliary features like terminal, explorer, chat, etc.

**Comment by dv336699** [comment]
I want to move all sidebars to the right like I can do in vscode, is there an option now?
