### ISSUE TITLE
Auto update not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by edorivai** [getcursor/cursor#927]
Type: <b>Bug</b>

I have installed Cursor 0.9.5 using an AppImage on my Ubuntu 20.04 laptop. On startup, it notifies me that a new version (0.10.4) has been prepared and will be installed on exit. I have exited and restarted Cursor multiple times, have rebooted my laptop, but the app doesn't update. I'm still on 0.9.5, and the notification pops up on every startup.

![image](https://github.com/getcursor/cursor/assets/765358/2bb80cce-87d4-49de-a9c6-d7894ac3fce4)

VS Code version: Cursor 0.9.5 (73afd26947c390db3ddc73858adffaef3d09bdd0, 2023-09-08T06:08:45.482Z)
OS version: Linux x64 5.15.0-83-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|30.98GB (20.01GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.9.1
vscode-apollo|apo|1.19.11
atlascode|atl|3.0.5
tailwind-docs|aus|2.1.0
vagrant|bbe|0.5.0
prettier-toml|bod|0.1.0
vscode-tailwindcss|bra|0.10.0
rona|Bru|1.0.9
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.6
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
gitlens|eam|14.3.0
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.66
auto-rename-tag|for|0.1.10
vscode-sql-tagged-template-literals-syntax-only|fri|0.0.19
copilot|Git|1.111.404
vscode-pull-request-github|Git|0.70.0
go|gol|0.39.1
gti-vscode|Gra|0.2.2
vscode-graphql-syntax|Gra|1.2.2
saltstack|kor|0.0.9
css-converter|Lak|0.2.2
Kotlin|mat|1.7.1
rainbow-csv|mec|3.7.0
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.5883
sqltools|mtx|0.28.0
typescript-explicit-types|nic|0.0.9
vscode-subword-navigation|ow|1.2.0
toggle|reb|0.0.2
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.10.3
shader|sle|1.1.5
stately-vscode|sta|1.14.3
jest-snapshot-language-support|tle|1.1.1
es6-string-html|Tob|2.12.1
pdf|tom|1.2.2
material-ui-codemorphs|vsc|1.5.0
markdown-all-in-one|yzh|3.5.1
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details>

**Comment by edorivai** [comment]
Update: I just downloaded the new AppImage from the website manually, installed it seemed to have seemlessly updated. All my previous app state still in place, previous project opens up when starting etc.

**Comment by mbtre** [comment]
Same on Mac. Had to install it again to get it updated. CMD+P "Attempt Update" did not work either..

**Comment by arpagon** [comment]
#844

**Comment by danperks** [comment]
Cursor's auto-updating functionality has been changed since this bug, so will close

**Comment by akosiyawin** [comment]
This issue still happening on Ubuntu. Auto update still not working, you have to manually download the AppImage and install.

**Comment by paulocoutinhox** [comment]
I have the same problem. It don't update on Ubuntu. After restart it always show the "has a new version" banner.

**Comment by tayou89** [comment]
I'm using Ubuntu 22.04. I have the same problem. Is the only way to update Cursor editor removing all my current Cursor and downloading new Cursor from website?
