### ISSUE TITLE
[bug]ctrl+k generates extra blank lines and curly braces

### ISSUE THREAD

**Issue by TJtangjun** [getcursor/cursor#935]
![a](https://github.com/getcursor/cursor/assets/23148245/8cad26d3-4686-42f7-91bf-80e67d3a5e2f)
![b](https://github.com/getcursor/cursor/assets/23148245/4156d329-f63b-4f9c-8f18-f75630073833)

This problem, which I tested twice, generated some blank lines and extra curly braces
version: windows 11, Cursor 0.11.0

```javascript
// compute sum of array elements

const sum = (arr) => {
  return arr.reduce((acc, curr) => acc + curr, 0);
}
```

**Comment by TJtangjun** [comment]
This is serious and makes it almost impossible for me to use the code generation feature, please fix this as soon as possible.

**Comment by truell20** [comment]
Apologies about this! Should be fixed in the latest update. Let me know if you still have any issues.
