### ISSUE TITLE
How to remove 'code' alias for cursor in MacOS(m2 chip)?

### ISSUE THREAD

**Issue by peter65374** [getcursor/cursor#936]
OS: MacOS 12.6
Device: Macbook pro M2chip
Question: How to remove 'code' alias for cursor? When installing, I agreed the 'code' alias in command line for cursor. However, I prefer to use 'cursor' in command line to start. I checked ~/.bash_profile and ~/.zshrc and none of PATH setting found there. It seems that cursor inject some script when I install it, which required my laptop password or finger print. Is there any way to remove it?

**Comment by xilopaint** [comment]
Search for the following in the command palette:

`Shell Command: Uninstall cursor command from PATH`

**Comment by eh8** [comment]
Cursor installs symlinks in your `/usr/local/bin/` folder when you agree to create the aliases for `code` and `cursor`. Deleting the `code` symlink will solve the issue.

`rm /usr/local/bin/code`

**Comment by bagustris** [comment]
@eh8 

Is there any way to make the alias only work for Cursor terminal? This means that if we type "code" inside the Cursor terminal, it will launch Cursor; otherwise, (in other terminals outside the Cursor), it will launch the real vscode itself.

**Comment by eh8** [comment]
@bagustris 

Perhaps you can write a function in your `.zshrc` or `.bashrc` that detects the current running terminal via parent process ID and sets the shell alias accordingly 

(I have _not_ tested this approach since I'm on mobile, but here's what GPT suggests)

```bash
# Function to get the terminal name
get_terminal_name() {
    ps -o comm= -p $(ps -o ppid= -p $$)
}

# Define the alias based on the terminal name
if [[ "$(get_terminal_name)" == "cursor" ]]; then
    alias code="cursor"
else
    alias code="code"
fi
```

**Comment by bagustris** [comment]
@eh8 Thanks, it works!!!
