### ISSUE TITLE
Python Cursor Extension not Activating

### ISSUE THREAD

**Issue by seanl01** [getcursor/cursor#939]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

![image](https://github.com/getcursor/cursor/assets/57535001/cf6cf408-ad7b-4c62-9a98-3734f58ee489)
![image](https://github.com/getcursor/cursor/assets/57535001/4442cb4e-5151-4970-9ea8-90d397706df5)

- Since the recent update, I have been having trouble with the Python Cursor extension. It doesn't seem to be able to activate. In the console, I see some error messages. 
- I am unable to get intellisense for python now.

**Comment by truell20** [comment]
Are you on Cursor version 0.11.0?

**Comment by jjfantini** [comment]
+1

OS: Windows 11
Cursor V 0.11.0

THis same thing is happening to me, and now Black Formatter isn't working, Ruff still isn't working

**Comment by truell20** [comment]
Believe this should be fixed in the next release

**Comment by truell20** [comment]
Pushed a hotfix for this. Let me know if anything looks off after you upgrade! Thank you for reporting this!

**Comment by truell20** [comment]
Closing for now, let me know if you run into issues

**Comment by seanl01** [comment]
Thank you! No issues now.
