### ISSUE TITLE
.ipynb Python Language Support Not Working

### ISSUE THREAD

**Issue by jjfantini** [getcursor/cursor#940]
OS: Windows 11

When using Cursor AI, I have a .ipynb that I am doing analysis on. When I use a function from my current python package, there is no information shown when I hover above a function, class or method. THis is not the case with VSCode, where language support is present in notebooks.

Can we please have this feature added?

**Comment by truell20** [comment]
What version of Cursor are you on?

**Comment by jjfantini** [comment]
0.11.0

**Comment by truell20** [comment]
Pushed a hotfix for this. Let me know if anything looks off after you upgrade! Thank you for reporting this!

**Comment by truell20** [comment]
Closing for now, let me know if you run into issues
