### ISSUE TITLE
Add option to move 'Activity Bar' to the left

### ISSUE THREAD

**Issue by kraten** [getcursor/cursor#941]
VSCode shows the Activity Bar on the left, which I find very convenient to use when dealing with numerous icons. It would be great to have such an option for Cursor too. Thanks!

<img width="352" alt="image" src="https://github.com/getcursor/cursor/assets/25284793/92cf0483-edcc-46d5-8944-faf744843343">

**Comment by truell20** [comment]
Workaround here: https://forum.cursor.sh/t/getting-used-to-the-orientation-of-the-primary-sidebar/20/4?u=truell20
