### ISSUE TITLE
Your IDE is too difficult to use.

### ISSUE THREAD

**Issue by zdjzce923** [getcursor/cursor#942]
Can you make IDE plugins? The layout for the cursor editor seems like it's from an IDE several years ago.

**Comment by jjfantini** [comment]
Its literally the same as VSCode?

**Comment by abrahamvphilip** [comment]
The only slight difference is in the sidebar, but I guess it's more clean this way.

That's more of an opinionated preference and if there's a way to configure it, that should solve the problem.

Apart from that, cursor is literally a clone of vscode.

**Comment by truell20** [comment]
You can configure the sidebar here: https://forum.cursor.sh/t/getting-used-to-the-orientation-of-the-primary-sidebar/20/4?u=truell20

**Comment by jjfantini** [comment]
Since the value of cursor is not having a plugin, that would defeat the purpose. 

Cursor is the IDE of the future...
