### ISSUE TITLE
[BUG] `Pylance` and `Python Language Server` very slow, no code-suggestions

### ISSUE THREAD

**Issue by jjfantini** [getcursor/cursor#947]
OS: Windows 11
Cursor Version: Latest (as of posting)

Alas, Pylance and Python Language Server are now working...albeit very slowly. There is no recognition of functions, classes and methods, leading to no code completion behaviors or suggestions while writing code. There is no way to see what is available from the selected class, method, or function.

## VSCode:
- suggestions working fluidly and as I type
![vscode-syntax-working](https://github.com/getcursor/cursor/assets/63276164/cc105f71-d618-4fba-b2b9-cc23e4ecbb4e)

## Cursor:
- suggestions not working
- syntax not highlighting 
![syntax_error](https://github.com/getcursor/cursor/assets/63276164/f4fbd52a-1cb2-41f7-ab59-98df0ccdbb48)

**Comment by Sanger2000** [comment]
Could you try running: Cmd+shift+p -> Python Select Interpreter and then select the standard python interpreter that you use?

Also, if you search through the extensions on the left, what does it say for python/pylance?

**Comment by truell20** [comment]
Just checking in here

**Comment by jjfantini** [comment]
I selected the standard one I use, which is a conda env inside my project folder. It says Pylance is installed. 

@Sanger2000

**Comment by truell20** [comment]
Could you file a bug report using the feedback button in the top right with your Github username? This will give us access to your local logs which will help debug.

**Comment by jjfantini** [comment]
I can do so, I did some testing and it seems that the interpreter runs v slow when using a local conda environment (local meaning it is in my project WD)

**Comment by jjfantini** [comment]
Latest update: still no avail, I start Cursor and highlighting and the syntax is there, and then few minutes into development all text is white and no suggestions. 

Its a sad day moving back to VScode.

**Comment by jjfantini** [comment]
Reloading Window helps reset the language server, with version 0.13.0, this should be faster and more robust...closing.
