### ISSUE TITLE
anyone knows how to log out github copilot in cursor? 

### ISSUE THREAD

**Issue by ghbtest** [getcursor/cursor#948]
I accidentally logged in github copilot extension using an account that has no subscription of copilot. I couldn't find a way to switch to a different account in cursor. Anyone knows how to do it please share. Thanks a lot.

**Comment by arvid220u** [comment]
<img width="632" alt="Screenshot 2023-09-22 at 12 18 28 PM" src="https://github.com/getcursor/cursor/assets/2716295/10b8c44d-b905-4fc1-aaf6-4023584f17e1">

Hey! Try Cmd-Shift-P and "sign out of github".

**Comment by ghbtest** [comment]
it works. thanks!
