### ISSUE TITLE
not use

### ISSUE THREAD

**Issue by Robinbiao** [getcursor/cursor#95]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/18207227/226151048-3c933957-75d9-4698-a058-b543361c137d.png">

**Comment by Baneist** [comment]
the same problem.

**Comment by jinhyhenry** [comment]
face with the same issue.

**Comment by truell20** [comment]
Apologies about this. I think OpenAI had an outage during this time! Think it should be fixed now. Thanks for reporting.
