### ISSUE TITLE
[Fix Found] Python extension no longer support - Code version too old

### ISSUE THREAD

**Issue by Yarden92** [getcursor/cursor#953]
I recently noticed that the Python extension is no longer supported and is disabled since the Code version underneath Cursor, is too old:
<img width="642" alt="image" src="https://github.com/getcursor/cursor/assets/19271465/ce53fbde-1e18-4479-90ed-1e1bc05e2a1d">

my Cursor version is up to date with the recent update
<img width="259" alt="image" src="https://github.com/getcursor/cursor/assets/19271465/5f382459-6500-4f88-9154-ffeef1677cb8">

Is it possible to update the Code version underneath Cursor? or its up to Cursor to update both?

**Comment by truell20** [comment]
Thanks for reporting this, will push a fix shortly. As an immediate fix, try "Switch to Pre-release Version." Does that fix this for you?

**Comment by Yarden92** [comment]
Yes, it does, thank you!

**Comment by tcul86** [comment]
Can you elaborate more on this?

**Comment by psychaos999** [comment]
Hi, I cant install past the python extension version v2023.14.0. I dont have the option to install a prerelase version.
If I try to manually install the vsix file it fails complaining vscode version is too old....Can u please fix this?

**Comment by psychaos999** [comment]
the problem is bigger than the single python extension. All dependent extensions can't upgrade past an old release being bound to python ext  version

**Comment by mike1936** [comment]
#997

**Comment by jakobFNF** [comment]
A staged rollout for the VS Code version update (0.13.0) has started. You can also redownload from https://cursor.sh/ to instantly get the latest version (all of your settings/extensions will move over to the redownloaded version).
