### ISSUE TITLE
Can't use Figma plugin with cursor

### ISSUE THREAD

**Issue by Mng-dev-ai** [getcursor/cursor#958]
Figma asks you to open vscode to complete auth, is there any workaround to do it with cusror?

**Comment by truell20** [comment]
Here's a temporary workaround! https://forum.cursor.sh/t/figma-extension-support/135

**Comment by Mng-dev-ai** [comment]
it works! thank you

**Comment by truell20** [comment]
Figma's extension now natively supports Cursor (as of v0.3.4)! Let us know if you run into any issues.

**Comment by russ0133** [comment]
Neither native nor the workaround works. Using Ubuntu. @truell20

**Comment by bitcoin4cashqc** [comment]
For me I added MimeType=x-scheme-handler/cursor; to the cursor.desktop, not sure if it was the issue or I needed to restart cursor but hey, maybe that's good to know

**Comment by bitcoin4cashqc** [comment]
I do get this loading a page tho : 

`Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.. `
