### ISSUE TITLE
The generated code is incomplete and appears to be limited in length

### ISSUE THREAD

**Issue by cx421774557** [getcursor/cursor#96]
For example, write the following program:
C++ is used to write a network framework based on epoll.

**Comment by langqinqieyi** [comment]
I get the same problem like you

**Comment by HOG-StarCraft** [comment]
ME TOO

**Comment by taixs** [comment]
ME TOO

**Comment by SilenceEagle** [comment]
+1

**Comment by allan-xie** [comment]
me too

**Comment by truell20** [comment]
Newest version should allow for longer outputs! Lmk if you want even longer outputs.
