### ISSUE TITLE
`.cursorignore` and `.gitignore` are not always respected for Codebase Indexing

### ISSUE THREAD

**Issue by McBroColi** [getcursor/cursor#965]
1) If you can, please include a screenshot of your problem
![Cursor_QsXme0COyz](https://github.com/getcursor/cursor/assets/4147952/a698d981-d76b-4d6e-9152-fc645bb53076)

2) Please include the name of your operating system - **Windows 11 Home**

3) If you can, steps to reproduce are super helpful

It seems that I am having trouble restricting the Codebase Indexing access. It doesn't ignore directories properly in my workspace, leading it to generate embeddings for a plethora of garbage including a ton of `.json`-format debug files in my project. It's quite cumbersome and I imagine not cost-efficient.

There is also already a separate issue about this, but it is worth mentioning that during this process the indexing freezes and will not finish.

Specific steps to reproduce would be rather general. Use a large directory with a lot of files like any bundled web project and it does not seem to be able to properly index my code, and especially not respect the `.cursorignore` or `.gitignore` files (`.gitignore` is specified in the settings that it is also ignored, so I make the assumption it should work).

**Comment by arvid220u** [comment]
Could you try removing the slash at the start of each file in the .cursorignore?

**Comment by McBroColi** [comment]
Yes. Here is the same repository being scanned with the `.cursorignore` configured without any slashes: 
![image](https://github.com/getcursor/cursor/assets/4147952/f28638f8-6c5c-4f9a-ae30-9556ed5b7145)

And just in case, the same target with the slashes at the end:
![image](https://github.com/getcursor/cursor/assets/4147952/efc786e2-adfe-4350-b83f-9b9ebf3918e8)

It is important to note that the progress bar and the view of files being scanned give me the impression that they are being indexed, but I really can't verify whether or not they actually are being processed. Sometimes, however, the index finishes building and these files are sometimes, and are sometimes not, available/show up as embeddings for queries.

**Comment by arvid220u** [comment]
Could you try version 0.12.1 and see if that fixes the problem for you? We pushed a fix to make the ignore parsing much more robust

**Comment by McBroColi** [comment]
Yes, it worked brilliantly on the first try, thank you! Closing this issue as indexing does not freeze, parser works as expected for both `.cursorignore` and `.gitignore` on my end.

**Comment by gsusI** [comment]
@arvid220u, when autogenerating .cursorignore, it'd be great to have commented examples showing how to exclude typical files and dirs; in terms of syntax, there's just too much variety out there to make assumptions
