### ISSUE TITLE
can not install on ubuntu 18.04 x64

### ISSUE THREAD

**Issue by gneworld** [getcursor/cursor#97]
![image](https://user-images.githubusercontent.com/30924021/226159915-1ac620ee-1fd5-4651-bb72-8a31cf40a901.png)

**Comment by YinDennis** [comment]
i have the same problem.

**Comment by truell20** [comment]
Thanks for reporting this! Seems to come from the change we made where we added in a terminal. Will investigate.

**Comment by mickey-cool** [comment]
me too！

**Comment by TimVerion** [comment]
me too!

**Comment by wsltsg1988** [comment]
me too

**Comment by xioqishi** [comment]
but i can work well on 20.04

**Comment by longswordinhand** [comment]
me too

**Comment by Sunchanghao** [comment]
> 

Will this issue be fixed？

**Comment by hawgjmrd72** [comment]
me too

**Comment by mickey-cool** [comment]
@truell20  will this problem be solved soon?

**Comment by truell20** [comment]
Think this is fixed in the latest version? Could someone let me know if it works or doesn't work? Apologies about this!

**Comment by TimVerion** [comment]
The latest version is not yet fixed

**Comment by danperks** [comment]
Seems to affect 22.04 (see #135) but may still regard the previous version of Cursor.

**Comment by danperks** [comment]
Closing as this appears to be resolved in newer versions

**Comment by Andndre** [comment]
![image](https://github.com/getcursor/cursor/assets/81848639/fd4e03c5-30c4-475c-8797-5f8e9d5d19fa)
Hi, I got the same error on Debian 12
