### ISSUE TITLE
The advanced setting menu is gone, where can we control which data you collect ? 

### ISSUE THREAD

**Issue by MatthieuToulemont** [getcursor/cursor#979]
In this [issue](https://github.com/getcursor/cursor/issues/41) it was said we control which data you collect by clicking on advanced in the settings but the advanced button is gone for me (chrome & safari)

I guess this has been updated since. 
Where can we control the data you collect now ? 

![Screenshot 2023-10-10 at 10 05 47](https://github.com/getcursor/cursor/assets/75613333/3e893c23-bd65-4eb2-aa15-d980655afcab)

**Comment by arvid220u** [comment]
Check out the advanced settings inside Cursor itself! If you cmd-shift-P for "cursor settings" and scroll down you should be able to find it

**Comment by MatthieuToulemont** [comment]
Thank you !
