### ISSUE TITLE
Can not open mu cursor now!!!!!!

### ISSUE THREAD

**Issue by future1122** [getcursor/cursor#98]
I can not open cursor this afternoon until now.  my os is windows 10. could you help me?

**Comment by zhanglistar** [comment]
No sorry

**Comment by truell20** [comment]
Hi! Could you share a screenshot of what shows up when you try to open Cursor?

**Comment by future1122** [comment]
Hi Sir ,I found the problem.
the shortcut is link to wrong path. I will close the issue. Thanks for response!
![screenshot](https://user-images.githubusercontent.com/26534468/226227791-24727596-6821-400e-8b23-480de452c14c.png)
