### ISSUE TITLE
Chat Completion stuck in loop for version 0.9.3 and 0.12.3

### ISSUE THREAD

**Issue by jpetrantoni** [getcursor/cursor#982]
Issue:
I am unable to use the chat or edit functionality. I have tried multiple queries and none of them work. I have ensured its not connectivity issues. I also quit Cursor multiple times and upgraded to latest version.

Issue Screenshot:
<img width="1351" alt="Screenshot 2023-10-10 at 5 47 52 PM" src="https://github.com/getcursor/cursor/assets/79169021/cfa1f987-0117-41e8-8342-79c4e70b123e">

Cursor Info:
Version: 0.12.3
VSCode Version: 1.80.1
Commit: 3c1a98b47d7c2e903562d2b756fc9cafe4915fb0
Date: 2023-10-08T22:51:40.884Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by jpetrantoni** [comment]
I tried logging out and back in, on new log in I am getting the below error

<img width="1489" alt="Screenshot 2023-10-10 at 6 39 35 PM" src="https://github.com/getcursor/cursor/assets/79169021/4814062f-292a-4b6d-ae25-10837098f097">

**Comment by filipegalo-valispace** [comment]
same here

**Comment by whatif-dev** [comment]
Same for us. I think they are experiencing some issues on their end. Once you go Cursor... you can't go back. lol.

**Comment by filipegalo-valispace** [comment]
> Same for us. I think they are experiencing some issues on their end. Once you go Cursor... you can't go back. lol.

it seems I forgot how to walk 🤣

**Comment by whatif-dev** [comment]
I'm like crap... Does that mean we have to go back to Chatgpt and start cut and pasting again! 😳 haahahahha.

**Comment by andyzhu01** [comment]
Yep, experiencing some server issues, but should be resolved soon!
