### ISSUE TITLE
`cmd + k` overwrites Terminal existing functionality 

### ISSUE THREAD

**Issue by darioarias** [getcursor/cursor#987]
1) If you can, please include a screenshot of your problem

   <img width="801" alt="Screenshot 2023-10-12 at 07 41 26" src="https://github.com/getcursor/cursor/assets/28869753/136fc703-2843-4302-aa41-ef71f4c4c8f6">

   **note**: `cmd + k` would normally clear the terminal, instead it invokes the ai functionality. 

2) Please include the name of your operating system
os: MacOs, version: Sonoma 14.0

3) If you can, steps to reproduce are super helpful
   1. Open Cursor
   2. Open Terminal
   3. Try to clear the terminal using `cmd + k`

**suggestion**:  allow users to remap the pre-existing functionality to clear terminal or allow users to remap how to invoke the ai functionality.

**Comment by wahidkadwaikar** [comment]
You can change the bindings for "Terminal: Generate in Terminal" in your keyboard shortcuts. Is that what you were looking for?

<img width="1048" alt="image" src="https://github.com/getcursor/cursor/assets/6859865/d7100607-6538-4e41-932c-e6d5e2aedf59">

**Comment by darioarias** [comment]
<img width="1136" alt="Screenshot 2023-10-17 at 19 44 22" src="https://github.com/getcursor/cursor/assets/28869753/f3e579aa-09d2-42b0-94df-b00bb78ad872">

For some reason I do not get that option in settings. Moreover, in the above image you can see me trying the suggestion that comes up and it still doesn't work. (I restarted `Cursor` after making changes just in case). Moreover, I ran the `>Cursor: Attempt Update` command from the `Command Palette (cmd + shift + p)` just in case I had an outdated version. Still nothing ☹️.

**Comment by wahidkadwaikar** [comment]
Ah! Should have clarified. You need to look into Keyboard Shortcuts not Settings. (command + R, command +S) should do the trick. 👍 

<img width="488" alt="image" src="https://github.com/getcursor/cursor/assets/6859865/5ced20c8-b352-4d64-bd4a-f69d0f105c09">

**Comment by darioarias** [comment]
Can confirm that the above works. Will be closing issue. Thank you once more @wahidkadwaikar!

**Comment by darioarias** [comment]
Can confirm that the above works. Will be closing issue. Thank you once more @wahidkadwaikar!

**Comment by defected2020** [comment]
The shortcuts don't save for me when testing.

**Comment by kaligrafy** [comment]
In the latest version of Cursor, the change is ignored and cmd-K opens this:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/ba0d6b02-ebfb-4d45-9c77-3537b7970aa2">

**Comment by NovqiGarrix** [comment]
> In the latest version of Cursor, the change is ignored and cmd-K opens this: <img alt="image" width="530" src="https://private-user-images.githubusercontent.com/879608/365218988-ba0d6b02-ebfb-4d45-9c77-3537b7970aa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDQzODgsIm5iZiI6MTcyNTgwNDA4OCwicGF0aCI6Ii84Nzk2MDgvMzY1MjE4OTg4LWJhMGQ2YjAyLWViZmItNGQ0NS05Yzc3LTM1MzdiNzk3MGFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNDAxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzA4ODU3ZjE3ZjQ4YjdiYjc1YjU4NDljMWU0YmEwN2JiNWExMDQ3YmFkNmVhN2IzODdiMzZlMDY5NDVhZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HJc6eHrpzUjTS7zOQYNjRFWZQ-TzRSFc5FNcNKKEHMA">

Same here... Version 0.40.4

**Comment by NovqiGarrix** [comment]
I searched the shortcut (which is Command+K) by keys, and found this.

<img width="1166" alt="Screenshot 2024-09-08 at 21 09 14" src="https://github.com/user-attachments/assets/ec184527-321a-4dbb-8c78-5de715b6cfbb">

Then just change the keys for `composer.startComposerPrompt`. it works for me

**Comment by turker0** [comment]
> I searched the shortcut (which is Command+K) by keys, and found this.
> 
> <img alt="Screenshot 2024-09-08 at 21 09 14" width="1166" src="https://private-user-images.githubusercontent.com/83995024/365443845-ec184527-321a-4dbb-8c78-5de715b6cfbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTQwOTMsIm5iZiI6MTcyNTk1Mzc5MywicGF0aCI6Ii84Mzk5NTAyNC8zNjU0NDM4NDUtZWMxODQ1MjctMzIxYS00ZGJiLThjNzgtNWRlNzE1YjZjZmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA3MzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNzY3ZThjOTdkYzZhZmU2M2MzZWM1NDBkNWRmODJiNGJiYmQ3OTM4NGI1OWQzNDVlMjdjZTM2MzljODUzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7GenN5m5aKew_D_BpLYBw_5aYq9CBxIJk4-m4bRi7TA">
> Then just change the key binding for `composer.startComposerPrompt`. it works for me

Also change "Generate in terminal" which is also "cmd+k"

**Comment by midaz** [comment]
Thanks for this change!

**Comment by KrishEnacton** [comment]
Guys could you please provide steps to change current cursor terminal shortcut(cmd+k) to (cmd+shift+k) and I want to use (cmd+k) to clear my terminal

**Comment by tedma4** [comment]
This issue doesn't happen in Wind Surf. Switching to that.

**Comment by Galic-Miroslav** [comment]
Go to keyboard shortcuts and find cursorai.action.generateInTerminal

**Comment by eddietindame** [comment]
Why does cursor have a habit of overwriting commonly used existing shortcuts? Makes the experience truly painful.

**Comment by martinytodorov** [comment]
Same here. Updated Cursor and trying to figure out how to clear my Terminal again...
