### ISSUE TITLE
can't use /edit to generate code

### ISSUE THREAD

**Issue by TJtangjun** [getcursor/cursor#988]
![image](https://github.com/getcursor/cursor/assets/23148245/955f996c-8363-48d2-a711-1075ff8b0823)

When I use /edit to generate the code, I get the error shown in the picture. I don't think I have a problem with my network, because I can use other AI functions normally.

e2caa54a-4c60-4eeb-b139-ff47be26f2a4

**Comment by TJtangjun** [comment]
I'm in China

**Comment by TJtangjun** [comment]
but when I switch to GPT4 mode ,it work successfully.

**Comment by jakobFNF** [comment]
I have the same issue. /edit only works with GPT-4 or shouldn't be able to be used with GPT-3.5 in the first place. Noted this down as a bug.

**Comment by jakobFNF** [comment]
This is now fixed. Thank you for your report!
