### ISSUE TITLE
Rename the Configuration "Local Mode" to something representing

### ISSUE THREAD

**Issue by Patrick10203** [getcursor/cursor#998]
When you use "Local Mode" everything in the prompt is still send to Cursor's Servers. This is incredibly misleading. There is nothing Local in the "Local Mode". Either rename it to something representing it (that you are sending data to your servers) or change the feature so that there it is actually no Cursor server involved.

**Comment by jakobFNF** [comment]
It will probably be renamed to 'Privacy Mode' in the next update. Thank you for your feedback!

**Comment by singerbj** [comment]
Is there a plan or ability to enable local only mode that does not send any data to Cursor?
